In [1]:
!pip install openai pandas

Requirement already satisfied: openai in /home/aakash/NIC/.venv/lib/python3.12/site-packages (2.7.1)
Requirement already satisfied: pandas in /home/aakash/NIC/.venv/lib/python3.12/site-packages (2.3.3)
Requirement already satisfied: anyio<5,>=3.5.0 in /home/aakash/NIC/.venv/lib/python3.12/site-packages (from openai) (4.11.0)
Requirement already satisfied: distro<2,>=1.7.0 in /home/aakash/NIC/.venv/lib/python3.12/site-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /home/aakash/NIC/.venv/lib/python3.12/site-packages (from openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.10.0 in /home/aakash/NIC/.venv/lib/python3.12/site-packages (from openai) (0.11.1)
Requirement already satisfied: pydantic<3,>=1.9.0 in /home/aakash/NIC/.venv/lib/python3.12/site-packages (from openai) (2.12.4)
Requirement already satisfied: sniffio in /home/aakash/NIC/.venv/lib/python3.12/site-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /home/aakash/NIC/.venv/lib/python3.12/site-packages (from openai) (4.67.1)
Requirement already satisfied: typing-extensions<5,>=4.11 in /home/aakash/NIC/.venv/lib/python3.12/site-packages (from openai) (4.15.0)
Requirement already satisfied: idna>=2.8 in /home/aakash/NIC/.venv/lib/python3.12/site-packages (from anyio<5,>=3.5.0->openai) (3.11)
Requirement already satisfied: certifi in /home/aakash/NIC/.venv/lib/python3.12/site-packages (from httpx<1,>=0.23.0->openai) (2025.10.5)
Requirement already satisfied: httpcore==1.* in /home/aakash/NIC/.venv/lib/python3.12/site-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /home/aakash/NIC/.venv/lib/python3.12/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /home/aakash/NIC/.venv/lib/python3.12/site-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in /home/aakash/NIC/.venv/lib/python3.12/site-packages (from pydantic<3,>=1.9.0->openai) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /home/aakash/NIC/.venv/lib/python3.12/site-packages (from pydantic<3,>=1.9.0->openai) (0.4.2)
Requirement already satisfied: numpy>=1.26.0 in /home/aakash/NIC/.venv/lib/python3.12/site-packages (from pandas) (2.3.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/aakash/NIC/.venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/aakash/NIC/.venv/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/aakash/NIC/.venv/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /home/aakash/NIC/.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
!pip install python-dotenv

Requirement already satisfied: python-dotenv in /home/aakash/NIC/.venv/lib/python3.12/site-packages (1.2.1)

In [3]:
import json
from openai import OpenAI
import pandas as pd
from IPython.display import Image, display

In [4]:
import os
import logging
logging.basicConfig(
    format='%(asctime)s : %(levelname)s - %(message)s',
    level=logging.INFO
)
from dotenv import load_dotenv
load_dotenv()

True

In [5]:
OPENAI_API_KEY=os.getenv('OPENAI_API_KEY')

In [21]:
client=OpenAI(
    api_key=OPENAI_API_KEY
)

In [22]:
response=client.responses.create(
    model='gpt-5-mini',
    input='Write one sentence bedtime story about Korean 2015 drama series Reply 1988'
)
print(response.output_text)

2025-11-24 11:04:34,388 : INFO - HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"

As the moon rose over Ssangmun-dong, five lifelong friends and their families drifted off surrounded by laughter, home-cooked scents, and the gentle promise that the warmth of their neighborhood would keep their sweetest memories safe forever.

In [7]:
df=pd.read_csv('/home/aakash/NIC/cdl-updated/nic-metadata-cleaning/data/original/Catalog_mapping.csv')
df.head()

,dcterms:title,dcterms:creator,dcterms:description,dcatin:jurisdictionLevel,dcterms:created,dcterms:issued,dcterms:modified,dcat:accessURL,dcterms:identifier,dcat:landingPage,...,dcterms:isPartOf,dcterms:isReferencedBy,dcterms:isReplacedBy,dcterms:replaces,dcterms:isVersionOf,dcterms:hasVersion,dcterms:relation,Unnamed: 43,No mapping available,No mapping available.1
0,All India Pincode Boundary Geo JSON,Ministry of Communications;Department of Posts,This will provide the Pincode boundary of Post...,Central,2025-05-09,2025-05-09,2025-05-09,NaN,NaN,https://data.gov.in/catalog/all-india-pincode-...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"20,923",0
1,Crime in India - 2022,Ministry of Home Affairs;Department of States;...,Catalog contains data of Crime in India - 2022...,Central,2024-04-10,2024-04-12,2024-04-12,NaN,NaN,https://data.gov.in/catalog/crime-india-2022,...,NaN,NaN,NaN,NaN,Crime in India [https://www.data.gov.in/datase...,NaN,NaN,NaN,"32,297",0
2,Indian Sign Language Dictionary,Ministry of Social Justice and Empowerment;Dep...,The Indian Sign Language (ISL) Dictionary has ...,Central,2024-02-06,2024-02-07,2025-02-18,NaN,NaN,https://data.gov.in/catalog/indian-sign-langua...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"11,580",0
3,Demographic Data of Unorganised Workers regist...,Ministry of Labour and Employment,The catalog contains data for self-registratio...,Central,2023-06-07,2023-12-21,2025-06-19,NaN,NaN,https://data.gov.in/catalog/demographic-data-u...,...,https://www.data.gov.in/catalog/eshram-registr...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"51,289",0
4,Answers Data of Rajya Sabha Questions for Sess...,Rajya Sabha,Get questions' Answers Data of Session 260 of ...,Central,2023-12-18,2023-12-19,2024-03-11,NaN,NaN,https://data.gov.in/catalog/answers-data-rajya...,...,NaN,NaN,NaN,NaN,Rajya Sabha Questions: https://www.data.gov.in...,NaN,NaN,NaN,"4,514",0

In [8]:
#for filling in title, description, note wherever required.
# TODO Create a generic prompt template 
metadata_enhancement_prompt="""

# System Prompt: Catalog-Level Metadata Enhancement for India Government Open Data

## Role
You are an expert metadata curator specializing in government open data standards including Dublin Core, DCAT v3, and India's data.gov.in cataloging specifications. Your task is to generate enhanced, standardized metadata **for catalog-level metadata**, focusing specifically on improving:
- **dcterms:title** (Catalog Title)
- **dcterms:description** (Catalog Description)

Catalogs typically do **not** contain short description, abstract, or notes like dataset resources. Therefore, your focus is to create **rich, clear, comprehensive catalog metadata** that improves discoverability and comprehension without inventing facts not supported by metadata.

## Instructions
Do not make mistakes.  
Keep all enhancements **catalog-level**, not dataset-level.  
Do not add fictitious indicators, metrics, units, or field names.

## Input Format
You will receive CSV rows with the following key columns:
- **dcterms:title** – Existing catalog title (often short, incomplete, or unclear)
- **dcterms:description** – Current description (may be empty or minimal)
- **dcat:theme** – Thematic categories (semicolon-separated)
- **dcterms:spatial** – Geographic scope (e.g., India, specific states)
- **dcatin:jurisdictionLevel** – Government level (Central/State)
- **dct:accrualPeriodicity** – Update frequency (Daily, Monthly, Annual, etc.)
- **dcat:keyword** – Existing keywords
- **dcterms:publisher** – Publishing ministry/department
- Other administrative fields for context

---

# Task Requirements

## 1. Generate Enhanced Catalog Title (dcterms:title)
Create an improved catalog title that:
- Preserves the original meaning
- Adds clarity, expands abbreviations, and removes ambiguity
- Clearly indicates domain and scope
- Is formatted in Title Case
- Length: **10–20 words**, maximum 25
- Avoids dataset-level terminology like “records”, “fields”, “table”, “resource”

### Enhancement Logic
- Start with existing title → rewrite for clarity
- Expand abbreviations (RoC → Registrars of Companies)
- Add context if the title is too vague
- Include geographic or temporal scope where clearly implied
- Do **not** fabricate specifics (e.g., number of datasets)

---

## 2. Generate Comprehensive Catalog Description (dcterms:description)
Write a **2–4 sentence** description that:
- Explains what the catalog contains (in general terms)
- Mentions thematic scope (agriculture, health, finance, etc.)
- Explains purpose and relevance of the catalog
- Mentions update frequency and jurisdiction if available
- Provides high-level context without dataset-specific field details
- Length: **70–150 words**

### Generation Logic
- If description exists → enhance, expand, modernize
- If empty → generate from available metadata fields
- Mention:
  - What the catalog covers
  - Its purpose or utility
  - Geographic scope (India, states)
  - Update frequency if relevant
  - Publisher or agency context

### Strict Constraints
- **Do not mention specific dataset fields or column names**
- **Do not invent methodology details**
- **Do not generate dataset-level descriptions**
- Keep content catalog-level and generalized

---

# Output Format
Return valid JSON with:

{
  "enhanced_title": "...",
  "enhanced_description": "...",
  "processing_summary": {
    "title_changes": "Brief explanation of improvements",
    "description_changes": "How the description was expanded/clarified"
  },
  "metadata_quality_score": 0.85,
  "quality_score_explanation": "How score was calculated",
  "source_fields_used": ["list", "of", "fields", "used"]
}

### Metadata Quality Score (0.0 to 1.0)
- Completeness (50%): Title + description enhanced
- Enhancement Quality (30%): Degree of clarity added
- Input Metadata Usefulness (20%): How much metadata contributed

Scoring guidelines:
- **0.9–1.0**: Strong enhancements and rich metadata
- **0.7–0.89**: Good enhancements, moderate metadata
- **0.5–0.69**: Basic enhancements, low metadata richness
- **<0.5**: Very limited possible improvement

---

## Special Handling for Indian Government Catalogs

### Ministry/Department Context
- Expand ministry names in description
- Use formal names in full (Ministry of Agriculture & Farmers Welfare)

### Geographic Indicators
- Use “India” or state names explicitly
- Include jurisdiction level where helpful

### Sector-Specific Notes (high level only)
- Agriculture → markets, crops, production, prices
- Health → indicators, public health programs
- Finance → economic indicators, annual trends
- Education → learning, schools, enrolment

### Acronym Handling
Expand common acronyms at catalog level:
- KCC → Kisan Call Centre  
- APMC → Agricultural Produce Market Committee  
- PHC → Primary Health Centre  
- MSME → Micro, Small & Medium Enterprises  
- RoC → Registrars of Companies  

---

## Error Handling
- Missing title → Score = 0.0; return explanation
- Empty description → Generate new based on other fields
- Very low metadata → Provide clean generic description with low score

## Constraints
- Maintain factual accuracy
- Use Indian English
- Do not add dataset-level specifics
- Keep language professional, clear, and consistent

"""

In [25]:
# for keyword/theme generation
categorize_system_prompt="""
# SYSTEM PROMPT: Catalog-Level Keyword, Sector (Theme) and Group (Subject) Enhancement

## ROLE
You are an expert metadata curator specializing in Indian Open Government Data (OGD), DCAT-India, Dublin Core, and metadata taxonomy design.  
Your task is to generate clean, consistent, catalog-level:
- **dcat:keyword** (Layman Keywords)
- **dcat:theme** (Sector)

based on the catalog's high-level purpose, using the given inputs.

This enhancement is for **CATALOGS**, not datasets.

---

# INPUT FORMAT
You will receive the following fields:

- **dcterms:subject** → existing Groups (may be empty, noisy, inconsistent)  
- **dcat:theme** → existing Sectors (may be empty or too generic)  
- **dcat:keyword** → existing Keywords (often sparse or unclean)
- **dcterms:title** – Existing catalog title (often short, incomplete, or unclear)
- **dcterms:description** – Current description (may be empty or minimal)

Use these fields + the additional context provided (title, description, publisher, etc.) to generate **new enriched metadata values**.

---

# TASK REQUIREMENTS
## 1. Enhanced Layman Keywords (`enhanced_keywords`)

Generate **6–10 highly discoverable**, layman-friendly keywords.

### Rules
- Must be **1–2 words**, in **CamelCase**.  
- Must reflect the **actual content** of the dataset.  
- Should help a normal user find this dataset easily.  
- Avoid:
  - Ministry/Department names  
  - Administrative terms  
  - Very generic umbrella words  
  - The word *“India”*  
  - Technical/internal vocabulary  
- Use the dataset **Title, description, Sector, etc. 




---

## 2. Sponsored Keywords (`sponsored_keywords`)

These are the **3–5 strongest search terms**, directly tied to the dataset **title**.

### Rules
- 1–2 words, **CamelCase**.  
- Highest semantic similarity to the dataset title.  
- Avoid administrative terms, avoid “India” unless in the official title.
- Should be slighly different from `enhanced_keywords`, focusing more on exact title relevance.
- Avoid making them identical to `enhanced_keywords`.


---

## 3. Generate Sector (dcat:theme)
One or more sectors may be allowed, but **prioritize ONE primary sector**.

Choose from controlled vocabulary that is used by dcat-AP:

- Agriculture  
- Health  
- Education  
- Finance & Economy  
- Transport  
- Energy  
- Environment  
- Governance & Administration  
- Social Welfare  
- Rural Development  
- Urban Development  
- Water Resources  
- Disaster Management  
- Science & Technology  
- Commerce & Industry  
- Housing  
- Employment & Labour  
- Others (only when unavoidable)

Rules:
- Sector must reflect the **overall domain** of the entire catalog
- Use publisher/ministry to infer if missing
- Do not assign overly broad sector (“Others” only if no other fits)

---

# OUTPUT FORMAT

Return a **valid JSON object**:

{
  "generated_keywords": ["keyword1", "keyword2", ...],
  "sponsored_keywords": ["keyword1", "keyword2", ...],
  "sector": "Primary sector assigned",
  "processing_summary": {
    "keyword_logic": "How keywords were derived",
    "sector_logic": "Why the sector was selected",
    "sponsored_keywords": "How sponsored keywords were chosen"
  },
  "source_fields_used": ["dcterms:subject", "dcat:theme", "dcat:keyword"]
}

---

# SPECIAL HANDLING FOR INDIAN GOVERNMENT CONTEXT
- Use official terminology aligned with Indian ministries
- Abbreviations allowed only if widely used (GST, APMC, PHC, NFHS)
- Prefer Indian-specific terms (district, state, block, panchayat)
- Ensure classification reflects India’s administrative domains

---

# ERROR HANDLING
- If all inputs are empty → generate generic but safe output  
- If conflicts exist → trust catalog title > description > publisher > input fields  
- If contradictory themes exist → choose the most central domain
"""

In [ ]:

# for keyword generation
keyword_prompt= '''




## Metadata Keyword Generation + High Value Data (HVD) Classification Prompt

Role: You are an expert metadata curator specializing in government open data standards (Dublin Core, DCAT v3, data.gov.in). Your task is to generate **layman-friendly keywords**, **sponsored keywords**, and **High Value Data (HVD) category** for a dataset using the metadata provided.

You will receive the dataset metadata in plain text, for example:

Title: <title text>  
Catalog Title: <catalog_title text>  
Ministry/Department: <ministry_department text>  
Sector: <sector text>  
Sector Resource: <sector_resource text>  
CDOS State Ministry: <cdos_state_ministry text>  
Note: <note or description text>  


Your job is to analyze this metadata and return **one single JSON object** following the structure described below.

---

# 1. Enhanced Layman Keywords (`enhanced_keywords`)

Generate **6–10 highly discoverable**, layman-friendly keywords.

### Rules
- Must be **1–2 words**, in **CamelCase**.  
- Must reflect the **actual content** of the dataset.  
- Should help a normal user find this dataset easily.  
- Avoid:
  - Ministry/Department names  
  - Administrative terms  
  - Very generic umbrella words  
  - The word *“India”*  
  - Technical/internal vocabulary  
- Use the dataset **Title, Catalog Title, Sector, Sector Resource, Note**.

### Output format
A **comma-separated string**, e.g.:

```

"enhanced_keywords": "RainfallData, WeatherTrend, DailyRain, MonsoonPattern"

```

---

# 2. Sponsored Keywords (`sponsored_keywords`)

These are the **3–5 strongest search terms**, directly tied to the dataset **title**.

### Rules
- 1–2 words, **CamelCase**.  
- Highest semantic similarity to the dataset title.  
- Avoid administrative terms, avoid “India” unless in the official title.
- Should be slighly different from `enhanced_keywords`, focusing more on exact title relevance.
### Output format

```

"sponsored_keywords": "MandiPrice, CommodityRate, MarketPrice"

```

---

# 3. High Value Data Classification (`hvd_category`)

You will receive:

`HVD Flag: <0 or 1>`

### If HVD Flag = 0:
- No classification.
- Output:

- You must **always** generate `enhanced_keywords`, `sponsored_keywords`, `justification`, `confidence_score`, and `metadata_gaps` **for every dataset**, **regardless of the HVD Flag value**.  
- The HVD Flag only affects the value of `"hvd_category"`.

```

"hvd_category": ""

```

### If HVD Flag = 1:
Classify the dataset into **one** category from:

1. geospatial  
2. earth observation and environment  
3. meteorological  
4. statistics  
5. companies and company ownership  
6. mobility  

Choose based on **Title, Catalog Title, Note**, and content meaning.

### Output format example
```

"hvd_category": "statistics"

```

---

# 4. Additional Required Fields

Your JSON must also include:

| Key | Description |
|------|------------|
| `"title"` | Copy the dataset title from the input |
| `"justification"` | 1–2 sentences explaining keyword + HVD reasoning |
| `"confidence_score"` | Float 0–1 indicating confidence |
| `"metadata_gaps"` | List describing missing or unclear metadata |

If no metadata gaps:



"metadata_gaps": []



---

# 5. Output Format (STRICT)

You must output **exactly ONE JSON object**, with **ALL keys**, and **nothing else**.

- No markdown  
- No comments  
- No explanations outside JSON  
- No "error" field  
- Must be valid JSON  

### Required JSON structure:

json
{
  "title": "",
  "enhanced_keywords": "",
  "sponsored_keywords": "",
  "justification": "",
  "confidence_score": 0.0,
  "metadata_gaps": [],
  "hvd_category": ""
}


Populate every field appropriately.

---

# 6. Example Output (Structure Only)

json
{
  "title": "Current Daily Price of Various Commodities from Various Markets (Mandi)",
  "enhanced_keywords": "MandiPrice, CommodityPrice, DailyPrice, MarketRate, WholesalePrice, AgricultureMarket, PriceTrend, CropPrice",
  "sponsored_keywords": "MandiPrice, CommodityPrice, MarketRate, DailyPrice",
  "justification": "The dataset provides daily wholesale commodity prices, so keywords focus on commodity pricing and mandis. It fits the statistics HVD category because it involves structured numerical market data.",
  "confidence_score": 0.9,
  "metadata_gaps": ["Geographic coverage missing", "Temporal start date not specified"],
  "hvd_category": "statistics"
}









'''

In [26]:
def get_keywords(metadata_content):
    response=client.chat.completions.create(
         model='gpt-5-nano',
         temperature=1,
         response_format={
             "type":"json_object",
        
         },
         messages=[
              {
                  "role":"system",
                  "content":categorize_system_prompt
              },
              {
                  "role":"user",
                  "content":metadata_content
              }
         ],

    )
    return json.loads(response.choices[0].message.content)

In [9]:
def get_enhanced_metadata(metadata_content):
    response = client.chat.completions.create(
        model='gpt-5-nano',
        temperature=1,
        response_format={"type": "json_object"},
        messages=[
            {
                "role": "system",
                "content": metadata_enhancement_prompt
            },
            {
                "role": "user",
                "content": metadata_content
            }
        ],
    )
    return json.loads(response.choices[0].message.content)

In [10]:
df=pd.read_csv("/home/aakash/NIC/cdl-updated/nic-metadata-cleaning/data/ogd_metadata_sample/sample_catalog_nic.csv", encoding="cp1252", )
df.head()

,title,body:value,changed,created,published_date,field_asset_jurisdiction:name,field_ds_govt_type,field_ministry_department:name,field_sector:name,from_api,keywords,high_value_dataset,is_api_available,node_alias,ogdp_view_count
0,All India Pincode Boundary Geo JSON,This will provide the Pincode boundary of Post...,5/9/2025,5/9/2025,5/9/2025,All India,Central,Ministry of Communications;Department of Posts,All,0,PINCODE;Geojson ;Geo Json File,1,0,/catalog/all-india-pincode-boundary-geo-json,5
1,Crime in India - 2022,Catalog contains data of Crime in India - 2022...,4/12/2024,4/10/2024,4/12/2024,All India,Central,Ministry of Home Affairs;Department of States;...,Police,0,Indian Penal Code;Crime;Crimes under Special a...,0,0,/catalog/crime-india-2022,4251
2,Indian Sign Language Dictionary,The Indian Sign Language (ISL) Dictionary has ...,2/18/2025,2/6/2024,2/7/2024,All India,Central,Ministry of Social Justice and Empowerment;Dep...,Disabled,0,Sign Language;Indian Sign Language;Sign Langua...,0,0,/catalog/indian-sign-language-dictionary,3268
3,Demographic Data of Unorganised Workers regist...,The catalog contains data for self-registratio...,6/19/2025,6/7/2023,12/21/2023,All India,Central,Ministry of Labour and Employment,Unorganized Sector Workers,1,eShram;eShram Registration;MoLE;Labour and Emp...,1,0,/catalog/demographic-data-unorganised-workers-...,21424
4,Answers Data of Rajya Sabha Questions for Sess...,Get questions' Answers Data of Session 260 of ...,3/11/2024,12/18/2023,12/19/2023,All India,Central,Rajya Sabha,All,0,Rajya Sabha,0,0,/catalog/answers-data-rajya-sabha-questions-se...,2811

In [14]:
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
import csv
from threading import Lock

In [15]:
def extract_clean_value(value):
    """Clean and extract value from field"""
    if pd.isna(value) or value == 'nan' or value == '':
        return ""
    return str(value).strip()

def parse_semicolon_separated(value):
    """Parse semicolon-separated values into a list"""
    if not value or pd.isna(value):
        return []
    return [v.strip() for v in str(value).split(';') if v.strip()]

In [12]:
def process_row_generation(row):
    """Process a single catalog row for title + description enhancement only"""

    # --- helper to robustly read columns (handles leading/trailing spaces in sheet) ---
    def safe_get(key, default=""):
        if key in row:
            return row.get(key, default)
        # fallback: match by stripped key
        for k in row.index:
            if isinstance(k, str) and k.strip() == key:
                return row.get(k, default)
        return default
        
    # Primary fields for enhancement (catalog-level)
    title = extract_clean_value(safe_get("dcterms:title", ""))
    description = extract_clean_value(safe_get("dcterms:description", ""))

    # Supporting metadata fields (based on actual sheet columns)
    themes = parse_semicolon_separated(safe_get("dcat:theme", ""))
    spatial = extract_clean_value(safe_get("dcterms:spatial", ""))
    temporal = extract_clean_value(safe_get("dcterms:temporal", ""))
    jurisdiction = extract_clean_value(safe_get("dcatin:jurisdictionLevel", ""))
    frequency = extract_clean_value(safe_get("dct:accrualPeriodicity", ""))
    keywords = extract_clean_value(safe_get("dcat:keyword", ""))
    publisher = extract_clean_value(safe_get("dcterms:publisher", ""))
    creator = extract_clean_value(safe_get("dcterms:creator", ""))

    # vCard fields in your sheet have leading spaces, safe_get handles that
    contact_name = extract_clean_value(safe_get("vCard:fn", ""))
    org_name = extract_clean_value(safe_get("vcard:organization-name", ""))
    contact_email = extract_clean_value(safe_get("vcard:hasEmail", ""))
    contact_role = extract_clean_value(safe_get("vcard:role", ""))

    # Build metadata content string for the LLM (catalog-level)
    metadata_content = f'''
=== CURRENT CATALOG METADATA ===
Catalog Title: {title}
Catalog Description: {description}

=== CONTEXTUAL INFORMATION ===
Themes: {'; '.join(themes) if themes else 'Not specified'}
Keywords: {keywords if keywords else 'Not specified'}
Publisher: {publisher if publisher else 'Not specified'}
Creator: {creator if creator else 'Not specified'}
Organization: {org_name if org_name else 'Not specified'}
Contact Person: {contact_name if contact_name else 'Not specified'}
Contact Email: {contact_email if contact_email else 'Not specified'}
Contact Role: {contact_role if contact_role else 'Not specified'}

=== COVERAGE DETAILS ===
Spatial Coverage: {spatial if spatial else 'India'}
Temporal Coverage: {temporal if temporal else 'Not specified'}
Jurisdiction Level: {jurisdiction if jurisdiction else 'Not specified'}

=== UPDATE DETAILS ===
Update Frequency: {frequency if frequency else 'Not specified'}

TASK: Generate enhanced catalog-level metadata values for dcterms:title and dcterms:description only, according to the system prompt.
'''

    try:
        result = get_enhanced_metadata(metadata_content)
        logging.info(f"Processed catalog: {title[:50]}...")

    except Exception as e:
        logging.error(f"LLM failed for catalog '{title}': {e}")
        result = {
            "enhanced_title": title,
            "enhanced_description": description,
            "processing_summary": {
                "title_changes": "",
                "description_changes": "",
                "error": str(e)
            },
            "metadata_quality_score": 0.0,
            "quality_score_explanation": f"Processing failed: {str(e)}",
            "source_fields_used": []
        }

    return {
        "original_title": str(title),
        "original_description": str(description)[:500],

        # Enhanced catalog outputs
        "enhanced_title": result.get("enhanced_title", title),
        "enhanced_description": result.get("enhanced_description", description),

        # Summary + scoring
        "processing_summary": result.get("processing_summary", {}),
        "quality_score": result.get("metadata_quality_score", 0.0),
        "quality_score_explanation": result.get("quality_score_explanation", ""),
        "source_fields_used": result.get("source_fields_used", []),

        # Context fields retained for audit/debug
        "themes": str('; '.join(themes) if themes else ''),
        "publisher": str(publisher),
        "jurisdiction": str(jurisdiction),
        "frequency": str(frequency),

        # Full LLM JSON for traceability
        "llm_response": json.dumps(result)
    }

In [23]:
# Main execution
input_file = "/home/aakash/NIC/cdl-updated/nic-metadata-cleaning/data/original/Catalog_mapping.csv"
output_file = "/home/aakash/NIC/cdl-updated/nic-metadata-cleaning/data/metadata_cleaned_catalog_title_description.csv"

df = pd.read_csv(input_file)
print(f"Loaded {len(df)} rows")

csv_lock = Lock()

# Only fields that exist in the new function + new prompt
fieldnames = [
    # Original fields
    "original_title",
    "original_description",

    # Enhanced fields
    "enhanced_title",
    "enhanced_description",

    # Context fields (kept for audit/debug)
    "themes",
    "publisher",
    "jurisdiction",
    "frequency",

    # Processing metadata
    "quality_score",
    "quality_score_explanation",
    "title_changes",
    "description_changes",
    "source_fields_used",
    "llm_response"
]

# Write header once
with open(output_file, 'w', newline='', encoding='utf-8') as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()

results_array = []
max_workers = 8
rows_to_process = df.head(105)  # Change to df for all rows

with ThreadPoolExecutor(max_workers=max_workers) as executor:
    future_to_row = {
        executor.submit(process_row_generation, row): idx
        for idx, row in rows_to_process.iterrows()
    }

    for future in as_completed(future_to_row):
        try:
            result_obj = future.result()

            processing_summary = result_obj.get("processing_summary", {})

            csv_row = {
                # Original fields
                "original_title": result_obj.get("original_title", ""),
                "original_description": result_obj.get("original_description", ""),

                # Enhanced fields
                "enhanced_title": result_obj.get("enhanced_title", ""),
                "enhanced_description": result_obj.get("enhanced_description", ""),

                # Context fields
                "themes": result_obj.get("themes", ""),
                "publisher": result_obj.get("publisher", ""),
                "jurisdiction": result_obj.get("jurisdiction", ""),
                "frequency": result_obj.get("frequency", ""),

                # Processing metadata
                "quality_score": result_obj.get("quality_score", 0.0),
                "quality_score_explanation": result_obj.get("quality_score_explanation", ""),
                "title_changes": processing_summary.get("title_changes", ""),
                "description_changes": processing_summary.get("description_changes", ""),
                "source_fields_used": json.dumps(result_obj.get("source_fields_used", [])),
                "llm_response": result_obj.get("llm_response", "")
            }

            results_array.append(csv_row)

            with csv_lock:
                with open(output_file, 'a', newline='', encoding='utf-8') as f:
                    writer = csv.DictWriter(f, fieldnames=fieldnames)
                    writer.writerow(csv_row)

            print(f"✓ {csv_row['original_title'][:60]}...")

        except Exception as e:
            logging.error(f"Row failed: {e}")

print(f"\n✓ Complete! Results saved to {output_file}")

Loaded 86 rows

2025-11-24 11:05:34,311 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:05:34,432 : INFO - Processed catalog: Indian Sign Language Dictionary...

✓ Indian Sign Language Dictionary...

2025-11-24 11:05:35,897 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:05:35,904 : INFO - Processed catalog: Answers Data of Rajya Sabha Questions for Session ...

✓ Answers Data of Rajya Sabha Questions for Session 260...

2025-11-24 11:05:38,869 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:05:38,871 : INFO - Processed catalog: Crime in India - 2022...

✓ Crime in India - 2022...

2025-11-24 11:05:41,836 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:05:41,839 : INFO - Processed catalog: Performance Grading Index (PGI)...

✓ Performance Grading Index (PGI)...

2025-11-24 11:05:42,379 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:05:42,381 : INFO - Processed catalog: Mahatma Gandhi National Rural Employment Guarantee...

✓ Mahatma Gandhi National Rural Employment Guarantee Act (MGNR...

2025-11-24 11:05:45,414 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:05:45,417 : INFO - Processed catalog: All India Pincode Boundary Geo JSON...

✓ All India Pincode Boundary Geo JSON...

2025-11-24 11:05:47,146 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:05:47,151 : INFO - Processed catalog: Demographic Data of Unorganised Workers registered...

✓ Demographic Data of Unorganised Workers registered on eShram...

2025-11-24 11:05:49,464 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:05:49,467 : INFO - Processed catalog: Unique Disability ID (UDID)...

✓ Unique Disability ID (UDID)...

2025-11-24 11:05:59,109 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:05:59,113 : INFO - Processed catalog: Elephant Reserve and Population Status...

✓ Elephant Reserve and Population Status...

2025-11-24 11:06:01,355 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:06:01,361 : INFO - Processed catalog: Youth Hostel Scheme...

✓ Youth Hostel Scheme...

2025-11-24 11:06:08,849 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:06:08,855 : INFO - Processed catalog: Answers Data of Rajya Sabha Questions for Session ...

✓ Answers Data of Rajya Sabha Questions for Session 259...

2025-11-24 11:06:11,269 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:06:11,277 : INFO - Processed catalog: CBSE Result Statistics Class XII...

✓ CBSE Result Statistics Class XII...

2025-11-24 11:06:15,808 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:06:15,813 : INFO - Processed catalog: Crude Oil Processed by Refineries...

✓ Crude Oil Processed by Refineries...

2025-11-24 11:06:18,816 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:06:18,820 : INFO - Processed catalog: Import & Export of Petroleum Products...

✓ Import & Export of Petroleum Products...

2025-11-24 11:06:25,356 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:06:25,358 : INFO - Processed catalog: Ground Water Level Data under Atal Bhujal Yojana...

✓ Ground Water Level Data under Atal Bhujal Yojana...

2025-11-24 11:06:25,994 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:06:25,997 : INFO - Processed catalog: Consumption of Petroleum Products...

✓ Consumption of Petroleum Products...

2025-11-24 11:06:29,880 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:06:29,883 : INFO - Processed catalog: Quarterly Employment Survey (QES)...

✓ Quarterly Employment Survey (QES)...

2025-11-24 11:06:38,455 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:06:38,460 : INFO - Processed catalog: Answers Data of Rajya Sabha Questions for Session ...

✓ Answers Data of Rajya Sabha Questions for Session 258...

2025-11-24 11:06:39,707 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:06:39,712 : INFO - Processed catalog: Tele-Law Program under Designing Innovative Soluti...

✓ Tele-Law Program under Designing Innovative Solution for Hol...

2025-11-24 11:06:42,393 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:06:42,398 : INFO - Processed catalog: Patent Application...

✓ Patent Application...

2025-11-24 11:06:43,584 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:06:43,589 : INFO - Processed catalog: Crime in India - 2021...

✓ Crime in India - 2021...

2025-11-24 11:06:48,856 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:06:48,859 : INFO - Processed catalog: Hydrological Boundaries...

✓ Hydrological Boundaries...

2025-11-24 11:07:04,303 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:07:04,306 : INFO - Processed catalog: Daily Data of Evapo-transpiration...
2025-11-24 11:07:04,315 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:07:04,317 : INFO - Processed catalog: Boundaries of Water Resources Projects...

✓ Daily Data of Evapo-transpiration...
✓ Boundaries of Water Resources Projects...

2025-11-24 11:07:04,904 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:07:04,907 : INFO - Processed catalog: Boundaries of Region...

✓ Boundaries of Region...

2025-11-24 11:07:16,008 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:07:16,012 : INFO - Processed catalog: Startup Recognized by DPIIT...

✓ Startup Recognized by DPIIT...

2025-11-24 11:07:19,692 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:07:19,694 : INFO - Processed catalog: Global Youth Tobacco Survey (GYTS-4)...

✓ Global Youth Tobacco Survey (GYTS-4)...

2025-11-24 11:07:20,417 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:07:20,421 : INFO - Processed catalog: Longitudinal Ageing Study in India (LASI)...

✓ Longitudinal Ageing Study in India (LASI)...

2025-11-24 11:07:26,294 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:07:26,299 : INFO - Processed catalog: Reservoir...

✓ Reservoir...

2025-11-24 11:07:31,535 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:07:31,538 : INFO - Processed catalog: Soil Moisture...
2025-11-24 11:07:31,623 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:07:31,632 : INFO - Processed catalog: Local Government Directory (LGD)...

✓ Soil Moisture...
✓ Local Government Directory (LGD)...

2025-11-24 11:07:35,627 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:07:35,631 : INFO - Processed catalog: India Tourism Statistics...

✓ India Tourism Statistics...

2025-11-24 11:07:52,666 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:07:52,672 : INFO - Processed catalog: BHUKOSH...

✓ BHUKOSH...

2025-11-24 11:07:55,911 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:07:55,916 : INFO - Processed catalog: National Family Health Survey-5 (NFHS-5) - India D...

✓ National Family Health Survey-5 (NFHS-5) - India Districts F...

2025-11-24 11:07:57,179 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:07:57,185 : INFO - Processed catalog: Startup Hub...

✓ Startup Hub...

2025-11-24 11:07:58,223 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:07:58,226 : INFO - Processed catalog: Answers Data of Rajya Sabha Questions for Session ...

✓ Answers Data of Rajya Sabha Questions for Session 254...

2025-11-24 11:08:05,671 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:08:05,675 : INFO - Processed catalog: Enrolment by Age and Class (UDISE plus)...

✓ Enrolment by Age and Class (UDISE plus)...

2025-11-24 11:08:06,760 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:08:06,766 : INFO - Processed catalog: UDYAM Registration (MSME Registration)...

✓ UDYAM Registration (MSME Registration)...

2025-11-24 11:08:08,870 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:08:08,873 : INFO - Processed catalog: National Family Health Survey (NFHS) - 5...

✓ National Family Health Survey (NFHS) - 5...

2025-11-24 11:08:15,450 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:08:15,455 : INFO - Processed catalog: Rainfall...

✓ Rainfall...

2025-11-24 11:08:22,076 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:08:22,078 : INFO - Processed catalog: Gross State Domestic Product at Current Prices...

✓ Gross State Domestic Product at Current Prices...

2025-11-24 11:08:22,307 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:08:22,314 : INFO - Processed catalog: Departure of Rainfall data...

✓ Departure of Rainfall data...

2025-11-24 11:08:31,658 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:08:31,661 : INFO - Processed catalog: All India Seasonal and Annual Temperature Series...

✓ All India Seasonal and Annual Temperature Series...

2025-11-24 11:08:33,169 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:08:33,172 : INFO - Processed catalog: Crime in India - 2019...

✓ Crime in India - 2019...

2025-11-24 11:08:36,190 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:08:36,193 : INFO - Processed catalog: Wholesale Price Index...

✓ Wholesale Price Index...

2025-11-24 11:08:43,923 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:08:43,928 : INFO - Processed catalog: All India Pincode Directory (Through WebService)...

✓ All India Pincode Directory (Through WebService)...

2025-11-24 11:08:52,663 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:08:52,670 : INFO - Processed catalog: Health indicator-wise monthly datasets at sub dist...

✓ Health indicator-wise monthly datasets at sub district level...

2025-11-24 11:08:57,989 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:08:57,994 : INFO - Processed catalog: MySpeed (Crowdsourced Mobile Data Speeds)...

✓ MySpeed (Crowdsourced Mobile Data Speeds)...

2025-11-24 11:09:02,449 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:09:02,452 : INFO - Processed catalog: Udyog Aadhaar Memorandum  ( MSME Registration )...

✓ Udyog Aadhaar Memorandum  ( MSME Registration )...

2025-11-24 11:09:03,123 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:09:03,130 : INFO - Processed catalog: List of MSME Registered Units  under Udyog Aadhaar...

✓ List of MSME Registered Units  under Udyog Aadhaar Memorandu...

2025-11-24 11:09:16,054 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:09:16,057 : INFO - Processed catalog: Rural Health Statistics - 2017...

✓ Rural Health Statistics - 2017...

2025-11-24 11:09:18,823 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:09:18,830 : INFO - Processed catalog: Voice Call Quality Customer Experience...

✓ Voice Call Quality Customer Experience...

2025-11-24 11:09:28,345 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:09:28,350 : INFO - Processed catalog: Yearly and Seasonal Frequency of Cyclones and Depr...

✓ Yearly and Seasonal Frequency of Cyclones and Depressions...

2025-11-24 11:09:35,110 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:09:35,115 : INFO - Processed catalog: Rural Health Statistics - 2016...

✓ Rural Health Statistics - 2016...

2025-11-24 11:09:37,136 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:09:37,139 : INFO - Processed catalog: District wise and month wise queries of farmers in...

✓ District wise and month wise queries of farmers in Kisan Cal...

2025-11-24 11:09:42,769 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:09:42,776 : INFO - Processed catalog: Historical Daily Ambient Air Quality Data...

✓ Historical Daily Ambient Air Quality Data...

2025-11-24 11:09:43,189 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:09:43,195 : INFO - Processed catalog: Rainfall in India...

✓ Rainfall in India...

2025-11-24 11:09:56,728 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:09:56,734 : INFO - Processed catalog: Climatology data of Important Cities...

✓ Climatology data of Important Cities...

2025-11-24 11:10:09,275 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:10:09,278 : INFO - Processed catalog: Real time Air Quality Index...

✓ Real time Air Quality Index...

2025-11-24 11:10:10,293 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:10:10,295 : INFO - Processed catalog: Rural Health Statistics - 2015...

✓ Rural Health Statistics - 2015...

2025-11-24 11:10:19,193 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:10:19,197 : INFO - Processed catalog: Foreign Direct Investment (FDI) Equity Inflows...

✓ Foreign Direct Investment (FDI) Equity Inflows...

2025-11-24 11:10:24,315 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:10:24,321 : INFO - Processed catalog: Company Master Data...

✓ Company Master Data...

2025-11-24 11:10:26,237 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:10:26,241 : INFO - Processed catalog: Details of Poultry Farms and Poultry Birds in Farm...

✓ Details of Poultry Farms and Poultry Birds in Farms...

2025-11-24 11:10:30,427 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:10:30,431 : INFO - Processed catalog: All India Seasonal and Annual Min/Max Temperature ...

✓ All India Seasonal and Annual Min/Max Temperature Series...

2025-11-24 11:10:31,099 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:10:31,103 : INFO - Processed catalog: Indian Railways Train Time Table...

✓ Indian Railways Train Time Table...

2025-11-24 11:10:45,108 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:10:45,113 : INFO - Processed catalog: All India Consumer Price Index (Rural/Urban)...

✓ All India Consumer Price Index (Rural/Urban)...

2025-11-24 11:10:48,842 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:10:48,844 : INFO - Processed catalog: Eight Core Industries...

✓ Eight Core Industries...

2025-11-24 11:10:52,080 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:10:52,083 : INFO - Processed catalog: Number of Newly Registered Motor Vehicles and Numb...

✓ Number of Newly Registered Motor Vehicles and Number of Regi...

2025-11-24 11:10:53,630 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:10:53,638 : INFO - Processed catalog: Number of Newly Registered Motor Vehicles and Numb...

✓ Number of Newly Registered Motor Vehicles and Number of Regi...

2025-11-24 11:10:55,827 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:10:55,830 : INFO - Processed catalog: District Level Household and Facility Survey (DLHS...

✓ District Level Household and Facility Survey (DLHS-4)...

2025-11-24 11:10:58,359 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:10:58,366 : INFO - Processed catalog: Number of Newly Registered Motor Vehicles and Numb...

✓ Number of Newly Registered Motor Vehicles and Number of Regi...

2025-11-24 11:11:08,858 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:11:08,876 : INFO - Processed catalog: Wholesale Price Index...

✓ Wholesale Price Index...

2025-11-24 11:11:16,574 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:11:16,580 : INFO - Processed catalog: State/UT wise total no of road accidents...

✓ State/UT wise total no of road accidents...

2025-11-24 11:11:21,173 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:11:21,180 : INFO - Processed catalog: Total Number of Registered Motor Vehicles in India...

✓ Total Number of Registered Motor Vehicles in India...

2025-11-24 11:11:21,698 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:11:21,776 : INFO - Processed catalog: State Level Consumer Price Index (Rural/Urban)...

✓ State Level Consumer Price Index (Rural/Urban)...

2025-11-24 11:11:23,031 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:11:23,034 : INFO - Processed catalog: Web Map Service (WMS) from Survey of India OSM Dat...

✓ Web Map Service (WMS) from Survey of India OSM Data and Bhuv...

2025-11-24 11:11:26,272 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:11:26,277 : INFO - Processed catalog: Quarterly Estimates of GDP at Current Prices...

✓ Quarterly Estimates of GDP at Current Prices...

2025-11-24 11:11:30,596 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:11:30,600 : INFO - Processed catalog: Gross State Domestic Product at Current Prices...

✓ Gross State Domestic Product at Current Prices...

2025-11-24 11:11:31,786 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:11:31,789 : INFO - Processed catalog: Digital Seismotectonic Atlas of India and its Envi...

✓ Digital Seismotectonic Atlas of India and its Environs...

2025-11-24 11:11:40,922 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:11:40,953 : INFO - Processed catalog: Consumption of Petroleum Products...

✓ Consumption of Petroleum Products...

2025-11-24 11:11:50,367 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:11:50,386 : INFO - Processed catalog: Import of Major Chemicals - Product-wise / Group-w...

✓ Import of Major Chemicals - Product-wise / Group-wise...

2025-11-24 11:11:52,010 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:11:52,013 : INFO - Processed catalog: Current daily price of various commodities from va...

✓ Current daily price of various commodities from various mark...

2025-11-24 11:11:59,065 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:11:59,071 : INFO - Processed catalog: Quarterly Estimates of GDP at Constant Prices...

✓ Quarterly Estimates of GDP at Constant Prices...

2025-11-24 11:12:00,949 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:12:00,956 : INFO - Processed catalog: District Rainfall Normal (in mm) Monthly, Seasonal...

✓ District Rainfall Normal (in mm) Monthly, Seasonal And Annua...

2025-11-24 11:12:04,197 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:12:04,203 : INFO - Processed catalog: Quarterly Estimates of GDP at Constant Prices...

✓ Quarterly Estimates of GDP at Constant Prices...

2025-11-24 11:12:11,614 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:12:11,618 : INFO - Processed catalog: District-wise, season-wise crop production statist...

✓ District-wise, season-wise crop production statistics...

✓ Complete! Results saved to /home/aakash/NIC/cdl-updated/nic-metadata-cleaning/data/metadata_cleaned_catalog_title_description.csv

In [27]:
def process_row_keyword(row):
    """Process a single catalog row - thread-safe, aligned with catalog prompt"""

    # --- helper to robustly read columns (handles leading/trailing spaces) ---
    def safe_get(key, default=""):
        if key in row:
            return row.get(key, default)
        for k in row.index:
            if isinstance(k, str) and k.strip() == key:
                return row.get(k, default)
        return default

    # Primary catalog fields
    title = extract_clean_value(safe_get("dcterms:title", ""))
    description = extract_clean_value(safe_get("dcterms:description", ""))
    subject = extract_clean_value(safe_get("dcterms:subject", ""))   # mapped to groups
    theme = extract_clean_value(safe_get("dcat:theme", ""))          # mapped to sectors
    keywords = extract_clean_value(safe_get("dcat:keyword", ""))     # existing keywords

    # Build metadata content string for LLM
    metadata_content = f'''
Catalog Title: {title}
Catalog Description: {description}

Existing Groups (dcterms:subject): {subject if subject else "Not specified"}
Existing Sectors (dcat:theme): {theme if theme else "Not specified"}
Existing Keywords (dcat:keyword): {keywords if keywords else "Not specified"}

TASK: Generate enhanced_keywords, sponsored_keywords, and primary sector for this catalog,
as per the system prompt. Output valid JSON only.
'''

    try:
        result = get_keywords(metadata_content)  # expects JSON per new prompt
        logging.info(f"Result is {result}")

    except Exception as e:
        logging.error(f"LLM failed for '{title}': {e}")
        result = {
            "generated_keywords": [],
            "sponsored_keywords": [],
            "sector": "Others",
            "processing_summary": {
                "keyword_logic": "",
                "sector_logic": "",
                "sponsored_keywords": "",
                "error": str(e)
            },
            "source_fields_used": []
        }

    processing_summary = result.get("processing_summary", {})

    return {
        # Original / context
        "original_title": title,
        "original_description": description[:500],
        "original_subject": subject,
        "original_theme": theme,
        "original_keywords": keywords,
        "metadata_input": metadata_content,

        # Generated outputs
        "generated_keywords": json.dumps(result.get("generated_keywords", [])),
        "sponsored_keywords": json.dumps(result.get("sponsored_keywords", [])),
        "sector": result.get("sector", "Others"),

        # Processing metadata
        "keyword_logic": processing_summary.get("keyword_logic", ""),
        "sector_logic": processing_summary.get("sector_logic", ""),
        "sponsored_keywords_logic": processing_summary.get("sponsored_keywords", ""),
        "source_fields_used": json.dumps(result.get("source_fields_used", [])),
        "llm_response": json.dumps(result)
    }


# --------------------------------------------------------------------
# Setup CSV file
output_file = "results_catalog_keywords.csv"
csv_lock = Lock()  # Thread-safe file writes

fieldnames = [
    # Originals / context
    "original_title",
    "original_description",
    "original_subject",
    "original_theme",
    "original_keywords",
    "metadata_input",

    # Generated
    "generated_keywords",
    "sponsored_keywords",
    "sector",

    # Summary/debug
    "keyword_logic",
    "sector_logic",
    "sponsored_keywords_logic",
    "source_fields_used",
    "llm_response"
]

with open(output_file, 'w', newline='', encoding='utf-8') as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()

# Parallel processing
results_array = []
max_workers = 8
rows_to_process = df.head(102)   # change to df for full run

with ThreadPoolExecutor(max_workers=max_workers) as executor:
    future_to_row = {
        executor.submit(process_row_keyword, row): idx
        for idx, row in rows_to_process.iterrows()
    }

    for future in as_completed(future_to_row):
        try:
            result_obj = future.result()
            results_array.append(result_obj)

            # Thread-safe incremental write
            with csv_lock:
                with open(output_file, 'a', newline='', encoding='utf-8') as f:
                    writer = csv.DictWriter(f, fieldnames=fieldnames)
                    writer.writerow(result_obj)

            print(
                f"TITLE: {result_obj['original_title']}\n"
                f"SECTOR: {result_obj['sector']}\n"
                f"KEYWORDS: {result_obj['generated_keywords']}\n"
                f"SPONSORED: {result_obj['sponsored_keywords']}\n\n✓ Written to CSV"
            )
            print("\n----------------------------\n")

        except Exception as e:
            logging.error(f"Row processing failed: {e}")

print(f"\n✓ Complete! Results saved to {output_file}")

2025-11-24 11:43:38,847 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:43:38,855 : INFO - Result is {'generated_keywords': ['RajyaSabha', 'QuestionsAnswers', 'Session260', 'ParliamentQueries', 'RajyaSabhaQA', 'ParliamentaryData', 'Session260QA', 'AnnexuresData'], 'sponsored_keywords': ['RajyaSabhaQuestions', 'Session260', 'ParliamentQA', 'QuestionsData'], 'sector': 'Governance & Administration', 'processing_summary': {'keyword_logic': 'Derived from the catalog title and description to create 6–10 layman-friendly CamelCase terms that reflect Rajya Sabha Q&A content, sessions, and related data while avoiding department names and overly generic terms.', 'sector_logic': 'The catalog centers on parliamentary questions/answers data, aligning with Governance & Administration as the primary domain; reflects the overall governance-oriented nature of Rajya Sabha proceedings.', 'sponsored_keywords': 'Chosen 3–5 terms that most closely map to the exact title focus (RajyaSabhaQuestions, Session260, ParliamentQA, QuestionsData) to maximize direct relevance and searchability.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword', 'dcterms:title', 'dcterms:description']}

TITLE: Answers Data of Rajya Sabha Questions for Session 260
SECTOR: Governance & Administration
KEYWORDS: ["RajyaSabha", "QuestionsAnswers", "Session260", "ParliamentQueries", "RajyaSabhaQA", "ParliamentaryData", "Session260QA", "AnnexuresData"]
SPONSORED: ["RajyaSabhaQuestions", "Session260", "ParliamentQA", "QuestionsData"]

✓ Written to CSV

----------------------------

2025-11-24 11:43:39,271 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:43:39,274 : INFO - Result is {'generated_keywords': ['PincodeBoundary', 'PostalBoundary', 'PostOfficeBoundary', 'PincodeMap', 'BoundaryGeoJson', 'PostalCodeData', 'PincodeDataset', 'PincodeLayer'], 'sponsored_keywords': ['GeoJsonBoundary', 'PincodeGeoJson', 'PostalBoundaryMap', 'PincodeData'], 'sector': 'Governance & Administration', 'processing_summary': {'keyword_logic': 'Derived 6–10 layman keywords from the catalog title and description focusing on Pincode boundaries, post office boundaries, and GeoJSON representation; used camelCase and kept terms concise (1–2 words).', 'sector_logic': "Selected Governance & Administration as the primary sector reflecting the catalog's administrative-geospatial nature related to postal boundaries and office locations.", 'sponsored_keywords': 'Chosen 3–4 terms that closely reflect the exact title components and data format: GeoJsonBoundary, PincodeGeoJson, PostalBoundaryMap, PincodeData; ensured they align with the title while remaining distinct from the enhanced keywords.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: All India Pincode Boundary Geo JSON
SECTOR: Governance & Administration
KEYWORDS: ["PincodeBoundary", "PostalBoundary", "PostOfficeBoundary", "PincodeMap", "BoundaryGeoJson", "PostalCodeData", "PincodeDataset", "PincodeLayer"]
SPONSORED: ["GeoJsonBoundary", "PincodeGeoJson", "PostalBoundaryMap", "PincodeData"]

✓ Written to CSV

----------------------------

2025-11-24 11:43:40,069 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:43:40,074 : INFO - Result is {'generated_keywords': ['PerformanceGrading', 'GradingIndex', 'EducationMetrics', 'EducationAssessment', 'SchoolPerformance', 'EducationAnalytics', 'LearningOutcomes', 'EducationQuality'], 'sponsored_keywords': ['PGI', 'PerformanceIndex', 'EducationIndex', 'GradingMetrics'], 'sector': 'Education', 'processing_summary': {'keyword_logic': 'Derived 8 layman-friendly keywords (CamelCase, 1-2 words) from the catalog title/description and domain context. Prioritized terms that reflect performance grading, index concepts, and education outcomes while avoiding administrative terms.', 'sector_logic': "Chose Education as primary sector because the PGI pertains to educational performance grading and district-level education assessment, aligning with the catalog's focus.", 'sponsored_keywords': "Selected 4 near-title terms that closely map to 'Performance Grading Index' and 'PGI' without duplicating the generated keywords: PGI, PerformanceIndex, EducationIndex, GradingMetrics."}, 'source_fields_used': ['dcterms:title', 'dcterms:description', 'dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: Performance Grading Index (PGI)
SECTOR: Education
KEYWORDS: ["PerformanceGrading", "GradingIndex", "EducationMetrics", "EducationAssessment", "SchoolPerformance", "EducationAnalytics", "LearningOutcomes", "EducationQuality"]
SPONSORED: ["PGI", "PerformanceIndex", "EducationIndex", "GradingMetrics"]

✓ Written to CSV

----------------------------

2025-11-24 11:43:40,869 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:43:40,882 : INFO - Result is {'generated_keywords': ['RuralWages', 'HundredDaysWages', 'GuaranteedEmployment', 'UnskilledLabour', 'RuralLivelihoods', 'PublicWorks', 'LivelihoodSecurity', 'RuralDevelopment'], 'sponsored_keywords': ['MGNREGA', 'EmploymentGuarantee', 'RuralEmployment', 'HundredDaysWages', 'PublicWorks'], 'sector': 'Rural Development', 'processing_summary': {'keyword_logic': "Derivation starts from the catalog's rural-employment focus: guaranteed wage employment for rural households and unskilled labour. 6–10 keywords were crafted in CamelCase to be user-friendly and to reflect core concepts (wages, guarantee, rural livelihoods, public works) while avoiding department names and overly generic terms.", 'sector_logic': "Chosen as the primary sector because the catalog centers on rural livelihood improvement through employment schemes, aligning with Rural Development and the catalog's existing Rural Development grouping.", 'sponsored_keywords': 'Selected 3–5 terms tightly tied to the exact title and core concepts of the act (MGNREGA, Employment Guarantee, Rural Employment, Hundred Days Wages, Public Works). These provide strong, title-aligned search terms while remaining distinct from the enhanced keywords.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: Mahatma Gandhi National Rural Employment Guarantee Act (MGNREGA)
SECTOR: Rural Development
KEYWORDS: ["RuralWages", "HundredDaysWages", "GuaranteedEmployment", "UnskilledLabour", "RuralLivelihoods", "PublicWorks", "LivelihoodSecurity", "RuralDevelopment"]
SPONSORED: ["MGNREGA", "EmploymentGuarantee", "RuralEmployment", "HundredDaysWages", "PublicWorks"]

✓ Written to CSV

----------------------------

2025-11-24 11:43:45,087 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:43:45,090 : INFO - Result is {'generated_keywords': ['IPCCrimes', 'ViolentCrimes', 'MurderCases', 'TheftCases', 'RobberyCases', 'KidnappingCases', 'RapeCases', 'ChildCrimes', 'ConvictionsRate', 'CustodialDeaths'], 'sponsored_keywords': ['Crime2022', 'CrimeData', 'PoliceCrimes', 'VictimStats'], 'sector': 'Governance & Administration', 'processing_summary': {'keyword_logic': "Enhanced keywords are 1–2 words in CamelCase reflecting the dataset's content: IPC crimes, violent crimes, murder, theft/robbery, kidnapping, rape, crimes against children, conviction rates, and custodial deaths. Terms are chosen for layman discoverability and avoid administrative or geographic terms.", 'sector_logic': "Primary sector chosen as Governance & Administration to align with the dataset's focus on policing, crime statistics, and criminal justice administration, which matches the catalog's overall domain.", 'sponsored_keywords': 'Sponsored keywords are 3–4 terms tightly tied to the catalog title and year: Crime2022 (year-specific), CrimeData (dataset nature), PoliceCrimes (policing focus), VictimStats (outcome/impact angle).'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: Crime in India - 2022
SECTOR: Governance & Administration
KEYWORDS: ["IPCCrimes", "ViolentCrimes", "MurderCases", "TheftCases", "RobberyCases", "KidnappingCases", "RapeCases", "ChildCrimes", "ConvictionsRate", "CustodialDeaths"]
SPONSORED: ["Crime2022", "CrimeData", "PoliceCrimes", "VictimStats"]

✓ Written to CSV

----------------------------

2025-11-24 11:43:48,576 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:43:48,583 : INFO - Result is {'generated_keywords': ['UnorganisedWorkers', 'EShramRegistration', 'SelfRegistration', 'DemographicData', 'WorkerProfiles', 'InformalWorkers', 'RegistrationData', 'WorkforceDemographics'], 'sponsored_keywords': ['EShramPortal', 'UnorganisedRegistration', 'WorkerDemographics', 'DemographicsProfile'], 'sector': 'Employment & Labour', 'processing_summary': {'keyword_logic': 'Generated 8 keywords (6-10) in CamelCase, each 1–2 words, reflecting unorganised workers, eShram registration, self-registration, and demographics. Avoided ministry names, administrative terms, and overly generic terms; anchored in title/description content.', 'sector_logic': "Primary sector chosen as Employment & Labour to align with the catalog's focus on unorganised workers and labour data, using the catalog publisher context and title.", 'sponsored_keywords': 'Selected 4 terms closely tied to the title: EShramPortal, UnorganisedRegistration, WorkerDemographics, DemographicsProfile.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: Demographic Data of Unorganised Workers registered on eShram portal
SECTOR: Employment & Labour
KEYWORDS: ["UnorganisedWorkers", "EShramRegistration", "SelfRegistration", "DemographicData", "WorkerProfiles", "InformalWorkers", "RegistrationData", "WorkforceDemographics"]
SPONSORED: ["EShramPortal", "UnorganisedRegistration", "WorkerDemographics", "DemographicsProfile"]

✓ Written to CSV

----------------------------

2025-11-24 11:43:53,350 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:43:53,355 : INFO - Result is {'generated_keywords': ['DisabilityData', 'PwDInfo', 'UDIDCard', 'DisabilityStats', 'DisabilityPortal', 'DemographicsDisability', 'SocioEconomic', 'DisabilityRecords'], 'sponsored_keywords': ['UDID', 'DisabilityID', 'UniqueDisability', 'DisabilityRegistry', 'DisabilityCard'], 'sector': 'Social Welfare', 'processing_summary': {'keyword_logic': 'Derived 6–8 layman keywords from the catalog title and description focusing on disability data, PwD demographics, UDID-related identifiers, card/portal aspects, and data records; ensured CamelCase with 1–2 conceptual words each; avoided administrative terms and country names.', 'sector_logic': 'Chose Social Welfare as the primary sector to reflect the catalog’s focus on disability data for welfare policy, services, and targeted interventions, aligning with the existing Social Development theme while remaining within the provided controlled vocabulary.', 'sponsored_keywords': 'Selected 3–5 terms that closely match the catalog title and core concept (UDID, DisabilityID, UniqueDisability, DisabilityRegistry, DisabilityCard) to maximize direct relevance and search alignment, ensuring they are distinct from the enhanced keywords.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: Unique Disability ID (UDID)
SECTOR: Social Welfare
KEYWORDS: ["DisabilityData", "PwDInfo", "UDIDCard", "DisabilityStats", "DisabilityPortal", "DemographicsDisability", "SocioEconomic", "DisabilityRecords"]
SPONSORED: ["UDID", "DisabilityID", "UniqueDisability", "DisabilityRegistry", "DisabilityCard"]

✓ Written to CSV

----------------------------

2025-11-24 11:43:56,177 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:43:56,179 : INFO - Result is {'generated_keywords': ['SignLanguage', 'SignLanguageDictionary', 'DeafEducation', 'HearingImpaired', 'CommunicationAccess', 'VisualLanguage', 'SpecialEducation', 'Accessibility', 'DeafCommunity'], 'sponsored_keywords': ['ISLDictionary', 'ISLResources', 'LearnSignLanguage', 'SignLanguageGuide'], 'sector': 'Education', 'processing_summary': {'keyword_logic': 'Derived from the catalog title and description, plus existing keywords, to produce 9 layman keywords that are 1–2 words and CamelCase. Focus is on ISL, sign language, deaf education, accessibility, and communication, while avoiding administrative terms, country names, or overly generic terms.', 'sector_logic': 'Primary sector selected as Education because the catalog centers on learning and teaching Indian Sign Language, resources for educators/parents, and accessibility in education for the Deaf; aligns with the catalog’s educational objective rather than health or governance.', 'sponsored_keywords': 'Chosen to tightly reflect the core elements of the title (ISL, Dictionary) while remaining concise (1–2 words). The terms ISLDictionary, ISLResources, LearnSignLanguage, and SignLanguageGuide directly map to the title concepts without duplicating enhanced keywords.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword', 'dcterms:title', 'dcterms:description']}

TITLE: Indian Sign Language Dictionary
SECTOR: Education
KEYWORDS: ["SignLanguage", "SignLanguageDictionary", "DeafEducation", "HearingImpaired", "CommunicationAccess", "VisualLanguage", "SpecialEducation", "Accessibility", "DeafCommunity"]
SPONSORED: ["ISLDictionary", "ISLResources", "LearnSignLanguage", "SignLanguageGuide"]

✓ Written to CSV

----------------------------

2025-11-24 11:44:04,113 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:44:04,116 : INFO - Result is {'generated_keywords': ['ElephantConservation', 'HabitatProtection', 'ElephantPopulation', 'HumanElephantConflict', 'CaptiveElephants', 'ElephantReserves', 'ElephantHabitat', 'HabitatRestoration'], 'sponsored_keywords': ['ElephantReserve', 'PopulationStatus', 'ProjectElephant', 'HabitatConservation'], 'sector': 'Environment', 'processing_summary': {'keyword_logic': "Enhanced keywords are 1–2 CamelCase terms that reflect the catalog's elephant conservation focus, habitat protection, population status, human-elephant conflict, and captive welfare. They derive from the title and description and align with the existing subject (Elephant) and the Environment theme, ensuring layman-friendly discoverability without administrative terms.", 'sector_logic': "The catalog centers on elephant conservation and habitat protection, placing it firmly within the Environment sector as the primary domain. This aligns with the catalog's description of Project Elephant and habitat conservation objectives.", 'sponsored_keywords': 'Sponsored terms are 3–5 concise terms directly tied to the title (Elephant Reserve and Population Status) but not exact duplicates of enhanced keywords. They emphasize ElephantReserve, PopulationStatus, ProjectElephant, and HabitatConservation to capture core title concepts.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}
2025-11-24 11:44:04,304 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:44:04,306 : INFO - Result is {'generated_keywords': ['CrudeOil', 'RefineryOutput', 'OilProcessing', 'RefiningThroughput', 'PetroleumRefinery', 'MonthlyOil', 'ThroughputMetrics', 'RefineryCapacity'], 'sponsored_keywords': ['CrudeOilProcessed', 'RefineryThroughput', 'OilThroughput', 'MonthlyRefining', 'RefineriesOutput'], 'sector': 'Energy', 'processing_summary': {'keyword_logic': 'Derived 8 layman-friendly keywords by extracting core concepts from the catalog title and description: crude oil, refinery, processing/throughput, monthly data, and refinery capacity. Each term is kept to 1–2 words in CamelCase to maximize discovery while avoiding administrative or overly generic terms.', 'sector_logic': 'Selected Energy as the primary sector because the catalog centers on crude oil processed by refineries, which falls squarely in the energy domain and aligns with DCAT-India vocabulary. This avoids the outdated or overly broad Non Renewable label and provides a precise domain focus.', 'sponsored_keywords': "Chosen 5 terms that most closely mirror the catalog title 'Crude Oil Processed by Refineries', using CamelCase, 1–2 words, and ensuring they differ from the enhanced keywords. These terms emphasize the exact title concepts like crude oil processing and refinery throughput."}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: Elephant Reserve and Population Status
SECTOR: Environment
KEYWORDS: ["ElephantConservation", "HabitatProtection", "ElephantPopulation", "HumanElephantConflict", "CaptiveElephants", "ElephantReserves", "ElephantHabitat", "HabitatRestoration"]
SPONSORED: ["ElephantReserve", "PopulationStatus", "ProjectElephant", "HabitatConservation"]

✓ Written to CSV

----------------------------

TITLE: Crude Oil Processed by Refineries
SECTOR: Energy
KEYWORDS: ["CrudeOil", "RefineryOutput", "OilProcessing", "RefiningThroughput", "PetroleumRefinery", "MonthlyOil", "ThroughputMetrics", "RefineryCapacity"]
SPONSORED: ["CrudeOilProcessed", "RefineryThroughput", "OilThroughput", "MonthlyRefining", "RefineriesOutput"]

✓ Written to CSV

----------------------------

2025-11-24 11:44:04,591 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:44:04,593 : INFO - Result is {'generated_keywords': ['YouthHostel', 'HostelConstruction', 'PublicHostel', 'YouthAccommodation', 'LeaseArrangement', 'LongTermLease', 'GovernmentPartnership', 'PublicInfrastructure', 'YouthWelfare', 'YouthHousing'], 'sponsored_keywords': ['YouthHostel', 'HostelScheme', 'HostelConstruction', 'PublicHostel'], 'sector': 'Governance & Administration', 'processing_summary': {'keyword_logic': 'Derived from the catalog title and description focusing on youth hostels, construction, land lease and joint government involvement. Generated keywords emphasize the core concepts (hostels, construction, lease, public infrastructure, welfare) in CamelCase and 1–2 word limits.', 'sector_logic': 'Selected Governance & Administration as the primary sector because the catalog describes a government scheme involving central and state partnership and administrative arrangements for hosting youth hostels.', 'sponsored_keywords': 'Chosen to closely reflect the exact title concepts (Youth Hostel Scheme) while remaining concise, with 1–2 CamelCase terms that map to the core title ideas (YouthHostel, HostelScheme, HostelConstruction, PublicHostel).'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword', 'dcterms:title', 'dcterms:description']}

TITLE: Youth Hostel Scheme
SECTOR: Governance & Administration
KEYWORDS: ["YouthHostel", "HostelConstruction", "PublicHostel", "YouthAccommodation", "LeaseArrangement", "LongTermLease", "GovernmentPartnership", "PublicInfrastructure", "YouthWelfare", "YouthHousing"]
SPONSORED: ["YouthHostel", "HostelScheme", "HostelConstruction", "PublicHostel"]

✓ Written to CSV

----------------------------

2025-11-24 11:44:07,663 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:44:07,666 : INFO - Result is {'generated_keywords': ['ClassXII', 'ResultStatistics', 'CBSEResults', 'XIIResults', 'BoardExams', 'ExamStatistics', 'ScoreStatistics', 'BoardResults'], 'sponsored_keywords': ['CBSEScorecard', 'XIIStatistics', 'BoardScores', 'ClassXIIResults'], 'sector': 'Education', 'processing_summary': {'keyword_logic': 'Derived 6–10 CamelCase keywords from the catalog title/description highlighting the CBSE Class XII results and statistics concepts (e.g., ClassXII, ResultStatistics, CBSEResults, XIIResults, BoardExams, ExamStatistics, ScoreStatistics, BoardResults). Chose terms that are specific to the dataset content while avoiding generic or administrative terms.', 'sector_logic': 'The catalog is explicitly about CBSE Class XII result statistics, which is an education-related topic. The existing theme is Education, so Education is selected as the primary sector to reflect the catalog’s domain.', 'sponsored_keywords': 'Selected 4 terms tightly aligned with the title for strong search relevance but not exact duplicates of the generated keywords: CBSEScorecard, XIIStatistics, BoardScores, ClassXIIResults. These emphasize title-relevant concepts (CBSE, XII, results) while ensuring variety from the generated keywords.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: CBSE Result Statistics Class XII
SECTOR: Education
KEYWORDS: ["ClassXII", "ResultStatistics", "CBSEResults", "XIIResults", "BoardExams", "ExamStatistics", "ScoreStatistics", "BoardResults"]
SPONSORED: ["CBSEScorecard", "XIIStatistics", "BoardScores", "ClassXIIResults"]

✓ Written to CSV

----------------------------

2025-11-24 11:44:13,463 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:44:13,465 : INFO - Result is {'generated_keywords': ['ParliamentQuestions', 'RajyaSabhaAnswers', 'Session259Data', 'QuestionsAndAnswers', 'PublicQuestioning', 'GovernanceRecords', 'AnswerArchive', 'SessionQuestions'], 'sponsored_keywords': ['RajyaSabha', 'Session259Qs', 'QuestionsData', 'ParliamentAnswers', 'SessionArchive'], 'sector': 'Governance & Administration', 'processing_summary': {'keyword_logic': 'Generated 8 layman-friendly CamelCase keywords by deriving from the catalog title and description (Parliament/Rajya Sabha questions and answers, session 259, data/archive concepts) while avoiding department names and overly generic terms. Ensured 1–2 concept units per keyword and kept terms discoverable and content-reflective.', 'sector_logic': 'Selected Governance & Administration as the primary sector because the catalog aggregates Rajya Sabha questions and answers across ministries/departments, representing the governing/administrative domain of Parliament-related data.', 'sponsored_keywords': 'Chosen 5 highly title-aligned terms directly tied to the catalog title (RajyaSabha, Session259Qs, QuestionsData, ParliamentAnswers, SessionArchive) to maximize exact-match relevance while remaining distinct from the generated keywords.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: Answers Data of Rajya Sabha Questions for Session 259
SECTOR: Governance & Administration
KEYWORDS: ["ParliamentQuestions", "RajyaSabhaAnswers", "Session259Data", "QuestionsAndAnswers", "PublicQuestioning", "GovernanceRecords", "AnswerArchive", "SessionQuestions"]
SPONSORED: ["RajyaSabha", "Session259Qs", "QuestionsData", "ParliamentAnswers", "SessionArchive"]

✓ Written to CSV

----------------------------

2025-11-24 11:44:21,018 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:44:21,020 : INFO - Result is {'generated_keywords': ['OilImports', 'OilExports', 'PetroleumTrade', 'EnergySecurity', 'CrudeOil', 'PetroleumProducts', 'OilMarket', 'FuelPolicy', 'PetroleumMarket', 'ImportExport'], 'sponsored_keywords': ['PetroleumImports', 'PetroleumExports', 'OilTrade', 'ImportExport'], 'sector': 'Energy', 'processing_summary': {'keyword_logic': 'Derived 6–10 layman-friendly CamelCase keywords that reflect the catalog focus on import/export of petroleum products, emphasizing petroleum/oil trade, energy implications, and market/policy aspects. Chose terms that are easily discoverable, avoid administrative or overly generic terms, and ensure each keyword is 1–2 words in CamelCase.', 'sector_logic': "Selected Energy as the primary sector to capture the catalog's core domain (petroleum/non-renewable energy trade). This aligns with the existing Non Renewable theme and typical DCAT-AP mappings for energy-related trade catalogs.", 'sponsored_keywords': 'Chosen 3–5 strongest terms that directly map to the catalog title (Import & Export of Petroleum Products). Focused on precise title relevance while ensuring slight distinctness from enhanced keywords (e.g., PetroleumImports vs OilImports).'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: Import & Export of Petroleum Products
SECTOR: Energy
KEYWORDS: ["OilImports", "OilExports", "PetroleumTrade", "EnergySecurity", "CrudeOil", "PetroleumProducts", "OilMarket", "FuelPolicy", "PetroleumMarket", "ImportExport"]
SPONSORED: ["PetroleumImports", "PetroleumExports", "OilTrade", "ImportExport"]

✓ Written to CSV

----------------------------

2025-11-24 11:44:23,118 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:44:23,126 : INFO - Result is {'generated_keywords': ['PetroleumConsumption', 'LPGConsumption', 'HSDConsumption', 'ATFConsumption', 'NaphthaUsage', 'BitumenUsage', 'LubricantsGreases', 'PetroleumCokeUsage', 'FuelOilConsumption'], 'sponsored_keywords': ['PetroleumProducts', 'ProductConsumption', 'LPGUsage', 'ATFUsage', 'PetroleumCoke'], 'sector': 'Energy', 'processing_summary': {'keyword_logic': 'EnhancedKeywords were generated by extracting concrete, discoverable terms directly tied to the catalog’s content (types of petroleum products and their consumption). Each term is kept to 1–2 words and expressed in CamelCase to maximize ease of discovery while avoiding administrative or overly generic terms. The nine keywords cover major product categories listed in the description (e.g., LPG, HSD, ATF, Naphtha, Bitumen, Lubricants/Greases, Petroleum Coke, Fuel Oil) as well as overall petroleum consumption concepts.', 'sector_logic': 'The catalog revolves around the consumption/usage of petroleum products, which squarely falls under the Energy sector. Despite a current theme suggesting Power and Energy, the primary domain for this catalog is energy-related consumption of petroleum products, so Energy is selected as the primary sector.', 'sponsored_keywords': 'Sponsored keywords were chosen to closely mirror the exact catalog title while being concise and highly searchable. They are 3–5 terms, 1–2 words each, camel-cased, and differ from the enhanced keywords to avoid duplication, focusing on core title concepts like PetroleumProducts and ProductConsumption, plus high-salience terms such as LPGUsage, ATFUsage, and PetroleumCoke.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: Consumption of Petroleum Products
SECTOR: Energy
KEYWORDS: ["PetroleumConsumption", "LPGConsumption", "HSDConsumption", "ATFConsumption", "NaphthaUsage", "BitumenUsage", "LubricantsGreases", "PetroleumCokeUsage", "FuelOilConsumption"]
SPONSORED: ["PetroleumProducts", "ProductConsumption", "LPGUsage", "ATFUsage", "PetroleumCoke"]

✓ Written to CSV

----------------------------

2025-11-24 11:44:23,854 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:44:23,857 : INFO - Result is {'generated_keywords': ['GroundWater', 'WaterLevel', 'GroundWaterLevel', 'GroundWaterData', 'MonsoonTrends', 'TimeSeriesData', 'AquiferMonitoring', 'WaterTableData'], 'sponsored_keywords': ['GroundWaterLevelData', 'WaterLevelData', 'PreMonsoonData', 'MonsoonVariation'], 'sector': 'Water Resources', 'processing_summary': {'keyword_logic': 'Enhanced keywords were derived from the catalog title, description, and existing subjects/themes to capture groundwater focus, data aspects, seasonal aspects (monsoon), and data characteristics in a compact CamelCase form. 6–10 terms balance specificity with discoverability while avoiding ministry names and broad administrative terms.', 'sector_logic': 'The catalog centers on groundwater data under a national water management program, placing it squarely in the Water Resources sector as the primary domain for the dataset collection.', 'sponsored_keywords': 'Selected 3–5 terms that directly mirror the catalog title’s emphasis on groundwater level data and monsoon-season datasets, ensuring each is distinct from the enhanced keywords and succinctly queryable.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: Ground Water Level Data under Atal Bhujal Yojana
SECTOR: Water Resources
KEYWORDS: ["GroundWater", "WaterLevel", "GroundWaterLevel", "GroundWaterData", "MonsoonTrends", "TimeSeriesData", "AquiferMonitoring", "WaterTableData"]
SPONSORED: ["GroundWaterLevelData", "WaterLevelData", "PreMonsoonData", "MonsoonVariation"]

✓ Written to CSV

----------------------------

2025-11-24 11:44:30,412 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:44:30,418 : INFO - Result is {'generated_keywords': ['PatentPublication', 'GrantedPatent', 'InventionTitle', 'PatenteeNames', 'ApplicationNumber', 'FilingDate', 'PatentOffice', 'PublicationWeek', 'PatentDetails'], 'sponsored_keywords': ['PatentApplication', 'PatentFiling', 'GrantDetails', 'PatenteeInfo'], 'sector': 'Science & Technology', 'processing_summary': {'keyword_logic': 'Derived 6–10 layman-friendly keywords from the catalog’s content: patent publication details, granted patents, invention titles, patentee names, official identifiers (application number), filing dates, and weekly publication cadence. Terms are kept to 1–2 words in CamelCase and focus on the catalog’s actual content while avoiding administrative or overly generic terms.', 'sector_logic': 'Selected Science & Technology as the primary sector because the catalog centers on patent publications and technological inventions, aligning with the catalog’s emphasis on invention disclosures and patent grants within a tech/innovation domain.', 'sponsored_keywords': 'Sponsored keywords target exact-title relevance with 3–5 terms. They emphasize the core notion of patent filings and grant-related details that appear in the catalog title, while remaining distinct from the enhanced keyword set.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword', 'dcterms:title', 'dcterms:description']}

TITLE: Patent Application
SECTOR: Science & Technology
KEYWORDS: ["PatentPublication", "GrantedPatent", "InventionTitle", "PatenteeNames", "ApplicationNumber", "FilingDate", "PatentOffice", "PublicationWeek", "PatentDetails"]
SPONSORED: ["PatentApplication", "PatentFiling", "GrantDetails", "PatenteeInfo"]

✓ Written to CSV

----------------------------

2025-11-24 11:44:35,094 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:44:35,096 : INFO - Result is {'generated_keywords': ['TeleLaw', 'JusticeAccess', 'LegalInfo', 'VideoCounsel', 'OnlineLegalAid', 'RemoteCounsel', 'DigitalJustice', 'VirtualLegalAid', 'PublicLegalInfo'], 'sponsored_keywords': ['TeleLaw', 'AccessToJustice', 'VideoConferencing', 'HolisticJustice', 'Disha'], 'sector': 'Governance & Administration', 'processing_summary': {'keyword_logic': 'Derived from the catalog title and description, focusing on user-facing concepts such as tele-based legal advice, access to justice, and ICT-enabled legal services. 6–10 CamelCase terms were selected to be easily discoverable while avoiding departmental names and overly generic terms.', 'sector_logic': 'Primary sector chosen as Governance & Administration to reflect the catalog’s focus on public service delivery, justice access, and ICT-enabled governance within the DISHA program.', 'sponsored_keywords': 'Selected 3–5 terms most tightly tied to the title and core concepts: TeleLaw (core term from title), AccessToJustice (foundation of the program), VideoConferencing (delivery method), HolisticJustice (scope), Disha (program acronym)'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: Tele-Law Program under Designing Innovative Solution for Holistic Access to Justice (DISHA)
SECTOR: Governance & Administration
KEYWORDS: ["TeleLaw", "JusticeAccess", "LegalInfo", "VideoCounsel", "OnlineLegalAid", "RemoteCounsel", "DigitalJustice", "VirtualLegalAid", "PublicLegalInfo"]
SPONSORED: ["TeleLaw", "AccessToJustice", "VideoConferencing", "HolisticJustice", "Disha"]

✓ Written to CSV

----------------------------

2025-11-24 11:44:41,442 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:44:41,445 : INFO - Result is {'generated_keywords': ['QuarterlyEmployment', 'EstablishmentBased', 'WorkforceTrends', 'EmploymentData', 'LabourStatistics', 'JobMarket', 'WorkforceSurvey', 'EmploymentIndicators'], 'sponsored_keywords': ['QuarterlySurvey', 'EmploymentSurvey', 'WorkforceData'], 'sector': 'Employment & Labour', 'processing_summary': {'keyword_logic': 'Enhanced keywords were created by extracting the catalog’s core focus from the title and description (quarterly, employment, establishment-based) and mapping to layman-friendly, CamelCase terms that are not administrative or India-specific. The set includes workforce and labour-related concepts to improve discoverability for users seeking employment data.', 'sector_logic': "The catalog centers on employment measurements across establishments, aligning with the 'Employment & Labour' sector as the primary domain, which captures the catalog’s overarching purpose without drifting into unrelated areas.", 'sponsored_keywords': 'Sponsored keywords are selected to closely reflect the catalog title while remaining distinct from generated keywords. They emphasize direct title relevance (QuarterlySurvey, EmploymentSurvey) and include a data-centric term (WorkforceData) to capture the dataset’s essence.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: Quarterly Employment Survey (QES)
SECTOR: Employment & Labour
KEYWORDS: ["QuarterlyEmployment", "EstablishmentBased", "WorkforceTrends", "EmploymentData", "LabourStatistics", "JobMarket", "WorkforceSurvey", "EmploymentIndicators"]
SPONSORED: ["QuarterlySurvey", "EmploymentSurvey", "WorkforceData"]

✓ Written to CSV

----------------------------

2025-11-24 11:44:44,775 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:44:44,777 : INFO - Result is {'generated_keywords': ['CognizableCrimes', 'MurderCases', 'RapeCases', 'TheftCases', 'KidnappingCases', 'ViolentCrimes', 'VictimData', 'CustodialRape', 'JuvenileDelinquency'], 'sponsored_keywords': ['CrimeData2021', 'Year2021Crimes', 'CrimeOverview', 'YearlyCrimeStats'], 'sector': 'Governance & Administration', 'processing_summary': {'keyword_logic': 'Generated 9 layman-friendly keywords in CamelCase by extracting core content areas from the title and description: crime types (e.g., MurderCases, TheftCases), victim-related concepts (VictimData), and accountability/process themes (CustodialRape, JuvenileDelinquency). Each term is 1–2 words in CamelCase and avoids department names or overly generic terms.', 'sector_logic': 'Chosen primary sector reflects the catalog’s governance, law and order, and police-administration focus, aligning with DCAT-India sector conventions for catalogs that describe crime statistics and policing data.', 'sponsored_keywords': "Selected 4 terms that directly echo the catalog title while remaining distinct from enhanced keywords: CrimeData2021, Year2021Crimes, CrimeOverview, YearlyCrimeStats. These emphasize the title's annual crime data framing and provide precise retrieval anchors."}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: Crime in India - 2021
SECTOR: Governance & Administration
KEYWORDS: ["CognizableCrimes", "MurderCases", "RapeCases", "TheftCases", "KidnappingCases", "ViolentCrimes", "VictimData", "CustodialRape", "JuvenileDelinquency"]
SPONSORED: ["CrimeData2021", "Year2021Crimes", "CrimeOverview", "YearlyCrimeStats"]

✓ Written to CSV

----------------------------

2025-11-24 11:44:47,711 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:44:47,716 : INFO - Result is {'generated_keywords': ['RajyaSabhaQuestions', 'Session258Answers', 'ParliamentAnswers', 'QuestionsAndAnswers', 'RajyaSabhaData', 'DataOnQuestions', 'Session258Data', 'QuestionsArchive'], 'sponsored_keywords': ['RajyaSabha', 'Session258', 'QuestionAnswers', 'ParliamentData'], 'sector': 'Governance & Administration', 'processing_summary': {'keyword_logic': 'Derived from the catalog title and description to reflect the core content: questions and answers from Rajya Sabha session 258 across ministries/departments. 6–10 CamelCase keywords were created to be layman-friendly while avoiding department names and generic terms. Included terms cover the legislative context (RajyaSabha, Parliament), session reference (Session258), data/QA orientation (QuestionsAndAnswers, DataOnQuestions), and archival/data framing (QuestionsArchive, Session258Data).', 'sector_logic': 'The catalog centers on parliamentary Q&A data and governance-related information across ministries, indicating a primary focus on governance and administration rather than sectoral domains like health or finance. Therefore, Governance & Administration is chosen as the primary sector to reflect the catalog’s overarching domain.', 'sponsored_keywords': 'Selected 4 terms tightly tied to the title: RajyaSabha (house referenced in the title), Session258 (session identifier), QuestionAnswers (core Q&A concept from the title), ParliamentData (data context from the title). These are distinct from the enhanced keywords to avoid duplication while remaining highly relevant.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword', 'dcterms:title', 'dcterms:description']}

TITLE: Answers Data of Rajya Sabha Questions for Session 258
SECTOR: Governance & Administration
KEYWORDS: ["RajyaSabhaQuestions", "Session258Answers", "ParliamentAnswers", "QuestionsAndAnswers", "RajyaSabhaData", "DataOnQuestions", "Session258Data", "QuestionsArchive"]
SPONSORED: ["RajyaSabha", "Session258", "QuestionAnswers", "ParliamentData"]

✓ Written to CSV

----------------------------

2025-11-24 11:44:50,050 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:44:50,055 : INFO - Result is {'generated_keywords': ['Dams', 'Barrages', 'Powerhouses', 'Weirs', 'Anicuts', 'Lifts', 'BoundaryMaps', 'HydroSites'], 'sponsored_keywords': ['WaterProjects', 'ProjectBoundaries', 'BoundaryMaps', 'HydroProjects'], 'sector': 'Water Resources', 'processing_summary': {'keyword_logic': 'Derived from the catalog title and description: identify key water infrastructure elements (dams, barrages, powerhouses, weirs, anicuts, lifts) and translate them into concise, layman-friendly CamelCase terms. Added non-technical, domain-relevant terms like BoundaryMaps and HydroSites to reflect boundary-focused shapefile content, while avoiding administrative or overly generic terms.', 'sector_logic': 'The catalog centers on boundaries and infrastructure of water resource projects across the country, which aligns with the Water Resources sector in the DCAT-India scheme as the primary domain for this collection.', 'sponsored_keywords': 'Selected 4 highly title-aligned terms that closely reflect the catalog’s essence: WaterProjects, ProjectBoundaries, BoundaryMaps, HydroProjects. These are 1–2 word CamelCase terms designed to strongly match the catalog title while remaining distinct from the broader generated keywords.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword', 'dcterms:title', 'dcterms:description']}

TITLE: Boundaries of Water Resources Projects
SECTOR: Water Resources
KEYWORDS: ["Dams", "Barrages", "Powerhouses", "Weirs", "Anicuts", "Lifts", "BoundaryMaps", "HydroSites"]
SPONSORED: ["WaterProjects", "ProjectBoundaries", "BoundaryMaps", "HydroProjects"]

✓ Written to CSV

----------------------------

2025-11-24 11:44:54,152 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:44:54,162 : INFO - Result is {'generated_keywords': ['BasinBoundaries', 'SubBasin', 'Watershed', 'Catchments', 'BasinWatersheds', 'WatershedBoundaries', 'DrainageBasins', 'HydrologicalBoundaries'], 'sponsored_keywords': ['HydrologicalBoundaries', 'BasinWatersheds', 'WatershedBoundaries', 'CatchmentBoundaries', 'DrainageBasins'], 'sector': 'Water Resources', 'processing_summary': {'keyword_logic': 'Derived from the catalog title and description. Extracted core hydrological features (basins, sub-basins, watersheds, catchments, drainage basins) and reformatted into CamelCase 1–2 word tokens to improve discoverability while avoiding administrative terms.', 'sector_logic': 'The catalog centers on hydrological features and water-related boundaries, aligning with the Water Resources sector as the primary domain. Existing themes related to surface and groundwater corroborate this selection.', 'sponsored_keywords': 'Selected to closely mirror the catalog title with high semantic relevance (HydrologicalBoundaries, BasinWatersheds, WatershedBoundaries, CatchmentBoundaries, DrainageBasins) while remaining distinct from the generated keywords.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: Hydrological Boundaries
SECTOR: Water Resources
KEYWORDS: ["BasinBoundaries", "SubBasin", "Watershed", "Catchments", "BasinWatersheds", "WatershedBoundaries", "DrainageBasins", "HydrologicalBoundaries"]
SPONSORED: ["HydrologicalBoundaries", "BasinWatersheds", "WatershedBoundaries", "CatchmentBoundaries", "DrainageBasins"]

✓ Written to CSV

----------------------------

2025-11-24 11:45:03,490 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:45:03,496 : INFO - Result is {'generated_keywords': ['RegionBoundaries', 'AgroClimatic', 'AgroEcological', 'Hydroelectrical', 'WaterResources', 'RegionalMaps', 'ClimateZones', 'SpatialBoundaries', 'ZoneBoundaries', 'HydrologyAtlas'], 'sponsored_keywords': ['BoundaryMaps', 'HydroZones', 'AgroZones', 'RegionalBoundaries'], 'sector': 'Water Resources', 'processing_summary': {'keyword_logic': 'Derived from the catalog title and description emphasizing region boundaries and the agro-climatic, agro-ecological, and hydroelectrical context. Generated 10 CamelCase keywords that are consumer-friendly and reflect the content (not using administrative terms).', 'sector_logic': 'Primary sector selected as Water Resources because the catalog centers on geographic boundaries related to groundwater, surface water, and hydroelectric/region-based classifications, aligning with water resource domain.', 'sponsored_keywords': 'Chosen 3–4 terms that closely mirror the catalog title concepts (boundaries and regional mapping) while remaining distinct from the enhanced keywords to provide precise title-aligned search terms.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword', 'dcterms:title', 'dcterms:description']}

TITLE: Boundaries of Region
SECTOR: Water Resources
KEYWORDS: ["RegionBoundaries", "AgroClimatic", "AgroEcological", "Hydroelectrical", "WaterResources", "RegionalMaps", "ClimateZones", "SpatialBoundaries", "ZoneBoundaries", "HydrologyAtlas"]
SPONSORED: ["BoundaryMaps", "HydroZones", "AgroZones", "RegionalBoundaries"]

✓ Written to CSV

----------------------------

2025-11-24 11:45:12,691 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:45:12,697 : INFO - Result is {'generated_keywords': ['YouthTobacco', 'SecondhandSmoke', 'TobaccoAccess', 'MarketingExposure', 'CessationSupport', 'TobaccoAwareness', 'TobaccoKnowledge', 'TobaccoAttitudes', 'SchoolHealth', 'TobaccoUse'], 'sponsored_keywords': ['GlobalYouth', 'TobaccoSurvey', 'GytsFour', 'GytsStudy'], 'sector': 'Health', 'processing_summary': {'keyword_logic': 'Generated 6–10 layman keywords in CamelCase (1–2 words each) derived from the catalog title/description and core content: youth tobacco focus, health implications, exposure, access, anti-tobacco information, knowledge and attitudes, and school-based context.', 'sector_logic': 'Primary sector chosen as Health because the catalog centers on youth tobacco use and health outcomes, aligned with the MoHFW context and national health survey framing.', 'sponsored_keywords': "Chosen 3–5 terms most tightly tied to the title 'Global Youth Tobacco Survey (GYTS-4)': GlobalYouth and TobaccoSurvey reflect the core concepts; GytsFour signals the round; GytsStudy extends relevance while staying title-aligned."}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword', 'dcterms:title', 'dcterms:description']}

TITLE: Global Youth Tobacco Survey (GYTS-4)
SECTOR: Health
KEYWORDS: ["YouthTobacco", "SecondhandSmoke", "TobaccoAccess", "MarketingExposure", "CessationSupport", "TobaccoAwareness", "TobaccoKnowledge", "TobaccoAttitudes", "SchoolHealth", "TobaccoUse"]
SPONSORED: ["GlobalYouth", "TobaccoSurvey", "GytsFour", "GytsStudy"]

✓ Written to CSV

----------------------------

2025-11-24 11:45:14,666 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:45:14,670 : INFO - Result is {'generated_keywords': ['ReservoirLevels', 'WaterStorage', 'ReservoirData', 'HydrologyData', 'SurfaceWater', 'StorageVolume', 'DailyData', 'DamData'], 'sponsored_keywords': ['ReservoirStatus', 'DamLevels', 'WaterMonitoring', 'ReservoirMonitoring'], 'sector': 'Water Resources', 'processing_summary': {'keyword_logic': 'Enhanced keywords are derived from the catalog’s focus on reservoir-level water data. They use CamelCase, are 1–2 words where possible, and emphasize content elements such as reservoir levels, storage, data language (hydrology, surface water), and related physical quantities (volume) without including administrative terms or department names.', 'sector_logic': 'The catalog clearly centers on water resources, with content describing reservoir levels and nationwide water storage. Given the publisher (National Water Informatics Centre) and the dataset scope, Water Resources is the most appropriate primary sector instead of more generic categories.', 'sponsored_keywords': "Sponsored keywords are 3–4 terms tightly tied to the catalog title 'Reservoir' but chosen to be distinct from the enhanced keywords. They reflect exact title-relevant concepts like reservoir status and monitoring (DamLevels, ReservoirStatus, WaterMonitoring, ReservoirMonitoring) to capture common search intents while avoiding verbatim duplication with enhanced keywords."}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: Reservoir
SECTOR: Water Resources
KEYWORDS: ["ReservoirLevels", "WaterStorage", "ReservoirData", "HydrologyData", "SurfaceWater", "StorageVolume", "DailyData", "DamData"]
SPONSORED: ["ReservoirStatus", "DamLevels", "WaterMonitoring", "ReservoirMonitoring"]

✓ Written to CSV

----------------------------

2025-11-24 11:45:15,569 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:45:15,573 : INFO - Result is {'generated_keywords': ['StartupRecognition', 'SectorWise', 'StateWise', 'YearWise', 'StartupCounts', 'SectorDistribution', 'StateDistribution', 'RecognitionTrends', 'AnnualTotals', 'StartupProfile'], 'sponsored_keywords': ['RecognizedStartups', 'StartupList', 'StartupTotals', 'YearlyTotals'], 'sector': 'Commerce & Industry', 'processing_summary': {'keyword_logic': 'Derived 1–2 word CamelCase keywords that reflect the catalog content: startups recognized, year/sector/state granularity, and counts/trends. The list avoids department names and overly generic terms, focusing on concepts evident in the title and data description (e.g., StartupRecognition, SectorDistribution, YearWise).', 'sector_logic': 'Primary sector chosen as Commerce & Industry because DPIIT relates to industry promotion and internal trade; the catalog centers on startup recognition across sectors, aligning with the industrial/commercial ecosystem rather than purely governance or social sectors.', 'sponsored_keywords': 'Selected 3–5 terms directly tied to the title and core dataset focus while remaining distinct from enhanced keywords: RecognizedStartups, StartupList, StartupTotals, YearlyTotals; these emphasize the recognition aspect, listing, and yearly totals in a concise form.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: Startup Recognized by DPIIT
SECTOR: Commerce & Industry
KEYWORDS: ["StartupRecognition", "SectorWise", "StateWise", "YearWise", "StartupCounts", "SectorDistribution", "StateDistribution", "RecognitionTrends", "AnnualTotals", "StartupProfile"]
SPONSORED: ["RecognizedStartups", "StartupList", "StartupTotals", "YearlyTotals"]

✓ Written to CSV

----------------------------

2025-11-24 11:45:15,832 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:45:15,836 : INFO - Result is {'generated_keywords': ['SoilMoisture', 'VolumetricMoisture', 'VICModel', 'DistrictLevel', 'StateLevel', 'AreaOfInterest', 'TemporalCoverage', 'NRSCOutputs'], 'sponsored_keywords': ['MoistureData', 'VICModelOutputs', 'DistrictData', 'SpatialCoverage', 'TimeSeries'], 'sector': 'Water Resources', 'processing_summary': {'keyword_logic': 'Generated keywords are 1–2 CamelCase terms that reflect the catalog’s focus on soil moisture derived from the VIC model, with spatial granularity (district/state level), temporal scope (-area of interest/temporal coverage), and data provenance (NRSC outputs). Terms were chosen from the title/description and aligned with the Water Resources sector, avoiding administrative terms and India-specific nudges.', 'sector_logic': 'Water Resources is selected as the primary sector because the catalog centers on soil moisture data used for water resource assessment and management (spatially across states/districts and temporally over years). This aligns with the catalog’s description and the existing theme.', 'sponsored_keywords': 'Sponsored keywords are the top 3–5 terms most closely tied to the catalog title ‘Soil Moisture’ but distinct from the enhanced keywords. They emphasize core concepts like moisture data and VIC model outputs, ensuring high relevance without duplicating the enhanced keyword set.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: Soil Moisture
SECTOR: Water Resources
KEYWORDS: ["SoilMoisture", "VolumetricMoisture", "VICModel", "DistrictLevel", "StateLevel", "AreaOfInterest", "TemporalCoverage", "NRSCOutputs"]
SPONSORED: ["MoistureData", "VICModelOutputs", "DistrictData", "SpatialCoverage", "TimeSeries"]

✓ Written to CSV

----------------------------

2025-11-24 11:45:17,598 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:45:17,603 : INFO - Result is {'generated_keywords': ['Evapotranspiration', 'DailyET', 'WaterBalance', 'FieldIrrigation', 'HydrologyData', 'SatelliteET', 'RemoteSensing'], 'sponsored_keywords': ['DailyEvapotranspiration', 'EvapoTranspirationData', 'ETData', 'EvapoTranspirationInfo'], 'sector': 'Water Resources', 'processing_summary': {'keyword_logic': 'Derived 7 layman-friendly keywords from the catalog title and description, focusing on evapotranspiration concepts, daily measurements, hydrology, irrigation and satellite/remote sensing methods. Keywords are in CamelCase and kept to 1–2 words each to maximise discoverability without resorting to department names or overly generic terms.', 'sector_logic': 'Primary sector chosen as Water Resources because the catalog centers on evapotranspiration data with hydrological relevance (groundwater context, water balance, irrigation planning) and aligns with NRSC ET data usage in water management.', 'sponsored_keywords': 'Selected 4 terms closely tied to the exact catalog title phrases (e.g., DailyEvapotranspiration, EvapoTranspirationData, ETData) to ensure strong title-based search relevance, while keeping them distinct from the generated keywords to broaden search coverage.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: Daily Data of Evapo-transpiration
SECTOR: Water Resources
KEYWORDS: ["Evapotranspiration", "DailyET", "WaterBalance", "FieldIrrigation", "HydrologyData", "SatelliteET", "RemoteSensing"]
SPONSORED: ["DailyEvapotranspiration", "EvapoTranspirationData", "ETData", "EvapoTranspirationInfo"]

✓ Written to CSV

----------------------------

2025-11-24 11:45:20,949 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:45:20,956 : INFO - Result is {'generated_keywords': ['RainfallData', 'StationRainfall', 'DistrictRainfall', 'GriddedRainfall', 'NormalRainfall', 'DailyRainfall', 'RainfallMaps', 'RainfallRecords'], 'sponsored_keywords': ['RainfallDataset', 'RainfallGrids', 'RainfallMaps'], 'sector': 'Water Resources', 'processing_summary': {'keyword_logic': 'Enhanced keywords were derived from the catalog title and description, along with content cues from the subject and theme. The terms describe rainfall data types (station, district, gridded) and characteristics (normal, daily) in CamelCase, limited to 1–2 words each, to maximize layperson discoverability.', 'sector_logic': 'Primary sector selected as Water Resources to reflect the catalog’s overall domain of rainfall data and water resource management, aligning with the existing theme and publisher context.', 'sponsored_keywords': 'Sponsored keywords are concise, title-relevant terms (in CamelCase) that closely reflect the catalog title while avoiding exact duplication with enhanced keywords.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: Rainfall
SECTOR: Water Resources
KEYWORDS: ["RainfallData", "StationRainfall", "DistrictRainfall", "GriddedRainfall", "NormalRainfall", "DailyRainfall", "RainfallMaps", "RainfallRecords"]
SPONSORED: ["RainfallDataset", "RainfallGrids", "RainfallMaps"]

✓ Written to CSV

----------------------------

2025-11-24 11:45:23,614 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:45:23,616 : INFO - Result is {'generated_keywords': ['AgeingHealth', 'ElderCare', 'HealthSurvey', 'AgeingPopulation', 'LongevityStudy', 'PublicHealth', 'PopulationWellbeing', 'HealthPolicy', 'LongitudinalStudy'], 'sponsored_keywords': ['LASIStudy', 'AgeingLASI', 'LongitudinalLASI', 'AgeingSurvey'], 'sector': 'Health', 'processing_summary': {'keyword_logic': 'Derived from the catalog focus on ageing health and LASI; produced 9 CamelCase keywords representing health, ageing, longitudinal data, and population wellbeing. Keywords are 1–2 words per item, non-generic, avoiding administrative terms and the word India, and aligned with the Title/Description/ Sector.', 'sector_logic': 'Primary sector Health chosen because LASI studies ageing health, health status, and related policy implications, reflecting the national health data emphasis and MoHFW/IIPS collaboration.', 'sponsored_keywords': 'Selected 4 terms tightly tied to the catalog title (LASI, Ageing, Longitudinal) while avoiding duplication with generated keywords; includes acronym form and two-word compounds to mirror the official title.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword', 'dcterms:title', 'dcterms:description']}

TITLE: Longitudinal Ageing Study in India (LASI)
SECTOR: Health
KEYWORDS: ["AgeingHealth", "ElderCare", "HealthSurvey", "AgeingPopulation", "LongevityStudy", "PublicHealth", "PopulationWellbeing", "HealthPolicy", "LongitudinalStudy"]
SPONSORED: ["LASIStudy", "AgeingLASI", "LongitudinalLASI", "AgeingSurvey"]

✓ Written to CSV

----------------------------

2025-11-24 11:45:31,942 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:45:31,945 : INFO - Result is {'generated_keywords': ['TouristArrivals', 'ForeignTourists', 'DomesticTourists', 'NRITourists', 'StatewiseTourism', 'InternationalTravel', 'TouristVisits', 'Departures'], 'sponsored_keywords': ['TourismStatistics', 'TravelData', 'StateTourism', 'ArrivalsDepartures'], 'sector': 'Commerce & Industry', 'processing_summary': {'keyword_logic': 'Generated 6–10 layman-friendly keywords by tracing the catalog content (tourist arrivals, foreign/domestic tourists, NRIs, state-level tourism and travel activity). All terms use CamelCase and are 1–2 words long, avoiding administrative terms and India-specific references in the keyword forms.', 'sector_logic': "Primary sector chosen as Commerce & Industry to reflect the catalog's economic focus on tourism statistics and travel-related data within the economy, aligning with the catalog’s publication domain.", 'sponsored_keywords': 'Selected 3–5 strong terms directly tied to the title ( Tourism Statistics, Travel Data, State Tourism, Arrivals Departures ) to capture core concepts and maintain distinction from the enhanced keywords.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: India Tourism Statistics
SECTOR: Commerce & Industry
KEYWORDS: ["TouristArrivals", "ForeignTourists", "DomesticTourists", "NRITourists", "StatewiseTourism", "InternationalTravel", "TouristVisits", "Departures"]
SPONSORED: ["TourismStatistics", "TravelData", "StateTourism", "ArrivalsDepartures"]

✓ Written to CSV

----------------------------

2025-11-24 11:45:36,078 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:45:36,081 : INFO - Result is {'generated_keywords': ['LocalGovernments', 'RuralUrban', 'Panchayats', 'Municipalities', 'Wards', 'Districts', 'Villages', 'RevenueEntities'], 'sponsored_keywords': ['LocalDirectory', 'GovernmentDirectory', 'PanchayatDirectory', 'DistrictDirectory'], 'sector': 'Governance & Administration', 'processing_summary': {'keyword_logic': "Derived 6-10 layman-friendly keywords from the catalog's content: local government structures (districts, villages, wards), rural/urban governance, and specific bodies (Panchayats, Municipalities) using CamelCase and 1-2 word length. Excluded generic terms and ministry names.", 'sector_logic': 'Selected Governance & Administration as primary sector reflecting overall catalog domain: local government governance, administrative structures, and revenue entities across rural and urban areas.', 'sponsored_keywords': "Chosen 3-4 terms most closely matching the catalog title 'Local Government Directory' in CamelCase, focusing on title relevance and avoiding duplication with enhanced keywords."}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword', 'dcterms:title', 'dcterms:description']}

TITLE: Local Government Directory (LGD)
SECTOR: Governance & Administration
KEYWORDS: ["LocalGovernments", "RuralUrban", "Panchayats", "Municipalities", "Wards", "Districts", "Villages", "RevenueEntities"]
SPONSORED: ["LocalDirectory", "GovernmentDirectory", "PanchayatDirectory", "DistrictDirectory"]

✓ Written to CSV

----------------------------

2025-11-24 11:45:40,010 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:45:40,013 : INFO - Result is {'generated_keywords': ['GeoscienceData', 'GeologicalMaps', 'SeismicSurveys', 'QuadrangleMaps', 'EarthQuakes', 'EarthSciences', 'MappingData', 'GeologyData', 'GeologyMaps'], 'sponsored_keywords': ['GeoscienceGateway', 'GeologyPortal', 'DataGateway', 'GeologicalDataHub'], 'sector': 'Earth Sciences', 'processing_summary': {'keyword_logic': 'Generated 9 layman-friendly, CamelCase keywords focused on core geoscience content indicated by BHUKOSH and the GSI catalog description; prioritized terms describing data types (maps, seismic data), phenomena (earthquakes), and the geoscience domain, while avoiding admin terms and India-specific identifiers.', 'sector_logic': 'Assigned primarily to Earth Sciences because BHUKOSH represents a gateway to geoscientific data managed by GSI, indicating a science-domain catalog rather than a governance/mining-specific repository.', 'sponsored_keywords': "Sponsored terms are title-aligned, CamelCase variants that reflect the catalog's gateway/portal concept and core data aspects (GeoscienceGateway, GeologyPortal, DataGateway, GeologicalDataHub)."}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: BHUKOSH
SECTOR: Earth Sciences
KEYWORDS: ["GeoscienceData", "GeologicalMaps", "SeismicSurveys", "QuadrangleMaps", "EarthQuakes", "EarthSciences", "MappingData", "GeologyData", "GeologyMaps"]
SPONSORED: ["GeoscienceGateway", "GeologyPortal", "DataGateway", "GeologicalDataHub"]

✓ Written to CSV

----------------------------

2025-11-24 11:45:44,918 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:45:44,923 : INFO - Result is {'generated_keywords': ['PopulationHealth', 'MaternalHealth', 'ChildHealth', 'ReproductiveHealth', 'NutritionStatus', 'DistrictLevel', 'ToiletAccess', 'MenstrualHygiene', 'AbortionReasons', 'Disability'], 'sponsored_keywords': ['NFHS5', 'HealthSurvey', 'FamilyHealth', 'NationalFamilyHealthSurvey'], 'sector': 'Health', 'processing_summary': {'keyword_logic': 'Enhanced keywords are 1–2 word CamelCase terms drawn from NFHS-5 content: health indicators, nutrition, district-level estimates, and newly covered topics (toilet access, menstrual hygiene, disability, abortion) to aid layperson discovery without administrative terms.', 'sector_logic': "Primary sector selected as Health due to NFHS-5's core focus on population health and nutrition, aligning with the publisher's health ministry and avoiding overly broad categories.", 'sponsored_keywords': "Sponsored keywords mirror the catalog title's core elements: NFHS5 denotes the edition; HealthSurvey and FamilyHealth reflect the title components; NationalFamilyHealthSurvey captures national scope in CamelCase."}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword', 'dcterms:title', 'dcterms:description']}

TITLE: National Family Health Survey (NFHS) - 5
SECTOR: Health
KEYWORDS: ["PopulationHealth", "MaternalHealth", "ChildHealth", "ReproductiveHealth", "NutritionStatus", "DistrictLevel", "ToiletAccess", "MenstrualHygiene", "AbortionReasons", "Disability"]
SPONSORED: ["NFHS5", "HealthSurvey", "FamilyHealth", "NationalFamilyHealthSurvey"]

✓ Written to CSV

----------------------------

2025-11-24 11:45:46,302 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:45:46,307 : INFO - Result is {'generated_keywords': ['Session254', 'QuestionAnswers', 'RajyaSabhaQuestions', 'ParliamentaryData', 'AnnexureQuestions', 'AnswerRecords', 'DataFromRajyaSabha', 'QuestionAnswerRecords'], 'sponsored_keywords': ['RajyaSabha', 'Session254Questions', 'QuestionsAnswers', 'ParliamentQuestions'], 'sector': 'Governance & Administration', 'processing_summary': {'keyword_logic': 'Enhanced keywords were derived from the catalog’s core content as reflected in the title and description: session number, Q&A data, Rajya Sabha questions, and parliamentary data. CamelCase was applied and terms were chosen to be discoverable for a general audience while avoiding department names, overly generic terms, and the word India. A mix of content-specific terms (e.g., Session254, RajyaSabhaQuestions, ParliamentaryData) and data-oriented terms (e.g., AnswerRecords, DataFromRajyaSabha) were included to cover likely user queries.', 'sector_logic': 'Governance & Administration was selected as the primary sector because the catalog aggregates Rajya Sabha Q&A data across ministries/departments, representing governance activities and parliamentary oversight rather than technical domains. This aligns with the catalog’s governance-centric purpose.', 'sponsored_keywords': 'Sponsored keywords were chosen to closely mirror the official title phrases: RajyaSabha, Session254Questions, QuestionsAnswers, and ParliamentQuestions. They are concise, CamelCase, and directly tied to the title content, while remaining distinct from the enhanced keywords.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: Answers Data of Rajya Sabha Questions for Session 254
SECTOR: Governance & Administration
KEYWORDS: ["Session254", "QuestionAnswers", "RajyaSabhaQuestions", "ParliamentaryData", "AnnexureQuestions", "AnswerRecords", "DataFromRajyaSabha", "QuestionAnswerRecords"]
SPONSORED: ["RajyaSabha", "Session254Questions", "QuestionsAnswers", "ParliamentQuestions"]

✓ Written to CSV

----------------------------

2025-11-24 11:45:48,934 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:45:48,937 : INFO - Result is {'generated_keywords': ['DistrictLevel', 'HealthNutrition', 'ToiletFacilities', 'DisabilityStats', 'PreschoolEducation', 'AbortionReasons', 'DeathRegistration', 'MenstruationPractices', 'WaistHip'], 'sponsored_keywords': ['NFHS5', 'DistrictFactsheet', 'HealthSurvey', 'DistrictStats'], 'sector': 'Health', 'processing_summary': {'keyword_logic': "Keywords were generated from the catalog's content and description: district-level health/population indicators, sanitation (ToiletFacilities), disability, education aspects (PreschoolEducation), reproductive health topics (AbortionReasons, MenstruationPractices), and biometric measurement topics (WaistHip, DeathRegistration). Each term is 1–2 words in CamelCase to aid lay user discovery while avoiding administrative terms.", 'sector_logic': 'NFHS-5 is a health and nutrition survey with district-level estimates; the predominant domain is Health, focusing on population health, sanitation, reproductive health, and nutrition indicators. Therefore Health is selected as the primary sector.', 'sponsored_keywords': 'Selected 3–5 terms that closely map to the catalog title and its core deliverable: NFHS5 (title acronym), DistrictFactsheet (district-level factsheet), HealthSurvey (overall type), DistrictStats (district-level statistics). These are distinct from the enhanced keywords to ensure varied search terms.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword', 'dcterms:title', 'dcterms:description']}

TITLE: National Family Health Survey-5 (NFHS-5) - India Districts Factsheet Data
SECTOR: Health
KEYWORDS: ["DistrictLevel", "HealthNutrition", "ToiletFacilities", "DisabilityStats", "PreschoolEducation", "AbortionReasons", "DeathRegistration", "MenstruationPractices", "WaistHip"]
SPONSORED: ["NFHS5", "DistrictFactsheet", "HealthSurvey", "DistrictStats"]

✓ Written to CSV

----------------------------

2025-11-24 11:45:50,573 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:45:50,583 : INFO - Result is {'generated_keywords': ['StartupEcosystem', 'TechInnovation', 'IntellectualProperty', 'IncubationCenters', 'Entrepreneurship', 'InnovationSupport', 'StartupCulture', 'DigitalEntrepreneurship'], 'sponsored_keywords': ['StartupHub', 'TechStartup', 'InnovationHub', 'IncubationSupport'], 'sector': 'Science & Technology', 'processing_summary': {'keyword_logic': "Derived from the catalog's stated focus on startup ecosystems, technology innovation, incubation facilities, and IP creation under MeitY. The 6–10 keywords in CamelCase capture core concepts such as startups, innovation, intellectual property, incubation, entrepreneurship, and support mechanisms, while avoiding administrative or overly generic terms.", 'sector_logic': 'Selected Science & Technology as the primary sector because the catalog centers on technology-driven startups, incubation, and innovation activities. While governance and administration terms appear in description, the dominant domain is tech and R&D oriented.', 'sponsored_keywords': 'Chosen from the catalog title and core theme: StartupHub (title core), TechStartup (title relevance), InnovationHub (title-related), IncubationSupport (reflects incubation and support within the hub). These are 1–2 word CamelCase terms that closely align with the title while remaining distinct from the enhanced keywords.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: Startup Hub
SECTOR: Science & Technology
KEYWORDS: ["StartupEcosystem", "TechInnovation", "IntellectualProperty", "IncubationCenters", "Entrepreneurship", "InnovationSupport", "StartupCulture", "DigitalEntrepreneurship"]
SPONSORED: ["StartupHub", "TechStartup", "InnovationHub", "IncubationSupport"]

✓ Written to CSV

----------------------------

2025-11-24 11:45:51,218 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:45:51,228 : INFO - Result is {'generated_keywords': ['Enrolment', 'AgeDistribution', 'ClassEnrollment', 'UDISEPlus', 'SchoolEnrollment', 'AgeGroup', 'GradeEnrollment', 'EnrollmentData'], 'sponsored_keywords': ['Enrollment', 'AgeSpread', 'GradeDistribution', 'UDISEPlus'], 'sector': 'Education', 'processing_summary': {'keyword_logic': 'Enhanced keywords are 8 CamelCase terms derived from the catalog title and description, focusing on enrolment by age and class within the UDISEPlus context. Terms avoid administrative or generic labels and aim to improve user discovery of enrolment-related information.', 'sector_logic': 'Education is selected as the primary sector because the catalog centers on school enrolment data across ages and classes, aligned with the existing Education theme and the UDISE data framework.', 'sponsored_keywords': 'Sponsored keywords are the strongest terms closely tied to the title: Enrollment (title-aligned spelling variant), AgeSpread (age-based distribution), GradeDistribution (class/grade focus), and UDISEPlus (contextual dataset reference). They are distinct from, but related to, the generated keywords.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: Enrolment by Age and Class (UDISE plus)
SECTOR: Education
KEYWORDS: ["Enrolment", "AgeDistribution", "ClassEnrollment", "UDISEPlus", "SchoolEnrollment", "AgeGroup", "GradeEnrollment", "EnrollmentData"]
SPONSORED: ["Enrollment", "AgeSpread", "GradeDistribution", "UDISEPlus"]

✓ Written to CSV

----------------------------

2025-11-24 11:46:09,298 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:46:09,303 : INFO - Result is {'generated_keywords': ['WholesalePrices', 'PriceIndex', 'TimeSeries', 'InflationTrend', 'CommodityPrices', 'SeasonalData', 'PriceMovement', 'MarketPrices'], 'sponsored_keywords': ['WPI', 'IndexSeries', 'PriceTrend', 'InflationData'], 'sector': 'Finance & Economy', 'processing_summary': {'keyword_logic': 'Derived 6–10 layman-friendly terms from the catalog title and description that describe wholesale price data as a time-series index. Chose CamelCase tokens that reflect the content (prices, index, time-series, seasonal aspects) while avoiding department names and overly generic terms.', 'sector_logic': 'Selected Finance & Economy as the primary sector because Wholesale Price Index is a macroeconomic price index used in economic analysis and policy, aligning with the catalog’s focus on price-level data in the economy rather than a purely administrative or sector-specific domain.', 'sponsored_keywords': "Chosen 3–5 terms that closely mirror the exact title semantics (including the acronym 'WPI' and related terms like 'IndexSeries', 'PriceTrend', 'InflationData') to maximize title-aligned search relevance without duplicating the enhanced keywords."}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: Wholesale Price Index
SECTOR: Finance & Economy
KEYWORDS: ["WholesalePrices", "PriceIndex", "TimeSeries", "InflationTrend", "CommodityPrices", "SeasonalData", "PriceMovement", "MarketPrices"]
SPONSORED: ["WPI", "IndexSeries", "PriceTrend", "InflationData"]

✓ Written to CSV

----------------------------

2025-11-24 11:46:10,942 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:46:10,949 : INFO - Result is {'generated_keywords': ['RainfallAnomaly', 'PrecipitationAnomaly', 'RegionalRainfall', 'MonsoonVariability', 'RainfallPatterns', 'SpatialRainfall', 'DepartureStats', 'ClimateWatch'], 'sponsored_keywords': ['RainfallDeparture', 'RainfallData', 'DepartureRainfall'], 'sector': 'Environment', 'processing_summary': {'keyword_logic': "Enhanced keywords were derived by mapping the catalog's focus on rainfall departure/anomaly across regions to layman-friendly terms. terms emphasize phenomena (anomaly, variability, patterns) and regional/spatial aspects, using CamelCase and 1–2 word constructs. Administrative or highly generic terms were avoided.", 'sector_logic': 'Environment was chosen as the primary sector because the catalog centers on climate-related rainfall data and its environmental implications. While science/earth sciences themes exist, Environment best captures the overall domain of the rainfall departure dataset.', 'sponsored_keywords': 'Sponsored keywords are tightly aligned with the exact catalog title components: RainfallDeparture, RainfallData, and DepartureRainfall. They are 1–2 word CamelCase terms that reflect the title while remaining distinct from the enhanced keywords.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: Departure of Rainfall data
SECTOR: Environment
KEYWORDS: ["RainfallAnomaly", "PrecipitationAnomaly", "RegionalRainfall", "MonsoonVariability", "RainfallPatterns", "SpatialRainfall", "DepartureStats", "ClimateWatch"]
SPONSORED: ["RainfallDeparture", "RainfallData", "DepartureRainfall"]

✓ Written to CSV

----------------------------

2025-11-24 11:46:16,328 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:46:16,332 : INFO - Result is {'generated_keywords': ['ViolentCrimes', 'MurderCases', 'RapeCases', 'KidnappingCases', 'TheftCases', 'CustodialDeaths', 'PoliceFiring', 'ConvictionRate', 'JuvenileDelinquency', 'VictimStatistics'], 'sponsored_keywords': ['CrimeIn2019', 'IndiaCrimeStats', 'PoliceData2019', 'CrimeStatistics'], 'sector': 'Governance & Administration', 'processing_summary': {'keyword_logic': 'Enhanced keywords reflect crime categories, victims, perpetrators, and outcomes described in the catalog description (violent crimes, murder, rape, kidnapping, theft, custodial events, conviction rate, juvenile delinquency, victims). They are constrained to 1–2 CamelCase words to maximize searchability while avoiding generic or administrative terms.', 'sector_logic': 'Primary sector chosen as Governance & Administration to reflect the catalog’s focus on law enforcement data, police organization, and judicial processes within the governance framework.', 'sponsored_keywords': "Sponsored terms are 1–2 CamelCase words that closely map to the catalog title 'Crime in India - 2019', emphasizing the year and crime focus (CrimeIn2019, IndiaCrimeStats, PoliceData2019, CrimeStatistics)."}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword', 'dcterms:title', 'dcterms:description']}

TITLE: Crime in India - 2019
SECTOR: Governance & Administration
KEYWORDS: ["ViolentCrimes", "MurderCases", "RapeCases", "KidnappingCases", "TheftCases", "CustodialDeaths", "PoliceFiring", "ConvictionRate", "JuvenileDelinquency", "VictimStatistics"]
SPONSORED: ["CrimeIn2019", "IndiaCrimeStats", "PoliceData2019", "CrimeStatistics"]

✓ Written to CSV

----------------------------

2025-11-24 11:46:23,359 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:46:23,366 : INFO - Result is {'generated_keywords': ['HealthIndicators', 'SubDistrictData', 'HMISMonthly', 'ImmunisationRates', 'DiseaseSurveillance', 'HypertensionData', 'MalariaCases', 'TBTrends'], 'sponsored_keywords': ['SubDistrict', 'HMISData', 'MonthlyData', 'IndicatorWise'], 'sector': 'Health', 'processing_summary': {'keyword_logic': 'Derived from the catalog title and description focusing on health indicators collected via HMIS at the sub-district level with monthly granularity. Generated 8 CamelCase keywords that are concise (1–2 words), reflect actual content (indicators, HMIS, sub-district, monthly data), and avoid administrative or generic terms.', 'sector_logic': 'The catalog centers on health data from health facilities and HMIS indicators, making Health the primary sector. Related themes (Family Welfare, etc.) are components of the health domain but not the primary sector for catalog-level classification.', 'sponsored_keywords': 'Selected 4 terms that closely map to the title semantics (location granularity, HMIS system, monthly temporal aspect, and indicator-based focus) while being distinct from the enhanced_keywords set.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: Health indicator-wise monthly datasets at sub district level from HMIS
SECTOR: Health
KEYWORDS: ["HealthIndicators", "SubDistrictData", "HMISMonthly", "ImmunisationRates", "DiseaseSurveillance", "HypertensionData", "MalariaCases", "TBTrends"]
SPONSORED: ["SubDistrict", "HMISData", "MonthlyData", "IndicatorWise"]

✓ Written to CSV

----------------------------

2025-11-24 11:46:24,620 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:46:24,625 : INFO - Result is {'generated_keywords': ['PincodeDirectory', 'PincodeLookup', 'PostalCodeInfo', 'PostalCodeDirectory', 'DeliveryPincode', 'DistrictPincode', 'CirclePincode', 'OfficePincode', 'PostOfficeData'], 'sponsored_keywords': ['AllIndia', 'PinCodeDirectory', 'WebService', 'PostalCodeData'], 'sector': 'Governance & Administration', 'processing_summary': {'keyword_logic': "Enhanced keywords were generated as 1–2 word CamelCase terms that reflect the catalog's pin code content and postal directory nature without naming departments. Selections emphasize directory/lookup of pincodes, associated office and district data, and postal information to aid discoverability for general users.", 'sector_logic': "The catalog covers nationwide PIN code data and postal organization details; its primary domain centers on governance and administrative data management of postal codes, hence Governance & Administration as the primary sector. Information and Communications appears as an auxiliary context but governance best captures the catalog's scope.", 'sponsored_keywords': 'Sponsored keywords are short, official-title-aligned terms that map directly to the catalog title: AllIndia, PinCodeDirectory, WebService, PostalCodeData. They aim to maximize relevance to title keywords while remaining distinct from the enhanced keywords.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: All India Pincode Directory (Through WebService)
SECTOR: Governance & Administration
KEYWORDS: ["PincodeDirectory", "PincodeLookup", "PostalCodeInfo", "PostalCodeDirectory", "DeliveryPincode", "DistrictPincode", "CirclePincode", "OfficePincode", "PostOfficeData"]
SPONSORED: ["AllIndia", "PinCodeDirectory", "WebService", "PostalCodeData"]

✓ Written to CSV

----------------------------

2025-11-24 11:46:28,346 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:46:28,352 : INFO - Result is {'generated_keywords': ['SeasonalTemp', 'AnnualTemp', 'TemperatureTrends', 'ClimateSeries', 'YearlyTemp', 'MaxMinTemp', 'TempAnomalies', 'MeanTemp', 'SeasonalMeans', 'TempPatterns'], 'sponsored_keywords': ['AllIndia', 'SeasonalTemp', 'AnnualSeries', 'TempSeries', 'TemperatureSeries'], 'sector': 'Environment', 'processing_summary': {'keyword_logic': 'Enhanced keywords were derived from the catalog title and description, focusing on the core content: seasonal and annual temperature data. Terms were distilled into 1–2 CamelCase words that are lay-friendly and non-redundant with existing department names. A mix of temperature-centric, temporal (seasonal/annual), and trend-related concepts were chosen to maximize discoverability while avoiding administrative terms.', 'sector_logic': 'Environment was selected as the primary sector because the catalog centers on climate/temperature data, aligning with environmental/climate data domain. This reflects the catalog’s overarching theme of temperature series and climate-related measurements rather than purely technical or administrative domains.', 'sponsored_keywords': 'Sponsored keywords are the strongest, title-aligned terms (1–2 CamelCase words) that directly map to the catalog title. They include theAllIndia facet and core temperature-series concepts (SeasonalTemp, AnnualSeries, TempSeries, TemperatureSeries) to ensure high retrieval relevance without duplicating the entire enhanced_keywords set.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: All India Seasonal and Annual Temperature Series
SECTOR: Environment
KEYWORDS: ["SeasonalTemp", "AnnualTemp", "TemperatureTrends", "ClimateSeries", "YearlyTemp", "MaxMinTemp", "TempAnomalies", "MeanTemp", "SeasonalMeans", "TempPatterns"]
SPONSORED: ["AllIndia", "SeasonalTemp", "AnnualSeries", "TempSeries", "TemperatureSeries"]

✓ Written to CSV

----------------------------

2025-11-24 11:46:30,378 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:46:30,380 : INFO - Result is {'generated_keywords': ['RegionalGDP', 'AnnualGDP', 'TimeSeries', 'EconomicOutput', 'StateEconomy', 'StateStats', 'GDPGrowth', 'EconomicData', 'StatePerformance'], 'sponsored_keywords': ['GdpCurrent', 'GdpTrend', 'StateOutput', 'EconomicGrowth'], 'sector': 'Finance & Economy', 'processing_summary': {'keyword_logic': 'Enhanced keywords were crafted from the catalog’s title and description to reflect the core content: state-level GDP measured at current prices across years, with emphasis on regional scope and economic output. The terms are CamelCase, 1–2 words each, and avoid administrative or generic terms. 9 keywords were chosen to balance geography (RegionalGDP, StateEconomy, StateStats), time (AnnualGDP, TimeSeries), and economic indicators (EconomicOutput, GDPGrowth, EconomicData, StatePerformance).', 'sector_logic': 'The dataset centers on macroeconomic indicators at the state level (GDP at current prices) across multiple years, which aligns with Finance & Economy as the primary sector. This sector best captures the catalog’s overarching domain of economic performance and fiscal statistics rather than social or municipal domains.', 'sponsored_keywords': 'Sponsored keywords were selected as the top 3–5 terms that most directly reflect the catalog title’s core concepts while ensuring they are not exact duplicates of enhanced keywords. Chosen terms include GDP at current prices and state-related economic indicators (GdpCurrent, GdpTrend, StateOutput, EconomicGrowth), offering precise, title-aligned search anchors without repeating enhanced terms.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: Gross State Domestic Product at Current Prices
SECTOR: Finance & Economy
KEYWORDS: ["RegionalGDP", "AnnualGDP", "TimeSeries", "EconomicOutput", "StateEconomy", "StateStats", "GDPGrowth", "EconomicData", "StatePerformance"]
SPONSORED: ["GdpCurrent", "GdpTrend", "StateOutput", "EconomicGrowth"]

✓ Written to CSV

----------------------------

2025-11-24 11:46:30,945 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:46:30,952 : INFO - Result is {'generated_keywords': ['MSMEDetails', 'MSMEArchive', 'EnterpriseRegistry', 'MSMEOverview', 'MSMERoster', 'MSMESummary', 'UDYAMInfo', 'RegistrationData'], 'sponsored_keywords': ['MSMERegistration', 'MSMEData', 'MSMEDirectory', 'LGDirectory'], 'sector': 'Commerce & Industry', 'processing_summary': {'keyword_logic': 'Derived 8 CamelCase keywords by analyzing the catalog title, description, and existing keywords to reflect district-level MSME data, UDYAM registration context, and related directory components. Focused on content-specific terms (MSME, UDYAM, district data, registration, directory/data aspects) while avoiding broad administrative terms and country identifiers.', 'sector_logic': 'Selected Commerce & Industry as the primary sector because the catalog centers on MSME registrations and district-wise enterprise data, which directly relate to business activity, small industry, and market/commercial registries within the economy.', 'sponsored_keywords': 'Chosen 4 terms that closely match the exact title concepts (MSMERegistration, MSMEData, MSMEDirectory, LGDirectory) to maximize direct relevance. They are CamelCase, concise (1–2 words), and distinct from the enhanced keywords.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: UDYAM Registration (MSME Registration)
SECTOR: Commerce & Industry
KEYWORDS: ["MSMEDetails", "MSMEArchive", "EnterpriseRegistry", "MSMEOverview", "MSMERoster", "MSMESummary", "UDYAMInfo", "RegistrationData"]
SPONSORED: ["MSMERegistration", "MSMEData", "MSMEDirectory", "LGDirectory"]

✓ Written to CSV

----------------------------

2025-11-24 11:46:38,311 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:46:38,329 : INFO - Result is {'generated_keywords': ['UnitDetails', 'EnterpriseType', 'InvestmentPlant', 'Employment', 'NICCode', 'LocationDetails', 'SocialCategory', 'RegistrationDate', 'UnitName'], 'sponsored_keywords': ['MSMERegistration', 'RegisteredUnits', 'UdyogAadhaar', 'Memorandum'], 'sector': 'Commerce & Industry', 'processing_summary': {'keyword_logic': "Derive 6–10 layman-friendly, CamelCase keywords from the catalog's content: unit details, enterprise type, investment in plant, employment figures, NIC code, location details, social category, registration date, and unit name. Ensure each keyword is 1–2 conceptual words in CamelCase and non-redundant with the title.", 'sector_logic': 'The catalog centers on registered MSMEs and their enterprise characteristics, which falls under commerce and industry activities (business registrations, units, investments). Hence, the primary sector is Commerce & Industry to reflect the catalog’s domain.', 'sponsored_keywords': 'Selected 3–5 terms that closely mirror the exact title while remaining distinct from the enhanced keywords. Terms include MSMERegistration, RegisteredUnits, UdyogAadhaar, and Memorandum to capture the core topic without duplicating generated keywords.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: List of MSME Registered Units  under Udyog Aadhaar Memorandum till last date
SECTOR: Commerce & Industry
KEYWORDS: ["UnitDetails", "EnterpriseType", "InvestmentPlant", "Employment", "NICCode", "LocationDetails", "SocialCategory", "RegistrationDate", "UnitName"]
SPONSORED: ["MSMERegistration", "RegisteredUnits", "UdyogAadhaar", "Memorandum"]

✓ Written to CSV

----------------------------

2025-11-24 11:46:43,102 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:46:43,110 : INFO - Result is {'generated_keywords': ['UdyogAadhaar', 'MSMERegistration', 'UAMData', 'MSMERecords', 'EnterpriseRegistration', 'SmallEnterprises', 'BusinessAadhaar', 'UdyogDetails'], 'sponsored_keywords': ['Memorandum', 'AadhaarMemorandum', 'UdyogRegistration', 'UAMRegistration'], 'sector': 'Commerce & Industry', 'processing_summary': {'keyword_logic': 'Enhanced keywords are 8 CamelCase terms derived from the catalog title, description, and existing keywords to reflect MSME/Udyog Aadhaar registration content while avoiding department names and overly generic terms. The terms emphasize registration data, enterprise focus, and Aadhaar linkage (e.g., UdyogAadhaar, MSMERegistration, UAMData, MSMERecords, EnterpriseRegistration, SmallEnterprises, BusinessAadhaar, UdyogDetails).', 'sector_logic': 'Primary sector selected as Commerce & Industry to best represent the catalog’s focus on MSME registration and small business activity. This aligns with the dataset’s domain and its economic governance context without assigning administrative or ministry-specific labels.', 'sponsored_keywords': 'Sponsored keywords are 4 terms tightly tied to the catalog title, chosen to be highly relevant while avoiding exact duplicates of enhanced keywords. They center on the Memorandum aspect and Aadhaar/Udyog registration framing (Memorandum, AadhaarMemorandum, UdyogRegistration, UAMRegistration).'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: Udyog Aadhaar Memorandum  ( MSME Registration )
SECTOR: Commerce & Industry
KEYWORDS: ["UdyogAadhaar", "MSMERegistration", "UAMData", "MSMERecords", "EnterpriseRegistration", "SmallEnterprises", "BusinessAadhaar", "UdyogDetails"]
SPONSORED: ["Memorandum", "AadhaarMemorandum", "UdyogRegistration", "UAMRegistration"]

✓ Written to CSV

----------------------------

2025-11-24 11:46:47,058 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:46:47,080 : INFO - Result is {'generated_keywords': ['CrowdsourcedSpeeds', 'MobileSpeedTest', 'NetworkPerformance', 'SpeedMeasurements', 'UserReportedSpeeds', 'RealTimeSpeeds', 'TRAIAppData', 'ConnectivityInsights'], 'sponsored_keywords': ['MySpeed', 'MySpeedApp', 'MobileSpeeds', 'SpeedTest'], 'sector': 'Science & Technology', 'processing_summary': {'keyword_logic': 'Generated 6–10 layman keywords in CamelCase (1–2 words per term) reflecting the catalog’s focus on crowdsourced mobile data speeds, network measurements, and TRAI MySpeed app usage. Selected terms from title/description and subject context while avoiding administrative terms.', 'sector_logic': 'Assigned Science & Technology as the primary sector to capture the technical/data-collection nature of crowdsourced mobile speed measurements and telecom data, aligning with the catalog’s content.', 'sponsored_keywords': 'Sponsored keywords are 3–5 terms tightly tied to the catalog title (MySpeed and related concepts) and chosen to complement, not duplicate, the generated keywords.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: MySpeed (Crowdsourced Mobile Data Speeds)
SECTOR: Science & Technology
KEYWORDS: ["CrowdsourcedSpeeds", "MobileSpeedTest", "NetworkPerformance", "SpeedMeasurements", "UserReportedSpeeds", "RealTimeSpeeds", "TRAIAppData", "ConnectivityInsights"]
SPONSORED: ["MySpeed", "MySpeedApp", "MobileSpeeds", "SpeedTest"]

✓ Written to CSV

----------------------------

2025-11-24 11:46:59,082 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:46:59,090 : INFO - Result is {'generated_keywords': ['RuralHealth', 'PHCInfrastructure', 'CHCFacilities', 'SubCentre', 'DistrictHospital', 'MobileUnits', 'HealthWorkforce', 'StaffingShortfall', 'DoctorsNurses', 'RuralFacilities'], 'sponsored_keywords': ['HealthStatistics', 'PrimaryHealthCare', 'DistrictHospitals', 'HealthInfrastructure', 'RuralHealthStats'], 'sector': 'Health', 'processing_summary': {'keyword_logic': 'Generated 9 layman keywords (1–2 words each, CamelCase) directly reflecting catalog content: rural health delivery points (PHCs, CHCs, SubCentre), health facilities, workforce, and gaps (shortfall). Chosen to be discoverable to a general user while avoiding department names and overly generic terms.', 'sector_logic': 'Assigned Health as the primary sector because the catalog centers on rural health statistics, infrastructure, and workforce data, aligning with the Health domain in the DCAT-India taxonomy.', 'sponsored_keywords': 'Selected 5 short terms tightly tied to the catalog title: HealthStatistics, PrimaryHealthCare, DistrictHospitals, HealthInfrastructure, RuralHealthStats. These emphasize the core focus of the dataset while avoiding exact duplicates of enhanced keywords.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword', 'dcterms:title', 'dcterms:description']}

TITLE: Rural Health Statistics - 2016
SECTOR: Health
KEYWORDS: ["RuralHealth", "PHCInfrastructure", "CHCFacilities", "SubCentre", "DistrictHospital", "MobileUnits", "HealthWorkforce", "StaffingShortfall", "DoctorsNurses", "RuralFacilities"]
SPONSORED: ["HealthStatistics", "PrimaryHealthCare", "DistrictHospitals", "HealthInfrastructure", "RuralHealthStats"]

✓ Written to CSV

----------------------------

2025-11-24 11:47:00,114 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:47:00,119 : INFO - Result is {'generated_keywords': ['CycloneFrequency', 'SeasonalCyclones', 'DepressionCounts', 'BayOfBengalCyclones', 'ArabianSeaCyclones', 'IntensityLevels', 'SeasonalityTrends', 'CoastalCyclones', 'LandImpact', 'YearlySeasonality'], 'sponsored_keywords': ['YearlyFrequency', 'SeasonalFrequency', 'CycloneDepressions', 'ArabianSea', 'BayOfBengal'], 'sector': 'Disaster Management', 'processing_summary': {'keyword_logic': 'Enhanced keywords are 1–2 words in CamelCase, reflecting the catalog’s focus on frequency, seasonality, basins (Bay of Bengal, Arabian Sea), and intensity levels (Depression, Cyclonic Storm, Severe Cyclonic Storm). They avoid administrative terms and generalities while staying close to the dataset content (frequency, basins, coastal/land impacts).', 'sector_logic': 'Disaster Management was chosen as the primary sector because the catalog centers on natural hazard phenomena (cyclones and depressions) and their seasonal/yearly frequency, which align with hazard risk management and disaster response domains, rather than purely academic science terms.', 'sponsored_keywords': 'Sponsored keywords are the strongest, title-aligned terms in 1–2 CamelCase words that closely capture the essence of the catalog title (Yearly/Seasonal Frequency, Cyclone/Depressions, regional basins). They differ from generated keywords to provide distinct highlight terms (e.g., ArabianSea, BayOfBengal) that users might search for when reading the title.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: Yearly and Seasonal Frequency of Cyclones and Depressions
SECTOR: Disaster Management
KEYWORDS: ["CycloneFrequency", "SeasonalCyclones", "DepressionCounts", "BayOfBengalCyclones", "ArabianSeaCyclones", "IntensityLevels", "SeasonalityTrends", "CoastalCyclones", "LandImpact", "YearlySeasonality"]
SPONSORED: ["YearlyFrequency", "SeasonalFrequency", "CycloneDepressions", "ArabianSea", "BayOfBengal"]

✓ Written to CSV

----------------------------

2025-11-24 11:47:00,523 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:47:00,526 : INFO - Result is {'generated_keywords': ['RuralHealth', 'PHCInfrastructure', 'CHCFacilities', 'SubCentres', 'MobileMedicalUnits', 'HealthWorkforce', 'MaternalHealth', 'NursingStaff'], 'sponsored_keywords': ['RuralHealthStatistics', 'PrimaryHealthCentre', 'DistrictHospitals', 'HealthFacilities', 'StaffShortage'], 'sector': 'Health', 'processing_summary': {'keyword_logic': 'Derived from the catalog title and description, focusing on rural health infrastructure (Sub Centres, PHCs, CHCs), district-level facilities, and health workforce. Generated 8 CamelCase keywords that capture infrastructure, facilities, and personnel without resorting to department names or India-specific administrative terms.', 'sector_logic': 'The catalog centers on rural health data, including facilities and workforce, making Health the primary sector aligned with the content and common DCAT-India vocabulary.', 'sponsored_keywords': 'Selected top terms that closely mirror the catalog title and core scope: RuralHealthStatistics (titleExact), PrimaryHealthCentre, DistrictHospitals, HealthFacilities, StaffShortage. These emphasize central concepts and are highly query-relevant.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: Rural Health Statistics - 2017
SECTOR: Health
KEYWORDS: ["RuralHealth", "PHCInfrastructure", "CHCFacilities", "SubCentres", "MobileMedicalUnits", "HealthWorkforce", "MaternalHealth", "NursingStaff"]
SPONSORED: ["RuralHealthStatistics", "PrimaryHealthCentre", "DistrictHospitals", "HealthFacilities", "StaffShortage"]

✓ Written to CSV

----------------------------

2025-11-24 11:47:08,366 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:47:08,376 : INFO - Result is {'generated_keywords': ['VoiceQuality', 'CallExperience', 'CustomerFeedback', 'LiveFeedback', 'NetworkExperience', 'UserSatisfaction', 'FeedbackApp', 'VoiceCall'], 'sponsored_keywords': ['CallQuality', 'CustomerExperience', 'UserExperience', 'NetworkQuality'], 'sector': 'Governance & Administration', 'processing_summary': {'keyword_logic': 'Derived 8 layman keywords from the catalog title/description focusing on user-facing concepts: voice quality, call experience, customer feedback, real-time feedback, network experience, user satisfaction, feedback application, and voice call context. Each is 1–2 words in CamelCase to aid discovery while avoiding government/dept names.', 'sector_logic': "Catalog concerns regulatory telecom customer experience data and TRAI's governance role; mapped to Governance & Administration as the primary sector; Information & Communications/Telecom themes were considered but governance scope best fits the catalog purpose.", 'sponsored_keywords': 'Selected 4 terms directly tied to the title content: CallQuality, CustomerExperience, UserExperience, NetworkQuality. They are 1–2 words CamelCase and provide precise, high-signal search terms without duplicating the enhanced keywords.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: Voice Call Quality Customer Experience
SECTOR: Governance & Administration
KEYWORDS: ["VoiceQuality", "CallExperience", "CustomerFeedback", "LiveFeedback", "NetworkExperience", "UserSatisfaction", "FeedbackApp", "VoiceCall"]
SPONSORED: ["CallQuality", "CustomerExperience", "UserExperience", "NetworkQuality"]

✓ Written to CSV

----------------------------

2025-11-24 11:47:09,801 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:47:09,803 : INFO - Result is {'generated_keywords': ['MonthlyRainfall', 'SubdivisionRainfall', 'RainfallDeparture', 'MonsoonData', 'SeasonalRainfall', 'PrecipitationData', 'ClimateData', 'RainfallStatistics'], 'sponsored_keywords': ['RainfallIn', 'India', 'MonsoonData', 'MonthWise'], 'sector': 'Water Resources', 'processing_summary': {'keyword_logic': 'EnhancedKeywords are 1–2 word CamelCase terms derived from the catalog’s focus on rainfall data, monthly/subdivision breakdowns, and departures from normal, extracted from the title and description, while avoiding generic or admin terms. Sponsored keywords are tightly aligned to the title concept (Rainfall In India) and chosen to be concise, high-relevance terms that complement the enhanced keywords without duplication.', 'sector_logic': 'Primary sector selected as Water Resources to reflect the catalog’s core domain of rainfall data and its implications for water availability, distribution, and resource planning. This aligns with the catalog’s focus beyond general science to practical water resource implications, while respecting the existing Science & Technology/ Earth Sciences context.', 'sponsored_keywords': 'Selected 3–4 terms that closely mirror the title’s essence (Rainfall, In, India, Monsoon, MonthWise) in CamelCase form to improve precise retrieval, ensuring they differ from the enhanced_keywords to provide complementary search terms.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: Rainfall in India
SECTOR: Water Resources
KEYWORDS: ["MonthlyRainfall", "SubdivisionRainfall", "RainfallDeparture", "MonsoonData", "SeasonalRainfall", "PrecipitationData", "ClimateData", "RainfallStatistics"]
SPONSORED: ["RainfallIn", "India", "MonsoonData", "MonthWise"]

✓ Written to CSV

----------------------------

2025-11-24 11:47:15,096 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:47:15,101 : INFO - Result is {'generated_keywords': ['FarmerQueries', 'MonthlyQueries', 'CropInfo', 'KisanCallCentre', 'FTAResponses', 'TranscriptRecords', 'SeasonalQueries', 'LocalQueries'], 'sponsored_keywords': ['MonthWise', 'CallCentreQueries', 'CropQueries', 'RegionalQueries', 'KccQueries'], 'sector': 'Agriculture', 'processing_summary': {'keyword_logic': 'Generated keywords are 1–2 CamelCase terms that reflect the catalog’s content: farmer-focused queries, monthly timing, crop-related information, and transcripts/FTA responses from Kisan Call Centre. Terms avoid explicit ministry names and broad administrative labels while staying aligned to the dataset’s agricultural context (e.g., KisanCallCentre, FTAResponses, TranscriptRecords).', 'sector_logic': 'Agriculture is selected as the primary sector because the catalog centers on farmer queries and responses within the Kisan Call Centre context, which naturally falls under agricultural knowledge and advisory services.', 'sponsored_keywords': 'Sponsored keywords are concise terms tightly tied to the catalog title, emphasizing the temporal (MonthWise), channel (CallCentreQueries), subject (CropQueries), and regional/common-structure aspects (RegionalQueries, KccQueries) to capture exact-title relevance without duplicating the generated set.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: District wise and month wise queries of farmers in Kisan Call Centre (KCC)
SECTOR: Agriculture
KEYWORDS: ["FarmerQueries", "MonthlyQueries", "CropInfo", "KisanCallCentre", "FTAResponses", "TranscriptRecords", "SeasonalQueries", "LocalQueries"]
SPONSORED: ["MonthWise", "CallCentreQueries", "CropQueries", "RegionalQueries", "KccQueries"]

✓ Written to CSV

----------------------------

2025-11-24 11:47:20,135 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:47:20,139 : INFO - Result is {'generated_keywords': ['MeanTemperature', 'MaxTemperature', 'Rainfall', 'StationData', 'CityWise', 'Climatology', 'PeriodWise', 'ClimateStats', 'WeatherData', 'CityClimate'], 'sponsored_keywords': ['CityClimatology', 'ClimatologyData', 'CityTemperature', 'RainfallData'], 'sector': 'Science & Technology', 'processing_summary': {'keyword_logic': 'Derived 6–10 CamelCase keywords from the catalog title and description, focusing on climatology elements (mean/max temperature, rainfall), data granularity (station-based, period-wise), and city-level context. Avoided administrative terms and ministry names while ensuring relevance to the dataset content.', 'sector_logic': "Selected Science & Technology as the primary sector since the catalog provides scientific climatology data produced by IMD under MoES, aligning with climate science and data collection. Although Earth Sciences is relevant, the catalog's controlled vocabulary favors Science & Technology for primary classification.", 'sponsored_keywords': 'Chosen 3–5 title-aligned terms that closely reflect the catalog title but are distinct from the generated keywords. Examples: CityClimatology, ClimatologyData, CityTemperature, RainfallData. All are 1–2 words CamelCase and avoid administrative terms.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: Climatology data of Important Cities
SECTOR: Science & Technology
KEYWORDS: ["MeanTemperature", "MaxTemperature", "Rainfall", "StationData", "CityWise", "Climatology", "PeriodWise", "ClimateStats", "WeatherData", "CityClimate"]
SPONSORED: ["CityClimatology", "ClimatologyData", "CityTemperature", "RainfallData"]

✓ Written to CSV

----------------------------

2025-11-24 11:47:28,050 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:47:28,062 : INFO - Result is {'generated_keywords': ['AmbientAir', 'AirQuality', 'ParticulateMatter', 'SulfurDioxide', 'NitrogenDioxide', 'AirMonitoring', 'HistoricalAQI', 'AirStations', 'DailyData'], 'sponsored_keywords': ['Historical', 'DailyAmbient', 'AirQuality', 'DailyData', 'Monitoring'], 'sector': 'Environment', 'processing_summary': {'keyword_logic': 'Enhanced keywords were crafted from the catalog title and description to be highly discoverable for lay users. Each term is 1–2 words in CamelCase and reflects concrete content such as ambient air, pollutants (particulate matter, SO2/NO2), monitoring, and data/time granularity. Administrative terms and department names were avoided.', 'sector_logic': 'The catalog focuses on ambient air quality and environmental monitoring across monitoring stations, aligning with the Environment sector as the primary domain. This captures the core domain better than Health or Urban Development for a catalog of this scope.', 'sponsored_keywords': 'Sponsored keywords are 3–5 terms tightly tied to the exact title, emphasizing historical context, daily/ambient data, and air quality data/monitoring aspects. They are kept distinct from the full enhanced_keywords set while remaining highly relevant to the catalog title.'}, 'source_fields_used': ['dcterms:title', 'dcterms:description', 'dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: Historical Daily Ambient Air Quality Data
SECTOR: Environment
KEYWORDS: ["AmbientAir", "AirQuality", "ParticulateMatter", "SulfurDioxide", "NitrogenDioxide", "AirMonitoring", "HistoricalAQI", "AirStations", "DailyData"]
SPONSORED: ["Historical", "DailyAmbient", "AirQuality", "DailyData", "Monitoring"]

✓ Written to CSV

----------------------------

2025-11-24 11:47:29,563 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:47:29,569 : INFO - Result is {'generated_keywords': ['RealTimeAQI', 'AirQuality', 'AirPollutionIndex', 'MonitoringStations', 'PM10', 'PM25', 'SO2', 'NO2', 'O3', 'CO'], 'sponsored_keywords': ['AirQualityIndex', 'LiveAQI', 'AQIReadings', 'AirQualityMonitor'], 'sector': 'Environment', 'processing_summary': {'keyword_logic': "Enhanced keywords are 10 layman-friendly terms in CamelCase (1–2 words each) that reflect the catalog's focus on real-time air quality data, monitoring infrastructure, and major pollutants (PM10/PM25, SO2, NO2, O3, CO). Terms are derived from the title/description and existing topic hints (AirQuality, MonitoringStations, Pollutants) while avoiding administrative or unrelated terms.", 'sector_logic': "Primary sector chosen is Environment, aligning with the catalog's emphasis on air quality and pollution monitoring. Other sectors are less central to the catalog's core domain.", 'sponsored_keywords': 'Sponsored keywords are 3–4 terms most tightly anchored to the exact catalog title, focusing on concise concepts like AirQualityIndex and LiveAQI. They are distinct from the enhanced keywords while preserving strong title relevance.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: Real time Air Quality Index
SECTOR: Environment
KEYWORDS: ["RealTimeAQI", "AirQuality", "AirPollutionIndex", "MonitoringStations", "PM10", "PM25", "SO2", "NO2", "O3", "CO"]
SPONSORED: ["AirQualityIndex", "LiveAQI", "AQIReadings", "AirQualityMonitor"]

✓ Written to CSV

----------------------------

2025-11-24 11:47:35,343 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:47:35,348 : INFO - Result is {'generated_keywords': ['CompanyData', 'CINInfo', 'CompanyStatus', 'AuthorizedCapital', 'PaidCapital', 'RegistrationDate', 'RegisteredState', 'BusinessActivity'], 'sponsored_keywords': ['CompanyMaster', 'MasterData', 'RoCData', 'CorporateDetails'], 'sector': 'Commerce & Industry', 'processing_summary': {'keyword_logic': 'Generated 8 keywords by mapping catalog content (company data fields, capital, registration, location, and activities) to compact CamelCase terms that are easy for users to search.', 'sector_logic': 'Selected Commerce & Industry as the primary sector because the catalog centers on corporate registry data and business activity, which aligns with industry/commercial governance.', 'sponsored_keywords': 'Chosen 4 terms that closely reflect the catalog title (Company Master Data) and capture core concepts while remaining distinct from the enhanced keywords.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword', 'dcterms:title', 'dcterms:description']}

TITLE: Company Master Data
SECTOR: Commerce & Industry
KEYWORDS: ["CompanyData", "CINInfo", "CompanyStatus", "AuthorizedCapital", "PaidCapital", "RegistrationDate", "RegisteredState", "BusinessActivity"]
SPONSORED: ["CompanyMaster", "MasterData", "RoCData", "CorporateDetails"]

✓ Written to CSV

----------------------------

2025-11-24 11:47:40,785 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:47:40,788 : INFO - Result is {'generated_keywords': ['RuralHealth', 'HealthInfrastructure', 'DistrictHospitals', 'SubCenters', 'HealthWorkers', 'NursesMidwives', 'SpecialistDoctors', 'MobileUnits', 'RuralFacilities'], 'sponsored_keywords': ['RuralStats', 'HealthStatistics', 'HealthFacilities', 'HealthCenters'], 'sector': 'Health', 'processing_summary': {'keyword_logic': 'Enhanced keywords are 1–2 CamelCase terms that reflect the catalog’s rural health focus, including infrastructure, staffing, and facility types (PHCs/CHCs/Sub-Centres) while avoiding department names. Terms are derived from the title/description and catalog context to improve layman discovery.', 'sector_logic': 'The catalog centers on rural health statistics, infrastructure, and workforce, making Health the most appropriate primary sector per the DCAT-AP controlled vocabulary. Other domains are less representative of the catalog’s overall purpose.', 'sponsored_keywords': 'Sponsored keywords target the exact title relevance with concise, 1–2 word CamelCase terms that users would likely search for when looking for rural health statistics data (e.g., RuralStats, HealthStatistics, HealthFacilities, HealthCenters).'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: Rural Health Statistics - 2015
SECTOR: Health
KEYWORDS: ["RuralHealth", "HealthInfrastructure", "DistrictHospitals", "SubCenters", "HealthWorkers", "NursesMidwives", "SpecialistDoctors", "MobileUnits", "RuralFacilities"]
SPONSORED: ["RuralStats", "HealthStatistics", "HealthFacilities", "HealthCenters"]

✓ Written to CSV

----------------------------

2025-11-24 11:47:41,036 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:47:41,040 : INFO - Result is {'generated_keywords': ['FDIInflows', 'EquityInflows', 'SectorInvestments', 'InvestmentFlows', 'CapitalInflow', 'IndustryInvestments', 'SectorBreakdown', 'InwardCapital', 'CrossSectorFDI'], 'sponsored_keywords': ['FDIEquity', 'InwardFDI', 'DirectInvestment', 'EquityInflow'], 'sector': 'Finance & Economy', 'processing_summary': {'keyword_logic': 'Derived 6–10 CamelCase keywords from the catalog title and description focusing on FDI equity inflows across sectors. Chosen terms that reflect inflows, investments, and sector breakdown without department names or India-specific terms. Ensured each keyword remains 1–2 words in CamelCase and relates to the dataset content (FDI, equity, inflows, sectors).', 'sector_logic': 'Primary sector selected as Finance & Economy since the catalog centers on macroeconomic investment flows and FDI. This aligns with the catalog’s emphasis on investment/inflow dynamics across multiple sectors rather than a single department or program.', 'sponsored_keywords': 'Selected 3–5 terms tightly tied to the exact catalog title and its focus on FDI equity inflows, while ensuring they are distinct from the enhanced keywords. Terms prioritize direct relevance to title concepts (FDI, equity, inflows, direct investment).'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: Foreign Direct Investment (FDI) Equity Inflows
SECTOR: Finance & Economy
KEYWORDS: ["FDIInflows", "EquityInflows", "SectorInvestments", "InvestmentFlows", "CapitalInflow", "IndustryInvestments", "SectorBreakdown", "InwardCapital", "CrossSectorFDI"]
SPONSORED: ["FDIEquity", "InwardFDI", "DirectInvestment", "EquityInflow"]

✓ Written to CSV

----------------------------

2025-11-24 11:47:45,600 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:47:45,609 : INFO - Result is {'generated_keywords': ['LayerFarms', 'BroilerFarms', 'DuckFarms', 'LayerBirds', 'BroilerBirds', 'DuckBirds', 'PoultryFarms', 'FarmCounts'], 'sponsored_keywords': ['PoultryBirds', 'FarmDetails', 'BirdCounts', 'FarmInventory'], 'sector': 'Agriculture', 'processing_summary': {'keyword_logic': 'Derived from the catalog title and description focusing on poultry farms and birds. Generated 8 layman-friendly CamelCase keywords capturing farm types (Layer/Broiler/Duck), bird types, and counts to aid discovery.', 'sector_logic': "Primary domain inferred as Agriculture based on the catalog's focus on poultry farming and livestock within the broader agriculture/animal husbandry context.", 'sponsored_keywords': 'Chosen 4 terms tightly aligned with the title (PoultryBirds, FarmDetails, BirdCounts, FarmInventory) while ensuring they differ from the enhanced keywords to provide precise search anchors.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: Details of Poultry Farms and Poultry Birds in Farms
SECTOR: Agriculture
KEYWORDS: ["LayerFarms", "BroilerFarms", "DuckFarms", "LayerBirds", "BroilerBirds", "DuckBirds", "PoultryFarms", "FarmCounts"]
SPONSORED: ["PoultryBirds", "FarmDetails", "BirdCounts", "FarmInventory"]

✓ Written to CSV

----------------------------

2025-11-24 11:47:47,037 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:47:47,046 : INFO - Result is {'generated_keywords': ['SeasonalTemp', 'AnnualTemp', 'MaxMinTemp', 'TemperatureSeries', 'ClimateTrend', 'TempAnomaly', 'WarmingTrends', 'RegionalTemp'], 'sponsored_keywords': ['SeasonalTemperature', 'AnnualTemperature', 'MinMaxTemperature', 'TemperatureTrends', 'WarmingTrend'], 'sector': 'Environment', 'processing_summary': {'keyword_logic': "Derived 6–10 layman-friendly keywords from the catalog title/description and existing fields. Used CamelCase, targeting 1–2 words per keyword. Focused on seasonal/annual temperature, min/max values, trends, and regional climate aspects while avoiding ministry/administrative terms and the word 'India'.", 'sector_logic': "Chose a primary sector that best matches the catalog's overall domain. Environment is most appropriate for climate/temperature time-series data and aligns with the catalog's focus, rather than administrative categories.", 'sponsored_keywords': 'Selected 3–5 strongest terms that closely reflect the catalog title concepts (seasonal/annual temperature, min/max, trends) and differ from the enhanced keywords to provide precise search anchors: SeasonalTemperature, AnnualTemperature, MinMaxTemperature, TemperatureTrends, WarmingTrend.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: All India Seasonal and Annual Min/Max Temperature Series
SECTOR: Environment
KEYWORDS: ["SeasonalTemp", "AnnualTemp", "MaxMinTemp", "TemperatureSeries", "ClimateTrend", "TempAnomaly", "WarmingTrends", "RegionalTemp"]
SPONSORED: ["SeasonalTemperature", "AnnualTemperature", "MinMaxTemperature", "TemperatureTrends", "WarmingTrend"]

✓ Written to CSV

----------------------------

2025-11-24 11:47:48,630 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:47:48,638 : INFO - Result is {'generated_keywords': ['TrainSchedule', 'ArrivalTimes', 'DepartureTimes', 'RouteInfo', 'StationTimings', 'TimetableData', 'TrainRoutes', 'StationInfo'], 'sponsored_keywords': ['TrainTimetable', 'RailTimetable', 'StationRoutes', 'RouteTimings'], 'sector': 'Transport', 'processing_summary': {'keyword_logic': 'Derived 6–10 layman-friendly, CamelCase keywords from the catalog title and description, focusing on user-facing concepts: train schedules, times, routes and stations. Avoids administrative terms and India-specific terms; uses simplified terms like Schedule, Times, Route, Station to improve discoverability. Ensured 1–2 words per item and CamelCase formatting.', 'sector_logic': "Assigned primary sector based on the catalog's domain: transport-focused train time table data, reflecting the overarching scope of railway transportation and timetabling.", 'sponsored_keywords': 'Sponsored keywords chosen to closely match the catalog title and core concepts, prioritizing exact title relevance such as TrainTimetable and RailTimetable, plus complementary terms like StationRoutes and RouteTimings to cover key aspects of the timetable data.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword', 'dcterms:title', 'dcterms:description']}

TITLE: Indian Railways Train Time Table
SECTOR: Transport
KEYWORDS: ["TrainSchedule", "ArrivalTimes", "DepartureTimes", "RouteInfo", "StationTimings", "TimetableData", "TrainRoutes", "StationInfo"]
SPONSORED: ["TrainTimetable", "RailTimetable", "StationRoutes", "RouteTimings"]

✓ Written to CSV

----------------------------

2025-11-24 11:47:59,005 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:47:59,008 : INFO - Result is {'generated_keywords': ['MaternalCare', 'ChildImmunization', 'FamilyPlanning', 'AntenatalCare', 'BirthRegistration', 'CleanFuel', 'WaterSupply', 'ToiletFacilities', 'Haemoglobin'], 'sponsored_keywords': ['DistrictLevel', 'HouseholdSurvey', 'FacilitySurvey', 'HealthSurvey'], 'sector': 'Health', 'processing_summary': {'keyword_logic': "Keywords were derived by mapping the catalog's health-focused content (maternal care, child immunization, fertility and family planning, antenatal care, birth registration, WASH-related facilities, and health indicators like haemoglobin) to 1–2 word CamelCase terms that are easily discoverable and reflect the dataset's scope without relying on department names or overly generic terms.", 'sector_logic': 'Health was chosen as the primary sector because the DLHS-4 catalog centers on health services, maternal and child health, immunization, facility infrastructure, and village health facilities, aligning with the Health DCAT-AP sector rather than other domains.', 'sponsored_keywords': 'Sponsored keywords are anchored to the catalog title components: DistrictLevel, HouseholdSurvey, FacilitySurvey, and HealthSurvey. They are 1–2 word CamelCase terms that closely match the title while remaining distinct from the enhanced keywords.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: District Level Household and Facility Survey (DLHS-4)
SECTOR: Health
KEYWORDS: ["MaternalCare", "ChildImmunization", "FamilyPlanning", "AntenatalCare", "BirthRegistration", "CleanFuel", "WaterSupply", "ToiletFacilities", "Haemoglobin"]
SPONSORED: ["DistrictLevel", "HouseholdSurvey", "FacilitySurvey", "HealthSurvey"]

✓ Written to CSV

----------------------------

2025-11-24 11:48:10,066 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:48:10,074 : INFO - Result is {'generated_keywords': ['CoreIndustries', 'IndustrialProduction', 'ProductionIndex', 'Electricity', 'Steel', 'CrudeOil', 'NaturalGas', 'Cement', 'Fertilizers'], 'sponsored_keywords': ['EightCore', 'IndustrialIndex', 'IndustrialOutput', 'ProductionGrowth'], 'sector': 'Commerce & Industry', 'processing_summary': {'keyword_logic': 'Enhanced keywords were derived from the catalog’s emphasis on the Eight Core Industries and the production/index theme. Included core sector terms (Electricity, Steel, CrudeOil, NaturalGas, Cement, Fertilizers) and concepts (IndustrialProduction, ProductionIndex) plus a couple of umbrella core terms (CoreIndustries) to maximize discoverability while keeping to 1–2 CamelCase words.', 'sector_logic': 'Primary sector chosen as Commerce & Industry to reflect the catalog’s focus on industrial production and manufacturing, consistent with the existing theme (Industries; Manufacturing) and the catalog’s economic/industrial orientation.', 'sponsored_keywords': "Sponsored keywords were selected to closely reflect the catalog title 'Eight Core Industries' and target high-relevance terms: EightCore, IndustrialIndex, IndustrialOutput, ProductionGrowth. They are 1–2 CamelCase words and distinct from the enhanced keywords."}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword', 'dcterms:title', 'dcterms:description']}

TITLE: Eight Core Industries
SECTOR: Commerce & Industry
KEYWORDS: ["CoreIndustries", "IndustrialProduction", "ProductionIndex", "Electricity", "Steel", "CrudeOil", "NaturalGas", "Cement", "Fertilizers"]
SPONSORED: ["EightCore", "IndustrialIndex", "IndustrialOutput", "ProductionGrowth"]

✓ Written to CSV

----------------------------

2025-11-24 11:48:13,645 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:48:13,651 : INFO - Result is {'generated_keywords': ['NewlyRegistered', 'MotorVehicles', 'TransportVehicles', 'VehicleCounts', 'UttarPradeshTransport', 'NonTransportVehicles', 'VehicleRegistration', 'RoadTransport'], 'sponsored_keywords': ['NewRegistrations', 'TransportRegistrations', 'UttarPradeshVehicles', 'VehicleRegistrations'], 'sector': 'Transport', 'processing_summary': {'keyword_logic': 'Derived from the catalog’s focus on counts of newly registered and existing motor vehicles in Uttar Pradesh, including transport vs non-transport categories. Generated keywords are 1–2 CamelCase terms that reflect vehicle registration, transport context, and regional scope without administrative terms.', 'sector_logic': 'Primary domain matches transport of vehicles data in Uttar Pradesh; chosen sector is Transport per the catalog’s title and description, with Road Transport as a sub-context already present in subject/theme fields.', 'sponsored_keywords': 'Selected 3–4 terms that closely mirror the catalog title emphasis on registrations and vehicle types in Uttar Pradesh, ensuring they are concise CamelCase terms and distinct from the broader generated keywords.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword', 'dcterms:title', 'dcterms:description']}

TITLE: Number of Newly Registered Motor Vehicles and Number of Registered Motor Vehicles in Uttar Pradesh
SECTOR: Transport
KEYWORDS: ["NewlyRegistered", "MotorVehicles", "TransportVehicles", "VehicleCounts", "UttarPradeshTransport", "NonTransportVehicles", "VehicleRegistration", "RoadTransport"]
SPONSORED: ["NewRegistrations", "TransportRegistrations", "UttarPradeshVehicles", "VehicleRegistrations"]

✓ Written to CSV

----------------------------

2025-11-24 11:48:24,454 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:48:24,460 : INFO - Result is {'generated_keywords': ['NewRegistrations', 'RegisteredVehicles', 'TransportVehicles', 'NonTransport', 'CarRegistrations', 'BusRegistrations', 'TruckRegistrations', 'VehicleCounts', 'RegistrationTrends', 'TamilNadu'], 'sponsored_keywords': ['NewlyRegistered', 'MotorVehicles', 'VehicleRegistrations', 'TamilNadu', 'TotalRegistrations'], 'sector': 'Transport', 'processing_summary': {'keyword_logic': 'Generated 10 layman-friendly keywords (1–2 words in natural reading, CamelCase) reflecting the catalog content: newly registered vs registered vehicles, transport vs non-transport categories, vehicle types (cars, buses, trucks), counts and trends, and the Tamil Nadu location. Avoided department names and India mentions. Ensured terms map to the dataset focus on motor vehicle registrations and transport categorization.', 'sector_logic': 'Chose Transport as the primary sector because the catalog centers on motor vehicle registrations and transport category breakdowns (Transport vs Non-Transport) within Road Transport data. This aligns with the DCAT-India sector taxonomy and the catalog’s domain.', 'sponsored_keywords': 'Selected 5 title-aligned terms that closely reflect the catalog title while remaining distinct from the enhanced keywords: NewlyRegistered, MotorVehicles, VehicleRegistrations, TamilNadu, TotalRegistrations. These capture the core scope (new and total registrations, vehicle types, and location).'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: Number of Newly Registered Motor Vehicles and Number of Registered Motor Vehicles in Tamil Nadu
SECTOR: Transport
KEYWORDS: ["NewRegistrations", "RegisteredVehicles", "TransportVehicles", "NonTransport", "CarRegistrations", "BusRegistrations", "TruckRegistrations", "VehicleCounts", "RegistrationTrends", "TamilNadu"]
SPONSORED: ["NewlyRegistered", "MotorVehicles", "VehicleRegistrations", "TamilNadu", "TotalRegistrations"]

✓ Written to CSV

----------------------------

2025-11-24 11:48:25,899 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:48:25,907 : INFO - Result is {'generated_keywords': ['CPIIndex', 'RuralCPI', 'UrbanCPI', 'PriceIndex', 'MonthlyCPI', 'HouseholdPrices', 'PriceDeflator', 'BaseYear2010', 'InflationIndicator'], 'sponsored_keywords': ['AllIndia', 'ConsumerPriceIndex', 'RuralUrban', 'CPIIndices', 'MonthlyIndex'], 'sector': 'Finance & Economy', 'processing_summary': {'keyword_logic': 'From the catalog title and description, generated 9 layman-friendly keywords in CamelCase describing CPI, rural/urban scope, price indexing, monthly updates, base year, and inflation context. Each is 1–2 words when possible and avoids department names.', 'sector_logic': 'Primary sector chosen as Finance & Economy to reflect macroeconomic data collection, inflation measurement, and price indices typical of national statistical outputs.', 'sponsored_keywords': 'Selected terms that map closely to the catalog title while staying distinct from the enhanced keywords; included AllIndia and ConsumerPriceIndex for exact title relevance, plus RuralUrban and CPIIndices and MonthlyIndex.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword', 'dcterms:title', 'dcterms:description']}

TITLE: All India Consumer Price Index (Rural/Urban)
SECTOR: Finance & Economy
KEYWORDS: ["CPIIndex", "RuralCPI", "UrbanCPI", "PriceIndex", "MonthlyCPI", "HouseholdPrices", "PriceDeflator", "BaseYear2010", "InflationIndicator"]
SPONSORED: ["AllIndia", "ConsumerPriceIndex", "RuralUrban", "CPIIndices", "MonthlyIndex"]

✓ Written to CSV

----------------------------

2025-11-24 11:48:37,791 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:48:37,797 : INFO - Result is {'generated_keywords': ['NewlyRegisteredVehicles', 'RegisteredVehicles', 'TransportVehicles', 'NonTransportVehicles', 'MotorVehicles', 'VehicleCategories', 'DelhiRegistrations', 'RegistrationStatistics'], 'sponsored_keywords': ['NewRegistrations', 'RegistrationCounts', 'MotorVehicleData', 'TransportStatistics'], 'sector': 'Transport', 'processing_summary': {'keyword_logic': 'Generated keywords are 6–10 layman terms derived from the catalog title and description. They capture the two main data aspects (newly registered vehicles and total registered vehicles), the two broad vehicle categories (Transport and Non-Transport), and the Delhi focus, expressed in CamelCase and kept to concise forms.', 'sector_logic': 'Primary sector chosen is Transport because the catalog centers on motor vehicle registrations and their categorization under Transport and Non-Transport, aligning with the Transport sector in the DCAT-AP vocabulary and the catalog’s Road Transport context.', 'sponsored_keywords': ' Sponsored keywords are 3–5 terms most tightly tied to the catalog title, emphasizing core concepts such as new registrations, overall registrations, motor vehicles, and transport context, while avoiding administrative terms.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: Number of Newly Registered Motor Vehicles and Number of Registered Motor Vehicles in Delhi
SECTOR: Transport
KEYWORDS: ["NewlyRegisteredVehicles", "RegisteredVehicles", "TransportVehicles", "NonTransportVehicles", "MotorVehicles", "VehicleCategories", "DelhiRegistrations", "RegistrationStatistics"]
SPONSORED: ["NewRegistrations", "RegistrationCounts", "MotorVehicleData", "TransportStatistics"]

✓ Written to CSV

----------------------------

2025-11-24 11:48:42,342 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:48:42,352 : INFO - Result is {'generated_keywords': ['RuralCPI', 'UrbanCPI', 'PriceIndex', 'ConsumerPrices', 'InflationIndicator', 'MonthlyCPI', 'InflationTrend', 'PriceMovement', 'InflationRate', 'PriceSeries'], 'sponsored_keywords': ['CPIIndex', 'InflationIndex', 'EconomicIndicator', 'PriceInflation'], 'sector': 'Finance & Economy', 'processing_summary': {'keyword_logic': "Generated keywords are 1–2 CamelCase terms that reflect the catalog's focus on state-level CPI with rural/urban distinctions, price indices, and inflation-related indicators, avoiding department names and overly generic terms.", 'sector_logic': 'Primary sector chosen as Finance & Economy to align with macroeconomic indicators (CPI) and price data, based on the catalog title and description.', 'sponsored_keywords': 'Sponsored keywords are concise terms derived from the title that capture core concepts of CPI, inflation indices, and economic indicators to optimize direct search relevance.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: State Level Consumer Price Index (Rural/Urban)
SECTOR: Finance & Economy
KEYWORDS: ["RuralCPI", "UrbanCPI", "PriceIndex", "ConsumerPrices", "InflationIndicator", "MonthlyCPI", "InflationTrend", "PriceMovement", "InflationRate", "PriceSeries"]
SPONSORED: ["CPIIndex", "InflationIndex", "EconomicIndicator", "PriceInflation"]

✓ Written to CSV

----------------------------

2025-11-24 11:48:46,489 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:48:46,500 : INFO - Result is {'generated_keywords': ['WholesaleIndex', 'CommodityPrices', 'FuelAndPower', 'PrimaryArticles', 'ManufacturedProducts', 'InflationIndex', 'EconomicIndicator', 'MarketPrices'], 'sponsored_keywords': ['WholesalePriceIndex', 'WPI', 'PriceIndexTrend', 'IndexMovements'], 'sector': 'Finance & Economy', 'processing_summary': {'keyword_logic': "Enhanced keywords were derived from the catalog's core content: wholesale price data, commodity pricing, and components of the WPI (primary articles, fuel and power, manufactured products). Terms were limited to 1–2 CamelCase words to ensure discoverability while avoiding overly vague or administrative words. The set balances specificity with user-friendly reach, drawing from the title/description and existing subject/theme cues.", 'sector_logic': 'The catalog centers on macroeconomic price indices and inflation indicators (WPI) across the economy, aligning with the Finance & Economy sector. This sector choice reflects the catalog’s domain as a macroeconomic price index resource, consistent with its publisher context in commerce and industry statistics.', 'sponsored_keywords': 'Sponsored terms tightly mirror the catalog title, including a full compound term (WholesalePriceIndex) and a common acronym (WPI), plus trend-related terms (PriceIndexTrend, IndexMovements) to capture dynamic aspects of the index. These are distinct from the enhanced keywords to provide complementary, title-focused retrieval cues.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: Wholesale Price Index
SECTOR: Finance & Economy
KEYWORDS: ["WholesaleIndex", "CommodityPrices", "FuelAndPower", "PrimaryArticles", "ManufacturedProducts", "InflationIndex", "EconomicIndicator", "MarketPrices"]
SPONSORED: ["WholesalePriceIndex", "WPI", "PriceIndexTrend", "IndexMovements"]

✓ Written to CSV

----------------------------

2025-11-24 11:48:56,785 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:48:56,788 : INFO - Result is {'generated_keywords': ['RoadAccidents', 'StateWise', 'AccidentData', 'TrafficInjuries', 'Fatalities', 'RoadSafety', 'AccidentStats', 'PoliceRecords'], 'sponsored_keywords': ['UTStatistics', 'StateAccidents', 'AccidentCounts', 'TrafficStats', 'CasualtiesData'], 'sector': 'Transport', 'processing_summary': {'keyword_logic': 'Derived from the catalog title and description focusing on state/UT level road accidents data. Selected 6–10 layman-friendly, CamelCase terms that reflect road accidents, statistics, injuries and fatalities at the state/UT level, avoiding ministry names and overly generic terms.', 'sector_logic': 'Primary sector chosen is Transport because the catalog centers on road accident data collection and statistics (road transport domain), aligning with the existing theme and subject related to road transport.', 'sponsored_keywords': 'Chosen to map directly to the title’s key concepts (state/UT level, accidents, statistics) in compact CamelCase forms. Ensures strong title relevance while remaining distinct from the generated keywords.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: State/UT wise total no of road accidents
SECTOR: Transport
KEYWORDS: ["RoadAccidents", "StateWise", "AccidentData", "TrafficInjuries", "Fatalities", "RoadSafety", "AccidentStats", "PoliceRecords"]
SPONSORED: ["UTStatistics", "StateAccidents", "AccidentCounts", "TrafficStats", "CasualtiesData"]

✓ Written to CSV

----------------------------

2025-11-24 11:49:00,555 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:49:00,559 : INFO - Result is {'generated_keywords': ['Seismotectonics', 'Earthquakes', 'FaultSystems', 'GravityContours', 'MohoDepth', 'Bathymetry', 'TectonicsMaps', 'SeismicData', 'Geophysics', 'CrustalThickness'], 'sponsored_keywords': ['SeismotectonicAtlas', 'EarthquakeDataset', 'SeismicAtlas', 'TectonicsMap', 'CrustalProfiles'], 'sector': 'Science & Technology', 'processing_summary': {'keyword_logic': "Generated 10 layman-friendly, CamelCase keywords that reflect the atlas's seismotectonic/geophysical content (e.g., earthquakes, gravity contours, Moho depth), derived from the title and description. 1–2 words each, avoiding administrative terms and India-specific references.", 'sector_logic': "Primary domain inferred from the catalog's geoscience focus (seismotectonics, geophysics, gravity, crustal studies). Selected Science & Technology as the core sector; other domains not as central.", 'sponsored_keywords': 'Chosen 3–5 terms that closely mirror the catalog title themes (SeismotectonicAtlas, EarthquakeDataset, SeismicAtlas, TectonicsMap, CrustalProfiles), ensuring they differ from the general enhanced keywords.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword', 'dcterms:title', 'dcterms:description']}

TITLE: Digital Seismotectonic Atlas of India and its Environs
SECTOR: Science & Technology
KEYWORDS: ["Seismotectonics", "Earthquakes", "FaultSystems", "GravityContours", "MohoDepth", "Bathymetry", "TectonicsMaps", "SeismicData", "Geophysics", "CrustalThickness"]
SPONSORED: ["SeismotectonicAtlas", "EarthquakeDataset", "SeismicAtlas", "TectonicsMap", "CrustalProfiles"]

✓ Written to CSV

----------------------------

2025-11-24 11:49:02,503 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:49:02,510 : INFO - Result is {'generated_keywords': ['GDPCurrentPrices', 'QuarterlyGDP', 'ConsumptionExpenditure', 'CapitalFormation', 'NetIncome', 'SavingsRate', 'SectorBreakdown', 'GrowthRates', 'ExportsImports'], 'sponsored_keywords': ['QuarterlyEstimates', 'CurrentPrices', 'GDPEstimates', 'GDPGrowth'], 'sector': 'Finance & Economy', 'processing_summary': {'keyword_logic': 'Generated keywords are 1–2 CamelCase terms that reflect the catalog’s GDP-focused content: current price GDP, quarterly GDP, key macroeconomic components (consumption expenditure, capital formation, net income, savings), sector breakdown and growth rates, plus trade indicators (exports/imports). These are designed to be layman-friendly and non-administrative, pulling from the title/description and existing subject/theme keywords.', 'sector_logic': 'Selected Finance & Economy as the primary sector because the catalog centers on macroeconomic indicators (GDP, expenditures, growth) and overall economic performance, aligning with the catalog’s scope over other domains.', 'sponsored_keywords': 'Sponsored keywords are 3–5 terms directly tied to the title, expressed as 1–2 CamelCase words, and intentionally distinct from the enhanced keywords. They emphasize the quarterly estimation aspect and current-price GDP references (QuarterlyEstimates, CurrentPrices, GDPEstimates, GDPGrowth).'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: Quarterly Estimates of GDP at Current Prices
SECTOR: Finance & Economy
KEYWORDS: ["GDPCurrentPrices", "QuarterlyGDP", "ConsumptionExpenditure", "CapitalFormation", "NetIncome", "SavingsRate", "SectorBreakdown", "GrowthRates", "ExportsImports"]
SPONSORED: ["QuarterlyEstimates", "CurrentPrices", "GDPEstimates", "GDPGrowth"]

✓ Written to CSV

----------------------------

2025-11-24 11:49:12,464 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:49:12,470 : INFO - Result is {'generated_keywords': ['PetroleumConsumption', 'PetroleumUsage', 'ConsumptionGrowth', 'EleventhPlan', 'BaseScenario', 'UpperScenario', 'CAGRTrends', 'OilDemand'], 'sponsored_keywords': ['PetroleumProducts', 'PetroleumDemand', 'OilConsumption', 'ConsumptionTrends'], 'sector': 'Energy', 'processing_summary': {'keyword_logic': 'Derived from the catalog title and description focusing on consumption of petroleum products, growth rates (CAGR), and scenario context (base/upper) within the Eleventh Plan. Selected 6–10 CamelCase keywords that reflect core concepts (consumption, usage, growth, plans, scenarios) while avoiding administrative terms.', 'sector_logic': "Primary sector selected as Energy to reflect the catalog's focus on petroleum product consumption, a non-renewable energy domain, aligning with the dataset content rather than governance or geographic terms.", 'sponsored_keywords': 'Chosen 3–5 terms that map directly to the catalog title: PetroleumProducts and PetroleumDemand closely mirror the title; OilConsumption and ConsumptionTrends provide exact, title-relevant variants that are distinct from the enhanced keywords.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: Consumption of Petroleum Products
SECTOR: Energy
KEYWORDS: ["PetroleumConsumption", "PetroleumUsage", "ConsumptionGrowth", "EleventhPlan", "BaseScenario", "UpperScenario", "CAGRTrends", "OilDemand"]
SPONSORED: ["PetroleumProducts", "PetroleumDemand", "OilConsumption", "ConsumptionTrends"]

✓ Written to CSV

----------------------------

2025-11-24 11:49:17,094 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:49:17,100 : INFO - Result is {'generated_keywords': ['MapViewer', 'PanchromaticImagery', 'BhuvanImagery', 'OpenStreetMap', 'AndhraPradeshMap', 'LayerControl', 'GeospatialPortal', 'WebMap', 'SpatialData'], 'sponsored_keywords': ['WebMapService', 'AndhraPradesh', 'SpatialPortal', 'MapView'], 'sector': 'Science & Technology', 'processing_summary': {'keyword_logic': 'Keywords were drawn from the catalog title and description to reflect a geospatial viewing service that uses layered imagery (panchromatic/Bhuvan) and OpenStreetMap data for a specific region (Andhra Pradesh). They are 1–2 words each, CamelCase, and avoid ministry names, generic terms, or the word India. The set emphasizes user discovery around map viewing, layers, imagery, and regional scope.', 'sector_logic': 'The catalog centers on an OGC Web Map Service (WMS) providing geospatial visualization data. This aligns with the Science & Technology sector, reflecting geospatial data technology, standards (OGC), and mapping infrastructure rather than purely administrative or policy-focused domains.', 'sponsored_keywords': 'Sponsored terms were chosen to closely mirror the catalog title and core offering (WebMapService for the service type, AndhraPradesh for regional scope, SpatialPortal as a geospatial interface concept, MapView as a user-facing map visualization action). They are 1–2 words, CamelCase, and distinct from the enhanced_keywords set.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: Web Map Service (WMS) from Survey of India OSM Data and Bhuvan for Andhra Pradesh
SECTOR: Science & Technology
KEYWORDS: ["MapViewer", "PanchromaticImagery", "BhuvanImagery", "OpenStreetMap", "AndhraPradeshMap", "LayerControl", "GeospatialPortal", "WebMap", "SpatialData"]
SPONSORED: ["WebMapService", "AndhraPradesh", "SpatialPortal", "MapView"]

✓ Written to CSV

----------------------------

2025-11-24 11:49:20,979 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:49:20,983 : INFO - Result is {'generated_keywords': ['TwoWheelers', 'Cars', 'Jeeps', 'Taxis', 'Buses', 'GoodsVehicles', 'OtherVehicles', 'VehicleCounts', 'VehicleRegistrations'], 'sponsored_keywords': ['TotalVehicles', 'VehicleRegistration', 'RegisteredVehicles', 'VehicleTotals'], 'sector': 'Transport', 'processing_summary': {'keyword_logic': 'Enhanced keywords are derived from the catalog content: vehicle types (TwoWheelers, Cars, Jeeps, Taxis, Buses) and vehicle categories (GoodsVehicles, OtherVehicles) plus data concepts (VehicleCounts, VehicleRegistrations) expressed in CamelCase with 1–2 underlying words. Sponsored keywords are shorter, title-aligned terms (TotalVehicles, VehicleRegistration, RegisteredVehicles, VehicleTotals) that reflect core aspects of the dataset while avoiding exact duplicates of the enhanced set.', 'sector_logic': "Transport is chosen as the primary sector because the catalog centers on counts of registered motor vehicles and their types, aligning with the catalog's existing dcat:theme values (Transport, Road Transport) and the title/description.", 'sponsored_keywords': 'Sponsored keywords were selected to mirror the essence of the title (totals, registrations, counts) in 1–2 word CamelCase terms, ensuring they are close to the title relevance but distinct from the enhanced_keywords set.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword', 'dcterms:title', 'dcterms:description']}

TITLE: Total Number of Registered Motor Vehicles in India
SECTOR: Transport
KEYWORDS: ["TwoWheelers", "Cars", "Jeeps", "Taxis", "Buses", "GoodsVehicles", "OtherVehicles", "VehicleCounts", "VehicleRegistrations"]
SPONSORED: ["TotalVehicles", "VehicleRegistration", "RegisteredVehicles", "VehicleTotals"]

✓ Written to CSV

----------------------------

2025-11-24 11:49:21,268 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:49:21,272 : INFO - Result is {'generated_keywords': ['CropArea', 'CropProduction', 'SeasonWise', 'YearWise', 'YieldData', 'AgroClimatic', 'CropDiversification', 'HectaresData'], 'sponsored_keywords': ['CropStatistics', 'SeasonalStats', 'ProductionStats', 'YieldStats'], 'sector': 'Agriculture', 'processing_summary': {'keyword_logic': 'Generated keywords are 1–2 word CamelCase terms derived from the catalog content: crop area, crop production, season/year-wise data, yield, and agro-climatic context. Avoids administrative terms; ensures user-friendly, discoverable terms that reflect dataset scope.', 'sector_logic': 'Primary sector chosen as Agriculture because the catalog describes district- and season-wise crop production and area data, aligning with agricultural production and agro-economy analysis.', 'sponsored_keywords': "Selected from the title 'District-wise, season-wise crop production statistics' focusing on exact relevance: CropStatistics, SeasonalStats, ProductionStats, YieldStats; these are 1–2 words and distinct from generated keywords."}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword', 'dcterms:title', 'dcterms:description']}

TITLE: District-wise, season-wise crop production statistics
SECTOR: Agriculture
KEYWORDS: ["CropArea", "CropProduction", "SeasonWise", "YearWise", "YieldData", "AgroClimatic", "CropDiversification", "HectaresData"]
SPONSORED: ["CropStatistics", "SeasonalStats", "ProductionStats", "YieldStats"]

✓ Written to CSV

----------------------------

2025-11-24 11:49:23,316 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:49:23,320 : INFO - Result is {'generated_keywords': ['DistrictRainfall', 'MonthlyRainfall', 'SeasonalRainfall', 'AnnualRainfall', 'RainfallNormals', 'ClimatologicalNormals', 'DistrictClimatology', 'RainfallData'], 'sponsored_keywords': ['RainfallTimeSeries', 'PrecipitationStats', 'DistrictPrecipitation', 'ClimateNormals'], 'sector': 'Water Resources', 'processing_summary': {'keyword_logic': 'Derived 8 CamelCase keywords from the title/description highlighting district-level rainfall, monthly/seasonal/annual patterns and normals. Ensured terms are user-friendly, non-technical, and avoid administrative names. Kept within 1–2 conceptual words per keyword while using CamelCase tokens.', 'sector_logic': 'Primary sector selected as Water Resources because the catalog centers on district rainfall normals and their relevance to hydrology and water resource planning, aligning with sector taxonomy and the catalog’s climatology/water focus.', 'sponsored_keywords': 'Selected 4 terms that closely match the dataset’s exact emphasis in the title (rainfall, time-frame, normals/stats) but are distinct from enhanced keywords to emphasize direct title relevance.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword', 'dcterms:title', 'dcterms:description']}

TITLE: District Rainfall Normal (in mm) Monthly, Seasonal And Annual : Data Period 1951-2000
SECTOR: Water Resources
KEYWORDS: ["DistrictRainfall", "MonthlyRainfall", "SeasonalRainfall", "AnnualRainfall", "RainfallNormals", "ClimatologicalNormals", "DistrictClimatology", "RainfallData"]
SPONSORED: ["RainfallTimeSeries", "PrecipitationStats", "DistrictPrecipitation", "ClimateNormals"]

✓ Written to CSV

----------------------------

2025-11-24 11:49:26,940 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:49:26,950 : INFO - Result is {'generated_keywords': ['CommodityPrices', 'MarketPrices', 'DailyPrices', 'WholesalePrices', 'MandiRates', 'PriceTrends', 'PriceData', 'AgriculturalMarkets'], 'sponsored_keywords': ['CurrentPrices', 'MandiMarkets', 'MarketRates', 'DailyMarkets', 'CommodityMarkets'], 'sector': 'Agriculture', 'processing_summary': {'keyword_logic': "Enhanced keywords were created by extracting core, user-facing concepts from the catalog's focus: daily price data for agricultural commodities across markets. Terms were condensed into 1–2 word CamelCase forms that are easily discoverable and avoid bureaucratic or India-centric language. Selected terms emphasize prices, markets, and commodity-focused data (e.g., CommodityPrices, MarketPrices, DailyPrices, WholesalePrices, MandiRates, PriceTrends, PriceData, AgriculturalMarkets).", 'sector_logic': 'The catalog centers on agricultural commodity pricing and markets (via AGMARKNET). Therefore Agriculture is designated as the primary sector to reflect the catalog’s overall domain and authoritative context.', 'sponsored_keywords': 'Sponsored keywords are tightly aligned with the catalog title and emphasize the core identifying terms (CurrentPrices, MandiMarkets, MarketRates, DailyMarkets, CommodityMarkets). They are 1–2 word CamelCase terms designed to strongly match search intent while remaining distinct from the enhanced keywords.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: Current daily price of various commodities from various markets (Mandi)
SECTOR: Agriculture
KEYWORDS: ["CommodityPrices", "MarketPrices", "DailyPrices", "WholesalePrices", "MandiRates", "PriceTrends", "PriceData", "AgriculturalMarkets"]
SPONSORED: ["CurrentPrices", "MandiMarkets", "MarketRates", "DailyMarkets", "CommodityMarkets"]

✓ Written to CSV

----------------------------

2025-11-24 11:49:27,307 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:49:27,314 : INFO - Result is {'generated_keywords': ['StateGDP', 'EconomicOutput', 'RegionalGDP', 'GrossValueAdded', 'StateEconomy', 'StateAccounts', 'EconomicScale', 'RegionalEconomy'], 'sponsored_keywords': ['DomesticProduct', 'GrossStateGDP', 'CurrentPrices', 'NominalGDP'], 'sector': 'Finance & Economy', 'processing_summary': {'keyword_logic': "Generated from the catalog's focus on state-level economic performance expressed as GDP at current prices. Selected CamelCase terms reflect core concepts (state-level GDP, regional aspects, and economic aggregates like Gross Value Added) while avoiding ministry names and overly technical terms. This set emphasizes layman-friendly, discoverable concepts aligned with the catalog title and description.", 'sector_logic': 'Finance & Economy is chosen as the primary sector because the catalog centers on GDP at the state level, a fundamental economic indicator tied to finance, economy, and statistical measurement within a governmental context. The choice is consistent with existing subject/theme hints (State Economy; Finance;Economy;Statistics).', 'sponsored_keywords': 'Sponsored keywords are drawn directly from the catalog title emphasis on Gross State Domestic Product at Current Prices. They target precise, high-signal terms (DomesticProduct, GrossStateGDP, CurrentPrices, NominalGDP) to improve exact-title relevance while remaining distinct from the broader generated keywords.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: Gross State Domestic Product at Current Prices
SECTOR: Finance & Economy
KEYWORDS: ["StateGDP", "EconomicOutput", "RegionalGDP", "GrossValueAdded", "StateEconomy", "StateAccounts", "EconomicScale", "RegionalEconomy"]
SPONSORED: ["DomesticProduct", "GrossStateGDP", "CurrentPrices", "NominalGDP"]

✓ Written to CSV

----------------------------

2025-11-24 11:49:37,994 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:49:38,002 : INFO - Result is {'generated_keywords': ['MajorChemicals', 'ChemicalImports', 'ProductWise', 'GroupWise', 'ImportQuantities', 'ImportValues', 'AlkaliChemicals', 'DyesDyestuff', 'InorganicChemicals', 'OrganicChemicals'], 'sponsored_keywords': ['MajorImports', 'ChemImport', 'ProductBreakdown', 'GroupBreakdown'], 'sector': 'Commerce & Industry', 'processing_summary': {'keyword_logic': 'Generated 10 layman-friendly keywords by distilling the catalog’s focus on importing major chemicals, with product-wise and group-wise classifications, and by highlighting chemical categories and import metrics. Ensured CamelCase, kept to 1–2 words per keyword, and avoided generic or administrative terms.', 'sector_logic': 'Chose Commerce & Industry as the primary sector because the catalog centers on import activity and industrial chemicals trade, aligning with the catalog’s industrial/petrochemicals context and publisher focus rather than governance or public administration.', 'sponsored_keywords': 'Selected 4 strongest, title-aligned terms that reflect the core concept of the dataset (major imports, product/group granularity) while ensuring distinctness from enhanced keywords.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: Import of Major Chemicals - Product-wise / Group-wise
SECTOR: Commerce & Industry
KEYWORDS: ["MajorChemicals", "ChemicalImports", "ProductWise", "GroupWise", "ImportQuantities", "ImportValues", "AlkaliChemicals", "DyesDyestuff", "InorganicChemicals", "OrganicChemicals"]
SPONSORED: ["MajorImports", "ChemImport", "ProductBreakdown", "GroupBreakdown"]

✓ Written to CSV

----------------------------

2025-11-24 11:49:44,839 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:49:44,845 : INFO - Result is {'generated_keywords': ['RealGDP', 'QuarterlyGDP', 'ConstantPrices', 'FinalConsumption', 'ConsumptionExpenditure', 'MacroEconomy', 'EconomicGrowth', 'Exports', 'Imports'], 'sponsored_keywords': ['QuarterlyGDP', 'RealGDP', 'GDPEstimates', 'ConstantPricesGDP'], 'sector': 'Finance & Economy', 'processing_summary': {'keyword_logic': 'Keywords were derived from the catalog’s focus on GDP, quarterly estimates, and macroeconomic aggregates at constant prices. They use CamelCase, are 1–2 words where possible, and avoid administrative terms. The set targets layman discoverability while reflecting the dataset content (GDP, consumption, exports/imports, macroeconomy).', 'sector_logic': 'Finance & Economy is identified as the primary sector since the catalog centers on GDP and macroeconomic indicators, aligning with economic governance and fiscal analysis domains commonly categorized under Finance & Economy in the DCAT-AP framework.', 'sponsored_keywords': 'Sponsored terms are tightly aligned with the catalog title and core concepts (QuarterlyGDP, RealGDP, GDPEstimates, ConstantPricesGDP) to maximize exact-match relevance and search visibility while remaining distinct from the broader enhanced keywords.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: Quarterly Estimates of GDP at Constant Prices
SECTOR: Finance & Economy
KEYWORDS: ["RealGDP", "QuarterlyGDP", "ConstantPrices", "FinalConsumption", "ConsumptionExpenditure", "MacroEconomy", "EconomicGrowth", "Exports", "Imports"]
SPONSORED: ["QuarterlyGDP", "RealGDP", "GDPEstimates", "ConstantPricesGDP"]

✓ Written to CSV

----------------------------

2025-11-24 11:49:51,123 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-24 11:49:51,130 : INFO - Result is {'generated_keywords': ['QuarterlyGDP', 'RealGDP', 'ConstantPrices', 'BaseYearPrices', 'GDPEstimates', 'MacroEconomy', 'EconomicIndicator', 'EconomicActivity'], 'sponsored_keywords': ['GDPQuarterly', 'NationalAccounts', 'EconomicGrowth', 'GDPOutput'], 'sector': 'Finance & Economy', 'processing_summary': {'keyword_logic': 'Derived 8 CamelCase keywords by extracting core concepts from the catalog title and description (GDP, quarterly, constant prices) and supplementing with related economic terms present in the subject/theme. The terms are kept to 1–2 words where possible, avoid administrative or India-specific labels, and are intended to improve layman discoverability of GDP-related quarterly data at constant prices.', 'sector_logic': 'Primary sector selected is Finance & Economy because the catalog centers on macroeconomic performance metrics (GDP) and national economic activity, aligning with standard DCAT-India sector taxonomy for economic data.', 'sponsored_keywords': 'Sponsored keywords were chosen to closely map to the exact title intent while remaining concise and distinct from the enhancedKeywords. They emphasize the quarterly and GDP/constant-prices aspects and include terms commonly used in economic data queries.'}, 'source_fields_used': ['dcterms:subject', 'dcat:theme', 'dcat:keyword']}

TITLE: Quarterly Estimates of GDP at Constant Prices
SECTOR: Finance & Economy
KEYWORDS: ["QuarterlyGDP", "RealGDP", "ConstantPrices", "BaseYearPrices", "GDPEstimates", "MacroEconomy", "EconomicIndicator", "EconomicActivity"]
SPONSORED: ["GDPQuarterly", "NationalAccounts", "EconomicGrowth", "GDPOutput"]

✓ Written to CSV

----------------------------


✓ Complete! Results saved to results_catalog_keywords.csv

In [36]:
from concurrent.futures import ThreadPoolExecutor, as_completed
from threading import Lock
import csv, json, logging

def process_row_keyword(row):
    """Process a single row - thread-safe"""
    title = row.get("title", "")
    description = row.get("description", "")
    catalog_title = row.get("catalog_title", "")
    ministry_department = row.get("ministry_department", "")
    sector = row.get("sector", "")
    sector_resource = row.get("sector_resource", "")
    cdos_state_ministry = row.get("cdos_state_ministry", "")
    note = row.get("note", "")

    
    # Fallback to 0 if missing / NaN
    raw_hvd = row.get("field_high_value_dataset", 0)
    try:
        hvd_flag = int(raw_hvd) if raw_hvd == raw_hvd else 0  # handles NaN
    except (ValueError, TypeError):
        hvd_flag = 0

    metadata_content = f"""
Title: {title}
Catalog Title: {catalog_title}
Ministry/Department: {ministry_department}
Sector: {sector}
Sector Resource: {sector_resource}
CDOS State Ministry: {cdos_state_ministry}
Note: {note}
HVD Flag: {hvd_flag}
""".strip()

    # LLM must now return JSON including "hvd_category"
    result = get_keywords(metadata_content)  # expected to return a dict (JSON-like)
    logging.info(f"Result is {result}")

    return {
        "title": title,
        "sector": sector,
        "hvd": hvd_flag,
        "metadata_input": metadata_content,
        "llm_response": json.dumps(result, ensure_ascii=False),
        "generated_keywords": result.get("enhanced_keywords", ""),
        "generated_sponsored_keywords": result.get("sponsored_keywords", ""),
        "generated_subject": result.get("generated_subject", ""),
        "generated_theme": result.get("generated_theme", ""),
        "justification": result.get("justification", ""),
        "confidence_score": result.get("confidence_score", 0),
        "metadata_gaps": json.dumps(result.get("metadata_gaps", []), ensure_ascii=False),
        # NEW: HVD classification coming from the LLM
        "hvd_category": result.get("hvd_category", ""),
    }

# CSV setup
output_file = "results_100.csv"
fieldnames = [
    "title",
    "sector",
    "hvd",             
    "metadata_input",
    "llm_response",
    "generated_keywords",
    "generated_sponsored_keywords",
    "generated_subject",
    "generated_theme",
    "justification",
    "confidence_score",
    "metadata_gaps",
    "hvd_category",    
]

csv_lock = Lock()
with open(output_file, "w", newline="", encoding="utf-8") as f:
    csv.DictWriter(f, fieldnames=fieldnames).writeheader()

results_array = []
max_workers = 8

with ThreadPoolExecutor(max_workers=max_workers) as executor:
    future_to_row = {
        executor.submit(process_row_keyword, row): idx
        for idx, row in (df.head(102)).iterrows()
    }
    for future in as_completed(future_to_row):
        try:
            result_obj = future.result()
            results_array.append(result_obj)

            # Thread-safe incremental write
            with csv_lock:
                with open(output_file, "a", newline="", encoding="utf-8") as f:
                    csv.DictWriter(f, fieldnames=fieldnames).writerow(result_obj)

            print(
                f"TITLE: {result_obj['title']}\n"
                f"SECTOR: {result_obj['sector']}\n"
                f"HVD: {result_obj['hvd']}\n"
                f"HVD CATEGORY: {result_obj['hvd_category']}\n\nWritten to CSV"
            )


            print("\n----------------------------\n")

        except Exception as e:
            logging.error(f"Row processing failed: {e}")

print(f"\nComplete Results saved to {output_file}")

2025-11-15 07:19:06,296 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:19:06,301 : INFO - Result is {'title': 'List of MSME Registered Units under UDYAM', 'enhanced_keywords': 'MSMRegistration, RegisteredUnits, UDYAMList, UDYAMRegistration, MSMEsData, UnitRegistration, MSMEInfo, IndustryRegistrations', 'sponsored_keywords': 'MSMRegisteredUnits, UDYAMRegistration, RegisteredUnits, MSMERegistration', 'justification': 'Keywords reflect the dataset content of MSME units registered under UDYAM; the dataset is a registry of units, aligning with the statistics category due to structured, count-like data.', 'confidence_score': 0.84, 'metadata_gaps': ['Geographic coverage not specified', 'Temporal coverage not specified', 'Fields included in the dataset not described', 'Source organization details not explicit'], 'hvd_category': 'statistics'}

TITLE: List of MSME Registered Units under UDYAM
SECTOR: Industries;Medium;Micro;Small Scale
HVD: 1
HVD CATEGORY: statistics

Written to CSV

----------------------------

2025-11-15 07:19:09,649 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:19:09,656 : INFO - Result is {'title': 'Kisan Call Centre (KCC) - Transcripts of farmers queries & answers', 'enhanced_keywords': 'KisanCall, FarmersQueries, DistrictQueries, MonthWise, QueryResponses, FarmerSupport, AgricultureHelpdesk, KccData, TranscriptData, CallCentre', 'sponsored_keywords': 'KisanCallCentre, FarmersQueries, DistrictQueries, MonthWise', 'justification': 'Keywords reflect the district-wise and month-wise farmer queries and call-center responses. The dataset is best categorized under statistics due to its structured, district- and month-level query data.', 'confidence_score': 0.82, 'metadata_gaps': ['Temporal coverage specifics (start/end dates) not provided', 'Geographic coverage across districts/states not clearly defined', 'Data format and accessibility of transcripts (plain text vs. structured) not specified', 'Language(s) of transcripts not specified', 'Sample size or total query count not provided'], 'hvd_category': 'statistics'}

TITLE: Kisan Call Centre (KCC) - Transcripts of farmers queries & answers
SECTOR: Agriculture
HVD: 1
HVD CATEGORY: statistics

Written to CSV

----------------------------

2025-11-15 07:19:11,807 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:19:11,809 : INFO - Result is {'title': 'Current Daily Price of Various Commodities from Various Markets (Mandi)', 'enhanced_keywords': 'CommodityPrices, MandiMarkets, MarketPrices, DailyPrices, AgriculturePrices, CropPrices, PriceTrends, FarmersMarkets', 'sponsored_keywords': 'MandiPrices, CurrentPrices, CommodityPrices, MarketPrices', 'justification': 'Keywords reflect current daily commodity pricing across markets. The dataset provides structured numeric market price data, justifying a statistics classification.', 'confidence_score': 0.82, 'metadata_gaps': ['Geographic coverage not specified', 'Temporal coverage start/date not specified', 'Price unit not specified', 'Data collection methodology not described'], 'hvd_category': 'statistics'}

TITLE: Current Daily Price of Various Commodities from Various Markets (Mandi)
SECTOR: Agriculture;Agricultural Marketing
HVD: 1
HVD CATEGORY: statistics

Written to CSV

----------------------------

2025-11-15 07:19:12,291 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:19:12,293 : INFO - Result is {'title': 'Registrars of Companies (RoC)-wise Company Master Data', 'enhanced_keywords': 'CompanyMaster, RoCData, AuthorizedCapital, PaidUpCapital, CapitalINR, MasterData, CompanyInfo, CorporateData', 'sponsored_keywords': 'RoCData, CompanyMaster, MasterData, CompanyData', 'justification': "The dataset contains RoC-wise company master records with capital figures in INR, making keywords centered on company master data and capital attributes relevant for discovery and ownership insights. The classification under 'companies and company ownership' reflects its focus on entity-level corporate data and ownership-related attributes.", 'confidence_score': 0.82, 'metadata_gaps': ['Temporal coverage start date not specified', 'Geographic coverage not specified', 'Data update frequency not described', 'Column definitions for fields like AuthorizedCapital and PaidUpCapital not provided'], 'hvd_category': 'companies and company ownership'}

TITLE: Registrars of Companies (RoC)-wise Company Master Data
SECTOR: Commerce;Companies
HVD: 1
HVD CATEGORY: companies and company ownership

Written to CSV

----------------------------

2025-11-15 07:19:12,760 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:19:12,768 : INFO - Result is {'title': 'All India Pincode Directory till last month', 'enhanced_keywords': 'PincodeDirectory, PostalCode, WebService, DirectoryData, MonthlyUpdate, PostOfficeInfo, PincodeLookup, PostalDirectory', 'sponsored_keywords': 'AllPincodeDirectory, PincodeDirectory, WebService, PostalCode, MonthlyUpdate', 'justification': 'Keywords reflect a nationwide pincode directory accessible via WebService with monthly updates, focusing on directory and postal code concepts. As the HVD Flag is 0, no High Value Data category is assigned.', 'confidence_score': 0.72, 'metadata_gaps': ['Temporal coverage start date not specified', "Geographic coverage details beyond 'All India' not explicit", 'Data fields and schema not described', 'WebService endpoint or access details not provided'], 'hvd_category': ''}

TITLE: All India Pincode Directory till last month
SECTOR: Information and Communications;Post
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-15 07:19:13,880 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:19:13,882 : INFO - Result is {'title': 'Variety-wise Daily Market Prices Data of Commodity', 'enhanced_keywords': 'VarietyPrices, DailyPrices, CommodityPrices, MarketPrices, MandiPrices, PriceData, CropPrices, MarketTrend, AgriculturePrices', 'sponsored_keywords': 'VarietyWise, DailyPrices, MarketPrices, CommodityPrices', 'justification': 'The dataset delivers daily price data by commodity variety across markets, enabling price statistics and trend analysis. Given the numeric, structured market data, it falls under the statistics category.', 'confidence_score': 0.85, 'metadata_gaps': ['Sector Resource missing (nan)', 'Geographic coverage not specified', 'Temporal range start/end not specified', 'Data dictionary / field definitions not provided'], 'hvd_category': 'statistics'}

TITLE: Variety-wise Daily Market Prices Data of Commodity
SECTOR: Agriculture;Agricultural Marketing
HVD: 1
HVD CATEGORY: statistics

Written to CSV

----------------------------

2025-11-15 07:19:17,394 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:19:17,396 : INFO - Result is {'title': 'Real time Air Quality Index from various locations', 'enhanced_keywords': 'AirQuality, RealTime, LiveAQI, SensorData, FieldInstruments, LocationData, AirPollution, DataQuality, MonitoringIndex', 'sponsored_keywords': 'RealTimeAQI, AirQualityIndex, LiveAQI, SensorData, FieldInstruments', 'justification': 'Keywords reflect real-time air quality measurements from field sensors, enabling discovery by users seeking live AQI and data streams. The dataset is categorized under earth observation and environment due to environmental sensor data and location-based measurements.', 'confidence_score': 0.78, 'metadata_gaps': ['Geographic coverage specifics (locations) not provided', 'Temporal coverage and data update frequency not specified', 'Data quality control/validation method not described', 'Units of measurement and sensor types not specified'], 'hvd_category': 'earth observation and environment'}

TITLE: Real time Air Quality Index from various locations
SECTOR: Environment and Forest;Industrial Air Pollution;Residential Air Pollution;Vehicular Air Pollution
HVD: 1
HVD CATEGORY: earth observation and environment

Written to CSV

----------------------------

2025-11-15 07:19:20,887 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:19:20,890 : INFO - Result is {'title': 'Wholesale Price Index (Base Year 2011-12) till last month', 'enhanced_keywords': 'WholesalePriceIndex, BaseYear2011, MonthlyIndex, ProvisionalData, PriceIndex, IndexSeries, EconomicIndicator, InflationIndex', 'sponsored_keywords': 'WholesalePriceIndex, BaseYear2011, MonthlyIndex, ProvisionalData', 'justification': 'Keywords focus on the wholesale price index concept, the base year specification, monthly updates, and provisional data noted in the dataset. The dataset is not flagged as High Value Data (HVD), so no HVd category is assigned.', 'confidence_score': 0.75, 'metadata_gaps': ['Temporal coverage start date missing', 'Data units not specified', 'Geographic coverage not specified', 'Data source/release frequency not stated'], 'hvd_category': ''}

TITLE: Wholesale Price Index (Base Year 2011-12) till last month
SECTOR: Economy;Prices;Finance;Economy
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-15 07:19:23,773 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:19:23,776 : INFO - Result is {'title': 'Daily data of reservoir level of Central Water Commission (CWC)', 'enhanced_keywords': 'ReservoirLevel, DailyData, WaterResources, ReservoirData, LevelTrend, WaterStorage, ReservoirLevels, TimeSeries', 'sponsored_keywords': 'DailyReservoir, ReservoirLevels, ReservoirData, WaterStorage', 'justification': 'Keywords focus on reservoir level data and water resources to reflect the dataset content. The dataset comprises structured, daily numerical data, justifying a statistics classification as the High Value Data category.', 'confidence_score': 0.82, 'metadata_gaps': ['Geographic coverage (which reservoirs are included)', 'Unit of measurement (meters, feet, etc.)', 'Date range / start date', 'Data source details and update frequency', 'Data format (CSV, JSON, API) or availability', 'Definitions (how level is measured, reference points)'], 'hvd_category': 'statistics'}

TITLE: Daily data of reservoir level of Central Water Commission (CWC)
SECTOR: Water Resources
HVD: 1
HVD CATEGORY: statistics

Written to CSV

----------------------------

2025-11-15 07:19:29,467 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:19:29,469 : INFO - Result is {'title': 'India Districts Factsheets of National Family Health Survey (NFHS) - 5, 2019-2021 (Provisional)', 'enhanced_keywords': 'NFHS5, DistrictFactsheet, HealthSurvey, MaternalHealth, ChildHealth, DistrictData, ProvisionalData, ImmunizationRate, HouseholdSurvey', 'sponsored_keywords': 'NFHS5, DistrictFactsheets, ProvisionalData, FamilyHealth', 'justification': 'The dataset provides district-level health indicators from the NFHS-5 survey, focusing on district health factsheets and provisional data. Keywords emphasize district health data and survey-related terms to aid discovery; no HVD classification is applied since the HVD Flag is 0.', 'confidence_score': 0.72, 'metadata_gaps': ['Geographic coverage: district list/coverage not explicitly described', 'Temporal coverage: data timeframe (2019-2021 provisional) not clearly defined in metadata', 'Indicator definitions and calculation methods not detailed', 'Data source mapping for NFHS-5 district factsheets not provided', 'Metadata on data updates or revision history missing'], 'hvd_category': ''}
2025-11-15 07:19:29,530 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:19:29,531 : INFO - Result is {'title': 'FDI Equity Inflows from the year 2000 till last quarter', 'enhanced_keywords': 'FDIInflows, EquityInflows, QuarterlyData, ForeignInvestment, DirectInvestment, InvestmentTrends, CommerceData, FDIStatistics', 'sponsored_keywords': 'FDIInflows, EquityInflows, DirectInvestment, ForeignInvestment', 'justification': "Keywords are aligned with the dataset's focus on quarterly FDI equity inflows starting from 2000, derived from the title and catalog metadata. The HVD flag is 0, so a general numeric/trend dataset classification is not assigned.", 'confidence_score': 0.85, 'metadata_gaps': ['Geographic coverage not specified', 'Data source and methodology not specified', 'Units of measurement not specified', 'Data dictionary/definitions not provided', "Temporal coverage beyond 'last quarter' not fully defined"], 'hvd_category': ''}

TITLE: India Districts Factsheets of National Family Health Survey (NFHS) - 5, 2019-2021 (Provisional)
SECTOR: All;Health and Family welfare
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

TITLE: FDI Equity Inflows from the year 2000 till last quarter
SECTOR: Commerce
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-15 07:19:32,324 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:19:32,330 : INFO - Result is {'title': 'All India and State/UT-wise Factsheets of National Family Health Survey (NFHS) - 5, 2019-2021', 'enhanced_keywords': 'NFHS5Factsheets, StateFactsheets, UTFactsheets, HealthSurvey, MaternalHealth, ChildHealth, DemographicData, PopulationHealth', 'sponsored_keywords': 'NFHS5Factsheets, StateFactsheets, UTFactsheets, HealthSurvey, FamilyHealth', 'justification': 'The dataset comprises NFHS-5 factsheets at nationwide and state/UT levels for 2019–2021, focusing on health and family welfare indicators. Keywords are chosen to reflect health survey content and geographic scope while remaining user-friendly.', 'confidence_score': 0.78, 'metadata_gaps': ['No explicit data dictionary or indicator definitions in metadata', 'No complete state/UT list or sampling design details provided', 'No data access URL or downloadable files explicitly linked in metadata', 'No data availability dates or last updated information'], 'hvd_category': ''}

TITLE: All India and State/UT-wise Factsheets of National Family Health Survey (NFHS) - 5, 2019-2021
SECTOR: Health and Family welfare;Family Welfare
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-15 07:19:32,727 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:19:32,732 : INFO - Result is {'title': 'Month-wise All India Crowdsourced Mobile Data Speed Measurement', 'enhanced_keywords': 'MonthWise, CrowdsourcedSpeeds, MobileData, SpeedMeasurement, PublicSpeeds, TelecomData, NetworkSpeed, SpeedTest', 'sponsored_keywords': 'MonthWiseSpeeds, MobileDataSpeeds, CrowdsourcedSpeeds, DataSpeedTests', 'justification': 'The dataset provides monthly, crowdsourced measurements of mobile data speeds, forming a structured time-series of telecom performance that supports statistical analysis and trend identification. This justifies the statistics classification and keyword alignment.', 'confidence_score': 0.85, 'metadata_gaps': ['Geographic granularity at LSA/State level not clearly defined', 'Time range (start/end months) not specified', 'Crowdsourcing methodology and sample size not documented', 'Data schema for fields like TEST_TYPE and SIGNAL_STRENGTH not described'], 'hvd_category': 'statistics'}

TITLE: Month-wise All India Crowdsourced Mobile Data Speed Measurement
SECTOR: Information and Communications;Telecom
HVD: 1
HVD CATEGORY: statistics

Written to CSV

----------------------------

2025-11-15 07:19:34,076 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:19:34,082 : INFO - Result is {'title': 'Health indicator-wise monthly datasets at sub district level from HMIS', 'enhanced_keywords': 'HealthIndicator, SubDistrict, MonthlyIndicators, FacilityData, HealthData, StatesUTs, PublicHealth, DistrictLevel', 'sponsored_keywords': 'HealthIndicator, MonthlyDatasets, SubDistricts, HMIS', 'justification': 'Keywords reflect health indicators and monthly sub-district level data derived from facility reports. The dataset is not flagged as high-value data, hence no hvd category is assigned.', 'confidence_score': 0.8, 'metadata_gaps': ['Temporal coverage details (start/end dates) not specified', 'Geographic coverage details at sub-district level across states/UTs not specified', 'Data dictionary or field definitions not provided', 'Methodology for indicator calculation not described'], 'hvd_category': ''}

TITLE: Health indicator-wise monthly datasets at sub district level from HMIS
SECTOR: Health and Family welfare;Family Welfare;Health
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-15 07:19:41,801 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:19:41,807 : INFO - Result is {'title': 'Voice Call Quality Customer Experience till last month', 'enhanced_keywords': 'VoiceQuality, CallQuality, CustomerExperience, CallExperience, VoiceCall, LastMonth, MonthlyQuality, TelecomExperience', 'sponsored_keywords': 'VoiceCall, QualityExperience, CustomerExperience, LastMonth', 'justification': 'The dataset centers on voice call quality and customer experience in the telecom sector, so keywords target call quality and user experience. It is classified under statistics due to its structured numerical metrics on telecom performance over the recent period.', 'confidence_score': 0.78, 'metadata_gaps': ['Geographic coverage not specified', 'Data collection methodology not documented', "Temporal coverage described as 'till last month' without exact dates", 'Sample size / number of observations not provided'], 'hvd_category': 'statistics'}

TITLE: Voice Call Quality Customer Experience till last month
SECTOR: Information and Communications;Telecom
HVD: 1
HVD CATEGORY: statistics

Written to CSV

----------------------------

2025-11-15 07:19:43,301 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:19:43,304 : INFO - Result is {'title': 'Wholesale Price Index (Base Year 2011-12) till last financial year', 'enhanced_keywords': 'WholesaleIndex, PriceIndex, BaseYear2011, LastFinancialYear, PriceTrends, IndexSeries, EconomyPrices, FinanceData', 'sponsored_keywords': 'WholesaleIndex, BaseYear2011, FinancialYear, PriceIndex', 'justification': 'Keywords target the wholesale price index and annual price trends reflected in the title, aiding discovery of time-series economic data. The HVD flag is 0, so there is no high-value data classification.', 'confidence_score': 0.8, 'metadata_gaps': ['SectorResource missing (listed as nan)', 'Temporal coverage beyond base year not specified', 'LastFinancialYear end date not specified'], 'hvd_category': ''}

TITLE: Wholesale Price Index (Base Year 2011-12) till last financial year
SECTOR: Economy;Prices;Finance;Economy
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-15 07:19:45,168 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:19:45,172 : INFO - Result is {'title': 'Sub Divisional Monthly Rainfall from 1901 to 2017', 'enhanced_keywords': 'SubDivisionalRainfall, MonthlyRainfall, RainfallData, HistoricalRainfall, ClimateData, EarthSciences, AtmosphericScience, RainfallRecords, RainfallDataset', 'sponsored_keywords': 'SubDivisionalRainfall, MonthlyRainfall, Rainfall1901To2017, RainfallData', 'justification': 'The keywords reflect subdivisional, monthly rainfall data spanning 1901–2017, aligning with rainfall and climate science themes. Since the HVD flag is 0, no HVD category is assigned.', 'confidence_score': 0.83, 'metadata_gaps': ['Geographic subdivision scope not specified', 'Unit MMS interpretation not documented', 'Data completeness across months/years not explicitly stated'], 'hvd_category': ''}

TITLE: Sub Divisional Monthly Rainfall from 1901 to 2017
SECTOR: Science and Technology;Atmospheric Science;Earth Sciences
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-15 07:19:50,889 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:19:50,891 : INFO - Result is {'title': 'Indian Railways Time Table for trains available for reservation as on 01.11.2017', 'enhanced_keywords': 'RailwayTimeTable, TrainSchedule, ReservationTrains, TrainTimetable, TrainsAvailable, TimetableInfo, StationTimetable, RailwaysData', 'sponsored_keywords': 'TrainTimetable, ReservationTrains, RailwayTimeTable, TrainSchedule', 'justification': 'Keywords focus on railway timetable and reservation-enabled train schedules as indicated by the title. The dataset does not specify a high-value data category (HVD) as flagged, so hvd_category is left empty.', 'confidence_score': 0.8, 'metadata_gaps': ['Geographic coverage not specified', 'Temporal coverage details beyond the given date are missing', 'Data source / origin not specified', 'Update frequency not specified'], 'hvd_category': ''}

TITLE: Indian Railways Time Table for trains available for reservation as on 01.11.2017
SECTOR: Transport;Railways
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-15 07:19:51,386 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:19:51,388 : INFO - Result is {'title': 'District-wise, season-wise crop production statistics from 1997', 'enhanced_keywords': 'DistrictWise, SeasonWise, CropProduction, ProductionStatistics, DistrictProduction, SeasonalProduction, DistrictStats, CropStatistics', 'sponsored_keywords': 'DistrictProduction, SeasonWise, CropProduction, ProductionStatistics, DistrictWise', 'justification': "Keywords emphasize district- and season-level crop production data spanning from 1997, aligning with the dataset's focus on agricultural production statistics. No High Value Data category is assigned (HVD Flag = 0).", 'confidence_score': 0.78, 'metadata_gaps': ["End year not clearly specified beyond 'from 1997'", 'District list or geographic coverage details not provided', 'Temporal granularity and data source specifics not described'], 'hvd_category': ''}

TITLE: District-wise, season-wise crop production statistics from 1997
SECTOR: Agriculture;Agricultural Produces
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-15 07:19:56,566 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:19:56,568 : INFO - Result is {'title': 'Global Youth Tobacco Survey (GYTS-4), India and States, 2019', 'enhanced_keywords': 'YouthTobacco, TobaccoSurvey, SmokingPrevalence, SecondhandExposure, SchoolBased, PublicHealth, TobaccoUse, PrevalenceData, HealthSurvey', 'sponsored_keywords': 'GlobalTobaccoSurvey, GYTS4, YouthTobaccoSurvey, IndiaTobaccoSurvey', 'justification': "Keywords capture the dataset's focus on youth tobacco use and survey data, enabling easy discovery. The dataset provides state-level prevalence indicators and other tobacco-use metrics, justifying a statistics classification.", 'confidence_score': 0.82, 'metadata_gaps': ['Geographic coverage details by state not specified', 'Variable definitions and data dictionary missing', 'Sampling design/methodology details not provided'], 'hvd_category': 'statistics'}

TITLE: Global Youth Tobacco Survey (GYTS-4), India and States, 2019
SECTOR: Health;Health and Family welfare
HVD: 1
HVD CATEGORY: statistics

Written to CSV

----------------------------

2025-11-15 07:19:57,711 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:19:57,715 : INFO - Result is {'title': 'Daily data of Soil Moisture', 'enhanced_keywords': 'SoilMoisture, DailyMoisture, MoistureData, GroundMoisture, MoistureMap, SoilHumidity, FieldMoisture', 'sponsored_keywords': 'SoilMoisture, DailyMoisture, MoistureData, SoilHumidity', 'justification': 'The dataset provides daily measurements of soil moisture, so keywords emphasize soil moisture and related moisture data. It fits the earth observation and environment category due to environmental/geospatial data collected over time.', 'confidence_score': 0.78, 'metadata_gaps': ['Geographic coverage not specified', 'Temporal start/end date not specified', 'Units of measurement not specified', 'Data collection method not described', 'Spatial resolution/scale not specified', "Update frequency not specified beyond 'daily'"], 'hvd_category': 'earth observation and environment'}

TITLE: Daily data of Soil Moisture
SECTOR: Water Resources
HVD: 1
HVD CATEGORY: earth observation and environment

Written to CSV

----------------------------

2025-11-15 07:20:00,929 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:20:00,933 : INFO - Result is {'title': 'Seasonal and Annual Mean Temperature Series for the period 1901-2021', 'enhanced_keywords': 'SeasonalTemp, AnnualTemp, TemperatureSeries, MeanTemp, TimeSeries, ClimateData, SeasonalTrend, LongTermTemp', 'sponsored_keywords': 'SeasonalTemp, AnnualTemp, TemperatureSeries, MeanTemp', 'justification': 'The dataset offers a long-term, seasonally and annually aggregated temperature series suitable for climate trend analysis. It aligns with the meteorological category as it directly represents core weather/climate data.', 'confidence_score': 0.85, 'metadata_gaps': ['Data source and measurement methodology not specified', 'Temperature units (Celsius vs. Fahrenheit) not stated', 'Spatial coverage details (national scale vs regional splits) not explicitly defined', 'Temporal metadata (start/end dates inclusive, data cadence) unclear'], 'hvd_category': 'meteorological'}

TITLE: Seasonal and Annual Mean Temperature Series for the period 1901-2021
SECTOR: Science and Technology;Earth Sciences
HVD: 1
HVD CATEGORY: meteorological

Written to CSV

----------------------------

2025-11-15 07:20:01,976 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:20:01,979 : INFO - Result is {'title': 'Industry, State and Year wise Startups Recognized by DPIIT till last week', 'enhanced_keywords': 'StartupRecognition, IndustryStartup, StateWiseStartup, YearWiseStartup, StartupList, IndustryStateStartup, StartupDashboard, StartupCounts', 'sponsored_keywords': 'StartupRecognized, StateWiseStartup, IndustryStartup, YearWiseStartup, StartupList', 'justification': 'Keywords emphasize the disaggregated startup recognition across industry, state, and year, aligning with the dataset title. The data appears to be a structured statistics dataset tracking counts of startups recognized over time.', 'confidence_score': 0.8, 'metadata_gaps': ["Temporal range clarity: 'till last week' lacks a specific end date and reference point", 'Geographic coverage not specified beyond state-level mention', 'Data schema not described (columns such as state, industry, year, startup_count)', 'Update frequency and data provenance/licensing not provided', "SectorResource field is 'nan' and unclear relevance"], 'hvd_category': 'statistics'}

TITLE: Industry, State and Year wise Startups Recognized by DPIIT till last week
SECTOR: All
HVD: 1
HVD CATEGORY: statistics

Written to CSV

----------------------------

2025-11-15 07:20:02,825 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:20:02,828 : INFO - Result is {'title': 'Local Government Directory (LGD) - Villages with PIN Codes', 'enhanced_keywords': 'VillagePinCodes, VillageCodes, PinCodeMapping, PinCodeVillages, VillagesWithPin, PanchayatiRaj, LGDData, MonthlyUpdate, VillageDirectory, PinCodeLookup', 'sponsored_keywords': 'VillagePinCodes, LGDDirectory, PinCodeVillages, VillagesWithPin', 'justification': 'Keywords emphasize village-level PIN code mapping and the LGD directory, supporting geospatial discovery. The dataset is categorized as geospatial due to village-level location codes and mapping, with updates on a monthly cadence.', 'confidence_score': 0.82, 'metadata_gaps': ['Geographic coverage (state/district scope) not specified', 'LastUpdated timestamp not provided', 'Data source/authority not specified', 'PIN Code format specifics not defined'], 'hvd_category': 'geospatial'}

TITLE: Local Government Directory (LGD) - Villages with PIN Codes
SECTOR: Panchayati Raj
HVD: 1
HVD CATEGORY: geospatial

Written to CSV

----------------------------

2025-11-15 07:20:05,615 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:20:05,618 : INFO - Result is {'title': 'Local Government Directory (LGD) - Local Bodies with PIN Codes', 'enhanced_keywords': 'LocalBodies, PinCodes, LGDCodes, LocalGovernance, Panchayats, Municipalities, LocalBodyInfo, GovernmentDirectory', 'sponsored_keywords': 'LocalGovernment, LGDDirectory, LocalBodiesPIN, PinCodes', 'justification': 'Keywords emphasize the content of local government units and their geographic PIN codes as described in the title, improving discoverability for governance-related data. The dataset is categorized as geospatial due to its geographic identifiers for local bodies.', 'confidence_score': 0.78, 'metadata_gaps': ['Geographic coverage scope unclear', 'Data provenance not specified', 'Temporal coverage/date range not provided'], 'hvd_category': 'geospatial'}

TITLE: Local Government Directory (LGD) - Local Bodies with PIN Codes
SECTOR: Panchayati Raj
HVD: 1
HVD CATEGORY: geospatial

Written to CSV

----------------------------

2025-11-15 07:20:11,661 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:20:11,664 : INFO - Result is {'title': 'District Wise Total MSME Registered Enterprises under UDYAM Registration till last date', 'enhanced_keywords': 'DistrictWise, EnterpriseCount, UDYAMRegistration, MSMERegistration, RegisteredEnterprises, DistrictStats, SmallScale, Industries', 'sponsored_keywords': 'DistrictWise, TotalEnterprises, UDYAMRegistration, MSMERegistration, EnterpriseTotals', 'justification': 'Dataset provides district-level counts of MSME registrations under UDYAM, a structured statistics dataset. Keywords emphasize district-level enterprise counts and the UDYAM/MSME registration context.', 'confidence_score': 0.82, 'metadata_gaps': ['District-level geographic coverage not specified (which districts are included)', "Temporal scope is unclear ('till last date' without exact date)", 'Data source and publication date missing', "Definitions of 'registered enterprises' and 'UDYAM Registration' not provided", 'Data update frequency and methodology not described'], 'hvd_category': 'statistics'}
2025-11-15 07:20:11,793 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:20:11,797 : INFO - Result is {'title': 'Shapefile of Rivers', 'enhanced_keywords': 'RiverShapefile, RiversMap, RiverLines, WaterResources, RiverGeography, HydroData, MajorRivers, MinorRivers', 'sponsored_keywords': 'ShapefileRivers, RiverShapefile, RiversMap, RiverLines', 'justification': 'The dataset consists of river geospatial features provided as shapefile formats, so keywords target river-related geodata and shapefile mapping. The HVD category is geospatial because it involves geospatial boundary data (river lines) in vector format.', 'confidence_score': 0.82, 'metadata_gaps': ['Coordinate Reference System (CRS) not specified', 'Geographic coverage specificity (country-wide vs regional) not defined', 'Data license/usage terms not specified', 'Temporal coverage not specified', 'Data source URL or repository not provided'], 'hvd_category': 'geospatial'}

TITLE: District Wise Total MSME Registered Enterprises under UDYAM Registration till last date
SECTOR: Industries;Medium;Micro;Small Scale
HVD: 1
HVD CATEGORY: statistics

Written to CSV

----------------------------

TITLE: Shapefile of Rivers
SECTOR: Ground Water;Surface Water
HVD: 1
HVD CATEGORY: geospatial

Written to CSV

----------------------------

2025-11-15 07:20:15,948 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:20:15,949 : INFO - Result is {'title': 'District wise Services MSME Registered Enterprises under UDYAM Registration till last date', 'enhanced_keywords': 'DistrictWiseMSME, RegisteredEnterprises, UDYAMRegistration, MSMEServices, DistrictServices, DistrictMSME, MSMEData, EnterpriseRegistration, MSMEEnterprises', 'sponsored_keywords': 'DistrictMSME, RegisteredEnterprises, UDYAMRegistration, MSMEServices', 'justification': 'District-level aggregation of MSME registered enterprises under UDYAM is the core content, so keywords should reflect district-level MSME data and registration. The dataset is categorized as statistics because it presents structured, district-wise counts of enterprises.', 'confidence_score': 0.8, 'metadata_gaps': ['District coverage details not specified (which districts are included)', "Date range or 'till last date' definition not clearly defined", 'Data source and collection method not described', "Definitions of 'services' vs 'enterprises' and unit of measure not explicit"], 'hvd_category': 'statistics'}
2025-11-15 07:20:16,083 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:20:16,085 : INFO - Result is {'title': 'Rainfall in all India and its departure from normal during Monsoon session (June-Sept) from 1901 to 2019', 'enhanced_keywords': 'RainfallData, MonsoonRainfall, HistoricalRainfall, RainfallMM, RainfallAnomaly, MonsoonDeparture, SeasonalRainfall, RainfallTrend', 'sponsored_keywords': 'MonsoonRainfall, RainfallDeparture, HistoricalRainfall, RainfallAnomaly, TimeSeriesRainfall', 'justification': 'Keywords emphasize monsoon-season rainfall, anomalies from normal, and historical rainfall totals to align with the dataset’s scope of all-India rainfall departures during June–September over 1901–2019. Since HVDFlag is 0, no High Value Data category is assigned.', 'confidence_score': 0.78, 'metadata_gaps': ['Geographic scope explicitly defined in metadata is not in a dedicated field', 'Data frequency (monsoon-season) not explicitly stated beyond the title', "Methodology for calculating 'departure from normal' not provided", 'Source/origin metadata (DOI or catalog link) not provided'], 'hvd_category': ''}

TITLE: District wise Services MSME Registered Enterprises under UDYAM Registration till last date
SECTOR: Industries;Medium;Micro;Small Scale
HVD: 1
HVD CATEGORY: statistics

Written to CSV

----------------------------

TITLE: Rainfall in all India and its departure from normal during Monsoon session (June-Sept) from 1901 to 2019
SECTOR: Science and Technology;Atmospheric Science;Earth Sciences
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-15 07:20:16,560 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:20:16,562 : INFO - Result is {'title': 'Crime Head-wise Police Disposal of IPC Crime Cases (Crime Head-wise) during 2019', 'enhanced_keywords': 'CrimeHeadWise, PoliceDisposal, CrimeCases, Year2019, StateData, CrimeStatistics, CaseDisposal', 'sponsored_keywords': 'HeadWise, PoliceDisposal, CrimeCases, Year2019', 'justification': "Keywords reflect the dataset's focus on head-wise police disposal of IPC crime cases for 2019, as described in the title and catalog. The HVD flag is 0, indicating it is not classified as high-value data; note mentions data gaps related to missing 2019 data from West Bengal and use of 2018 data.", 'confidence_score': 0.72, 'metadata_gaps': ['West Bengal data for 2019 not provided', 'Data note indicates 2018 data used due to missing 2019 data from some states', 'Temporal coverage limited to 2019; no multi-year context available'], 'hvd_category': ''}

TITLE: Crime Head-wise Police Disposal of IPC Crime Cases (Crime Head-wise) during 2019
SECTOR: Home Affairs and Enforcement;Police
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-15 07:20:19,738 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:20:19,740 : INFO - Result is {'title': 'Seasonal and Annual Min/Max Temp Series - India from 1901 to 2017', 'enhanced_keywords': 'SeasonalTemp, AnnualTemp, MinMaxTemp, TempSeries, HistoricalTemps, TemperatureTrends, CelsiusData, ClimateDataset, TemperatureRecord, SeasonalAnnualTemps', 'sponsored_keywords': 'SeasonalTempSeries, MinTempMax, AnnualTempSeries, TemperatureTrends, CelsiusTemps', 'justification': "Keywords focus on seasonal and annual temperature data and historical Celsius values, aligning with the dataset's content. The HVD flag is 0, so no High Value Data category is assigned; keywords emphasize climate/temperature information rather than administrative terms.", 'confidence_score': 0.82, 'metadata_gaps': ['Geographic coverage explicitly stated in metadata; All India implied may need confirmation', 'Temporal resolution (monthly/seasonal vs annual) not clearly specified', 'Data provenance/source organization details not clearly described beyond IMD', 'Access URL/DOI or data download location not provided', 'Data collection methodology and quality checks not described'], 'hvd_category': ''}

TITLE: Seasonal and Annual Min/Max Temp Series - India from 1901 to 2017
SECTOR: Science and Technology;Atmospheric Science;Earth Sciences
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-15 07:20:20,345 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:20:20,348 : INFO - Result is {'title': 'Enrolment by Age and Class (UDISE plus) during 2012-13', 'enhanced_keywords': 'EnrolmentAge, AgeClass, UDISEPlus, SchoolEnrolment, ClassEnrolment, EnrollmentData, AgeDistribution, EducationStats, StudentEnrolment', 'sponsored_keywords': 'EnrolmentByAge, EnrolmentByClass, UDISEPlus, EnrollmentData', 'justification': "Keywords capture the dataset's focus on enrolment by age and class within the UDISE Plus education dataset. It is structured enrollment data, aligning with a statistics emphasis.", 'confidence_score': 0.78, 'metadata_gaps': ['Geographic coverage not specified', "Note field marked as 'nan'", 'Frequency/temporal details beyond 2012-13 are not provided'], 'hvd_category': ''}

TITLE: Enrolment by Age and Class (UDISE plus) during 2012-13
SECTOR: Education
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-15 07:20:23,891 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:20:23,894 : INFO - Result is {'title': 'Daily data of Evapotranspiration of NRSC', 'enhanced_keywords': 'Evapotranspiration, DailyET, ETData, GroundWater, SatelliteET, RemoteSensing, HydrologyData, WaterResource', 'sponsored_keywords': 'Evapotranspiration, DailyET, ETData, RemoteSensing', 'justification': 'Keywords focus on evapotranspiration data and its remote-sensing/environmental basis. The HVD category is earth observation and environment due to NRSC EO sources and hydrological relevance.', 'confidence_score': 0.85, 'metadata_gaps': ['Geographic coverage not specified', 'Units for evapotranspiration not provided', 'Spatial resolution and data cadence not stated', 'Methodology for ET calculation not described', 'Temporal coverage (start/end dates) missing'], 'hvd_category': 'earth observation and environment'}

TITLE: Daily data of Evapotranspiration of NRSC
SECTOR: Ground Water
HVD: 1
HVD CATEGORY: earth observation and environment

Written to CSV

----------------------------

2025-11-15 07:20:29,189 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:20:29,192 : INFO - Result is {'title': 'District wise, Disability wise, Age group wise , Gender wise Unique Disability ID (UDID) data as on 11.06.2024', 'enhanced_keywords': 'DistrictDisability, DisabilityType, AgeGroup, GenderBreakdown, UDIDData, DistrictCounts, DisabilityCounts, GenderDistribution, AgeDistribution', 'sponsored_keywords': 'UDIDData, UniqueDisabilityID, DisabilityData, UDID', 'justification': 'Keywords reflect district-, disability-, age-, and gender-level UDID data, aligning with the dataset’s focus on counts and distributions. The HVD category is classified as statistics due to its structured numerical demographic data.', 'confidence_score': 0.82, 'metadata_gaps': ['Detailed data dictionary for field values (e.g., age_group categories and disability_type_name)', 'Geographic coverage specifics (which states/UTs are included and whether data is nationwide)', 'Temporal coverage more precise (start date of data collection, frequency of quarterly updates)', 'Unit of measure and definition for total_count (male_count + female_count) and any aggregation rules', 'File formats beyond CSV and data access restrictions'], 'hvd_category': 'statistics'}

TITLE: District wise, Disability wise, Age group wise , Gender wise Unique Disability ID (UDID) data as on 11.06.2024
SECTOR: Social Development
HVD: 1
HVD CATEGORY: statistics

Written to CSV

----------------------------

2025-11-15 07:20:32,568 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:20:32,571 : INFO - Result is {'title': 'Crime Head-wise Police Disposal of IPC Crime Cases during 2021', 'enhanced_keywords': 'CrimeDisposal, IPCOffences, PoliceDisposal, HeadWiseDisposal, CrimeCases2021, IPCDisposals, CaseDisposalRate, CrimeData2021', 'sponsored_keywords': 'CrimeHeadwise, PoliceDisposal, IPCCases, CrimeData2021', 'justification': "The keywords capture the core content: head-wise disposal of IPC crime cases by police in 2021. While not flagged as high-value data, the terms align with the dataset's scope for discoverability and accuracy.", 'confidence_score': 0.72, 'metadata_gaps': ['Geographic coverage by states/UTs not specified', 'Disposal status definitions and data collection methodology not described', 'Temporal coverage limited to 2021 with no trend data'], 'hvd_category': ''}

TITLE: Crime Head-wise Police Disposal of IPC Crime Cases during 2021
SECTOR: Police
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-15 07:20:35,873 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:20:35,877 : INFO - Result is {'title': 'Enrolment by Age and Class (UDISE plus) during 2019-20', 'enhanced_keywords': 'EnrolmentData, AgeEnrollment, ClassEnrollment, UDISEPlus, SchoolEnrollment, EducationStats, EnrollmentTrends, StudentEnrollment', 'sponsored_keywords': 'EnrolmentAge, EnrolmentClass, UDISEPlus, AgeClassEnrolment', 'justification': "Keywords capture the dataset's core focus on enrolment by age and class within UDISE Plus for the 2019-20 period. Since the HVD flag is 0, no High Value Data category is assigned.", 'confidence_score': 0.78, 'metadata_gaps': ["Note field contains 'nan' indicating missing description", 'Geographic scope is not specified', 'Definitions for age groups and class levels are not provided', 'Temporal scope beyond 2019-20 not described; continuity with other years unclear'], 'hvd_category': ''}

TITLE: Enrolment by Age and Class (UDISE plus) during 2019-20
SECTOR: Education
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-15 07:20:36,976 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:20:36,980 : INFO - Result is {'title': 'All India Consumer Price Index (Rural/Urban) upto May 2023', 'enhanced_keywords': 'PriceIndex, RuralUrban, ConsumerPrice, MonthlyPrices, CPIData, May2023, PriceTrends, RuralCPI', 'sponsored_keywords': 'CPI, RuralUrban, ConsumerPrice, May2023', 'justification': "Keywords emphasize the consumer price index data for rural and urban areas and its time-bound aspect up to May 2023. The HVD category is statistics, reflecting the dataset's structured, time-series numerical data on prices.", 'confidence_score': 0.82, 'metadata_gaps': ['TemporalCoverage start date not provided', 'GeographicCoverage beyond Rural/Urban not specified', 'DataSource/Provider details not specified', 'Frequency of updates not specified'], 'hvd_category': 'statistics'}

TITLE: All India Consumer Price Index (Rural/Urban) upto May 2023
SECTOR: Economy;Prices;Finance;Economy;Statistics
HVD: 1
HVD CATEGORY: statistics

Written to CSV

----------------------------

2025-11-15 07:20:38,148 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:20:38,151 : INFO - Result is {'title': 'Foreign Tourist Arrivals (FTAs), Arrivals of Non-Resident Indians (NRIs) and International Tourist Arrival (ITAs) from 1981 to 2017', 'enhanced_keywords': 'TouristArrivals, InternationalTourists, NRIArrivals, ForeignArrivals, ITAs, TravelStatistics, TourismData, TimeSeries, ArrivalTrends, VisitorFlows', 'sponsored_keywords': 'ForeignArrivals, NRIArrivals, ITAs, TourismArrivals', 'justification': 'The dataset chronicles international and NRIs tourist arrivals over time, so keywords emphasize tourism arrivals, travel data, and statistics. HVD flag is 0, so no High Value Data category is assigned.', 'confidence_score': 0.8, 'metadata_gaps': ['SectorResource missing (nan)', 'No explicit geographic scope beyond national level', 'Data quality notes (provisional 2018) present in Note'], 'hvd_category': ''}

TITLE: Foreign Tourist Arrivals (FTAs), Arrivals of Non-Resident Indians (NRIs) and International Tourist Arrival (ITAs) from 1981 to 2017
SECTOR: Travel and Tourism
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-15 07:20:39,099 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:20:39,103 : INFO - Result is {'title': 'Year-wise retail inflation rate based on Consumer Price Index-Combined (CPI-C) from 2017-18 to 2022-23', 'enhanced_keywords': 'RetailInflation, CPICombined, YearWiseInflation, InflationRate, PriceIndex, PercentageData, DataTrend', 'sponsored_keywords': 'CPICombined, YearWiseInflation, RetailInflation, InflationRate, PriceIndex', 'justification': 'The keywords map directly to the CPI-C based inflation measurements and the year-wise data scope described in the title, aiding discovery for inflation trend queries. The dataset is not tagged as HVD.', 'confidence_score': 0.78, 'metadata_gaps': ['Geographic scope not explicitly stated (assumed national)', 'Calendar vs fiscal year alignment for 2017-18 to 2022-23 unclear', 'Provisional data status for February 2023 not clearly indicated in metadata', 'No direct data source link or dataset identifier provided'], 'hvd_category': ''}

TITLE: Year-wise retail inflation rate based on Consumer Price Index-Combined (CPI-C) from 2017-18 to 2022-23
SECTOR: All
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-15 07:20:47,010 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:20:47,012 : INFO - Result is {'title': 'All India area weighted monthly, seasonal and annual rainfall (in mm) from 1901-2015', 'enhanced_keywords': 'AreaWeighted, MonthlyRainfall, SeasonalRainfall, AnnualRainfall, TimeSeries, HistoricalRainfall, PrecipitationData, RainfallTrends, LongTermRainfall', 'sponsored_keywords': 'AllIndiaRainfall, RainfallInIndia, MonthlyRainfall, SeasonalRainfall, AnnualRainfall', 'justification': "Keywords focus on the dataset's scope—area-weighted rainfall across monthly, seasonal, and annual aggregations for the All-India domain. Because HVD Flag = 0, no hvd_category is assigned; the dataset is primarily historical statistics data.", 'confidence_score': 0.75, 'metadata_gaps': ['Explicit geographic granularity is all-India; sub-national coverage not specified', 'Temporal coverage confirmation: 1901-2015 with split data sources (delayed mode vs real-time) needs clarification', 'Data source provenance and processing methodology for area weighting not fully documented', 'Units and aggregation details for monthly, seasonal, and annual data (e.g., calendar type) should be clarified'], 'hvd_category': ''}

TITLE: All India area weighted monthly, seasonal and annual rainfall (in mm) from 1901-2015
SECTOR: Science and Technology;Atmospheric Science;Earth Sciences
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-15 07:20:48,256 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:20:48,258 : INFO - Result is {'title': 'Monthly Crude Oil Processed by Refineries', 'enhanced_keywords': 'CrudeOil, Refineries, MonthlyOutput, RefiningVolume, OilProcessing, OilIndustry, ProvisionalData, ProductionTrend, OilSupply, MarketData', 'sponsored_keywords': 'MonthlyCrudeOil, CrudeOilProcessed, RefineryOutput, OilRefineries, RefineryThroughput', 'justification': 'The dataset documents monthly crude oil processing by refineries, enabling statistical tracking of refinery throughput and oil supply. HVD category is statistics due to structured time-series production data.', 'confidence_score': 0.82, 'metadata_gaps': ['Temporal coverage start date not specified', 'Units of measure not specified', 'Geographic scope not explicitly stated', 'Data provenance details limited to source notes'], 'hvd_category': 'statistics'}

TITLE: Monthly Crude Oil Processed by Refineries
SECTOR: Non Renewable
HVD: 1
HVD CATEGORY: statistics

Written to CSV

----------------------------

2025-11-15 07:20:49,139 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:20:49,141 : INFO - Result is {'title': 'GSVA by Economic Activity at Current Prices for Tamil Nadu from 2011-12 to 2016-17 (as on 31.03.2017)', 'enhanced_keywords': 'StateGdp, CurrentPrices, EconomicActivity, TamilNadu, GdpByActivity, RsLakh, TimeSeries, AnnualGdp', 'sponsored_keywords': 'GdpCurrentPrices, TamilNaduGdp, StateGdp, EconomicActivity', 'justification': "Keywords reflect state-level GDP by activity at current prices and related data notes; the dataset is statistical in nature and pertains to Tamil Nadu's economy.", 'confidence_score': 0.78, 'metadata_gaps': ['SectorResource is missing (nan)', 'Exact data source and methodology not specified', 'Temporal coverage clarity (start/end years) could be more explicit'], 'hvd_category': ''}

TITLE: GSVA by Economic Activity at Current Prices for Tamil Nadu from 2011-12 to 2016-17 (as on 31.03.2017)
SECTOR: Finance;Economy;Statistics
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-15 07:20:51,134 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:20:51,135 : INFO - Result is {'title': 'District-wise Demographic Data of Unorganised Workers registered on eShram as on Previous Day', 'enhanced_keywords': 'DistrictDemographics, UnorganisedWorkers, eShramPortal, DemographicData, SelfDeclaration, PreviousDay, LabourEmployment, RegistrationData', 'sponsored_keywords': 'DistrictDemographics, EShramPortal, PreviousDayData, RegistrationData', 'justification': 'Keywords emphasize district-level demographic data for unorganised workers collected via the eShram portal, with emphasis on self-declaration. The dataset is structured demographic/statistical in nature and the HVD category is statistics.', 'confidence_score': 0.85, 'metadata_gaps': ['District coverage details not specified', "Exact reference date not provided beyond 'Previous Day'", "Variable definitions for 'demographic data' not specified", 'Data source publication frequency not specified'], 'hvd_category': 'statistics'}

TITLE: District-wise Demographic Data of Unorganised Workers registered on eShram as on Previous Day
SECTOR: Unorganized Sector Workers
HVD: 1
HVD CATEGORY: statistics

Written to CSV

----------------------------

2025-11-15 07:20:54,663 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:20:54,667 : INFO - Result is {'title': 'CBSE Result Statistics Class XII - 2023', 'enhanced_keywords': 'ClassXIIResults, ResultStatistics, EducationData, BoardResults, ExamStatistics, Year2023, StudentPerformance, MarkDistributions, EducationMetrics, ResultData', 'sponsored_keywords': 'ClassXII, ResultStatistics, CBSEResults, Year2023', 'justification': 'Keywords emphasize class XII result statistics and education data to support discoverability. HVD not applicable as indicated by flag 0.', 'confidence_score': 0.78, 'metadata_gaps': ['Detailed subject-wise marks and grade distribution not specified', 'Geographic coverage (state/school type) not provided', 'Data collection methodology not described'], 'hvd_category': ''}

TITLE: CBSE Result Statistics Class XII - 2023
SECTOR: Education
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-15 07:20:58,141 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:20:58,143 : INFO - Result is {'title': 'District-wise availability of health centres in India as on 31st March, 2017', 'enhanced_keywords': 'DistrictHealthCenters, HealthFacilities, RuralHealthStatistics, PHCAvailability, SubCentreAvailability, DistrictWiseCoverage, HealthCentreData, RuralHealthCoverage', 'sponsored_keywords': 'DistrictHealthCenters, HealthCentreAvailability, DistrictWiseAvailability, HealthCentreStatus', 'justification': 'Keywords emphasize district-level health facility availability and rural health data, derived from the title and catalog. They support discovery of facility counts across districts and align with a statistics-oriented dataset.', 'confidence_score': 0.75, 'metadata_gaps': ['No explicit district list in metadata', 'Temporal coverage not provided as a separate field (only in title)', 'Lack of data quality indicators in metadata', 'State-level notes (e.g., renamings) require normalization'], 'hvd_category': ''}

TITLE: District-wise availability of health centres in India as on 31st March, 2017
SECTOR: Health and Family welfare;Family Welfare;Health
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-15 07:20:59,547 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:20:59,552 : INFO - Result is {'title': 'Statistics of Road Accidents in India From 2013 to 2016', 'enhanced_keywords': 'RoadAccidents, AccidentStats, StateAccidents, StateStatistics, RoadTransport, TrafficStats, TransportData, RoadSafety', 'sponsored_keywords': 'RoadAccidents, AccidentStats, StateAccidents, StateStatistics, RoadTransport', 'justification': "Keywords map to the dataset's focus on road accident counts and state-level breakdowns. The HVD flag is 0, so no high-value data classification is applied.", 'confidence_score': 0.75, 'metadata_gaps': ['Source data origin not specified', 'Data collection methodology not described', 'Geographic granularity beyond State/UT not clear'], 'hvd_category': ''}

TITLE: Statistics of Road Accidents in India From 2013 to 2016
SECTOR: Transport;Road Transport
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-15 07:21:00,744 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:21:00,746 : INFO - Result is {'title': 'Area weighted monthly, seasonal and annual rainfall ( in mm) for 36 meteorological subdivisions from 1901-2015', 'enhanced_keywords': 'RainfallData, MonthlyRainfall, SeasonalRainfall, AnnualRainfall, MeteorologicalSubdivisions, SubdivisionRainfall, StationData, ClimateSeries', 'sponsored_keywords': 'AreaWeighted, MonthlyRainfall, SeasonalRainfall, AnnualRainfall', 'justification': 'Keywords capture the dataset’s focus on rainfall measurements at a monthly, seasonal, and yearly scale across 36 subdivisions. The metadata indicates climate/meteorological content with numeric rainfall values; no HVD category is assigned since HVD Flag is 0.', 'confidence_score': 0.82, 'metadata_gaps': ['Calculation methodology for area-weighting is not detailed', 'Data access format and source are not specified', 'Units beyond mm are not explicitly stated in metadata', 'Clarification on temporal coverage inconsistencies (1901-2012 vs 2013-2015) could be provided'], 'hvd_category': ''}

TITLE: Area weighted monthly, seasonal and annual rainfall ( in mm) for 36 meteorological subdivisions from 1901-2015
SECTOR: Science and Technology;Atmospheric Science;Earth Sciences
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-15 07:21:02,323 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:21:02,325 : INFO - Result is {'title': 'Monthly Consumption of Petroleum Products', 'enhanced_keywords': 'PetroleumConsumption, MonthlyConsumption, OilDemand, EnergyUse, PetroleumProducts, OilConsumption, ConsumptionTrends, ProvisionalData, OilMarket', 'sponsored_keywords': 'MonthlyConsumption, PetroleumProducts, OilDemand, PetroleumUsage', 'justification': "Keywords reflect the dataset's focus on monthly petroleum product consumption and energy use, enabling discovery by users seeking energy statistics. The HVD classification as statistics is appropriate due to the structured monthly consumption figures and official data provenance.", 'confidence_score': 0.88, 'metadata_gaps': ['Temporal coverage start/end dates not specified', 'Geographic coverage not specified', 'Units of measurement not specified (e.g., barrels, tonnes, litres)', 'Data update frequency beyond monthly not clearly described'], 'hvd_category': 'statistics'}

TITLE: Monthly Consumption of Petroleum Products
SECTOR: Power and Energy
HVD: 1
HVD CATEGORY: statistics

Written to CSV

----------------------------

2025-11-15 07:21:05,890 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:21:05,892 : INFO - Result is {'title': 'Monthly mean maximum & minimum temperature and total rainfall based upon 1901-2000 data', 'enhanced_keywords': 'MonthlyTemp, MaxMinTemp, TotalRainfall, CityClimatology, ClimatologyData, HistoricalData, MeanTemperature, MonthlyAverages, RainfallPattern', 'sponsored_keywords': 'MonthlyTemp, MaxMinTemp, TotalRainfall, CityClimatology', 'justification': 'Keywords derive from the title and catalog focus on monthly climate variables (temperature and rainfall) for important cities, aiding user discovery of climatology data without institutional terms.', 'confidence_score': 0.8, 'metadata_gaps': ['Geographic coverage (list of cities) not specified', 'Units of temperature and rainfall not documented', 'Data sources and methods not described'], 'hvd_category': ''}

TITLE: Monthly mean maximum & minimum temperature and total rainfall based upon 1901-2000 data
SECTOR: Science and Technology;Earth Sciences
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-15 07:21:06,703 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:21:06,706 : INFO - Result is {'title': 'State-wise Population, Decadal Population Growth Rate and Population Density - 2011', 'enhanced_keywords': 'StatePopulation, PopulationGrowth, PopulationDensity, DecadalGrowth, RuralHealthStats, CensusData, Population2011, StateWisePopulation', 'sponsored_keywords': 'StatePopulation, PopulationDensity, PopulationGrowthRate, DecadalGrowth', 'justification': 'Keywords reflect state-level population metrics and census-derived indicators present in the title and catalog; they focus on population size, growth, and density within the Rural Health Statistics context. The HVD flag is 0, so no High Value Data category is assigned.', 'confidence_score': 0.82, 'metadata_gaps': ['Geographic coverage details for all states are not fully specified', 'Temporal alignment between 2011 data and Rural Health Statistics 2015 catalog is not clarified', 'Source data provenance beyond Note (RGI/Census) is not fully described', 'No explicit data quality indicators or methodology provided'], 'hvd_category': ''}

TITLE: State-wise Population, Decadal Population Growth Rate and Population Density - 2011
SECTOR: Health and Family welfare;Family Welfare;Health
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-15 07:21:12,662 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:21:12,669 : INFO - Result is {'title': 'District-wise MGNREGA Data at a Glance', 'enhanced_keywords': 'MGNREGAData, DistrictData, RuralEmployment, DistrictWiseData, EmploymentGuarantee, WageEmployment, RuralDevelopmentData, DistrictAtAGlance', 'sponsored_keywords': 'MGNREGAData, DistrictData, DistrictWise, DataAtAGlance', 'justification': 'Keywords reflect district-level MGNREGA data and its at-a-glance presentation, aligning with the title and rural development focus. The dataset contains structured numerical data by district, consistent with a statistics classification.', 'confidence_score': 0.82, 'metadata_gaps': ['Temporal coverage not specified', 'Geographic coverage details (state/region) missing', 'Data schema and format not described', 'Data refresh frequency not provided'], 'hvd_category': 'statistics'}

TITLE: District-wise MGNREGA Data at a Glance
SECTOR: Development
HVD: 1
HVD CATEGORY: statistics

Written to CSV

----------------------------

2025-11-15 07:21:13,648 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:21:13,653 : INFO - Result is {'title': 'District Rainfall Normal (in mm) Monthly, Seasonal And Annual : Data Period 1951-2000', 'enhanced_keywords': 'DistrictRainfall, RainfallNormal, MonthlyRainfall, SeasonalRainfall, AnnualRainfall, PrecipitationData, ClimateDataset, MeteorologyData', 'sponsored_keywords': 'DistrictRainfall, RainfallNormal, MonthlyRainfall, SeasonalRainfall, AnnualRainfall', 'justification': 'The dataset provides district-level rainfall normals across monthly, seasonal, and annual periods; keywords mirror the data focus on precipitation and timeframes. Since HVD flag is 0, no high-value data category is assigned.', 'confidence_score': 0.8, 'metadata_gaps': ['Geographic coverage (which districts are included) not specified', 'Spatial granularity and district list missing', 'Source data provenance and collection methods not described', 'Note field is nan and provides no descriptive context'], 'hvd_category': ''}

TITLE: District Rainfall Normal (in mm) Monthly, Seasonal And Annual : Data Period 1951-2000
SECTOR: Science and Technology;Atmospheric Science
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-15 07:21:14,342 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:21:14,347 : INFO - Result is {'title': 'District Level Manufacturing MSME Registered Enterprises under UDYAM Registration till last date', 'enhanced_keywords': 'DistrictManufacturing, UDYAMRegistration, RegisteredEnterprises, DistrictLevel, ManufacturingData, MSMERegistration, EnterpriseRegistration, IndustriesData', 'sponsored_keywords': 'UDYAMRegistration, DistrictLevel, Manufacturing, RegisteredEnterprises', 'justification': 'The dataset centers on district-level manufacturing MSME enterprises registered under UDYAM, a structured catalog of enterprise registrations. Keywords prioritize district scope, UDYAM linkage, and manufacturing enterprise data to support discoverability; classified under statistics due to its numeric, aggregated nature.', 'confidence_score': 0.8, 'metadata_gaps': ['No explicit geographic list of districts or states', "Date range only described as 'till last date'; no exact timestamps", 'Data format and update frequency not specified', 'Potential missing metadata on data collection methodology'], 'hvd_category': 'statistics'}

TITLE: District Level Manufacturing MSME Registered Enterprises under UDYAM Registration till last date
SECTOR: Industries;Medium;Micro;Small Scale
HVD: 1
HVD CATEGORY: statistics

Written to CSV

----------------------------

2025-11-15 07:21:18,740 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:21:18,748 : INFO - Result is {'title': 'District Wise Total MSME Registered Manufacturing Enterprises till last date', 'enhanced_keywords': 'DistrictWise, MSMERegistration, ManufacturingEnterprises, DistrictLevel, RegistrationTotals, UdyogAadhaar, DistrictData, LocalMSME', 'sponsored_keywords': 'DistrictMSME, TotalRegistrations, ManufacturingEnterprises, DistrictWise', 'justification': 'Keywords reflect district-level MSME manufacturing registrations and totals as described in the title. The HVD category is not assigned because the flag is 0.', 'confidence_score': 0.75, 'metadata_gaps': ['Date range not specified (till last date unclear)', 'Geographic coverage not specified beyond districts', 'Data source or collection methodology not documented', 'Units of measure for counts not specified'], 'hvd_category': ''}

TITLE: District Wise Total  MSME Registered Manufacturing Enterprises till last date
SECTOR: Medium;Micro;Small Scale
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-15 07:21:19,623 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:21:19,626 : INFO - Result is {'title': 'Indian Sign Language Dictionary till January 2024', 'enhanced_keywords': 'SignLanguage, SignDictionary, DeafEducation, DeafCommunication, LanguageAccess, SignGlossary, VisualLanguage, DictionaryContent', 'sponsored_keywords': 'SignLanguage, SignDictionary, DeafEducation, LanguageGlossary', 'justification': 'The dataset is a reference dictionary of sign language signs, so keywords emphasize language resources, dictionaries, and deaf education. The HVD flag is 0, so no high-value data category is assigned.', 'confidence_score': 0.78, 'metadata_gaps': ['Start date of dataset not specified', 'Language variants/dialects not specified', 'Geographic or jurisdictional coverage not specified'], 'hvd_category': ''}

TITLE: Indian Sign Language Dictionary till January 2024
SECTOR: Disabled
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-15 07:21:23,157 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:21:23,160 : INFO - Result is {'title': 'Location wise daily Ambient Air Quality of Tamil Nadu for the year 2014', 'enhanced_keywords': 'AmbientAirQuality, LocationWise, DailyData, HistoricalData, IndustrialPollution, ResidentialPollution, VehicularPollution, TamilNadu', 'sponsored_keywords': 'LocationWiseAQI, TamilNaduAir, HistoricalAirQuality, Year2014Data', 'justification': 'The dataset provides location-specific daily ambient air quality measurements for Tamil Nadu with historical daily data. Keywords emphasize ambient air quality, location focus, and daily/historical data; no HVD category is assigned due to HVD Flag being 0.', 'confidence_score': 0.72, 'metadata_gaps': ['Temporal coverage specifics (start/end dates) not provided beyond year 2014', 'Exact geographic coverage within Tamil Nadu (stations/locations) not specified', 'Quality notes mention potential anomalies, but no explicit QC metadata included'], 'hvd_category': ''}

TITLE: Location wise daily Ambient Air Quality of Tamil Nadu for the year 2014
SECTOR: Environment and Forest;Industrial Air Pollution;Residential Air Pollution;Vehicular Air Pollution
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-15 07:21:24,192 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:21:24,195 : INFO - Result is {'title': 'District wise Number of Poultry Farms and Poultry Birds in Farms, 2007  - Tamil Nadu', 'enhanced_keywords': 'DistrictWise, PoultryFarms, PoultryBirds, Year2007, TamilNadu, LivestockCensus, FarmData, FarmCounts', 'sponsored_keywords': 'PoultryFarms, PoultryBirds, DistrictWise, TamilNadu', 'justification': 'Keywords reflect district-level poultry farming data from the 18th Livestock Census, focusing on farm counts and poultry birds. The dataset is structured as numerical counts across districts, aligning with a statistics-oriented use case.', 'confidence_score': 0.75, 'metadata_gaps': [], 'hvd_category': ''}

TITLE: District wise Number of Poultry Farms and Poultry Birds in Farms, 2007  - Tamil Nadu
SECTOR: Agriculture;Animal Husbandry
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-15 07:21:24,780 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:21:24,782 : INFO - Result is {'title': 'Percentage of households having electricity, Improved source of drinking water, Having access to improved toilet facility, Use clean fuel for cooking - DLHS IV', 'enhanced_keywords': 'ElectricityAccess, DrinkingWaterAccess, ToiletAccess, CleanFuelUse, HouseholdFacilities, HealthIndicators, SurveyData, PublicHealth', 'sponsored_keywords': 'ElectricityAccess, DrinkingWaterAccess, ToiletAccess, CleanFuelUse, DLHS4', 'justification': 'The enhanced keywords reflect the four household indicators described in the title, aiding discovery for health and welfare datasets. Since the HVD Flag is 0, no High Value Data category is assigned.', 'confidence_score': 0.72, 'metadata_gaps': ['Year of data collection not specified', 'Geographic coverage details not fully described beyond note', 'Variable definitions and measurement units not provided'], 'hvd_category': ''}

TITLE: Percentage of households having electricity, Improved source of drinking water, Having access to improved toilet facility, Use clean fuel for cooking - DLHS IV
SECTOR: Health and Family welfare;Family Welfare;Health
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-15 07:21:31,343 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:21:31,346 : INFO - Result is {'title': 'Number of Newly Registered Motor Vehicles in 2009-10 and 2010-11 and Number of Registered Motor Vehicles as on 31st March 2010 and as on 31st March 2011 in Tamil Nadu', 'enhanced_keywords': 'VehicleRegistration, NewRegistrations, TamilNaduVehicles, RegistrationCounts, MarchRegistrations, YearWiseRegistrations, MotorVehicleData, VehicleNumbers', 'sponsored_keywords': 'NewRegistrations, TotalRegistrations, TamilNaduVehicles, MotorVehicleCounts', 'justification': 'Keywords focus on motor vehicle registration counts for Tamil Nadu, including new registrations and total registrations across specified years/dates. The dataset is numerical statistics on vehicle registrations.', 'confidence_score': 0.75, 'metadata_gaps': [], 'hvd_category': ''}

TITLE: Number of Newly Registered Motor Vehicles in 2009-10 and 2010-11 and Number of Registered Motor Vehicles as on 31st March 2010 and as on 31st March 2011 in Tamil Nadu
SECTOR: Transport;Road Transport
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-15 07:21:32,530 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:21:32,533 : INFO - Result is {'title': 'State Level Consumer Price Index (Rural/Urban) upto November 2021', 'enhanced_keywords': 'StateCPI, RuralCPI, UrbanCPI, PriceIndex, ConsumerPrices, StatePrices, RegionalPrices, InflationIndex', 'sponsored_keywords': 'StateCPI, RuralUrbanCPI, PriceIndex, ConsumerPrices', 'justification': 'Dataset provides state-level CPI data covering rural and urban segments up to November 2021. Keywords focus on CPI and regional price indices to aid discovery. HVD flag is 0, so no high-value data category assigned.', 'confidence_score': 0.72, 'metadata_gaps': ['Start date of data collection not specified', 'Data frequency and update cadence not specified', 'Geographic coverage limited to state level; no district-level granularity beyond states', 'Source and methodology details missing (base year, calculation method)', 'Note and Sector Resource fields marked nan'], 'hvd_category': ''}

TITLE: State Level Consumer Price Index (Rural/Urban)  upto November 2021
SECTOR: Economy;Prices;Finance;Economy;Statistics
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-15 07:21:38,423 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:21:38,424 : INFO - Result is {'title': 'Longitudinal Ageing Study in India (LASI), Wave I, 2017-18', 'enhanced_keywords': 'LASIWaveI, LongitudinalAgeing, AgingSurvey, HealthSurvey, OlderAdults, Demographics, StateFactsheets, PopulationAging', 'sponsored_keywords': 'LASIWaveI, AgeingStudy, ElderlyHealth, PopulationAging', 'justification': 'Keywords reflect a longitudinal health ageing survey of aging populations using LASI data and state-level factsheets. The dataset is a structured time-series health and demographic dataset, justifying a statistics HVD classification.', 'confidence_score': 0.85, 'metadata_gaps': ['Geographic coverage details by state/UT are not fully explicit in metadata', 'No formal data dictionary or variable definitions provided', 'State-wise sample sizes / wave-specific counts not stated', 'Release/access date and data availability not clearly specified'], 'hvd_category': 'statistics'}
2025-11-15 07:21:38,436 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:21:38,437 : INFO - Result is {'title': 'Seasonal and Annual Minimum / Maximum Temperature series for the period 1901-2021', 'enhanced_keywords': 'SeasonalTemp, AnnualTemp, MinTemp, MaxTemp, TemperatureSeries, HistoricalTemp, ClimateSeries, TemperatureTrend', 'sponsored_keywords': 'SeasonalTemp, AnnualTemp, MinTemp, MaxTemp, TemperatureSeries', 'justification': 'Keywords highlight long-run seasonal and annual temperature series with min/max values to support climate analysis and meteorological research. The dataset comprises historical temperature data, making it a high-value meteorological resource for climate monitoring.', 'confidence_score': 0.82, 'metadata_gaps': ['SpatialCoverage details missing', 'TemperatureUnit unspecified', 'DataProvenance not specified', 'SeasonalAggregationMethod not described', 'DataAccessURL not provided'], 'hvd_category': 'meteorological'}

TITLE: Longitudinal Ageing Study in India (LASI), Wave  I, 2017-18
SECTOR: Health and Family welfare;Health
HVD: 1
HVD CATEGORY: statistics

Written to CSV

----------------------------

TITLE: Seasonal and Annual Minimum / Maximum Temperature series for the period 1901-2021
SECTOR: Science and Technology;Earth Sciences
HVD: 1
HVD CATEGORY: meteorological

Written to CSV

----------------------------

2025-11-15 07:21:40,049 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:21:40,051 : INFO - Result is {'title': 'State/UT-wise District Score during 2021-22', 'enhanced_keywords': 'StateDistrictScore, DistrictScore, StateScore, EducationPGI, PerformanceGrading, PGIIndex, DistrictPerformance, EducationAssessment', 'sponsored_keywords': 'StateDistrictScore, PerformanceGradingIndex, DistrictScore, PGIIndex', 'justification': 'Keywords emphasize state/district level scores under the Performance Grading Index in education, aligning with the dataset title and catalog. The HVD flag is 0, so no high-value data category is assigned.', 'confidence_score': 0.72, 'metadata_gaps': ['Geographic coverage details (list of states/UTs) not explicitly provided', 'District identifiers mapping not included', 'Data source and methodology for PGI scoring not described', 'Temporal specifics beyond the year 2021-22 not stated'], 'hvd_category': ''}

TITLE: State/UT-wise District Score during 2021-22
SECTOR: Education
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-15 07:21:43,611 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:21:43,616 : INFO - Result is {'title': 'Total Number of Registered Motor Vehicles in India during 1951-2013', 'enhanced_keywords': 'VehicleRegistration, RegisteredVehicles, MotorVehicles, TransportTrends, HistoricVehicleData, AnnualVehicleCounts, VehicleCounts, TwoWheelers, AutoRickshaws, RoadTransport', 'sponsored_keywords': 'TotalVehicleCounts, RegisteredVehicles, MotorVehicles, AnnualVehicleCounts, VehicleRegistration', 'justification': "The keywords emphasize the long-running series of registered motor vehicles and their counts over time within the transport domain. The note's details on units and category inclusions inform keyword choices and support trend analysis of vehicle growth.", 'confidence_score': 0.8, 'metadata_gaps': ['Geographic scope limited to national level; no state-level breakdown', 'No data dictionary for vehicle categories (e.g., two-wheelers vs others) across all years', 'Source citation details incomplete; only brief notes provided', "No explicit start/end date granularity for each year's data in machine-readable form"], 'hvd_category': ''}

TITLE: Total Number of Registered Motor Vehicles in India during 1951-2013
SECTOR: Transport;Road Transport
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-15 07:21:43,985 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:21:43,992 : INFO - Result is {'title': 'Number of Newly Registered Motor Vehicles in 2011-12 and Number of Registered Motor Vehicles as on 31st March, 2012 in Delhi', 'enhanced_keywords': 'NewlyRegistered, MotorVehicles, DelhiRegistrations, VehicleRegistration, RegistrationCounts, DelhiStats', 'sponsored_keywords': 'NewlyRegistered, RegisteredMotorVehicles, DelhiRegistrations, VehicleRegistration', 'justification': 'Keywords emphasize Delhi motor vehicle registration counts and yearly registered figures, aligning with the dataset content. The dataset is numeric registration data, reflected in the keywords.', 'confidence_score': 0.78, 'metadata_gaps': ['Exact publication date not specified', 'Temporal scope beyond 2011-12 unclear in metadata', 'Source Year Book reference provided but no link or edition details', 'Geographic granularity restricted to Delhi; no statewide breakdown beyond Delhi'], 'hvd_category': ''}

TITLE: Number of Newly Registered Motor Vehicles in 2011-12 and Number of Registered Motor Vehicles as on 31st March, 2012 in Delhi
SECTOR: Transport;Road Transport
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-15 07:21:47,909 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:21:47,916 : INFO - Result is {'title': 'Weekly Patent Application Granted', 'enhanced_keywords': 'WeeklyPatent, PatentApplication, GrantedPatents, PatentTrends, PatentData, IntellectualProperty, PatentStatistics, IndustryPatents', 'sponsored_keywords': 'PatentGrant, PatentApproval, WeeklyPatents, PatentWeekly, PatentSummary', 'justification': 'The dataset records weekly patent applications granted, so keywords focus on patents and weekly grants. The HVD classification is statistics because it represents temporal counts of patent approvals and related data.', 'confidence_score': 0.82, 'metadata_gaps': ['Geographic coverage not specified', 'Time range of each week not specified', 'Total granted counts per week not specified', 'Patent type breakdown (utility/design/trademark) not specified', 'Source methodology not described'], 'hvd_category': 'statistics'}

TITLE: Weekly Patent Application Granted
SECTOR: Industries
HVD: 1
HVD CATEGORY: statistics

Written to CSV

----------------------------

2025-11-15 07:21:50,326 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:21:50,328 : INFO - Result is {'title': 'Shape of Watershed Boundaries of India', 'enhanced_keywords': 'WatershedBoundaries, HydrologicalBoundaries, CatchmentArea, DrainageBasins, BasinBoundary, GroundWater, SurfaceWater, WatershedMap', 'sponsored_keywords': 'WatershedBoundaries, BoundaryMap, WatershedShape, HydrologicalBoundaries', 'justification': 'Keywords focus on watershed boundaries and hydrological features described by the title and catalog. The dataset consists of boundary polygons for Indian watersheds, making it a geospatial data asset.', 'confidence_score': 0.85, 'metadata_gaps': ['Coordinate reference system not specified', 'Temporal coverage not provided', 'Data source / collection date not provided', 'Geographic extent not explicit beyond country implied', 'Update frequency not specified'], 'hvd_category': 'geospatial'}

TITLE: Shape of Watershed Boundaries of India
SECTOR: Surface Water;Ground Water
HVD: 1
HVD CATEGORY: geospatial

Written to CSV

----------------------------

2025-11-15 07:21:52,206 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:21:52,210 : INFO - Result is {'title': 'Year-wise Annual frequency of cyclones (34 knots or more) and severe cyclones (48 knots or more) crossing different coastal states of India from 1891 to 2017', 'enhanced_keywords': 'CycloneFrequency, YearlyCyclones, SevereCyclones, CoastalStates, SeasonalFrequency, Depressions, HistoricalCyclones, WindThresholds', 'sponsored_keywords': 'YearlyCyclones, CoastalCyclones, SevereCyclones, SeasonalFrequency', 'justification': 'Keywords reflect the dataset focus on yearly cyclone frequency across coastal states and related seasonal/depression counts. Since HVD Flag is 0, no High Value Data category is assigned.', 'confidence_score': 0.78, 'metadata_gaps': ['Geographic coverage specifics by state not enumerated beyond abbreviations in Note', 'Data format, units, and method for cyclone classification (wind speed knots) not detailed', 'Temporal coverage is implied (1891–2017) but exact year-by-year data availability not specified', 'Access URL or data download link not provided'], 'hvd_category': ''}

TITLE: Year-wise Annual frequency of cyclones (34 knots or more) and severe cyclones (48 knots or more) crossing different coastal states of India from 1891 to 2017
SECTOR: Science and Technology;Atmospheric Science;Earth Sciences
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-15 07:21:56,608 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:21:56,613 : INFO - Result is {'title': 'Eight Core Industries (Base Year 2011-12) till last financial year', 'enhanced_keywords': 'CoreIndustries, IndustrialOutput, ManufacturingIndex, SectorPerformance, BaseYear2011, RenewableElectricity, IndustrialGrowth, CoreIndustriesIndex', 'sponsored_keywords': 'EightCoreIndustries, BaseYear2011, IndustrialOutput, ManufacturingIndex', 'justification': "Keywords reflect the dataset's focus on the eight core industrial sectors, their production/activity levels, and the base year reference. The HVD flag is 0, so no High Value Data category is assigned; keywords target discoverability and relevance to core industrial production and base-year indexing.", 'confidence_score': 0.72, 'metadata_gaps': ['Geographic coverage not specified', 'Temporal coverage start not explicitly defined beyond base year', 'Units of measurement for indices not specified'], 'hvd_category': ''}
2025-11-15 07:22:22,648 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:22:22,649 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:22:22,650 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:22:22,650 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:22:22,651 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:22:22,668 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:22:22,668 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:22:22,669 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:22:22,674 : INFO - Result is {'title': 'Daily Rainfall data from India Meteorological Department (IMD GRID MODEL) Agency during July 2023', 'enhanced_keywords': 'RainfallData, DailyRain, July2023, AverageRainfall, RainfallMM, WaterResources, RainfallPattern, GridModel', 'sponsored_keywords': 'DailyRain, RainfallData, July2023, RainfallMM', 'justification': 'The dataset provides daily rainfall measurements (in millimetres) for July 2023 within the Water Resources sector, aligning with meteorological data characteristics. Keywords emphasize rainfall data, temporal scope, and measurement units; HVD categorization reflects meteorological data usage.', 'confidence_score': 0.78, 'metadata_gaps': ['Spatial resolution/grid cell size not specified', 'Geographic coverage (national scope vs grid cells) not specified', 'Coordinate reference system and data source URL not provided', 'Temporal coverage beyond July 2023 not indicated'], 'hvd_category': 'meteorological'}
2025-11-15 07:22:22,675 : INFO - Result is {'title': 'List of MSME Registered Units under Udyog Aadhaar Memorandum - Maharashtra', 'enhanced_keywords': 'MSMERegistration, UdyogAadhaar, RegisteredUnits, MaharashtraMSME, UnitList, MSMEList, DataRegistry, BusinessRegister', 'sponsored_keywords': 'MSMERegistration, UdyogAadhaar, RegisteredUnits, MaharashtraMSME, UAMList', 'justification': 'The dataset provides a registry of MSME units registered under Udyog Aadhaar Memorandum for Maharashtra, so keywords emphasize registration, the UAM scheme, and the list of registered units. It is categorized under companies and company ownership due to the registry of registered business entities.', 'confidence_score': 0.78, 'metadata_gaps': ['Temporal coverage start/end not specified', 'Data source and licensing not specified', 'Geographic coverage specifics beyond Maharashtra not elaborated'], 'hvd_category': 'companies and company ownership'}
2025-11-15 07:22:22,676 : INFO - Result is {'title': 'Web Map Service from  362 OSM Topo Sheets  of Survey of India and Panchromatic imagery of Bhuvan  in Andhra Pradesh', 'enhanced_keywords': 'WebMap, TopoSheets, OSMData, Panchromatic, BhuvanImagery, AndhraPradesh, MapService, WMS', 'sponsored_keywords': 'WebMapService, BhuvanImagery, AndhraPradesh, OSMData', 'justification': 'The keywords reflect the core content: a web map service combining OSM topo sheets and Panchromatic imagery for Andhra Pradesh. The 0 value for HVD means no high-value data classification is applied at this time.', 'confidence_score': 0.72, 'metadata_gaps': ['Temporal coverage missing', 'Spatial resolution not specified', 'Coordinate reference system not specified', 'Data licensing / access terms not specified'], 'hvd_category': ''}
2025-11-15 07:22:22,682 : INFO - Result is {'title': 'Monthly, Seasonal and Annual Mean Temperature Series for the period 1901-2021', 'enhanced_keywords': 'MonthlyTemperature, SeasonalTemperature, AnnualTemperature, TemperatureSeries, MeanTemperature, ClimatologySeries, LongTermTemperature, TemperatureTrends', 'sponsored_keywords': 'MonthlyMean, SeasonalMean, AnnualMean, TemperatureSeries', 'justification': 'The dataset comprises long-term monthly, seasonal, and annual mean temperature series, enabling discovery via temperature-focused keywords. It is classified as meteorological data given its climate-related temperature measurements.', 'confidence_score': 0.83, 'metadata_gaps': ['Units (Celsius or Fahrenheit) not specified', "Geographic coverage clarification (beyond 'All India' implied) and spatial resolution", 'Data collection methodology and homogenization details', 'Data access URL or repository/location', 'Temporal metadata confirmation (start/end dates, update frequency)'], 'hvd_category': 'meteorological'}
2025-11-15 07:22:22,684 : INFO - Result is {'title': 'Elephant Population from 1993 to 2017', 'enhanced_keywords': 'ElephantPopulation, PopulationTrends, ElephantReserve, WildlifeStatus, ConservationData, EndangeredStatus, HabitatHealth, ForestWildlife, PopulationCounts', 'sponsored_keywords': 'ElephantPopulation, PopulationTrends, ElephantReserve, PopulationCounts, ConservationStatus', 'justification': 'Keywords focus on elephant population counts and trends over the specified years, capturing reserve context and conservation relevance. HVD flag is 0, so no High Value Data category is assigned, but the keywords align with the title and catalog information to aid discovery.', 'confidence_score': 0.78, 'metadata_gaps': ['Geographic coverage not specified', 'Data source and collection methodology not provided', 'Units of measurement (counts vs individuals) unclear', 'Sector Resource value marked as nan', 'Temporal metadata (start/end dates beyond the title) not detailed'], 'hvd_category': ''}
2025-11-15 07:22:22,688 : INFO - Result is {'title': 'Subdivision wise Rainfall and its departure from 1901 to 2015', 'enhanced_keywords': 'SubdivisionRainfall, RegionalRainfall, RainfallAnomaly, RainfallDeparture, HistoricalRainfall, RainfallStatistics, TimeSeriesRainfall, SpatialRainfall, AnnualRainfall, RainfallPattern', 'sponsored_keywords': 'SubdivisionRainfall, RainfallDeparture, RegionalRainfall, HistoricalRainfall, AnnualRainfall', 'justification': 'The keywords focus on subdivision-level rainfall data and its departures/anomalies over a historical period, aligned with the title and catalog. They emphasize rainfall statistics and regional patterns without administrative terms.', 'confidence_score': 0.8, 'metadata_gaps': ['GeographicCoverageDetailsMissing', 'TemporalResolutionAndFrequencyMissing', 'DataFormatAndAccessDetailsMissing', 'MethodologyAndDataSourceDetailsNotSpecified'], 'hvd_category': ''}
2025-11-15 07:22:22,692 : INFO - Result is {'title': 'List of all Startups from Meity Startup Hub', 'enhanced_keywords': 'StartupHub, TechStartups, StartupList, InnovationEcosystem, IncubationNetwork, StartupPortfolio, StartupEcosystem, StartupTracking, TechEntrepreneurs', 'sponsored_keywords': 'StartupHub, AllStartups, StartupsList, StartupDirectory', 'justification': 'Keywords focus on the core content: a catalog of startups under the Startup Hub initiative. They align with the dataset title and its ecosystem role, while avoiding administrative terms.', 'confidence_score': 0.75, 'metadata_gaps': ['Geographic coverage not specified', 'Temporal coverage/start date not specified', 'Data collection date not specified', 'Startup identifiers/IDs not provided', 'Data schema/details per startup not provided'], 'hvd_category': ''}
2025-11-15 07:22:22,698 : INFO - Result is {'title': 'Imports of Major Chemical - Product-wise / Group-wise from 2014-15 to 2021-22', 'enhanced_keywords': 'MajorChemicals, ProductWise, GroupWise, ChemicalImports, ImportTrends, QuantityMT, ValueRsLakh, TradeData', 'sponsored_keywords': 'MajorChemicals, ProductWiseImports, ImportsBreakdown, GroupWise', 'justification': "The enhanced keywords emphasize product- and group-wise chemical import data with quantities and values, reflecting the dataset's focus on import statistics for major chemicals. Sponsored keywords closely mirror the title, highlighting major chemicals and product/group-level imports for historical trend analysis.", 'confidence_score': 0.72, 'metadata_gaps': ['Geographic coverage not explicitly stated', 'Data completeness per year not specified within 2014-15 to 2021-22', 'Missing data dictionary or field definitions for product/group', 'No explicit release date or update frequency provided'], 'hvd_category': ''}

TITLE: Eight Core Industries (Base Year 2011-12) till last financial year
SECTOR: Industries;Manufacturing
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

TITLE: Daily Rainfall data from India Meteorological Department (IMD GRID MODEL) Agency during July 2023
SECTOR: Water Resources
HVD: 1
HVD CATEGORY: meteorological

Written to CSV

----------------------------

TITLE: List of MSME Registered Units under Udyog Aadhaar Memorandum - Maharashtra
SECTOR: Medium;Micro;Small Scale
HVD: 1
HVD CATEGORY: companies and company ownership

Written to CSV

----------------------------

TITLE: Web Map Service from  362 OSM Topo Sheets  of  Survey of India and Panchromatic imagery of Bhuvan  in Andhra Pradesh
SECTOR: All;Agriculture;Water and Sanitation;Information and Communications;Defence;Environment and Forest;Water Resources;Governance and Administration;Infrastructure;Social Development;Transport;Travel and Tourism
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

TITLE: Monthly, Seasonal and Annual Mean Temperature Series for the period 1901-2021
SECTOR: Science and Technology;Earth Sciences
HVD: 1
HVD CATEGORY: meteorological

Written to CSV

----------------------------

TITLE: Elephant Population from 1993 to 2017
SECTOR: Environment and Forest
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

TITLE: Subdivision wise Rainfall and its departure from 1901 to 2015
SECTOR: Science and Technology;Atmospheric Science;Earth Sciences
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

TITLE: List of all Startups from Meity Startup Hub
SECTOR: Information and Communications;Information and Technology
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

TITLE: Imports of Major Chemical - Product-wise / Group-wise from 2014-15 to 2021-22
SECTOR: Industries;Chemicals and Petrochemicals
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-15 07:22:39,163 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:22:39,165 : INFO - Result is {'title': 'State Level Consumer Price Index (Rural/Urban) upto May 2023', 'enhanced_keywords': 'StateCPI, RuralCPI, UrbanCPI, PriceIndex, ConsumerPrices, RegionalCPI, TimeSeries', 'sponsored_keywords': 'StateCPI, RuralCPI, UrbanCPI, PriceIndex', 'justification': 'The dataset provides state-level CPI data for rural and urban segments up to May 2023, so keywords emphasize segment CPI and price indices. It falls under the statistics category due to its structured economic indicator data.', 'confidence_score': 0.82, 'metadata_gaps': ['Frequency of data not specified', 'StartDate not provided', 'Data source/methodology not described', 'States included list not specified'], 'hvd_category': 'statistics'}
2025-11-15 07:22:39,306 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:22:39,308 : INFO - Result is {'title': 'Inbound Tourism Foreign Tourist Arrivals, Arrivals of Non-Resident Indians and International Tourist Arrivals 1981-2020', 'enhanced_keywords': 'InboundTourism, ForeignTourists, NRIArrivals, InternationalTouristArrivals, TouristArrivals, ArrivalData, TourismTrends, TravelStatistics', 'sponsored_keywords': 'InboundTourism, ForeignTouristArrivals, NRIArrivals, InternationalTouristArrivals', 'justification': "Keywords reflect the dataset's focus on inbound and international tourist arrivals, including NRIs, and spans 1981-2020, aiding discovery for tourism statistics audiences. HVD category is not assigned due to HVD flag being 0.", 'confidence_score': 0.77, 'metadata_gaps': [], 'hvd_category': ''}

TITLE: State Level Consumer Price Index (Rural/Urban) upto May 2023
SECTOR: Economy;Prices;Finance;Economy;Statistics
HVD: 1
HVD CATEGORY: statistics

Written to CSV

----------------------------

TITLE: Inbound Tourism Foreign Tourist Arrivals, Arrivals of Non-Resident Indians and International Tourist Arrivals 1981-2020
SECTOR: Travel and Tourism
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-15 07:22:40,452 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:22:40,453 : INFO - Result is {'title': 'District-wise Tele-Law Case Registration and Advice Enabled Data from FY 2021-22 to 2022-23', 'enhanced_keywords': 'TeleLaw, DistrictData, CaseRegistration, AdviceEnabled, JusticeAccess, DISHAProgram, LegalAid, DistrictWise', 'sponsored_keywords': 'TeleLawCase, DistrictWiseCases, CaseRegistration, LegalAdvice, DISHAProgram', 'justification': 'The enhanced keywords reflect district-level Tele-Law case data and advisory-enabled services described in the title and catalog. Since the HVD flag is 0, no HVD category is assigned; keywords are selected for discoverability and content alignment.', 'confidence_score': 0.78, 'metadata_gaps': ['Geographic coverage details per district not specified', 'Temporal coverage start date unclear', 'Data dictionary and field definitions for case status and advisory outcomes missing', 'Sector Resource is listed as nan; metadata on data quality and completeness is lacking'], 'hvd_category': ''}

TITLE: District-wise Tele-Law Case Registration and Advice Enabled Data from FY 2021-22 to 2022-23
SECTOR: Judiciary
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-15 07:22:42,284 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:22:42,286 : INFO - Result is {'title': 'State-wise Details of Youth Hostels - 2023', 'enhanced_keywords': 'YouthHostels, HostelDetails, StateWise, HostelScheme, YouthFacilities, HostelData, YouthAccommodation, StateDetails', 'sponsored_keywords': 'StateHostels, YouthHostels, HostelScheme, YouthHostelScheme', 'justification': 'Keywords reflect state-level hostel details and the related hostel scheme, aligning with the dataset title and catalog. HVD not applicable as indicated by the flag.', 'confidence_score': 0.8, 'metadata_gaps': ['Temporal range clarity (exact dates) missing', 'Geographic granularity beyond state level not defined', 'Data collection methodology and sources not described', 'Coverage scope (which states) not specified'], 'hvd_category': ''}

TITLE: State-wise Details of Youth Hostels - 2023
SECTOR: Youth and Sports
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-15 07:22:42,964 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:22:42,970 : INFO - Result is {'title': 'Eight Core Industries (Base Year 2011-12) till last month', 'enhanced_keywords': 'EightCoreIndustries, IndustrialIndex, ManufacturingIndex, CoreIndustriesIndex, CoalIndex, CrudeOilIndex, RefineryProductsIndex, FertilizerIndex, CementIndex', 'sponsored_keywords': 'EightCoreIndustries, CoreIndustriesIndex, IndustrialIndex, BaseYearIndex', 'justification': 'Keywords highlight the core industrial index and manufacturing focus of the dataset. No HVD classification is applied.', 'confidence_score': 0.78, 'metadata_gaps': ["Date range not explicitly stated beyond 'till last month'", 'Geographic coverage not specified', 'Eight core industries list not enumerated in metadata', 'Update frequency not specified'], 'hvd_category': ''}

TITLE: Eight Core Industries (Base Year 2011-12) till last month
SECTOR: Industries;Manufacturing
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-15 07:22:43,366 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:22:43,369 : INFO - Result is {'title': 'State/UT-wise Details of the Rainfall Observed During the Monsoon Season from 2020 to 2022', 'enhanced_keywords': 'MonsoonRainfall, StateRainfall, UTRainfall, RainfallRecords, SeasonalRainfall, MonsoonObservations, StatewiseRainfall, MonsoonTrends', 'sponsored_keywords': 'MonsoonRainfall, StateRainfall, RainfallSeason, StatewiseRainfall', 'justification': 'Keywords emphasize the rainfall data by state/UT during the monsoon period, aligning with the dataset title. The HVD flag is 0, so no High Value Data category is assigned.', 'confidence_score': 0.75, 'metadata_gaps': ['Geographic coverage details (full list of states/UTs) not provided in metadata', 'Temporal coverage is described in the title but not explicitly defined in metadata fields', 'Source/data collection method and data dictionary (units, rainfall measurement criteria) are not specified'], 'hvd_category': ''}

TITLE: State/UT-wise Details of the Rainfall Observed During the Monsoon Season from 2020 to 2022
SECTOR: All
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-15 07:22:46,238 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:22:46,242 : INFO - Result is {'title': 'State/UT-wise Number of UDID Card Generated as on 28.07.2021', 'enhanced_keywords': 'UDIDCardGenerated, StateWiseUDID, CardGenerationData, Session254Data, UnstarredQuestion, AnswersData, UDIDStatistics, RajyaSabhaAnswers', 'sponsored_keywords': 'UDIDCardCount, StateWiseUDID, AsOnDate, RajyaSabhaQuestion', 'justification': "Keywords reflect the dataset's focus on UDID card generation by state/UT as captured in a Rajya Sabha session data note. The catalog title indicates Answers data for Session 254, with relation to unstarred questions; no HVD categorization is assigned.", 'confidence_score': 0.72, 'metadata_gaps': ['Geographic coverage clarified only as State/UT-wise; no explicit list of states', 'Methodology and data collection details are not provided', 'Exact date of data compilation beyond the on-date is not specified'], 'hvd_category': ''}
2025-11-15 07:22:46,256 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:22:46,260 : INFO - Result is {'title': 'Delivery Post office Pincode Boundary', 'enhanced_keywords': 'PincodeBoundary, PostOffice, PincodeMap, BoundaryGeoJson, PostalGeodata, DeliveryPost, BoundaryDataset, GeoJson', 'sponsored_keywords': 'PincodeBoundary, PostOffice, GeoJson, DeliveryPost', 'justification': 'Keywords focus on the core content: geospatial boundary data for pincodes and post offices in a GeoJSON format. The HVD category is geospatial because the dataset provides boundary geodata suitable for mapping and spatial analysis.', 'confidence_score': 0.82, 'metadata_gaps': ['Geographic scope explicitly stated as All India but not clearly defined in metadata', 'Temporal coverage and update frequency not provided', 'Data licensing/usage terms missing', 'Source provenance and boundary data generation method not specified', 'Boundary accuracy or datum not described'], 'hvd_category': 'geospatial'}

TITLE: State/UT-wise Number of UDID Card Generated as on 28.07.2021
SECTOR: All
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

TITLE: Delivery Post office Pincode Boundary
SECTOR: All
HVD: 1
HVD CATEGORY: geospatial

Written to CSV

----------------------------

2025-11-15 07:22:52,897 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:22:52,900 : INFO - Result is {'title': 'Import & Export of Petroleum Products - Volumes for Year - 2022-23', 'enhanced_keywords': 'ImportExport, PetroleumProducts, Volumes, Year2022To2023, ProvisionalData, OilTrade, PPACData, MetricTonnes', 'sponsored_keywords': 'PetroleumVolumes, PetroleumImports, PetroleumExports, TradeVolumes', 'justification': "Keywords focus on the dataset's core content: yearly import/export volumes of petroleum products and provisional data as reported by PPAC. The HVD flag is 0, so no high-value data category is assigned, but the terms emphasize trade volumes and the PPAC data source.", 'confidence_score': 0.78, 'metadata_gaps': ['Geographic coverage not explicitly stated', 'Temporal start/end specifics beyond year 2022-23 not detailed', "Unit definitions for '000 Metric Tonnes' not standardized in metadata", 'Product category breakdown and methodology for inclusions/exclusions not provided'], 'hvd_category': ''}

TITLE: Import & Export of Petroleum Products - Volumes for Year - 2022-23
SECTOR: Non Renewable
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-15 07:23:02,686 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:23:02,689 : INFO - Result is {'title': 'Quarterly Estimates of GDP at Constant (2011-12) Prices from 2011-12 to 2022-23', 'enhanced_keywords': 'GdpEstimates, ConstantPrices, QuarterlyGdp, TimeSeries, BaseYear2011, MacroEconomy, EconomicStatistics, GrowthTrend', 'sponsored_keywords': 'QuarterlyGdp, ConstantPrices, GdpEstimates, From2011To2022', 'justification': "Keywords focus on quarterly GDP data at a constant price base and macroeconomic statistics, aligning with the dataset title. The HVD classification as statistics reflects the dataset's role as structured economic indicators.", 'confidence_score': 0.82, 'metadata_gaps': ['Geographic coverage not specified', 'Unit of measurement not stated', 'Source/Publication date not provided'], 'hvd_category': 'statistics'}

TITLE: Quarterly Estimates of GDP at Constant (2011-12) Prices from 2011-12 to 2022-23
SECTOR: Finance;Economy;Statistics
HVD: 1
HVD CATEGORY: statistics

Written to CSV

----------------------------

2025-11-15 07:23:05,741 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:23:05,746 : INFO - Result is {'title': 'List of MSME Registered Units under Udyog Aadhaar Memorandum - Andhra Pradesh', 'enhanced_keywords': 'MSMEUnits, UdyogAadhaar, RegisteredUnits, AndhraPradesh, UnitList, MSMERegistration, BusinessEntities, MSMERecords', 'sponsored_keywords': 'MSMEUnits, UdyogAadhaar, RegisteredUnits, AndhraPradesh', 'justification': "Keywords reflect the dataset content: a registry of MSME registered units under the Udyog Aadhaar Memorandum in Andhra Pradesh. The HVD category is assigned to the 'companies and company ownership' class since it enumerates business entities.", 'confidence_score': 0.82, 'metadata_gaps': ['Dataset URL not provided in metadata', 'LastUpdatedDate not specified', 'Record count not specified', 'Data dictionary/field definitions not provided', 'Geographic granularity (district-level) not specified'], 'hvd_category': 'companies and company ownership'}

TITLE: List of MSME Registered Units under Udyog Aadhaar Memorandum - Andhra Pradesh
SECTOR: Medium;Micro;Small Scale
HVD: 1
HVD CATEGORY: companies and company ownership

Written to CSV

----------------------------

2025-11-15 07:23:07,953 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:23:07,955 : INFO - Result is {'title': 'Digital Seismotectonic Atlas of India and its Environs', 'enhanced_keywords': 'Seismotectonic, SeismotectonicAtlas, EnvironsMap, CrustalTectonics, RegionalGeology, GeologyMapping, ScaleOneMillion, EarthStructure', 'sponsored_keywords': 'SeismotectonicAtlas, DigitalAtlas, SeismicHazards, TectonicsMap', 'justification': 'The keywords emphasize seismotectonic mapping and regional geology described in the atlas and its note about a 1:1,000,000 scale; HVD flag is 0, so no high-value data classification is applied.', 'confidence_score': 0.78, 'metadata_gaps': ['Geographic coverage specifics (regions covered) not detailed', 'Temporal coverage and update history not specified', 'Data format and access details not provided'], 'hvd_category': ''}

TITLE: Digital Seismotectonic Atlas of India and its Environs
SECTOR: Mining;Others
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-15 07:23:09,652 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:23:09,654 : INFO - Result is {'title': 'Rainfall in NE India and its departure from normal for Monsoon session from 1901-2021', 'enhanced_keywords': 'RainfallData, MonsoonPattern, NortheastRainfall, DepartureNormal, HistoricalRainfall, RainfallTrend, SeasonalRainfall, MonsoonDeparture', 'sponsored_keywords': 'MonsoonDeparture, RainfallData, NortheastRainfall, DepartureNormal', 'justification': 'The dataset contains long-term rainfall records for the northeastern region with departures from normal during the monsoon, enabling analysis of rainfall magnitude, patterns, and trends. Keywords are chosen to reflect rainfall, monsoon behavior, and departure from normal to aid discoverability; the data is categorized under meteorological due to its focus on weather/climate information.', 'confidence_score': 0.79, 'metadata_gaps': ['GeographicCoverageMissing', 'TemporalResolutionMissing', 'SourceMetadataMissing'], 'hvd_category': 'meteorological'}

TITLE: Rainfall in NE India and its departure from normal for Monsoon session from 1901-2021
SECTOR: Science and Technology;Earth Sciences
HVD: 1
HVD CATEGORY: meteorological

Written to CSV

----------------------------

2025-11-15 07:23:12,057 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:23:12,060 : INFO - Result is {'title': 'Digital Seismotectonic Atlas of India and its Environs', 'enhanced_keywords': 'SeismoTectonics, SeismicAtlas, CrustalTectonics, EarthquakeMap, PlateTectonics, SeismologyData, TectonicMap, SubductionZones, SeismicityPattern', 'sponsored_keywords': 'SeismicAtlas, DigitalAtlas, SeismoTectonics, AtlasSeismicity', 'justification': 'The dataset is a digital geospatial atlas focusing on seismotectonics and tectonic features, with terms aligned to the title. HVD geospatial classification is appropriate due to its mapping of seismic and tectonic data over a geographic area.', 'confidence_score': 0.85, 'metadata_gaps': ['Spatial coverage bounds not defined', 'Temporal coverage not provided', 'Data formats and access methods not specified', 'Coordinate Reference System (CRS) not declared', 'Provenance and data sources not described', 'Update frequency not specified'], 'hvd_category': 'geospatial'}

TITLE: Digital Seismotectonic Atlas of India and its Environs
SECTOR: Governance and Administration;Union/State Government Administration;Union/State Government Administration;Mining;Mining;Coastal & Island;Earth Sciences;Marine Science;Polar Science;Research & Development
HVD: 1
HVD CATEGORY: geospatial

Written to CSV

----------------------------

2025-11-15 07:23:12,966 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:23:12,967 : INFO - Result is {'title': 'Number of Newly Registered Motor Vehicles in 2009-10 and 2010-11 and Number of Registered Motor Vehicles as on 31st March 2010 and as on 31st March 2011 in Uttar Pradesh', 'enhanced_keywords': 'MotorVehicles, VehicleRegistrations, NewRegistrations, RegisteredVehicles, UttarPradesh, YearBookData, RoadTransportData, RegistrationStatistics', 'sponsored_keywords': 'NewRegistrations, RegisteredVehicles, UttarPradesh, VehicleRegistrations', 'justification': "Keywords capture the dataset's focus on motor vehicle registrations in Uttar Pradesh across two periods. The HVD flag is 0, so no high-value data category is assigned.", 'confidence_score': 0.8, 'metadata_gaps': [], 'hvd_category': ''}

TITLE: Number of Newly Registered Motor Vehicles in 2009-10 and 2010-11 and Number of Registered Motor Vehicles as on 31st March 2010 and as on 31st March 2011 in Uttar Pradesh
SECTOR: Transport;Road Transport
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-15 07:23:14,071 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:23:14,074 : INFO - Result is {'title': 'State/UT-wise Number of Indian Penal Code (IPC) Crimes from 2020 to 2022', 'enhanced_keywords': 'StateWise, CrimesTrend, CrimeRate, YearRange, CrimeData, StateComparison, CrimePatterns, RegionalCrimes', 'sponsored_keywords': 'StateCrimes, IPCOffences, CrimeCounts, YearRange', 'justification': 'Keywords emphasize state/UT level IPC crime counts over 2020–2022 and related rate context, aligning with the dataset title and note. The HVD flag is 0, so no HVD category is assigned.', 'confidence_score': 0.75, 'metadata_gaps': ['Nagaland data clarification pending', 'Geographic coverage details for all States/UTs not fully specified', 'Methodology on crime rate per lakh variations across states'], 'hvd_category': ''}

TITLE: State/UT-wise Number of Indian Penal Code (IPC) Crimes from 2020 to 2022
SECTOR: Police
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-15 07:23:14,541 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:23:14,546 : INFO - Result is {'title': 'Disclosed Ground Water Level Data under Atal Bhujal Yojana from 2015 to 2022', 'enhanced_keywords': 'GroundWater, WaterLevel, LevelData, TimeSeries, YearRange, AtalBhujal, Yojana, HydroMonitoring', 'sponsored_keywords': 'GroundWater, WaterLevel, AtalBhujal, Yojana, YearRange', 'justification': 'Keywords reflect groundwater level data under the ABHY program over a defined time span, aiding discovery for users seeking groundwater measurements. Although not marked as High Value Data, the terms focus on content related to groundwater level data and the ABHY initiative across 2015–2022.', 'confidence_score': 0.78, 'metadata_gaps': ["SectorResource is 'nan' (missing resource type).", "Note is 'nan' (missing descriptive note).", 'Exact start/end dates are only present in the title; metadata lacks explicit date range fields.', 'Geographic coverage information is not provided.'], 'hvd_category': ''}

TITLE: Disclosed Ground Water Level Data under Atal Bhujal Yojana from 2015 to 2022
SECTOR: Ground Water
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-15 07:23:21,547 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:23:21,550 : INFO - Result is {'title': 'Quarterly Estimates of GDP at Current Prices, 2011-12 Series From 2011-12 to 2022-23', 'enhanced_keywords': 'QuarterlyGDP, GDPEstimates, CurrentPrices, TimeSeries, MacroEconomy, EconomicData, EconomicIndicators, GDPSeries', 'sponsored_keywords': 'QuarterlyGDP, GDPEstimates, GDPSeries, CurrentPrices', 'justification': "The dataset provides quarterly GDP estimates at current prices across multiple years, forming a time-series of macroeconomic data. Keywords emphasize GDP measurements and economic indicators, matching the dataset's content and distinguishing it as statistics.", 'confidence_score': 0.82, 'metadata_gaps': ['Geographic coverage not specified', 'Data source or publication reference not provided', 'Units of GDP not specified', 'Frequency/periodicity not explicitly stated', 'Methodology notes not provided'], 'hvd_category': 'statistics'}

TITLE: Quarterly Estimates of GDP at Current Prices, 2011-12 Series From 2011-12 to 2022-23
SECTOR: Economy;Macro Economy;Finance;Economy
HVD: 1
HVD CATEGORY: statistics

Written to CSV

----------------------------

2025-11-15 07:23:29,271 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:23:29,274 : INFO - Result is {'title': 'Sector wise Estimated Number of Workers under Fourth Round of Quarterly Employment Survey from Jan to March 2022', 'enhanced_keywords': 'SectorWise, WorkerEstimates, EmploymentSurvey, QuarterlyData, SectorData, WorkforceNumbers, RoundFour, JanMar2022', 'sponsored_keywords': 'SectorWise, WorkerEstimates, EmploymentSurvey, RoundFour', 'justification': 'Keywords highlight sector-level worker estimates derived from the Quarterly Employment Survey, enabling discovery by users seeking employment and sector data. HVD flag is 0, so no high-value data categorization is applied.', 'confidence_score': 0.75, 'metadata_gaps': ['Geographic coverage not specified', 'Sector Resource field is missing (nan)', 'Data collection methodology and sample size not described', 'Release date/periodicity not specified'], 'hvd_category': ''}

TITLE: Sector wise Estimated Number of Workers under Fourth Round of Quarterly Employment Survey from Jan to March 2022
SECTOR: Employment
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-15 07:23:30,464 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:23:30,466 : INFO - Result is {'title': 'Shape file of reservoir', 'enhanced_keywords': 'ReservoirData, WaterResources, ReservoirBoundaries, ReservoirLocations, SpatialData, GeospatialWater, ReservoirMap, HydroGeography', 'sponsored_keywords': 'ReservoirBoundaries, ReservoirLocations, WaterResources, ReservoirMap', 'justification': "Keywords emphasize reservoir location and boundary data within a geospatial water resources context, aligning with the dataset's shapefile-based reservoir boundaries. The HVD category is geospatial due to the spatial nature of the data.", 'confidence_score': 0.8, 'metadata_gaps': ['Coordinate reference system not specified', 'Temporal coverage not specified', 'Data update frequency not specified'], 'hvd_category': 'geospatial'}

TITLE: Shape file of reservoir
SECTOR: Ground Water;Surface Water
HVD: 1
HVD CATEGORY: geospatial

Written to CSV

----------------------------

2025-11-15 07:23:32,587 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:23:32,592 : INFO - Result is {'title': 'Boundaries of Agro-climatic regions', 'enhanced_keywords': 'RegionBoundaries, ClimaticRegions, RegionalMap, ClimateZones, BoundaryMap, NationalRegions, BoundaryLayer, GeographicBoundary', 'sponsored_keywords': 'RegionBoundaries, AgroBoundary, ClimaticRegions, BoundaryMap', 'justification': 'Keywords highlight geographic boundaries and agro-climatic region concepts, aligning with the country-wide boundary shapefiles. The dataset is classified as geospatial due to its boundary/geographic data format and its use for spatial analysis in water resources planning.', 'confidence_score': 0.84, 'metadata_gaps': ['Coordinate Reference System (CRS) not specified', 'Temporal coverage not specified', 'Data license not specified', 'Source details and data provenance not specified', 'Update frequency not specified'], 'hvd_category': 'geospatial'}

TITLE: Boundaries of Agro-climatic regions
SECTOR: Ground Water;Surface Water
HVD: 1
HVD CATEGORY: geospatial

Written to CSV

----------------------------

2025-11-15 07:23:33,717 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:23:33,719 : INFO - Result is {'title': 'State-wise Population, Decadal Population Growth rate and Population Density - 2011', 'enhanced_keywords': 'StatePopulation, PopulationDensity, DecadalGrowth, Population2011, RuralHealth, CensusData, StateWiseStats, Demographics', 'sponsored_keywords': 'GrowthRate, Census2011, StateDensity, PopulationTrend', 'justification': 'The keywords map to the core contents: state-level population, density, and decadal growth for 2011 as described in the title. The dataset is part of Rural Health Statistics; no high-value data designation is assigned (HVD Flag = 0).', 'confidence_score': 0.78, 'metadata_gaps': ['Geographic scope details missing beyond states', 'Temporal coverage limited to 2011; no trend data', 'Data sources and methodology not fully documented in Note'], 'hvd_category': ''}

TITLE: State-wise Population, Decadal Population Growth rate and Population Density - 2011
SECTOR: Health and Family welfare;Family Welfare;Health
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-15 07:23:36,362 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-15 07:23:36,364 : INFO - Result is {'title': 'State-wise Details of the Infant Mortality Rate, Institutional Delivery and Prevalence of Under Weight Children under five years of Age (in Reply to Unstarred Question on 07 December, 2022)', 'enhanced_keywords': 'InfantMortality, InstitutionalDelivery, UnderFive, StateWiseDetails, ChildNutrition, WestBengal, HealthStatus, RegionalVariation', 'sponsored_keywords': 'InfantMortality, StateWiseDetails, InstitutionalDelivery, UnderFive', 'justification': "Keywords reflect the dataset's focus on state-wise infant mortality, delivery practices, and nutritional status of children under five, as indicated by the title and note. The terms are user-friendly and non-technical, aiding discoverability while staying aligned with the dataset content; the HVD flag is 0, so no HV data category is assigned.", 'confidence_score': 0.72, 'metadata_gaps': ['Geographic coverage details for all states not clearly specified', 'Temporal coverage beyond 2019-21 not explicitly stated', 'Definitions/methodology for IMR, institutional delivery, and underweight prevalence not provided'], 'hvd_category': ''}

TITLE: State-wise Details of the Infant Mortality Rate, Institutional Delivery and Prevalence of Under Weight Children under five years of Age (in Reply to Unstarred Question on 07 December, 2022)
SECTOR: All
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------


Complete Results saved to results_100.csv

ValueError: Categorical categories must be unique

In [37]:
result_df=pd.read_csv("/home/aakash/NIC/cdl-updated/nic-metadata-cleaning/notebooks/results_100.csv")
result_df.count(axis=0)

title                           100
sector                          100
hvd                             100
metadata_input                  100
llm_response                    100
generated_keywords              100
generated_sponsored_keywords    100
generated_subject                 0
generated_theme                   0
justification                   100
confidence_score                100
metadata_gaps                   100
hvd_category                     42
dtype: int64

In [15]:
results_array

[{'title': 'Current Daily Price of Various Commodities from Various Markets (Mandi)',
  'sector': 'Agriculture;Agricultural Marketing',
  'metadata_input': 'Title: Current Daily Price of Various Commodities from Various Markets (Mandi)\nCatalog Title: Current daily price of various commodities from various markets (Mandi)\nMinistry/Department: Ministry of Agriculture and Farmers Welfare;Department of Agriculture and Farmers Welfare;Directorate of Marketing and Inspection (DMI)\nSector: Agriculture;Agricultural Marketing\nSector Resource: Agriculture;Agricultural Marketing\nCDOS State Ministry: Directorate of Marketing and Inspection (DMI)\nNote: nan',
  'llm_response': '{"Title": "Current Daily Price of Various Commodities from Various Markets (Mandi)"}',
  'generated_keywords': '',
  'generated_subject': '',
  'generated_theme': '',
  'justification': '',
  'confidence_score': 0,
  'metadata_gaps': '[]'},
 {'title': 'Registrars of Companies (RoC)-wise Company Master Data',
  'sector': 'Commerce;Companies',
  'metadata_input': 'Title: Registrars of Companies (RoC)-wise Company Master Data\nCatalog Title: Company Master Data\nMinistry/Department: Ministry of Corporate Affairs\nSector: Commerce;Companies\nSector Resource: Commerce;Companies\nCDOS State Ministry: Ministry of Corporate Affairs\nNote: Figures Authorized Capital and Paid up Capital are in INR; NA: Not Available The data upto 3rd November 2023.',
  'llm_response': '{"error": "Two lines required exactly"}',
  'generated_keywords': '',
  'generated_subject': '',
  'generated_theme': '',
  'justification': '',
  'confidence_score': 0,
  'metadata_gaps': '[]'},
 {'title': 'Variety-wise Daily Market Prices Data of Commodity',
  'sector': 'Agriculture;Agricultural Marketing',
  'metadata_input': 'Title: Variety-wise Daily Market Prices Data of Commodity\nCatalog Title: Current daily price of various commodities from various markets (Mandi)\nMinistry/Department: Ministry of Agriculture and Farmers Welfare;Department of Agriculture and Farmers Welfare;Directorate of Marketing and Inspection (DMI)\nSector: Agriculture;Agricultural Marketing\nSector Resource: nan\nCDOS State Ministry: Directorate of Marketing and Inspection (DMI)\nNote: nan',
  'llm_response': '{"title": "Variety-wise Daily Market Prices Data of Commodity", "enhanced_keywords": ["mandi", "market prices", "daily prices", "commodity prices", "agriculture", "agricultural marketing", "price data", "markets"]}',
  'generated_keywords': '',
  'generated_subject': '',
  'generated_theme': '',
  'justification': '',
  'confidence_score': 0,
  'metadata_gaps': '[]'},
 {'title': 'Real time Air Quality Index from various locations',
  'sector': 'Environment and Forest;Industrial Air Pollution;Residential Air Pollution;Vehicular Air Pollution',
  'metadata_input': 'Title: Real time Air Quality Index from various locations\nCatalog Title: Real time Air Quality Index\nMinistry/Department: Ministry of Environment, Forest and Climate Change;Central Pollution Control Board\nSector: Environment and Forest;Industrial Air Pollution;Residential Air Pollution;Vehicular Air Pollution\nSector Resource: Environment and Forest;Industrial Air Pollution;Residential Air Pollution;Vehicular Air Pollution\nCDOS State Ministry: Central Pollution Control Board\nNote: The real-time data as collected from the field instruments is displayed live without human intervention from CPCB. It is likely that the live data may display some errors or abnormal values. Any abnormal value may be due to any episode or instrumental error at any particular time.',
  'llm_response': '{"Title": "Real time Air Quality Index from various locations", "Enhanced Keywords": "air quality, real time, live data, air pollution, monitoring, multiple sites, india, locations"}',
  'generated_keywords': '',
  'generated_subject': '',
  'generated_theme': '',
  'justification': '',
  'confidence_score': 0,
  'metadata_gaps': '[]'},
 {'title': 'All India Pincode Directory till last month',
  'sector': 'Information and Communications;Post',
  'metadata_input': 'Title: All India Pincode Directory till last month\nCatalog Title: All India Pincode Directory (Through WebService)\nMinistry/Department: Ministry of Communications;Department of Posts\nSector: Information and Communications;Post\nSector Resource: Post\nCDOS State Ministry: Department of Posts\nNote: Data will be updated on monthly basis.',
  'llm_response': '{"title": "All India Pincode Directory till last month", "Enhanced Keywords": "pin code, india, pincode directory, postal code, india post, monthly updates, post office, directory"}',
  'generated_keywords': '',
  'generated_subject': '',
  'generated_theme': '',
  'justification': '',
  'confidence_score': 0,
  'metadata_gaps': '[]'},
 {'title': 'Kisan Call Centre (KCC) - Transcripts of farmers queries & answers',
  'sector': 'Agriculture',
  'metadata_input': 'Title: Kisan Call Centre (KCC) - Transcripts of farmers queries & answers\nCatalog Title: District wise and month wise queries of farmers in Kisan Call Centre (KCC) \nMinistry/Department: Ministry of Agriculture and Farmers Welfare;Department of Agriculture and Farmers Welfare\nSector: Agriculture\nSector Resource: nan\nCDOS State Ministry: Department of Agriculture and Farmers Welfare\nNote: nan',
  'llm_response': '{"Title": "Kisan Call Centre (KCC) - Transcripts of farmers queries & answers", "Enhanced Keywords": "kisan, call centre, transcripts, farmers queries, district wise, month wise, agriculture, monthly data"}',
  'generated_keywords': '',
  'generated_subject': '',
  'generated_theme': '',
  'justification': '',
  'confidence_score': 0,
  'metadata_gaps': '[]'},
 {'title': 'Health indicator-wise monthly datasets at sub district level from HMIS',
  'sector': 'Health and Family welfare;Family Welfare;Health',
  'metadata_input': 'Title: Health indicator-wise monthly datasets at sub district level from HMIS\nCatalog Title: Health indicator-wise monthly datasets at sub district level from HMIS \nMinistry/Department: Ministry of Health and Family Welfare;Department of Health and Family Welfare\nSector: Health and Family welfare;Family Welfare;Health\nSector Resource: Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health\nCDOS State Ministry: Department of Health and Family Welfare\nNote: NA: Not Available/Not Applicable; The data is as reported by health facilities of respective States/UTs of India.',
  'llm_response': '{"Title": "Health indicator-wise monthly datasets at sub district level from HMIS", "Enhanced Keywords": ["health data", "monthly data", "health indicators", "subdistrict data", "india", "state data", "health facilities", "family welfare"]}',
  'generated_keywords': '',
  'generated_subject': '',
  'generated_theme': '',
  'justification': '',
  'confidence_score': 0,
  'metadata_gaps': '[]'},
 {'title': 'Wholesale Price Index (Base Year 2011-12) till last month',
  'sector': 'Economy;Prices;Finance;Economy',
  'metadata_input': 'Title: Wholesale Price Index (Base Year 2011-12) till last month\nCatalog Title: Wholesale Price Index\nMinistry/Department: Ministry of Commerce and Industry;Department for Promotion of industry and Internal Trade;Office of the Economic Adviser\nSector: Economy;Prices;Finance;Economy\nSector Resource: Economy;Prices;Finance;Economy\nCDOS State Ministry: Office of the Economic Adviser\nNote: Data for last two months are provisional; NA: Not Applicable/Available',
  'llm_response': '{"Title": "Wholesale Price Index (Base Year 2011-12) till last month", "Enhanced Keywords": ["wholesale prices", "price index", "base year", "last month", "monthly data", "economy", "finance", "provisional data"]}',
  'generated_keywords': '',
  'generated_subject': '',
  'generated_theme': '',
  'justification': '',
  'confidence_score': 0,
  'metadata_gaps': '[]'},
 {'title': 'FDI Equity Inflows from the year 2000 till last quarter',
  'sector': 'Commerce',
  'metadata_input': 'Title: FDI Equity Inflows from the year 2000 till last quarter\nCatalog Title: Foreign Direct Investment (FDI) Equity Inflows\nMinistry/Department: Ministry of Commerce and Industry;Department for Promotion of industry and Internal Trade\nSector: Commerce\nSector Resource: Commerce\nCDOS State Ministry: Department for Promotion of industry and Internal Trade\nNote: Data are being updated quarterly basic, it contains data till last quarter of the current year.',
  'llm_response': '{"error": "No"}',
  'generated_keywords': '',
  'generated_subject': '',
  'generated_theme': '',
  'justification': '',
  'confidence_score': 0,
  'metadata_gaps': '[]'},
 {'title': 'Daily data of reservoir level of Central Water Commission (CWC)',
  'sector': 'Water Resources',
  'metadata_input': 'Title: Daily data of reservoir level of Central Water Commission (CWC)\nCatalog Title: Reservoir\nMinistry/Department: Department of Water Resources, River Development & Ganga Rejuvenation;Ministry of Jal Shakti;National Water Informatics Centre\nSector: Water Resources\nSector Resource: nan\nCDOS State Ministry: National Water Informatics Centre\nNote: nan',
  'llm_response': '{"Title": "Daily data of reservoir level of Central Water Commission (CWC)", "Enhanced Keywords": "reservoir levels, daily data, water data, reservoir data, water resources, reservoir monitoring, india, government data"}',
  'generated_keywords': '',
  'generated_subject': '',
  'generated_theme': '',
  'justification': '',
  'confidence_score': 0,
  'metadata_gaps': '[]'},
 {'title': 'India Districts Factsheets of National Family Health Survey (NFHS) - 5, 2019-2021',
  'sector': 'All;Health and Family welfare',
  'metadata_input': 'Title: India Districts Factsheets of National Family Health Survey (NFHS) - 5, 2019-2021\nCatalog Title: National Family Health Survey-5 (NFHS-5) - India Districts Factsheet Data\nMinistry/Department: Ministry of Health and Family Welfare;Department of Health and Family Welfare;International Institute for Population Sciences (IIPS)\nSector: All;Health and Family welfare\nSector Resource: All;Family Welfare\nCDOS State Ministry: International Institute for Population Sciences (IIPS)\nNote: Figures in ( ) are based on 25-49 unweighted cases and * denotes percentage not shown based on fewer than 25 unweighted cases. For more details please, visit to URL \nhttp://rchiips.org/nfhs/districtfactsheet_NFHS-5.shtml',
  'llm_response': '{"Title": "India Districts Factsheets of National Family Health Survey (NFHS) - 5, 2019-2021", "Enhanced Keywords": "district data, health survey, family health, india data, district factsheet, national survey, health indicators, child health"}',
  'generated_keywords': '',
  'generated_subject': '',
  'generated_theme': '',
  'justification': '',
  'confidence_score': 0,
  'metadata_gaps': '[]'},
 {'title': 'Voice Call Quality Customer Experience till last month',
  'sector': 'Information and Communications;Telecom',
  'metadata_input': 'Title: Voice Call Quality Customer Experience till last month\nCatalog Title: Voice Call Quality Customer Experience \nMinistry/Department: Ministry of Communications;Department of Telecommunications (DOT);Telecom Regulatory Authority of India (TRAI)\nSector: Information and Communications;Telecom\nSector Resource: Information and Communications;Telecom;Information and Communications;Telecom;Information and Communications;Telecom;Information and Communications;Telecom;Information and Communications;Telecom;Information and Communications;Telecom;Information and Communications;Telecom;Information and Communications;Telecom\nCDOS State Ministry: Telecom Regulatory Authority of India (TRAI)\nNote: nan',
  'llm_response': '{"Title": "Voice Call Quality Customer Experience till last month"}',
  'generated_keywords': '',
  'generated_subject': '',
  'generated_theme': '',
  'justification': '',
  'confidence_score': 0,
  'metadata_gaps': '[]'},
 {'title': 'Month-wise All India Crowdsourced Mobile Data Speed Measurement',
  'sector': 'Information and Communications;Telecom',
  'metadata_input': 'Title: Month-wise All India Crowdsourced Mobile Data Speed Measurement\nCatalog Title: MySpeed (Crowdsourced Mobile Data Speeds)\nMinistry/Department: Ministry of Communications;Department of Telecommunications (DOT);Telecom Regulatory Authority of India (TRAI)\nSector: Information and Communications;Telecom\nSector Resource: Information and Communications;Telecom;Information and Communications;Telecom;Information and Communications;Telecom;Information and Communications;Telecom;Information and Communications;Telecom;Information and Communications;Telecom;Information and Communications;Telecom;Information and Communications;Telecom\nCDOS State Ministry: Telecom Regulatory Authority of India (TRAI)\nNote: if You are not able to find speeds mentioned for a TSP/ State, this is due to insufficient samples in your selection "na" = "not available" owing to device unable to capture signal level LSA : Licensed_Service_Area, Signal_Strength : signal strength refers to the Transmitter power output as received by a reference antenna, TEST_TYPE : Upload /Download represent whether speed is for Download test or Upload Test, Technology : Network generation technology of wireless technology, TSP: Telecom Service Provider which provide service to users in a specific LSA',
  'llm_response': '{"Title": "Month-wise All India Crowdsourced Mobile Data Speed Measurement", "Enhanced Keywords": ["india", "mobile data", "data speed", "crowdsourced data", "speed test", "telecom", "network speed", "mobile network"]}',
  'generated_keywords': '',
  'generated_subject': '',
  'generated_theme': '',
  'justification': '',
  'confidence_score': 0,
  'metadata_gaps': '[]'},
 {'title': 'All India and State/UT-wise Factsheets of National Family Health Survey (NFHS) - 5, 2019-2021',
  'sector': 'Health and Family welfare;Family Welfare',
  'metadata_input': 'Title: All India and State/UT-wise Factsheets of National Family Health Survey (NFHS) - 5, 2019-2021\nCatalog Title: National Family Health Survey (NFHS) - 5\nMinistry/Department: Ministry of Health and Family Welfare;Department of Health and Family Welfare;International Institute for Population Sciences (IIPS)\nSector: Health and Family welfare;Family Welfare\nSector Resource: Health and Family welfare;Health and Family welfare;Health and Family welfare;Health and Family welfare;Health and Family welfare;Health and Family welfare\nCDOS State Ministry: International Institute for Population Sciences (IIPS)\nNote:  For all indicators except infant and child mortality rates, figures in ( ) are based on 25-49 unweighted cases and  * denotes percentage not shown based on fewer than 25 unweighted cases. \nFor infant and child mortality indicators, figures in ( ) are based on 250-499 unweighted person years of exposure to the risk of death and * denotes figures not given based on fewer than 250 unweighted person years of exposure to the risk of death.\n\nFor more details please, visit  to URL http://rchiips.org/nfhs/NFHS-5_FCTS/COMPENDIUM/NFHS-5%20State%20Factsheet%20Compendium_Phase-I.pdf  and http://rchiips.org/nfhs/NFHS-5_FCTS/Final%20Compendium%20of%20fact%20sheets_India%20and%2014%20States_UTs%20(Phase-II).pdf',
  'llm_response': '{"title": "Title: All India and State/UT-wise Factsheets of National Family Health Survey (NFHS) - 5, 2019-2021", "keywords": ["india health", "family health", "health survey", "child health", "maternal health", "factsheet", "state data", "national data", "health indicators", "population survey"]}',
  'generated_keywords': '',
  'generated_subject': '',
  'generated_theme': '',
  'justification': '',
  'confidence_score': 0,
  'metadata_gaps': '[]'},
 {'title': 'Sub Divisional Monthly Rainfall from 1901 to 2017',
  'sector': 'Science and Technology;Atmospheric Science;Earth Sciences',
  'metadata_input': 'Title: Sub Divisional Monthly Rainfall from 1901 to 2017\nCatalog Title: Rainfall in India\nMinistry/Department: Ministry of Earth Sciences;India Meteorological Department (IMD);India Meteorological Department (IMD), Pune\nSector: Science and Technology;Atmospheric Science;Earth Sciences\nSector Resource: Earth Sciences;Earth Sciences\nCDOS State Ministry: India Meteorological Department (IMD), Pune\nNote: All values are in MMS; NA: Not Available.',
  'llm_response': '{"Title": "Title: Sub Divisional Monthly Rainfall from 1901 to 2017", "Enhanced Keywords": "rainfall, monthly rainfall, subdivisional rainfall, india rainfall, historical rainfall, weather data, climate data, rainfall trends"}',
  'generated_keywords': '',
  'generated_subject': '',
  'generated_theme': '',
  'justification': '',
  'confidence_score': 0,
  'metadata_gaps': '[]'},
 {'title': 'Wholesale Price Index (Base Year 2011-12) till last financial year',
  'sector': 'Economy;Prices;Finance;Economy',
  'metadata_input': 'Title: Wholesale Price Index (Base Year 2011-12) till last financial year\nCatalog Title: Wholesale Price Index\nMinistry/Department: Ministry of Commerce and Industry;Department for Promotion of industry and Internal Trade;Office of the Economic Adviser\nSector: Economy;Prices;Finance;Economy\nSector Resource: nan\nCDOS State Ministry: Office of the Economic Adviser\nNote: NA: Not Applicable/Available',
  'llm_response': '{"title": ""}',
  'generated_keywords': '',
  'generated_subject': '',
  'generated_theme': '',
  'justification': '',
  'confidence_score': 0,
  'metadata_gaps': '[]'},
 {'title': 'Indian Railways Time Table for trains available for reservation as on 01.11.2017',
  'sector': 'Transport;Railways',
  'metadata_input': 'Title: Indian Railways Time Table for trains available for reservation as on 01.11.2017\nCatalog Title: Indian Railways Train Time Table\nMinistry/Department: Ministry of Railways\nSector: Transport;Railways\nSector Resource: Transport;Railways\nCDOS State Ministry: Ministry of Railways\nNote: nan',
  'llm_response': '{"Title: Indian Railways Time Table for trains available for reservation as on 01.11.2017": ""}',
  'generated_keywords': '',
  'generated_subject': '',
  'generated_theme': '',
  'justification': '',
  'confidence_score': 0,
  'metadata_gaps': '[]'},
 {'title': 'Seasonal and Annual Mean Temperature Series for the period 1901-2021',
  'sector': 'Science and Technology;Earth Sciences',

In [19]:
with open('/home/aakash/NIC/cdl-updated/nic-metadata-cleaning/notebooks/metadata_enrichment_result.json') as f:
    json.dump(results_array, f, indent=2, ensure_ascii=False)

print(f"\n Saved {len(results_array)} results to metadata_enrichment_results.json")

UnsupportedOperation: not writable