In [2]:
import json
from openai import OpenAI
import pandas as pd
from IPython.display import Image, display

In [3]:
import os
import logging
logging.basicConfig(
    format='%(asctime)s : %(levelname)s - %(message)s',
    level=logging.INFO
)
from dotenv import load_dotenv
load_dotenv()

True

In [4]:
OPENAI_API_KEY=os.getenv('OPENAI_API_KEY')

In [5]:
print(OPENAI_API_KEY)

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

In [6]:
client=OpenAI(
    api_key=OPENAI_API_KEY
)

In [7]:
response=client.responses.create(
    model='gpt-5-mini',
    input='Write one sentence bedtime story about Korean 2015 drama series Reply 1988'
)
print(response.output_text)

2025-10-06 15:56:34,791 : INFO - HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"

In the quiet of Ssangmun-dong in 1988, five friends and their loving families curl up beneath twinkling stars, sharing laughter, secret crushes, and comforting memories that promise no matter how far they roam, home will always wait for them.

In [30]:
df=pd.read_csv('/home/prajna/civicdatalab/nic-metadata/nic-metadata-cleaning/data/sample_datasets_metadata/nic_sample_dataset.csv')
df.head()

,title,resource_category,catalog_title,govt_type,ministry_department,state_department,published_date,changed,created,sector,...,field_high_value_dataset,field_show_export,cdos_state_ministry,is_rated,external_api_reference,note,node_alias,ogdp_download_count,ogdp_view_count,domain
0,"Area weighted monthly, seasonal and annual rai...",Dataset,Rainfall in India,Central,Ministry of Earth Sciences;India Meteorologica...,NaN,30/3/2017,10/12/2021,2/1/2017,Science and Technology;Atmospheric Science;Ear...,...,0,True,"India Meteorological Department (IMD), Pune",1,NaN,Monthly rainfall series contains monthly rainf...,/resource/area-weighted-monthly-seasonal-and-a...,1380,1782,data.gov.in
1,Monthly mean maximum & minimum temperature and...,Dataset,Climatology data of Important Cities,Central,Ministry of Earth Sciences;India Meteorologica...,NaN,30/9/2016,10/12/2021,26/10/2015,Science and Technology;Earth Sciences,...,0,True,"India Meteorological Department (IMD), Pune",1,NaN,NaN,/resource/monthly-mean-maximum-minimum-tempera...,1320,5345,data.gov.in
2,Monthly Consumption of Petroleum Products,Dataset,Consumption of Petroleum Products,Central,Ministry of Petroleum and Natural Gas;Petroleu...,NaN,19/5/2023,27/6/2025,19/5/2023,Power and Energy,...,1,True,Petroleum Planning & Analysis Cell (PPAC),0,7492382.0,i) Part of the data may be provisional. For de...,/resource/monthly-consumption-petroleum-products,1264,1010,data.gov.in
3,"State-wise Population, Decadal Population Grow...",Dataset,Rural Health Statistics - 2015,Central,Ministry of Health and Family Welfare;Departme...,NaN,13/7/2016,10/12/2021,12/7/2016,Health and Family welfare;Family Welfare;Health,...,0,True,Department of Health and Family Welfare,1,NaN,For Manipur: Updated population of Manipur as ...,/resource/state-wise-population-decadal-popula...,1261,747,data.gov.in
4,District Wise Total MSME Registered Manufactu...,Dataset,Udyog Aadhaar Memorandum ( MSME Registration ),Central,"Ministry of Micro, Small and Medium Enterprises",NaN,24/7/2019,7/8/2019,23/7/2019,Medium;Micro;Small Scale,...,0,True,"Ministry of Micro, Small and Medium Enterprises",1,6667162.0,NaN,/resource/district-wise-total-msme-registered-...,1250,2092,data.gov.in

In [15]:
categorize_system_prompt='''
# System Prompt: Metadata Keyword Generation for Open Government Data

## Role
You are an expert metadata curator specializing in government open data standards including Dublin Core, DCAT v3, and data.gov.in specifications. Your task is to generate high-quality keywords and metadata classifications from dataset resource metadata. 
Some fields may contain semicolon separated values. Extract them individually to run processing. Also if similar semicolon separated values arise
use your best judgment to fix them and run downstream processing.

## Input Format
You will receive CSV rows with the following columns:
- title: Dataset resource title
- catalog_title: Catalog-level description
- sector: Top-level sector tags (semicolon-separated)
- sector_resource: Resource-level granular sector tags (semicolon-separated, may be null)
- ministry_department: Governing ministry/department (semicolon-separated)
- state_department: State-level department (may be null)
- note: Additional notes about the dataset (may be null)
- frequency: Update frequency (e.g., Daily, Monthly)
- granularity: Data granularity level
- govt_type: Government level (Central/State)
- Other technical fields for context

## Task Requirements

### 1. Generate Keywords (dcat:keyword)
Extract 5-10 free-text keywords that:
- Represent the core subject matter of the dataset
- Include domain-specific terminology
- Cover geographical scope if applicable
- Include temporal aspects if relevant
- Use both broad and specific terms
- Are actionable for search and discovery

**Extraction Logic:**
- Parse semicolon-separated values in sector, sector_resource, ministry_department
- Use your best judgment to create keywords from the existing metadata fields.
- You may come up with assumptions and best case tagging as well.
- Some fields may contain semicolon separated values. Extract them individually to run processing.

### 2. Generate Subject (dct:subject)
Create 3-5 subject classifications that:
- Represent topical categories at a higher abstraction level than keywords
- Follow thematic organization principles
- Can be used for faceted navigation
- Are consistent with Dublin Core subject recommendations

### 3. Generate Theme (dcat:theme)
Identify 2-4 high-level thematic categories that:
- Represent broad policy/domain areas
- Align with government data categorization schemes
- Enable cross-dataset discovery
- Map to standard taxonomies (e.g., COFOG - Classification of Functions of Government)

### 4. Provide Justification
For each generated field, explain:
- Which source columns were used
- What extraction/normalization rules were applied
- Why specific terms were selected or excluded
- Any ambiguities or assumptions made

### 5. Confidence Scoring
Assign confidence scores (0.0 to 1.0) based on:
- **1.0**: All source fields present with clear, unambiguous information
- **0.9**: Minor ambiguity or one secondary field missing
- **0.8**: Some interpretation required, multiple valid classifications possible
- **0.7**: Significant missing information (e.g., note, sector_resource null)
- **0.6**: Sparse metadata, heavy inference required
- **<0.6**: Insufficient metadata for reliable classification

## Output Format
Return a valid JSON with the following additional keys:
- generated_keywords: Comma-separated list of keywords
- generated_subject: Comma-separated list of subjects
- generated_theme: Comma-separated list of themes
- justification: Detailed reasoning for selections
- confidence_score: Float value 0.0-1.0
- metadata_gaps: Fields that were null/missing affecting quality


## Quality Guidelines

### Keyword Quality Rules:
1. Avoid redundancy with title terms unless critical
2. Include Hindi/regional language terms where applicable to Indian context
3. Use lowercase unless proper nouns
4. Separate compound concepts (e.g., "price data" → "prices", "market data")
5. Use your best judgment to structure the output JSON shape. 


### Subject Quality Rules:
1. Use established vocabularies when possible (Library of Congress, AGROVOC for agriculture)
2. Balance specificity and generality
3. Avoid overlapping with theme categories

### Theme Quality Rules:
1. Use government domain classifications (Agriculture, Health, Finance, etc.)
2. Limit to 2-4 to maintain meaningful categorization
3. Consider cross-cutting themes (e.g., "Public Services", "Economic Development")

## Special Handling

### Ministry/Department Processing:
- Extract parent ministry from hierarchical strings
- Use abbreviated forms if widely recognized (e.g., MoA for Ministry of Agriculture)
- Include as contextual keywords only if domain-relevant

### Null Field Handling:
- If sector_resource is null, rely heavily on sector and title
- If note is null, reduce confidence score by 0.1
- If state_department is null and govt_type is "Central", this is expected

### Frequency/Granularity Integration:
- Include temporal keywords for real-time/daily data (e.g., "daily", "real-time monitoring")
- Add "historical" for archived datasets
- Include "time-series" for temporally granular data

## Example Processing Logic

**Input:**
```
title: "Variety-wise Daily Market Prices Data of Commodity"
sector: "Agriculture;Agricultural Marketing"
ministry_department: "Ministry of Agriculture and Farmers Welfare;Department of Agriculture..."
frequency: "Daily"
```

**Processing Steps:**
1. Parse sector → ["Agriculture", "Agricultural Marketing"]
2. Extract from title → "variety", "market prices", "commodity"
3. Identify domain term → "mandi" (implied from catalog_title context)
4. Add temporal → "daily prices"
5. Add format → "price data"

**Output:**
- Keywords: agricultural commodities, market prices, mandi prices, daily data, crop varieties, agricultural marketing, price monitoring
- Subject: Agricultural Economics, Market Information Systems, Commodity Trading
- Theme: Agriculture, Economic Development
- Confidence: 0.85 (sector_resource null, but strong other fields)

## Constraints
- Maximum 10 keywords per resource
- Maximum 5 subjects per resource
- Maximum 4 themes per resource
- All outputs in English (add transliterated terms where culturally relevant)
- Maintain data.gov.in vocabulary consistency where applicable

## Error Handling
If critical fields (title, sector) are missing or malformed:
- Set confidence_score to 0.3
- Flag in metadata_gaps column
- Provide best-effort keywords from available fields
- Add justification note: "INSUFFICIENT_METADATA"
- If a column contains semicolon (;) separated values, first extract each value and then run processing.

'''

In [21]:
def get_keywords(metadata_content):
    response=client.chat.completions.create(
         model='gpt-5-mini',
         temperature=1,
         response_format={
             "type":"json_object"
         },
         messages=[
              {
                  "role":"system",
                  "content":categorize_system_prompt
              },
              {
                  "role":"user",
                  "content":metadata_content
              }
         ],

    )
    return response.choices[0].message.content

In [17]:
df=pd.read_csv("/home/prajna/civicdatalab/nic-metadata/nic-metadata-cleaning/data/sample_datasets_metadata/nic_sample_dataset.csv")
df.head()

,title,resource_category,catalog_title,govt_type,ministry_department,state_department,published_date,changed,created,sector,...,field_high_value_dataset,field_show_export,cdos_state_ministry,is_rated,external_api_reference,note,node_alias,ogdp_download_count,ogdp_view_count,domain
0,"Area weighted monthly, seasonal and annual rai...",Dataset,Rainfall in India,Central,Ministry of Earth Sciences;India Meteorologica...,NaN,30/3/2017,10/12/2021,2/1/2017,Science and Technology;Atmospheric Science;Ear...,...,0,True,"India Meteorological Department (IMD), Pune",1,NaN,Monthly rainfall series contains monthly rainf...,/resource/area-weighted-monthly-seasonal-and-a...,1380,1782,data.gov.in
1,Monthly mean maximum & minimum temperature and...,Dataset,Climatology data of Important Cities,Central,Ministry of Earth Sciences;India Meteorologica...,NaN,30/9/2016,10/12/2021,26/10/2015,Science and Technology;Earth Sciences,...,0,True,"India Meteorological Department (IMD), Pune",1,NaN,NaN,/resource/monthly-mean-maximum-minimum-tempera...,1320,5345,data.gov.in
2,Monthly Consumption of Petroleum Products,Dataset,Consumption of Petroleum Products,Central,Ministry of Petroleum and Natural Gas;Petroleu...,NaN,19/5/2023,27/6/2025,19/5/2023,Power and Energy,...,1,True,Petroleum Planning & Analysis Cell (PPAC),0,7492382.0,i) Part of the data may be provisional. For de...,/resource/monthly-consumption-petroleum-products,1264,1010,data.gov.in
3,"State-wise Population, Decadal Population Grow...",Dataset,Rural Health Statistics - 2015,Central,Ministry of Health and Family Welfare;Departme...,NaN,13/7/2016,10/12/2021,12/7/2016,Health and Family welfare;Family Welfare;Health,...,0,True,Department of Health and Family Welfare,1,NaN,For Manipur: Updated population of Manipur as ...,/resource/state-wise-population-decadal-popula...,1261,747,data.gov.in
4,District Wise Total MSME Registered Manufactu...,Dataset,Udyog Aadhaar Memorandum ( MSME Registration ),Central,"Ministry of Micro, Small and Medium Enterprises",NaN,24/7/2019,7/8/2019,23/7/2019,Medium;Micro;Small Scale,...,0,True,"Ministry of Micro, Small and Medium Enterprises",1,6667162.0,NaN,/resource/district-wise-total-msme-registered-...,1250,2092,data.gov.in

In [14]:
import time

In [29]:
results_array = []

for _, row in df[:5].iterrows():
    title = row.get("title", "")
    catalog_title = row.get("catalog_title", "")
    ministry_department = row.get("ministry_department", "")
    sector = row.get("sector", "")
    sector_resource = row.get("sector_resource", "")
    cdos_state_ministry = row.get("cdos_state_ministry", "")
    note = row.get("note", "")
    
    metadata_content = f'''
Title: {title}
Catalog Title: {catalog_title}
Ministry/Department: {ministry_department}
Sector: {sector}
Sector Resource: {sector_resource}
CDOS State Ministry: {cdos_state_ministry}
Note: {note}
    '''
    
    result = get_keywords(metadata_content)
    logging.info(f"Result is {result}")
    # Store in JSON object
    # result_obj = {
    #     "title": title,
    #     "sector": sector,
    #     "metadata_input": metadata_content,
    #     "llm_response": result,
    #     "generated_keywords": result.get("generated_keywords", ""),
    #     "generated_subject": result.get("generated_subject", ""),
    #     "generated_theme": result.get("generated_theme", ""),
    #     "justification": result.get("justification", ""),
    #     "confidence_score": result.get("confidence_score", 0),
    #     "metadata_gaps": result.get("metadata_gaps", "")
    # }
    
    results_array.append(result)
    
    print(f"TITLE: {title}\nSECTOR: {sector}\n\nRESULT: {result}")
    print("\n\n----------------------------\n\n")
    time.sleep(1)

2025-10-06 17:28:25,169 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-06 17:28:25,180 : INFO - Result is {
  "generated_keywords": "rainfall, precipitation, area-weighted rainfall, monthly rainfall, seasonal rainfall, annual rainfall, meteorological subdivisions, time-series, historical (1901-2015), imd (india meteorological department)",
  "generated_subject": "climatology, meteorological observations, hydrometeorology, climate time-series data",
  "generated_theme": "environment and climate, science and technology, water resources",
  "justification": "Source fields used: title, catalog_title, sector, sector_resource, ministry_department, CDOS State Ministry, note.\n\nExtraction & normalization rules applied:\n- Parsed semicolon-separated fields in sector and ministry_department into individual tokens (e.g., 'Science and Technology', 'Atmospheric Science', 'Earth Sciences'; 'Ministry of Earth Sciences', 'India Meteorological Department (IMD)').\n- Normalized all keywords/subjects/themes to lowercase per guidelines and avoided extraneous punctuation.\n- Retained core terms from the title (rainfall, monthly, seasonal, annual, area-weighted, meteorological subdivisions, 1901-2015) because they are central to discovery (rule allows title terms when critical).\n- Converted compound concepts to separate searchable phrases where useful (e.g., 'time-series' to represent temporal dataset nature).\n- Included an institutional keyword 'imd (india meteorological department)' because ministry/department fields strongly indicate the originating agency and this aids provenance-based discovery.\n- Added a concise historical temporal keyword 'historical (1901-2015)' to capture the long time-span and support temporal search facets.\n- Did not add assumptions-only terms (e.g., 'monsoon') because the metadata does not explicitly say monsoon-season breakdown; avoided over-assertion.\n- Included transliteration implicitly by keeping institutional acronym 'imd' (widely recognized in India); did not add Hindi script, but could add transliterated common term 'varsha' if required by local-language search—left out to keep keywords directly actionable in English.\n\nWhy specific terms were selected or excluded:\n- 'rainfall' and 'precipitation' included to cover both common-language and domain terminology.\n- 'area-weighted rainfall' preserved as it is a specific methodological attribute from the title and important for users assessing dataset methodology.\n- Temporal granularity keywords ('monthly', 'seasonal', 'annual', 'time-series', 'historical (1901-2015)') selected from title and note to indicate update cadence and long-term coverage.\n- 'meteorological subdivisions' included because title explicitly states data is provided for 36 such subdivisions (important spatial granularity).\n- 'imd (india meteorological department)' included from ministry_department for provenance and search filtering.\n- Excluded unit 'mm' as a separate keyword because unit is less useful for topical discovery and is redundant with 'rainfall' and dataset documentation; could be added in metadata fields instead.\n\nAmbiguities and assumptions:\n- The dataset covers 1901-2015 (title). The note clarifies periods for delayed vs real-time computation (1901-2012 delayed mode; 2013-2015 real-time). We treated the full range as historical time-series and added 'historical (1901-2015)'.\n- Frequency/granularity fields were not supplied explicitly (e.g., 'frequency' like monthly in a metadata column). We inferred temporal granularity (monthly/seasonal/annual) from the title and note.\n- Government level (central vs state) not specified explicitly; because the ministry is a central body (Ministry of Earth Sciences / IMD) we assumed central-level provenance but did not add 'central' as a keyword to avoid over-tagging.\n- Did not add subject terms like 'agriculture' or 'disaster management' because sector fields focused on atmospheric/earth sciences; those cross-uses are possible but would be speculative.\n\nConformity with rules:\n- Kept keywords to a maximum of 10 and subjects to 4; themes limited to 3.\n- Used lowercasing and concise phrases; retained domain-specific terminology and institutional context.",
  "confidence_score": 0.9,
  "metadata_gaps": [
    "frequency (update cadence) - not provided as separate field",
    "granularity (explicit spatial/temporal granularity field) - not provided",
    "govt_type (central/state) - not explicitly provided"
  ]
}

TITLE: Area weighted monthly, seasonal and annual rainfall ( in mm) for 36 meteorological subdivisions from 1901-2015
SECTOR: Science and Technology;Atmospheric Science;Earth Sciences

RESULT: {
  "generated_keywords": "rainfall, precipitation, area-weighted rainfall, monthly rainfall, seasonal rainfall, annual rainfall, meteorological subdivisions, time-series, historical (1901-2015), imd (india meteorological department)",
  "generated_subject": "climatology, meteorological observations, hydrometeorology, climate time-series data",
  "generated_theme": "environment and climate, science and technology, water resources",
  "justification": "Source fields used: title, catalog_title, sector, sector_resource, ministry_department, CDOS State Ministry, note.\n\nExtraction & normalization rules applied:\n- Parsed semicolon-separated fields in sector and ministry_department into individual tokens (e.g., 'Science and Technology', 'Atmospheric Science', 'Earth Sciences'; 'Ministry of Earth Sciences', 'India Meteorological Department (IMD)').\n- Normalized all keywords/subjects/themes to lowercase per guidelines and avoided extraneous punctuation.\n- Retained core terms from the title (rainfall, monthly, seasonal, annual, area-weighted, meteorological subdivisions, 1901-2015) because they are central to discovery (rule allows title terms when critical).\n- Converted compound concepts to separate searchable phrases where useful (e.g., 'time-series' to represent temporal dataset nature).\n- Included an institutional keyword 'imd (india meteorological department)' because ministry/department fields strongly indicate the originating agency and this aids provenance-based discovery.\n- Added a concise historical temporal keyword 'historical (1901-2015)' to capture the long time-span and support temporal search facets.\n- Did not add assumptions-only terms (e.g., 'monsoon') because the metadata does not explicitly say monsoon-season breakdown; avoided over-assertion.\n- Included transliteration implicitly by keeping institutional acronym 'imd' (widely recognized in India); did not add Hindi script, but could add transliterated common term 'varsha' if required by local-language search—left out to keep keywords directly actionable in English.\n\nWhy specific terms were selected or excluded:\n- 'rainfall' and 'precipitation' included to cover both common-language and domain terminology.\n- 'area-weighted rainfall' preserved as it is a specific methodological attribute from the title and important for users assessing dataset methodology.\n- Temporal granularity keywords ('monthly', 'seasonal', 'annual', 'time-series', 'historical (1901-2015)') selected from title and note to indicate update cadence and long-term coverage.\n- 'meteorological subdivisions' included because title explicitly states data is provided for 36 such subdivisions (important spatial granularity).\n- 'imd (india meteorological department)' included from ministry_department for provenance and search filtering.\n- Excluded unit 'mm' as a separate keyword because unit is less useful for topical discovery and is redundant with 'rainfall' and dataset documentation; could be added in metadata fields instead.\n\nAmbiguities and assumptions:\n- The dataset covers 1901-2015 (title). The note clarifies periods for delayed vs real-time computation (1901-2012 delayed mode; 2013-2015 real-time). We treated the full range as historical time-series and added 'historical (1901-2015)'.\n- Frequency/granularity fields were not supplied explicitly (e.g., 'frequency' like monthly in a metadata column). We inferred temporal granularity (monthly/seasonal/annual) from the title and note.\n- Government level (central vs state) not specified explicitly; because the ministry is a central body (Ministry of Earth Sciences / IMD) we assumed central-level provenance but did not add 'central' as a keyword to avoid over-tagging.\n- Did not add subject terms like 'agriculture' or 'disaster management' because sector fields focused on atmospheric/earth sciences; those cross-uses are possible but would be speculative.\n\nConformity with rules:\n- Kept keywords to a maximum of 10 and subjects to 4; themes limited to 3.\n- Used lowercasing and concise phrases; retained domain-specific terminology and institutional context.",
  "confidence_score": 0.9,
  "metadata_gaps": [
    "frequency (update cadence) - not provided as separate field",
    "granularity (explicit spatial/temporal granularity field) - not provided",
    "govt_type (central/state) - not explicitly provided"
  ]
}


----------------------------

2025-10-06 17:28:58,686 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-06 17:28:58,689 : INFO - Result is {
  "generated_keywords": "monthly mean temperatures, maximum temperature, minimum temperature, total monthly rainfall, climate normals (1901-2000), historical time-series, city-level climatology, IMD, Ministry of Earth Sciences, mausam",
  "generated_subject": "Climatology, Meteorology, Historical climate records, Urban climatology",
  "generated_theme": "Environment and Climate, Science & Technology, Meteorological Services",
  "justification": "Source fields used:\n- title: primary source for core variables (monthly mean maximum & minimum temperature, total rainfall), temporal scope (monthly), and baseline period (1901-2000).\n- catalog_title: provided geographical granularity hint ('Important Cities') → used to derive city-level / urban climatology subject and keyword.\n- ministry_department: parsed semicolon-separated values into ['Ministry of Earth Sciences', 'India Meteorological Department (IMD)', 'India Meteorological Department (IMD), Pune'] → used to include IMD and Ministry as contextual/authority keywords and to map to 'Meteorological Services' theme.\n- sector and sector_resource: both contain 'Science and Technology' and 'Earth Sciences' → used to justify Science & Technology and Environment/Climate themes and to emphasize climatology/meteorology subjects.\n\nExtraction and normalization rules applied:\n- Semicolon-separated ministry_department values were split and normalized (duplicate IMD entries collapsed to single 'IMD' token). Parent ministry normalized to 'Ministry of Earth Sciences' (abbreviation MoES not used as primary keyword to keep clarity, but ministry included as proper noun keyword).\n- Title phrases were converted to actionable keywords: 'monthly mean maximum & minimum temperature' → separated into 'monthly mean temperatures', 'maximum temperature', 'minimum temperature'. 'total rainfall' → 'total monthly rainfall'.\n- Temporal scope '1901-2000' normalized into 'climate normals (1901-2000)' and 'historical time-series' to capture both the idea of reference-period normals and archived time-series.\n- Catalog title 'Climatology data of Important Cities' produced 'city-level climatology' and 'urban climatology' as subject-level concepts.\n- Lowercase used for general terms; proper nouns retained capitalization (IMD, Ministry of Earth Sciences) following keyword rules.\n- Included a transliterated Hindi term 'mausam' to aid regional discovery per quality guidelines.\n\nWhy specific terms were selected or excluded:\n- Chosen keywords prioritize searchability: variable names, temporal descriptors, baseline period, provider (IMD), and geographic granularity (city-level).\n- Avoided redundant keywords that repeat title wording verbatim; instead split compound concepts (e.g., temperatures vs max/min) per rules.\n- Excluded terms unrelated to dataset (e.g., disaster management) because no indication in source fields that data is for that purpose.\n\nAmbiguities and assumptions:\n- Frequency/granularity fields are missing; title says 'Monthly', so 'monthly' and 'monthly mean' were inferred from title. If frequency metadata contradicted title, some keywords might need adjustment.\n- 'Important Cities' is ambiguous about exact geographic scope (national, regional, list of cities). Assumed city-level/urban scope rather than station-level or statewide aggregation.\n- Ministry/department entries included an IMD Pune mention; assumed this indicates dataset custodianship by IMD (national) rather than being limited to Pune.\n- Note field is null (nan), reducing ability to capture intended use, license, or additional variables; this lowered confidence.\n\nCompliance with task constraints:\n- Keywords limited to 10 items, separated compound concepts, included a regional (Hindi) term, and kept proper nouns capitalized.\n- Subjects are higher-level and non-overlapping with themes (subjects focus on scientific topics; themes focus on government domain areas).",
  "confidence_score": 0.8,
  "metadata_gaps": [
    "note",
    "frequency",
    "granularity",
    "govt_type"
  ]
}

TITLE: Monthly mean maximum & minimum temperature and total rainfall based upon 1901-2000 data
SECTOR: Science and Technology;Earth Sciences

RESULT: {
  "generated_keywords": "monthly mean temperatures, maximum temperature, minimum temperature, total monthly rainfall, climate normals (1901-2000), historical time-series, city-level climatology, IMD, Ministry of Earth Sciences, mausam",
  "generated_subject": "Climatology, Meteorology, Historical climate records, Urban climatology",
  "generated_theme": "Environment and Climate, Science & Technology, Meteorological Services",
  "justification": "Source fields used:\n- title: primary source for core variables (monthly mean maximum & minimum temperature, total rainfall), temporal scope (monthly), and baseline period (1901-2000).\n- catalog_title: provided geographical granularity hint ('Important Cities') → used to derive city-level / urban climatology subject and keyword.\n- ministry_department: parsed semicolon-separated values into ['Ministry of Earth Sciences', 'India Meteorological Department (IMD)', 'India Meteorological Department (IMD), Pune'] → used to include IMD and Ministry as contextual/authority keywords and to map to 'Meteorological Services' theme.\n- sector and sector_resource: both contain 'Science and Technology' and 'Earth Sciences' → used to justify Science & Technology and Environment/Climate themes and to emphasize climatology/meteorology subjects.\n\nExtraction and normalization rules applied:\n- Semicolon-separated ministry_department values were split and normalized (duplicate IMD entries collapsed to single 'IMD' token). Parent ministry normalized to 'Ministry of Earth Sciences' (abbreviation MoES not used as primary keyword to keep clarity, but ministry included as proper noun keyword).\n- Title phrases were converted to actionable keywords: 'monthly mean maximum & minimum temperature' → separated into 'monthly mean temperatures', 'maximum temperature', 'minimum temperature'. 'total rainfall' → 'total monthly rainfall'.\n- Temporal scope '1901-2000' normalized into 'climate normals (1901-2000)' and 'historical time-series' to capture both the idea of reference-period normals and archived time-series.\n- Catalog title 'Climatology data of Important Cities' produced 'city-level climatology' and 'urban climatology' as subject-level concepts.\n- Lowercase used for general terms; proper nouns retained capitalization (IMD, Ministry of Earth Sciences) following keyword rules.\n- Included a transliterated Hindi term 'mausam' to aid regional discovery per quality guidelines.\n\nWhy specific terms were selected or excluded:\n- Chosen keywords prioritize searchability: variable names, temporal descriptors, baseline period, provider (IMD), and geographic granularity (city-level).\n- Avoided redundant keywords that repeat title wording verbatim; instead split compound concepts (e.g., temperatures vs max/min) per rules.\n- Excluded terms unrelated to dataset (e.g., disaster management) because no indication in source fields that data is for that purpose.\n\nAmbiguities and assumptions:\n- Frequency/granularity fields are missing; title says 'Monthly', so 'monthly' and 'monthly mean' were inferred from title. If frequency metadata contradicted title, some keywords might need adjustment.\n- 'Important Cities' is ambiguous about exact geographic scope (national, regional, list of cities). Assumed city-level/urban scope rather than station-level or statewide aggregation.\n- Ministry/department entries included an IMD Pune mention; assumed this indicates dataset custodianship by IMD (national) rather than being limited to Pune.\n- Note field is null (nan), reducing ability to capture intended use, license, or additional variables; this lowered confidence.\n\nCompliance with task constraints:\n- Keywords limited to 10 items, separated compound concepts, included a regional (Hindi) term, and kept proper nouns capitalized.\n- Subjects are higher-level and non-overlapping with themes (subjects focus on scientific topics; themes focus on government domain areas).",
  "confidence_score": 0.8,
  "metadata_gaps": [
    "note",
    "frequency",
    "granularity",
    "govt_type"
  ]
}


----------------------------

2025-10-06 17:29:37,389 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-06 17:29:37,400 : INFO - Result is {
  "generated_keywords": "petroleum products, fuel consumption, monthly consumption, monthly time-series, energy statistics, oil demand, PPAC, DGCIS, provisional data, india",
  "generated_subject": "Energy consumption, Petroleum industry statistics, Economic indicators, Commodity trade statistics",
  "generated_theme": "Energy, Industry and Commerce, Economic Development",
  "justification": "Source fields used: title (Monthly Consumption of Petroleum Products), catalog_title (Consumption of Petroleum Products), sector (Power and Energy), ministry_department (Ministry of Petroleum and Natural Gas; Petroleum Planning & Analysis Cell (PPAC)), CDOS State Ministry (PPAC), note (sources: Oil Companies, DGCIS & online SEZ data; provisional data). Extraction and normalization rules applied: semicolon-separated ministry_department values parsed to extract parent ministry and agency (Ministry of Petroleum and Natural Gas; PPAC). sector_resource was 'nan' and treated as missing. Title text provided clear temporal granularity ('Monthly') so 'monthly' and 'monthly time-series' keywords were added even though the dedicated frequency column was absent. Note was parsed to identify data provenance (DGCIS) and provisional status. Selection rationale for keywords: - 'petroleum products' and 'fuel consumption' are direct topic matches from title/catalog_title. - 'monthly consumption' and 'monthly time-series' reflect temporal granularity explicit in title. - 'energy statistics' and 'oil demand' are domain-specific, actionable discovery terms (used by analysts/searches). - 'PPAC' and 'DGCIS' included as contextual/source organisation keywords (PPAC is primary custodian; DGCIS is a named source in notes). - 'provisional data' included because the note explicitly warns about provisional values. - 'india' inferred from the presence of the central Ministry and PPAC (central-national dataset), added for geographic discovery. Subjects: chosen at a higher abstraction level to support faceted navigation — 'Energy consumption' (broad sectoral subject), 'Petroleum industry statistics' (sector-specific statistics), 'Economic indicators' (consumption as an economic measure), and 'Commodity trade statistics' (DGCIS involvement implies trade/commodity data). Themes: aligned to government domain categories — 'Energy' (primary), 'Industry and Commerce' (covers oil industry and trade aspects), and 'Economic Development' (consumption and demand influence macroeconomic planning). Exclusions and assumptions: - sector_resource was missing so no finer-grained sector tags were derived. - State-level granularity or state department tags were not assumed; central ministry implies national scope (hence 'india' used), but no state-specific keywords were added. - Frequency column was missing but title contains 'Monthly' — frequency was inferred for keywords but the missing dedicated field is reported in metadata_gaps. - Hindi/regional transliterations were considered (e.g., 'petroleum upbhog') but omitted to avoid introducing noisy transliterations; they can be added on request. - No assumptions were made about commodity breakdown (diesel, petrol, ATF, etc.) because not provided. Ambiguities: - Exact granularity (national vs. state-level vs. company-level breakdown) is not stated; assumed national-level summary due to central ministry ownership. - The note indicates some data may be provisional and that multiple sources feed the dataset; this implies mixed completeness across series but exact columns affected are unknown.",
  "confidence_score": 0.8,
  "metadata_gaps": [
    "sector_resource",
    "frequency (explicit field missing; inferred from title)",
    "granularity",
    "govt_type"
  ]
}

TITLE: Monthly Consumption of Petroleum Products
SECTOR: Power and Energy

RESULT: {
  "generated_keywords": "petroleum products, fuel consumption, monthly consumption, monthly time-series, energy statistics, oil demand, PPAC, DGCIS, provisional data, india",
  "generated_subject": "Energy consumption, Petroleum industry statistics, Economic indicators, Commodity trade statistics",
  "generated_theme": "Energy, Industry and Commerce, Economic Development",
  "justification": "Source fields used: title (Monthly Consumption of Petroleum Products), catalog_title (Consumption of Petroleum Products), sector (Power and Energy), ministry_department (Ministry of Petroleum and Natural Gas; Petroleum Planning & Analysis Cell (PPAC)), CDOS State Ministry (PPAC), note (sources: Oil Companies, DGCIS & online SEZ data; provisional data). Extraction and normalization rules applied: semicolon-separated ministry_department values parsed to extract parent ministry and agency (Ministry of Petroleum and Natural Gas; PPAC). sector_resource was 'nan' and treated as missing. Title text provided clear temporal granularity ('Monthly') so 'monthly' and 'monthly time-series' keywords were added even though the dedicated frequency column was absent. Note was parsed to identify data provenance (DGCIS) and provisional status. Selection rationale for keywords: - 'petroleum products' and 'fuel consumption' are direct topic matches from title/catalog_title. - 'monthly consumption' and 'monthly time-series' reflect temporal granularity explicit in title. - 'energy statistics' and 'oil demand' are domain-specific, actionable discovery terms (used by analysts/searches). - 'PPAC' and 'DGCIS' included as contextual/source organisation keywords (PPAC is primary custodian; DGCIS is a named source in notes). - 'provisional data' included because the note explicitly warns about provisional values. - 'india' inferred from the presence of the central Ministry and PPAC (central-national dataset), added for geographic discovery. Subjects: chosen at a higher abstraction level to support faceted navigation — 'Energy consumption' (broad sectoral subject), 'Petroleum industry statistics' (sector-specific statistics), 'Economic indicators' (consumption as an economic measure), and 'Commodity trade statistics' (DGCIS involvement implies trade/commodity data). Themes: aligned to government domain categories — 'Energy' (primary), 'Industry and Commerce' (covers oil industry and trade aspects), and 'Economic Development' (consumption and demand influence macroeconomic planning). Exclusions and assumptions: - sector_resource was missing so no finer-grained sector tags were derived. - State-level granularity or state department tags were not assumed; central ministry implies national scope (hence 'india' used), but no state-specific keywords were added. - Frequency column was missing but title contains 'Monthly' — frequency was inferred for keywords but the missing dedicated field is reported in metadata_gaps. - Hindi/regional transliterations were considered (e.g., 'petroleum upbhog') but omitted to avoid introducing noisy transliterations; they can be added on request. - No assumptions were made about commodity breakdown (diesel, petrol, ATF, etc.) because not provided. Ambiguities: - Exact granularity (national vs. state-level vs. company-level breakdown) is not stated; assumed national-level summary due to central ministry ownership. - The note indicates some data may be provisional and that multiple sources feed the dataset; this implies mixed completeness across series but exact columns affected are unknown.",
  "confidence_score": 0.8,
  "metadata_gaps": [
    "sector_resource",
    "frequency (explicit field missing; inferred from title)",
    "granularity",
    "govt_type"
  ]
}


----------------------------

2025-10-06 17:30:18,657 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-06 17:30:18,664 : INFO - Result is {
  "generated_keywords": "population, population density, decadal population growth rate, state-wise data, census 2011, demographic indicators, Ministry of Health and Family Welfare (MoHFW), jan sankhya",
  "generated_subject": "Demography, Population studies, Census data, Public health statistics",
  "generated_theme": "Health, Population & vital statistics, Government statistics",
  "justification": "Source fields used: title, catalog_title, ministry_department, sector, sector_resource, note.\n\nExtraction and normalization rules applied:\n- Parsed semicolon-separated values in sector and ministry_department to confirm domain (Health; Family Welfare).\n- Extracted core measures from the title: 'population', 'decadal population growth rate', and 'population density'. Normalized 'decadal population growth rate' to a concise keyword and to the subject 'Population studies'.\n- Identified geographic granularity from the title term 'State-wise' and normalized it to 'state-wise data' and inferred national scope (states of India) because the note references Census of India and specific states (Manipur, Andhra Pradesh, Telangana).\n- Temporal aspect taken directly from the title: '2011' → represented as 'census 2011' in keywords to aid discovery by year and data source.\n- Included the governing body as a contextual keyword: Ministry of Health and Family Welfare (MoHFW) — extracted from ministry_department; abbreviated form included per special handling rules.\n- Added a Hindi transliteration keyword 'jan sankhya' to improve local-language discoverability (per keyword quality rules).\n- Avoided adding 'rural' as a keyword despite the catalog_title being 'Rural Health Statistics - 2015' because the resource title does not explicitly say the data are limited to rural population; catalog inclusion was used only as contextual support (not assumed as data scope).\n- Note content (source: Population Census of India; Manipur update; Andhra Pradesh and Telangana data collected from states) informed inclusion of 'census 2011' and supports the inference of state-level (India) coverage.\n\nWhy terms were selected or excluded:\n- Selected: core demographic measures (population, density, decadal growth) because they are the primary variables in the title and high-value search terms.\n- Selected: 'state-wise data' to reflect granularity; 'census 2011' and 'demographic indicators' because the note explicitly cites Census of India and contextualizes the dataset as demographic statistics useful for health planning.\n- Selected: ministry keyword (MoHFW) because the resource is governed by health/family welfare departments and this aids domain-specific discovery.\n- Selected: 'jan sankhya' as a transliterated local-language term to improve discoverability in Indian contexts.\n- Excluded: 'rural' as a definitive keyword because title does not state rural-only; catalog title suggests association but does not confirm dataset scope. Also avoided redundant repeat of title phrasing beyond essential normalized keywords.\n\nAmbiguities and assumptions:\n- Assumed national/state-level coverage (states of India) because the title says 'State-wise' and the note references Census of India and specific state updates, but the exact list of states/UTs covered is not provided.\n- Did not assume dataset frequency or time-series beyond the 2011 census year because no frequency/granularity fields were provided.\n- Assumed dataset is intended for public health/statistics use given catalog title and ministry, but did not recast the dataset as exclusively 'rural' for reasons noted above.\n\nConfidence rationale: see confidence_score and metadata_gaps.",
  "confidence_score": 0.8,
  "metadata_gaps": [
    "frequency",
    "granularity",
    "govt_type",
    "state_department (explicit field)"
  ]
}

TITLE: State-wise Population, Decadal Population Growth Rate and Population Density - 2011
SECTOR: Health and Family welfare;Family Welfare;Health

RESULT: {
  "generated_keywords": "population, population density, decadal population growth rate, state-wise data, census 2011, demographic indicators, Ministry of Health and Family Welfare (MoHFW), jan sankhya",
  "generated_subject": "Demography, Population studies, Census data, Public health statistics",
  "generated_theme": "Health, Population & vital statistics, Government statistics",
  "justification": "Source fields used: title, catalog_title, ministry_department, sector, sector_resource, note.\n\nExtraction and normalization rules applied:\n- Parsed semicolon-separated values in sector and ministry_department to confirm domain (Health; Family Welfare).\n- Extracted core measures from the title: 'population', 'decadal population growth rate', and 'population density'. Normalized 'decadal population growth rate' to a concise keyword and to the subject 'Population studies'.\n- Identified geographic granularity from the title term 'State-wise' and normalized it to 'state-wise data' and inferred national scope (states of India) because the note references Census of India and specific states (Manipur, Andhra Pradesh, Telangana).\n- Temporal aspect taken directly from the title: '2011' → represented as 'census 2011' in keywords to aid discovery by year and data source.\n- Included the governing body as a contextual keyword: Ministry of Health and Family Welfare (MoHFW) — extracted from ministry_department; abbreviated form included per special handling rules.\n- Added a Hindi transliteration keyword 'jan sankhya' to improve local-language discoverability (per keyword quality rules).\n- Avoided adding 'rural' as a keyword despite the catalog_title being 'Rural Health Statistics - 2015' because the resource title does not explicitly say the data are limited to rural population; catalog inclusion was used only as contextual support (not assumed as data scope).\n- Note content (source: Population Census of India; Manipur update; Andhra Pradesh and Telangana data collected from states) informed inclusion of 'census 2011' and supports the inference of state-level (India) coverage.\n\nWhy terms were selected or excluded:\n- Selected: core demographic measures (population, density, decadal growth) because they are the primary variables in the title and high-value search terms.\n- Selected: 'state-wise data' to reflect granularity; 'census 2011' and 'demographic indicators' because the note explicitly cites Census of India and contextualizes the dataset as demographic statistics useful for health planning.\n- Selected: ministry keyword (MoHFW) because the resource is governed by health/family welfare departments and this aids domain-specific discovery.\n- Selected: 'jan sankhya' as a transliterated local-language term to improve discoverability in Indian contexts.\n- Excluded: 'rural' as a definitive keyword because title does not state rural-only; catalog title suggests association but does not confirm dataset scope. Also avoided redundant repeat of title phrasing beyond essential normalized keywords.\n\nAmbiguities and assumptions:\n- Assumed national/state-level coverage (states of India) because the title says 'State-wise' and the note references Census of India and specific state updates, but the exact list of states/UTs covered is not provided.\n- Did not assume dataset frequency or time-series beyond the 2011 census year because no frequency/granularity fields were provided.\n- Assumed dataset is intended for public health/statistics use given catalog title and ministry, but did not recast the dataset as exclusively 'rural' for reasons noted above.\n\nConfidence rationale: see confidence_score and metadata_gaps.",
  "confidence_score": 0.8,
  "metadata_gaps": [
    "frequency",
    "granularity",
    "govt_type",
    "state_department (explicit field)"
  ]
}


----------------------------

2025-10-06 17:31:09,514 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-06 17:31:09,517 : INFO - Result is {
  "generated_keywords": "msme, udyog aadhaar, udyam registration, registered manufacturing enterprises, district-wise, cumulative counts, enterprise registry, micro enterprises, small enterprises, medium enterprises",
  "generated_subject": "Industrial Development, Small and Medium Enterprises, Regional Statistics, Business Registrations",
  "generated_theme": "Industry and Commerce, Economic Development, Enterprise Promotion",
  "justification": "Source columns used: title (District Wise Total MSME Registered Manufacturing Enterprises till last date), catalog_title (Udyog Aadhaar Memorandum (MSME Registration)), sector (Medium;Micro;Small Scale), sector_resource (Medium;Micro;Small Scale), ministry_department/CDOS State Ministry (Ministry of Micro, Small and Medium Enterprises). Note was null.\n\nExtraction and normalization rules applied:\n- Semicolon-separated fields (sector, sector_resource) were split into individual tags: \"Medium\", \"Micro\", \"Small Scale\" and normalized to the lowercase keywords \"micro enterprises\", \"small enterprises\", \"medium enterprises\" for clarity and searchability.\n- The catalog title indicates the registration system; both legacy and current registry names were included: \"udyog aadhaar\" (explicit in catalog_title) and the related modern term \"udyam registration\" (common alternate/related term) to improve discovery.\n- From the title, core domain terms were derived and normalized to avoid redundancy but remain actionable: \"registered manufacturing enterprises\" (captures registry + sector), \"district-wise\" (geographic granularity), and \"cumulative counts\" (\"till last date\" implies cumulative total). Added \"enterprise registry\" as an operational/searchable phrase.\n- Keywords are all in lowercase and separated into single concepts where possible (e.g., \"micro enterprises\", \"small enterprises\", \"medium enterprises\"). Hindi script was not added because the source uses English transliterations (\"Udyog Aadhaar\"); instead the transliterated form is preserved as a culturally relevant term.\n\nWhy terms were selected or excluded:\n- Included: terms that directly reflect what users would search for (msme, registration system name, register type, geographic granularity, enterprise size classes, and the cumulative/time dimension implied by \"till last date\"). The ministry name was used as contextual input but not duplicated as a keyword (to avoid overfitting) — ministry context is reflected through selection of MSME-related terms.\n- Excluded or de-emphasized: generic words from the title such as \"total\" were transformed into the more useful search term \"cumulative counts\". No domain-irrelevant keywords were added.\n\nAmbiguities and assumptions made:\n- \"till last date\" was interpreted as a cumulative or up-to-date total rather than a specific timestamped snapshot, so \"cumulative counts\" was added. If the dataset is time-series or updated periodically (daily/monthly), adding temporal keywords like \"time-series\" or \"daily\" would be appropriate, but update frequency was not provided.\n- Catalog title references Udyog Aadhaar Memorandum (UAM) — this registry has been succeeded by Udyam in practice; both terms were included to aid discovery across legacy and current searches.\n- The dataset appears central/ national in scope (district-wise across states) but govt_type was not provided; therefore geographic scope was captured only via \"district-wise\".\n\nField-specific derivation summary:\n- generated_keywords: derived primarily from title + catalog_title + sector tags.\n- generated_subject: abstracted from keywords to higher-level categories (industry, SMEs, regional stats, registration systems).\n- generated_theme: mapped to government domain categories relevant to MSME and industrial promotion.\n\nMetadata-driven decisions that affected quality:\n- Because frequency/granularity/government-level fields are missing, temporal and administrative keywords were conservatively applied (e.g., \"cumulative counts\" only) rather than more specific temporal tags.\n",
  "confidence_score": 0.8,
  "metadata_gaps": [
    "note",
    "frequency",
    "granularity",
    "govt_type"
  ]
}

TITLE: District Wise Total  MSME Registered Manufacturing Enterprises till last date
SECTOR: Medium;Micro;Small Scale

RESULT: {
  "generated_keywords": "msme, udyog aadhaar, udyam registration, registered manufacturing enterprises, district-wise, cumulative counts, enterprise registry, micro enterprises, small enterprises, medium enterprises",
  "generated_subject": "Industrial Development, Small and Medium Enterprises, Regional Statistics, Business Registrations",
  "generated_theme": "Industry and Commerce, Economic Development, Enterprise Promotion",
  "justification": "Source columns used: title (District Wise Total MSME Registered Manufacturing Enterprises till last date), catalog_title (Udyog Aadhaar Memorandum (MSME Registration)), sector (Medium;Micro;Small Scale), sector_resource (Medium;Micro;Small Scale), ministry_department/CDOS State Ministry (Ministry of Micro, Small and Medium Enterprises). Note was null.\n\nExtraction and normalization rules applied:\n- Semicolon-separated fields (sector, sector_resource) were split into individual tags: \"Medium\", \"Micro\", \"Small Scale\" and normalized to the lowercase keywords \"micro enterprises\", \"small enterprises\", \"medium enterprises\" for clarity and searchability.\n- The catalog title indicates the registration system; both legacy and current registry names were included: \"udyog aadhaar\" (explicit in catalog_title) and the related modern term \"udyam registration\" (common alternate/related term) to improve discovery.\n- From the title, core domain terms were derived and normalized to avoid redundancy but remain actionable: \"registered manufacturing enterprises\" (captures registry + sector), \"district-wise\" (geographic granularity), and \"cumulative counts\" (\"till last date\" implies cumulative total). Added \"enterprise registry\" as an operational/searchable phrase.\n- Keywords are all in lowercase and separated into single concepts where possible (e.g., \"micro enterprises\", \"small enterprises\", \"medium enterprises\"). Hindi script was not added because the source uses English transliterations (\"Udyog Aadhaar\"); instead the transliterated form is preserved as a culturally relevant term.\n\nWhy terms were selected or excluded:\n- Included: terms that directly reflect what users would search for (msme, registration system name, register type, geographic granularity, enterprise size classes, and the cumulative/time dimension implied by \"till last date\"). The ministry name was used as contextual input but not duplicated as a keyword (to avoid overfitting) — ministry context is reflected through selection of MSME-related terms.\n- Excluded or de-emphasized: generic words from the title such as \"total\" were transformed into the more useful search term \"cumulative counts\". No domain-irrelevant keywords were added.\n\nAmbiguities and assumptions made:\n- \"till last date\" was interpreted as a cumulative or up-to-date total rather than a specific timestamped snapshot, so \"cumulative counts\" was added. If the dataset is time-series or updated periodically (daily/monthly), adding temporal keywords like \"time-series\" or \"daily\" would be appropriate, but update frequency was not provided.\n- Catalog title references Udyog Aadhaar Memorandum (UAM) — this registry has been succeeded by Udyam in practice; both terms were included to aid discovery across legacy and current searches.\n- The dataset appears central/ national in scope (district-wise across states) but govt_type was not provided; therefore geographic scope was captured only via \"district-wise\".\n\nField-specific derivation summary:\n- generated_keywords: derived primarily from title + catalog_title + sector tags.\n- generated_subject: abstracted from keywords to higher-level categories (industry, SMEs, regional stats, registration systems).\n- generated_theme: mapped to government domain categories relevant to MSME and industrial promotion.\n\nMetadata-driven decisions that affected quality:\n- Because frequency/granularity/government-level fields are missing, temporal and administrative keywords were conservatively applied (e.g., \"cumulative counts\" only) rather than more specific temporal tags.\n",
  "confidence_score": 0.8,
  "metadata_gaps": [
    "note",
    "frequency",
    "granularity",
    "govt_type"
  ]
}


----------------------------

In [27]:
results_array

['{\n  "generated_keywords": "rainfall,precipitation,area-weighted rainfall,monthly rainfall,seasonal rainfall,annual rainfall,meteorological subdivisions,time-series (1901-2015),india,imd (india meteorological department)",\n  "generated_subject": "Meteorology,Climatology,Hydrology",\n  "generated_theme": "Environment and Climate,Science and Technology,Water Resources",\n  "justification": "Source columns used: title, catalog_title, sector, sector_resource, ministry_department, CDOS State Ministry, note.\\n\\nExtraction and normalization rules applied:\\n- Parsed semicolon-separated fields: sector and sector_resource both parsed into [\\"Science and Technology\\",\\"Atmospheric Science\\",\\"Earth Sciences\\"] and de-duplicated.\\n- Title parsed for core measurement and scope: \\"area weighted\\", \\"monthly, seasonal and annual rainfall\\", \\"36 meteorological subdivisions\\", and time span \\"1901-2015\\".\\n- Note inspected to confirm monthly series and mix of delayed-mode (1901-2012) and real-time (2013-2015) data; therefore included temporal/time-series emphasis.\\n- Ministry/department string parsed to parent ministry (Ministry of Earth Sciences) and implementing agency (IMD). Included IMD as a contextual keyword because it is central to dataset provenance and discovery.\\n- Keywords kept lowercase per guidelines, limited to 10, avoided redundant phrases from title except where critical (\\"rainfall\\" and temporal qualifiers are core discovery terms).\\n- Included geographic scope as \\"india\\" and agency shorthand \\"imd (india meteorological department)\\" for searchability.\\n- Did not include highly technical derived products (e.g., gridded) because source does not state such formats; avoided over-claiming.\\n- Added explicit time-series string \\"time-series (1901-2015)\\" to capture temporal range and aid discovery for historical analysis.\\n- Did not add regional language (Hindi) term because the dataset title and context are already explicit in English and the addition was optional; kept output focused and English-first as required.\\n\\nWhy specific terms were selected or excluded:\\n- Selected \\"area-weighted rainfall\\" because it describes the computation method in the title and is domain-specific.\\n- Selected temporal keywords (monthly, seasonal, annual, time-series) because title and note emphasize these granularities and long record length.\\n- Selected \\"meteorological subdivisions\\" to capture the spatial unit of aggregation (36 IMD subdivisions) which is important for spatial queries.\\n- Included \\"precipitation\\" as a commonly used synonym for cross-domain discovery.\\n- Included \\"imd (india meteorological department)\\" to support provenance-based search; excluded other ministry acronyms except Ministry of Earth Sciences implicitly in themes because IMD is the implementing agency most relevant to users.\\n- Excluded format-specific keywords (e.g., CSV, shapefile) or variables not mentioned (e.g., intensity, extremes) to avoid misinformation.\\n\\nAmbiguities and assumptions:\\n- The dataset frequency field is not provided explicitly; inferred monthly series from title/note and included monthly/seasonal/annual in keywords. Assumed no near-real-time stream beyond 2013-2015 being labeled as real-time in the note.\\n- Spatial granularity beyond \\"36 meteorological subdivisions\\" is assumed to be administrative/meteorological subdivision-level, not station-level or gridded; keywords reflect subdivision-level aggregation.\\n- Government level (central/state) and explicit frequency/granularity metadata fields were not provided; assumed central (IMD) management.\\n- Chose not to add Hindi transliteration since metadata already clear in English; can add on request.\\n\\nMapping to requested fields:\\n- Subjects chosen at a higher abstraction level (Meteorology, Climatology, Hydrology) to support faceted navigation across atmospheric and water resource datasets.\\n- Themes chosen to align with government domain categories: Environment and Climate (primary), Science and Technology (sector tag present), Water Resources (cross-cutting consumer domain).",\n  "confidence_score": 0.9,\n  "metadata_gaps": "frequency,granularity,govt_type"\n}']

In [30]:
with open('/home/prajna/civicdatalab/nic-metadata/nic-metadata-cleaning/metadata_enrichment_results.json', 'w', encoding='utf-8') as f:
    json.dump(results_array, f, indent=2, ensure_ascii=False)

print(f"\n Saved {len(results_array)} results to metadata_enrichment_results.json")

 Saved 5 results to metadata_enrichment_results.json