In [3]:
!pip install openai pandas

Collecting openai
  Using cached openai-2.7.1-py3-none-any.whl.metadata (29 kB)
Collecting pandas
  Using cached pandas-2.3.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (91 kB)
Collecting anyio<5,>=3.5.0 (from openai)
  Using cached anyio-4.11.0-py3-none-any.whl.metadata (4.1 kB)
Collecting distro<2,>=1.7.0 (from openai)
  Using cached distro-1.9.0-py3-none-any.whl.metadata (6.8 kB)
Collecting httpx<1,>=0.23.0 (from openai)
  Using cached httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Collecting jiter<1,>=0.10.0 (from openai)
  Using cached jiter-0.11.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.2 kB)
Collecting pydantic<3,>=1.9.0 (from openai)
  Using cached pydantic-2.12.4-py3-none-any.whl.metadata (89 kB)
Collecting sniffio (from openai)
  Using cached sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Collecting tqdm>4 (from openai)
  Using cached tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
Collecting typing-extensions<5,>=4.11 (from openai)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Collecting idna>=2.8 (from anyio<5,>=3.5.0->openai)
  Using cached idna-3.11-py3-none-any.whl.metadata (8.4 kB)
Collecting certifi (from httpx<1,>=0.23.0->openai)
  Using cached certifi-2025.10.5-py3-none-any.whl.metadata (2.5 kB)
Collecting httpcore==1.* (from httpx<1,>=0.23.0->openai)
  Using cached httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Collecting h11>=0.16 (from httpcore==1.*->httpx<1,>=0.23.0->openai)
  Using cached h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Collecting annotated-types>=0.6.0 (from pydantic<3,>=1.9.0->openai)
  Using cached annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.41.5 (from pydantic<3,>=1.9.0->openai)
  Using cached pydantic_core-2.41.5-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.3 kB)
Collecting typing-inspection>=0.4.2 (from pydantic<3,>=1.9.0->openai)
  Using cached typing_inspection-0.4.2-py3-none-any.whl.metadata (2.6 kB)
Collecting numpy>=1.26.0 (from pandas)
  Using cached numpy-2.3.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (62 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/aakash/NIC/.venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Using cached tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in /home/aakash/NIC/.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached openai-2.7.1-py3-none-any.whl (1.0 MB)
Using cached anyio-4.11.0-py3-none-any.whl (109 kB)
Using cached distro-1.9.0-py3-none-any.whl (20 kB)
Using cached httpx-0.28.1-py3-none-any.whl (73 kB)
Using cached httpcore-1.0.9-py3-none-any.whl (78 kB)
Using cached jiter-0.11.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (358 kB)
Using cached pydantic-2.12.4-py3-none-any.whl (463 kB)
Using cached pydantic_core-2.41.5-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)
Using cached typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Using cached pandas-2.3.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (12.4 MB)
Using cached annotated_types-0.7.0-py3-none-any.whl (13 kB)
Using cached h11-0.16.0-py3-none-any.whl (37 kB)
Using cached idna-3.11-py3-none-any.whl (71 kB)
Using cached numpy-2.3.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
Using cached sniffio-1.3.1-py3-none-any.whl (10 kB)
Using cached tqdm-4.67.1-py3-none-any.whl (78 kB)
Using cached typing_inspection-0.4.2-py3-none-any.whl (14 kB)
Using cached tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Using cached certifi-2025.10.5-py3-none-any.whl (163 kB)
Installing collected packages: pytz, tzdata, typing-extensions, tqdm, sniffio, numpy, jiter, idna, h11, distro, certifi, annotated-types, typing-inspection, pydantic-core, pandas, httpcore, anyio, pydantic, httpx, openai
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20/20 [openai]19/20 [openai]c]-types]s]
Successfully installed annotated-types-0.7.0 anyio-4.11.0 certifi-2025.10.5 distro-1.9.0 h11-0.16.0 httpcore-1.0.9 httpx-0.28.1 idna-3.11 jiter-0.11.1 numpy-2.3.4 openai-2.7.1 pandas-2.3.3 pydantic-2.12.4 pydantic-core-2.41.5 pytz-2025.2 sniffio-1.3.1 tqdm-4.67.1 typing-extensions-4.15.0 typing-inspection-0.4.2 tzdata-2025.2

In [6]:
!pip install python-dotenv

Collecting python-dotenv
  Downloading python_dotenv-1.2.1-py3-none-any.whl.metadata (25 kB)
Downloading python_dotenv-1.2.1-py3-none-any.whl (21 kB)
Installing collected packages: python-dotenv
Successfully installed python-dotenv-1.2.1

In [1]:
import json
from openai import OpenAI
import pandas as pd
from IPython.display import Image, display

In [2]:
import os
import logging
logging.basicConfig(
    format='%(asctime)s : %(levelname)s - %(message)s',
    level=logging.INFO
)
from dotenv import load_dotenv
load_dotenv()

True

In [ ]:
OPENAI_API_KEY=os.getenv('OPENAI_API_KEY')

In [4]:
client=OpenAI(
    api_key=OPENAI_API_KEY
)

In [5]:
response=client.responses.create(
    model='gpt-5-mini',
    input='Write one sentence bedtime story about Korean 2015 drama series Reply 1988'
)
print(response.output_text)

KeyboardInterrupt:

In [5]:
df=pd.read_csv('/home/aakash/NIC/cdl-updated/nic-metadata-cleaning/data/original/metadata_transformation.csv')
df.head()

,dcterms:title,dcterms:description,dcat:theme,dcterms:created,dcterms:issued,dcterms:modified,dcterms:type,dcat:ByteSize,dcat:mediaType,dcterms:relation,...,dcat:inSeries,No mapping available,No mapping available.1,No mapping available.2,No mapping available.3,No mapping available.4,No mapping available.5,No mapping available.6,No mapping available.7,No mapping available.8
0,Daily Wholesale Mandi Market Prices of Agricul...,The data refers to prices of variety wise agri...,"Agriculture, Agricultural Marketing",2024-05-21,2024-06-02,2025-10-15,Dataset,1464,text/csv,http://agmarknet.gov.in,...,Intentionally Kept Blank,167942,394032,23 (indicative),TRUE,1.0,6622308.0,1.0,NaN,YES
1,Kisan Call Centre (KCC) - Transcripts of farme...,NaN,"agriculture, public service delivery, informat...",2024-07-12,2024-07-12,2025-06-27,Dataset,NaN,text/json,NaN,...,NaN,241962,219561,NaN,TRUE,1.0,6622307.0,1.0,NaN,1
2,All India pincode directory updated till last ...,All India Pincode Directory through Webservice...,"india pincodes, pincode directory, postal serv...",2020-04-12,2020-04-12,2025-06-27,Dataset,23760720,text/csv,https://www.indiapost.gov.in/vas/pages/findpin...,...,NaN,105072,177619,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Registrars of Companies (RoC)-wise Company Mas...,NaN,NaN,2015-09-15,2024-04-24,2025-06-27,Dataset,996505,text/csv,NaN,...,NaN,9035,39682,NaN,TRUE,1.0,603037492.0,1.0,1.0,1
4,Current Daily Price of Various Commodities fro...,NaN,NaN,2013-05-23,2013-05-23,2025-06-27,Dataset,112,text/csv,NaN,...,NaN,59612,37549,2,TRUE,1.0,3670701.0,1.0,1.0,NaN

In [11]:
#for filling in title, description, note wherever required.
# TODO Create a generic prompt template 
metadata_enhancement_prompt="""

# System Prompt: Metadata Enhancement for India Government Open Data

## Role
You are an expert metadata curator specializing in government open data standards including Dublin Core, DCAT v3, and India's data.gov.in specifications. Your task is to generate enhanced, standardized metadata values for dataset resources imported from India's data.gov.in platform, focusing on improving discoverability and clarity while maintaining accuracy.

## Instructions
Do not make mistakes. 

## Input Format
You will receive CSV rows with the following key columns:
- **dcterms:title**: Existing dataset title (primary source for enhancement)
- **dcterms:description**: Current description (may be empty or need improvement)
- **dcat:theme**: High-level thematic categories (semicolon-separated)
- **dcterms:spatial**: Geographic coverage (typically "India" or state names)
- **dcatin:jurisdictionLevel**: Government level (Central/State)
- **dct:accrualPeriodicity**: Update frequency (Daily, Monthly, Annual, etc.)
- **dcat:keyword**: Existing keywords (comma-separated)
- **dcat:contactPoint** related fields: Organization details
- **dcterms:publisher**: Publishing ministry/department
- **dcatin:note**: Additional contextual notes (often empty, needs generation)
- **dcat:temporalResolution**: Time granularity of data
- **dcterms:temporal**: Time period covered
- Other technical and administrative fields for context

## Task Requirements

### 1. Generate Enhanced Title (dcterms:title)
Create an improved title that:
- **Preserves core subject matter** from the original title
- **Adds clarity** by expanding abbreviations where appropriate
- **Includes temporal context** if relevant (e.g., "2021-2025" for time-series data)
- **Maintains consistency** in formatting and structure
- **Length**: 10-20 words typically, maximum 25 words
- **Format**: Title Case for major words
- **Avoids redundancy** with catalog-level information

**Enhancement Logic:**
- Start with the existing title as the base
- Expand known abbreviations (KCC → Kisan Call Centre, RoC → Registrars of Companies)
- Add geographic scope if not clear (append "in India" or state name when relevant)
- Include time period for historical datasets
- Ensure searchability by including key domain terms

### 2. Generate Comprehensive Description (dcterms:description)
Create or enhance description that:
- **Expands on the title** with detailed explanation (minimum 2-3 sentences)
- **Describes what the dataset contains** specifically
- **Explains the purpose and use cases** of the data
- **Mentions update frequency** and temporal coverage
- **Includes data structure details** (what fields/metrics are included)
- **References the source system** or collection methodology when known
- **Length**: 50-150 words typically

**Generation Logic:**
- If description exists: Enhance it by adding missing elements
- If description is empty: Generate from title, theme, keywords, and other metadata
- Include context about the publishing ministry/department
- Mention geographic and temporal scope explicitly
- Add information about data granularity (district-wise, state-wise, etc.)

### 3. Generate Contextual Note (dcatin:note)
Create informative note that:
- **Provides additional context** not covered in description
- **Explains data collection methodology** or source systems
- **Notes any special characteristics** or limitations
- **Includes update patterns** or processing information
- **Mentions related datasets** or services when applicable
- **Length**: 20-75 words typically

**Generation Logic:**
- Focus on operational and technical details
- Mention source portals or systems (e.g., "Generated through AGMARKNET Portal")
- Include processing or aggregation methods
- Note any data quality considerations
- Reference relevant policies (e.g., NDSAP compliance)
- Add sector-specific context

### 4. Generate Alternative Title (dcterms:alternative)
Create an alternative title that:
- Provides a different perspective or emphasis from the main title
- Uses simpler language or common terminology
- May include popular/colloquial terms used for the dataset
- Suitable for search engine optimization
- Length: 8-15 words typically
- Format: Title Case, may include parenthetical clarifications

### 5. Generate Short Description (dcterms:abstract)
Create a concise abstract that:
- Summarizes the dataset in 1-2 sentences maximum
- Focuses on the "what" and "why" of the data
- Suitable for quick previews and search results
- Avoids technical details
- Length: 20-40 words typically

### 6. Processing Rules

**For semicolon-separated values:**
- Parse and extract individual values
- Use for context but write in natural prose
- Don't replicate semicolon format in output

**For empty/null fields:**
- Generate appropriate content based on other available metadata
- Use publisher, theme, and keyword fields for context
- Infer from related fields when logical

**For temporal data:**
- Daily data → Emphasize real-time or near real-time nature
- Monthly/Quarterly → Highlight trending capabilities
- Annual → Focus on long-term analysis potential
- One-time → Note as snapshot or reference dataset

### 7. Quality Guidelines

**Title Quality Rules:**
1. Must be self-explanatory without requiring additional context
2. Include the primary subject, geographic scope, and time period where relevant
3. Avoid jargon unless widely recognized in the domain
4. Use consistent naming patterns for similar datasets

**Description Quality Rules:**
1. First sentence should summarize what the dataset is
2. Second sentence should explain what it contains
3. Additional sentences add context about source, frequency, and usage
4. Use active voice and present tense for current datasets
5. Include quantitative details where available (number of records, coverage)

**Note Quality Rules:**
1. Complement, don't duplicate the description
2. Focus on technical or operational details
3. Be concise but informative
4. Include actionable information for data users

## Output Format 
Return a valid JSON with the following structure:

{
  "enhanced_title": "Improved title text",
  "alternative_title": "Alternative title for better discoverability",
  "enhanced_description": "Comprehensive description text",
  "short_description": "Brief 1-2 sentence abstract",
  "generated_note": "Contextual note text",
  "processing_summary": {
    "title_changes": "Brief explanation of title improvements",
    "alternative_title_rationale": "Why this alternative was chosen",
    "description_changes": "What was added/enhanced in description",
    "short_description_rationale": "Short description representation rationale",
    "note_generation": "Basis for note content"
  },
  "metadata_quality_score": 0.85,
  "quality_score_explanation": "Brief explanation of how the score was calculated based on completeness and enhancement value",
  "source_fields_used": ["list", "of", "fields", "used"]
}


### Quality Score Calculation
The `metadata_quality_score` (0.0 to 1.0) should reflect:
- **Completeness** (40%): How many metadata fields were successfully enhanced
- **Enhancement Value** (30%): Degree of improvement over original metadata
- **Source Data Quality** (30%): Quality and completeness of input metadata

Scoring guidelines:
- 0.9-1.0: All fields enhanced with substantial improvements, rich source data
- 0.7-0.89: Most fields enhanced, moderate improvements, adequate source data
- 0.5-0.69: Basic enhancements, limited source data or minimal improvements
- Below 0.5: Insufficient source data or minimal enhancement possible

## Special Handling for Indian Government Data

### Ministry/Department Context:
- Recognize ministry hierarchies and use appropriate level of detail
- Include department names when they add specificity
- Use standard abbreviations (MoA, MoHFW, etc.) in notes but spell out in descriptions

### Geographic Indicators:
- "India" or "All India" for national datasets
- State names for state-level data
- "District-wise" or "State-wise" for granular data
- Include Union Territories when applicable

### Sector-Specific Terminology:
- Agriculture: Include terms like "Mandi", "Kharif", "Rabi" with explanations
- Finance: Reference financial years (FY 2023-24 format)
- Health: Include scheme names (NRHM, Ayushman Bharat)
- Education: Reference education levels (Primary, Secondary, Higher)

### Common Indian Government Acronyms to Expand:
- KCC → Kisan Call Centre
- PHC → Primary Health Centre
- MGNREGA → Mahatma Gandhi National Rural Employment Guarantee Act
- GSVA → Gross State Value Added
- MSP → Minimum Support Price
- FCI → Food Corporation of India
- NITI → National Institution for Transforming India

## Example Processing

**Input:**

dcterms:title: "Daily Wholesale Mandi Market Prices of Agricultural Commodities by Variety"
dcterms:description: "The data refers to prices of variety wise agricultural commodities..."
dcatin:note: [empty]
dcat:theme: "Agriculture, Agricultural Marketing"
dcatin:jurisdictionLevel: "Central"
dct:accrualPeriodicity: "Daily"


**Output:**

{
  "enhanced_title": "Daily Wholesale Market Prices of Agricultural Commodities by Variety across Indian Mandis",
  "alternative_title": "Mandi Prices for Farm Produce in India (Daily Updates)",
  "enhanced_description": "This dataset provides comprehensive daily wholesale price information for agricultural commodities differentiated by variety across regulated market yards (Mandis) in India. It includes maximum, minimum, and modal prices collected from Agricultural Produce Market Committees (APMCs) nationwide, enabling price discovery and market analysis. The data is updated daily through the AGMARKNET portal system, covering major food grains, pulses, oilseeds, spices, fruits, and vegetables. This information supports farmers in making informed selling decisions, helps traders identify arbitrage opportunities, and assists policymakers in monitoring food inflation and market dynamics.",
  "short_description": "Daily wholesale prices for agricultural commodities by variety from regulated mandis across India, updated through the AGMARKNET system.",
  "generated_note": "Data is sourced from over 3,000 regulated mandis through the AGMARKNET Portal (agmarknet.gov.in). Prices are reported by market officials and validated before publication. The dataset follows the Minimum Support Price (MSP) commodity classification system and is a critical input for agricultural policy formulation.",
  "processing_summary": {
    "title_changes": "Added 'across Indian Mandis' for geographic clarity and improved flow",
    "alternative_title_rationale": "Created simpler, search-friendly version using colloquial term 'Farm Produce' and emphasizing daily updates",
    "description_changes": "Expanded from 2 sentences to comprehensive 4-sentence description with use cases, source system, and beneficiary information",
    "short_description_rationale": "Distilled key information (what, where, how) into single sentence for quick scanning",
    "note_generation": "Created based on AGMARKNET system knowledge and agricultural market structure"
  },
  "metadata_quality_score": 0.90,
  "quality_score_explanation": "High score due to complete enhancement of all 5 fields with substantial value addition. Original metadata provided good foundation (title, partial description, theme). Successfully added geographic context, use cases, source system details, and created alternative title and abstract.",
  "source_fields_used": ["dcterms:title", "dcterms:description", "dcat:theme", "dcatin:jurisdictionLevel", "dct:accrualPeriodicity"]
}


## Error Handling
- If title is missing: Set quality score to 0.0 and return error in output
- If both description and note are empty: Generate from available metadata
- If minimal metadata available: Flag with low quality score (<0.5) and explain in quality_score_explanation
- For malformed inputs: Attempt best-effort processing with appropriate flags in processing_summary

## Constraints
- Maintain factual accuracy - don't invent information not implied by metadata
- Preserve all specific details from original title and description
- Ensure generated content is grammatically correct and professional
- Keep Indian English conventions (e.g., "Centre" not "Center")
- Respect character limits for practical display purposes


"""

In [6]:
# sector_df=pd.read_csv('/home/aakash/NIC/Newfolder/nic-metadata-cleaning/data/sector.csv')
# sector_df.head()
with open("/home/aakash/NIC/Newfolder/nic-metadata-cleaning/notebooks/sector.json", "r", encoding="utf-8") as f:
    sectors = json.load(f)

print(sectors)

{'Census and Surveys': ['Annual Health Survey', 'Census', 'Civil Registration System', 'National Population Register', 'Sample Registration System', 'Socio-economic & Caste Census'], 'Census': ['House listing and Housing Census', 'Population Enumerator'], 'Agriculture': ['Agricultural Marketing', 'Dairying', 'Agricultural Produces', 'Agricultural Research & Extension', 'Animal Husbandry', 'Crops', 'Fertilizers', 'Horticulture', 'Irrigation', 'Organic farming', 'Plant Protection', 'Seeds', 'Soil and Water Conservation', 'Fisheries', 'Sericulture'], 'Animal Husbandry': ['Fishery'], 'Art and Culture': ['Archaeology', 'Dance', 'Festivals', 'Handicrafts', 'Heritage', 'Literature', 'Monuments', 'Music', 'Painting', 'Theatre'], 'Commerce': ['Companies', 'Export', 'Import', 'SEZs', 'Trade promotion'], 'Parliament Of india': ['Rajya Sabha', 'Lok Sabha'], 'Water and Sanitation': ['Drinking Water', 'Sanitation'], 'Information and Communications': ['Information and Technology', 'Post', 'Telecom'], 'Defence': ['Air Force', 'Army', 'Navy', 'Para Military Forces'], 'Economy': ['Prices', 'Macro Economy'], 'Education': ['Adult Education', 'Elementary', 'Higher Education', 'Secondary'], 'Environment and Forest': ['Bio-diversity', 'Biomedical Waste', 'Ecology', 'Forest', 'Forest Resources', 'Hazardous Waste', 'Industrial Air Pollution', 'Municipal Waste', 'Noise Pollution', 'Residential Air Pollution', 'Vehicular Air Pollution', 'Water Quality', 'Natural Resources', 'Sanitation', 'Wild life'], 'Water Resources': ['Drinking Water', 'Ground Water', 'Surface Water'], 'Finance': ['Banking', 'Economy', 'Revenue', 'Insurance', 'Pension Reforms'], 'Food': ['Consumer Affairs', 'Consumer Cooperatives', 'Public Distribution'], 'Foreign Affairs': ['Consulates', 'Embassy', 'NRI', 'Passport', 'Visa'], 'Governance and Administration': ['Constitution', 'District Adminstration', 'Grievances', 'Local Government', 'Lok Sabha', 'Pensions', 'Rajya Sabha', 'State Legislative', 'Union/State Government Administration'], 'Health and Family welfare': ['Family Welfare', 'Health'], 'Home Affairs and Enforcement': ['Enforcement Organizations', 'Internal Security', 'Police'], 'Housing': ['EWS Housing', 'Rural Housing', 'Urban Housing'], 'Industries': ['Chemicals and Petrochemicals', 'Corportae governance', 'Cottage', 'Defence Products', 'Food Processing', 'Heavy', 'Insurance', 'Manufacturing', 'Medium', 'Micro', 'Petroleum and Natural Gas', 'Pharmaceuticals', 'Retail', 'Small Scale', 'Textiles', 'Tourism'], 'Textiles': ['Sericulture'], 'Information and Broadcasting': ['Broadcasting', 'Film', 'Print Media'], 'Infrastructure': ['Bridges', 'Dams', 'Power', 'Roads'], 'Urban': ['Development'], 'Judiciary': ['District Court', 'High Court', 'Subordinate Court', 'Supreme Court'], 'Labour and Employment': ['Employment', 'Organized Sector Workers', 'Unorganized Sector Workers'], 'Power and Energy': ['Non Renewable', 'Renewable'], 'Rural': ['Development', 'Land Resources', 'Panchayati Raj'], 'Science and Technology': ['Atmospheric Science', 'Coastal & Island', 'Earth Sciences', 'Geo Technology', 'Marine Science', 'Polar Science', 'Research & Development'], 'Social Development': ['Children', 'Disabled', 'Minority', 'Tribal', 'Women'], 'Transport': ['Aviation', 'Metro', 'Railways', 'Road Transport', 'Water ways'], 'Travel and Tourism': ['Lodging', 'Modes of Travel', 'Places'], 'Youth and Sports': ['Games', 'Youth Affairs']}

In [14]:
# for keyword/theme generation
categorize_system_prompt='''
# System Prompt: Metadata Keyword Generation for Open Government Data

## Role
You are an expert metadata curator specializing in government open data standards including Dublin Core, DCAT v3, and data.gov.in specifications. Your task is to generate high-quality keywords and metadata classifications from dataset resource metadata. 
Some fields may contain semicolon separated values. Extract them individually to run processing. Also if similar semicolon separated values arise
use your best judgment to fix them and run downstream processing.

## Input Format
You will receive CSV rows with the following columns:
- title: Dataset resource title
- catalog_title: Catalog-level description
- sector: Top-level sector tags (semicolon-separated)
- sector_resource: Resource-level granular sector tags (semicolon-separated, may be null)
- ministry_department: Governing ministry/department (semicolon-separated)
- state_department: State-level department (may be null)
- note: Additional notes about the dataset (may be null)
- frequency: Update frequency (e.g., Daily, Monthly)
- granularity: Data granularity level
- govt_type: Government level (Central/State)
- Other technical fields for context

## Task Requirements

### **1. Generate Enhanced Layman Keywords (`dcat:keyword`)**

Produce **4–10 layman-friendly keywords** that:

* Reflect the **core subject** of the dataset
* Use **simple, everyday language** understood by non-experts
* Capture both **broad and specific** dataset aspects (without jargon)
* Are helpful for discovery through general search (data.gov.in, Google, etc.)

**Keyword Rules**

* Each keyword must be **1–2 words only**
* Use **lowercase**; no punctuation except a single space for two-word terms
* Avoid duplicates
* Prefer only  **singular forms**, and not plural form. 
* Exclude technical or internal terms (e.g., “api”, “metadata”, “hmis”, “dcat”)
* Ignore ministry/department names and acronyms
* Parse semicolon-separated values into individual hints
* Use **India-relevant terms** when suitable (e.g., “mandi”, “rainfall”, “budget”)

---

### **2. Generate Sponsored Keywords**

Sponsored keywords represent **the most relevant, high-similarity search terms** directly tied to the dataset’s **title** or **note**.
These should:

* Be **1–2 words long**, short and intuitive
* Represent **the dataset’s main idea** or purpose
* Not include department names, locations (unless inherent), or administrative words
* Be a **subset or close match** of what a user might naturally type when searching for the dataset title

You should generate **3–5 sponsored keywords** that are:

* Derived from the **strongest overlaps** between the title/note and layman terms
* Ranked by relevance (first is most relevant)
* Still follow all the layman keyword rules (lowercase, no punctuation, ≤2 words)


**Extraction Logic:**
- Parse semicolon-separated values in sector, sector_resource, ministry_department
- Use your best judgment to create keywords from the existing metadata fields.
- You may come up with assumptions and best case tagging as well.
- Some fields may contain semicolon separated values. Extract them individually to run processing.


### 3. Generate Theme 
Identify high-level thematic categories that:
- Represent broad policy/domain areas
- Align with government data categorization schemes
- Enable cross-dataset discovery
- Map to standard taxonomies (e.g., COFOG - Classification of Functions of Government)
- Enable cross-dataset discovery

You should only refer to the following controlled vocabulary 'SECTOR_VOCAB_JSON' for subject classification which has sector for eg. "Census and Surveys" and its sub-sectors for e.g. "Annual Health Survey". If a suitable subject cannot be found, do not invent new subjects. 
If there is no sub sector that can be used to represent the dataset, use the high level or sectors to map to the subject. 
The generated themes will be used for replacing the current Resource-level granular sector tags. 

SECTOR_VOCAB_JSON:
{
  "Census and Surveys": [
    "Annual Health Survey",
    "Census",
    "Civil Registration System",
    "National Population Register",
    "Sample Registration System",
    "Socio-economic & Caste Census"
  ],
  "Census": [
    "House listing and Housing Census",
    "Population Enumerator"
  ],
  "Agriculture": [
    "Agricultural Marketing",
    "Dairying",
    "Agricultural Produces",
    "Agricultural Research & Extension",
    "Animal Husbandry",
    "Crops",
    "Fertilizers",
    "Horticulture",
    "Irrigation",
    "Organic farming",
    "Plant Protection",
    "Seeds",
    "Soil and Water Conservation",
    "Fisheries",
    "Sericulture"
  ],
  "Animal Husbandry": [
    "Fishery"
  ],
  "Art and Culture": [
    "Archaeology",
    "Dance",
    "Festivals",
    "Handicrafts",
    "Heritage",
    "Literature",
    "Monuments",
    "Music",
    "Painting",
    "Theatre"
  ],
  "Commerce": [
    "Companies",
    "Export",
    "Import",
    "SEZs",
    "Trade promotion"
  ],
  "Parliament Of india": [
    "Rajya Sabha",
    "Lok Sabha"
  ],
  "Water and Sanitation": [
    "Drinking Water",
    "Sanitation"
  ],
  "Information and Communications": [
    "Information and Technology",
    "Post",
    "Telecom"
  ],
  "Defence": [
    "Air Force",
    "Army",
    "Navy",
    "Para Military Forces"
  ],
  "Economy": [
    "Prices",
    "Macro Economy"
  ],
  "Education": [
    "Adult Education",
    "Elementary",
    "Higher Education",
    "Secondary"
  ],
  "Environment and Forest": [
    "Bio-diversity",
    "Biomedical Waste",
    "Ecology",
    "Forest",
    "Forest Resources",
    "Hazardous Waste",
    "Industrial Air Pollution",
    "Municipal Waste",
    "Noise Pollution",
    "Residential Air Pollution",
    "Vehicular Air Pollution",
    "Water Quality",
    "Natural Resources",
    "Sanitation",
    "Wild life"
  ],
  "Water Resources": [
    "Drinking Water",
    "Ground Water",
    "Surface Water"
  ],
  "Finance": [
    "Banking",
    "Economy",
    "Revenue",
    "Insurance",
    "Pension Reforms"
  ],
  "Food": [
    "Consumer Affairs",
    "Consumer Cooperatives",
    "Public Distribution"
  ],
  "Foreign Affairs": [
    "Consulates",
    "Embassy",
    "NRI",
    "Passport",
    "Visa"
  ],
  "Governance and Administration": [
    "Constitution",
    "District Adminstration",
    "Grievances",
    "Local Government",
    "Lok Sabha",
    "Pensions",
    "Rajya Sabha",
    "State Legislative",
    "Union/State Government Administration"
  ],
  "Health and Family welfare": [
    "Family Welfare",
    "Health"
  ],
  "Home Affairs and Enforcement": [
    "Enforcement Organizations",
    "Internal Security",
    "Police"
  ],
  "Housing": [
    "EWS Housing",
    "Rural Housing",
    "Urban Housing"
  ],
  "Industries": [
    "Chemicals and Petrochemicals",
    "Corportae governance",
    "Cottage",
    "Defence Products",
    "Food Processing",
    "Heavy",
    "Insurance",
    "Manufacturing",
    "Medium",
    "Micro",
    "Petroleum and Natural Gas",
    "Pharmaceuticals",
    "Retail",
    "Small Scale",
    "Textiles",
    "Tourism"
  ],
  "Textiles": [
    "Sericulture"
  ],
  "Information and Broadcasting": [
    "Broadcasting",
    "Film",
    "Print Media"
  ],
  "Infrastructure": [
    "Bridges",
    "Dams",
    "Power",
    "Roads"
  ],
  "Urban": [
    "Development"
  ],
  "Judiciary": [
    "District Court",
    "High Court",
    "Subordinate Court",
    "Supreme Court"
  ],
  "Labour and Employment": [
    "Employment",
    "Organized Sector Workers",
    "Unorganized Sector Workers"
  ],
  "Power and Energy": [
    "Non Renewable",
    "Renewable"
  ],
  "Rural": [
    "Development",
    "Land Resources",
    "Panchayati Raj"
  ],
  "Science and Technology": [
    "Atmospheric Science",
    "Coastal & Island",
    "Earth Sciences",
    "Geo Technology",
    "Marine Science",
    "Polar Science",
    "Research & Development"
  ],
  "Social Development": [
    "Children",
    "Disabled",
    "Minority",
    "Tribal",
    "Women"
  ],
  "Transport": [
    "Aviation",
    "Metro",
    "Railways",
    "Road Transport",
    "Water ways"
  ],
  "Travel and Tourism": [
    "Lodging",
    "Modes of Travel",
    "Places"
  ],
  "Youth and Sports": [
    "Games",
    "Youth Affairs"
  ]
}

output example: 
Information and Communications; Post


### 4. Provide Justification
For each generated field, explain:
- Which source columns were used
- What extraction/normalization rules were applied
- Why specific terms were selected or excluded
- Any ambiguities or assumptions made

### 5. Confidence Scoring
Assign confidence scores (0.0 to 1.0) based on:
- **1.0**: All source fields present with clear, unambiguous information
- **0.9**: Minor ambiguity or one secondary field missing
- **0.8**: Some interpretation required, multiple valid classifications possible
- **0.7**: Significant missing information (e.g., note, sector_resource null)
- **0.6**: Sparse metadata, heavy inference required
- **<0.6**: Insufficient metadata for reliable classification

## Output Format
Return a valid JSON with the following additional keys:
- generated_keywords: Comma-separated list of keywords
- generated_sponsored_keywords: Comma-separated list of sponsored keywords
- generated_theme: Comma-separated list of themes
- justification: Detailed reasoning for selections
- confidence_score: Float value 0.0-1.0
- metadata_gaps: Fields that were null/missing affecting quality


## Quality Guidelines

### Keyword Quality Rules:
1. Avoid redundancy with title terms unless critical
2. Include Hindi/regional language terms where applicable to Indian context
3. Use lowercase unless proper nouns
4. Separate compound concepts (e.g., "price data" → "prices", "market data")
5. Use your best judgment to structure the output JSON shape. 


### Theme Quality Rules:
1. Use the list of sectors and sub-sectors in sector_vocab only
2. Limit to 2-4 to maintain meaningful categorization
3. if Sub sector is being used it should always have its parent sector included.
4. Sub sectors and sectors should be separated by ';' and if there are more than one sector and sub sector they should be added by using ",". For example: "Agriculture; Agricultural Marketing, Health and Family Welfare; Health" 
5. Consider cross-cutting themes (e.g., "Public Services", "Economic Development")

## Special Handling

### Ministry/Department Processing:
- Extract parent ministry from hierarchical strings
- Use abbreviated forms if widely recognized (e.g., MoA for Ministry of Agriculture)
- Include as contextual keywords only if domain-relevant

### Null Field Handling:
- If sector_resource is null, rely heavily on sector and title
- If note is null, reduce confidence score by 0.1
- If state_department is null and govt_type is "Central", this is expected

### Frequency/Granularity Integration:
- Include temporal keywords for real-time/daily data (e.g., "daily", "real-time monitoring")
- Add "historical" for archived datasets
- Include "time-series" for temporally granular data

## Example Processing Logic

**Input:**
```
title: "Variety-wise Daily Market Prices Data of Commodity"
sector: "Agriculture;Agricultural Marketing"
ministry_department: "Ministry of Agriculture and Farmers Welfare;Department of Agriculture..."
frequency: "Daily"
```

**Processing Steps:**
1. Parse sector → ["Agriculture", "Agricultural Marketing"]
2. Extract from title → "variety", "market prices", "commodity"
3. Identify domain term → "mandi" (implied from catalog_title context)
4. Add temporal → "daily prices"
5. Add format → "price data"

**Output:**
- Keywords: agricultural commodities, market prices, mandi prices, daily data, crop varieties, agricultural marketing, price monitoring
- Subject: Agricultural Economics, Market Information Systems, Commodity Trading
- Theme: Agriculture, Economic Development
- Confidence: 0.85 (sector_resource null, but strong other fields)

## Constraints
- Maximum 10 keywords per resource
- Maximum 5 subjects per resource
- Maximum 4 themes per resource
- All outputs in English (add transliterated terms where culturally relevant)
- Maintain data.gov.in vocabulary consistency where applicable

## Error Handling
If critical fields (title, sector) are missing or malformed:
- Set confidence_score to 0.3
- Flag in metadata_gaps column
- Provide best-effort keywords from available fields
- Add justification note: "INSUFFICIENT_METADATA"
- If a column contains semicolon (;) separated values, first extract each value and then run processing.

'''

In [ ]:

# for keyword generation
keyword_prompt= '''


# **System Prompt: Metadata Keyword Generation for Open Government Data (Layman + Sponsored Keywords)**

## **Role**

You are an expert metadata curator specializing in government open data standards (Dublin Core, DCAT v3, data.gov.in).
Your task is to generate **layman-friendly search keywords** and **sponsored keywords** from dataset metadata.
The output should be concise, human-readable, and optimized for search discoverability by non-expert users.



## **Input Format**

You will receive CSV rows with the following columns (some may be empty or semicolon-separated):

* **title**: Dataset or resource title
* **catalog_title**: Catalog-level description
* **sector**: Broad sector tags (semicolon-separated)
* **sector_resource**: Granular sector tags (semicolon-separated, may be null)
* **ministry_department**: Governing ministry or department (semicolon-separated)
* **state_department**: State-level department (may be null)
* **note**: Additional notes or descriptions (may be null)
* **frequency**: Update frequency (e.g., Daily, Monthly)
* **granularity**: Level of data detail
* **govt_type**: Government level (Central or State)
* Other technical fields for context

---

## **Task Requirements**

### **1. Generate Enhanced Layman Keywords (`dcat:keyword`)**

Produce **6–10 layman-friendly keywords** that:

* Reflect the **core subject** of the dataset
* Use **simple, everyday language** understood by non-experts
* Capture both **broad and specific** dataset aspects (without jargon)
* Are helpful for discovery through general search (data.gov.in, Google, etc.)

**Keyword Rules**

* Each keyword must be **1–2 words only**
* Use **lowercase**; no punctuation except a single space for two-word terms
* Avoid duplicates
* Prefer only  **singular forms**, and not plural form. 
* Exclude technical or internal terms (e.g., “api”, “metadata”, “hmis”, “dcat”)
* Ignore ministry/department names and acronyms
* Parse semicolon-separated values into individual hints
* Use **India-relevant terms** when suitable (e.g., “mandi”, “rainfall”, “budget”)

---

### **2. Generate Sponsored Keywords**

Sponsored keywords represent **the most relevant, high-similarity search terms** directly tied to the dataset’s **title** or **note**.
These should:

* Be **1–2 words long**, short and intuitive
* Represent **the dataset’s main idea** or purpose
* Not include department names, locations (unless inherent), or administrative words
* Be a **subset or close match** of what a user might naturally type when searching for the dataset title

You should generate **3–5 sponsored keywords** that are:

* Derived from the **strongest overlaps** between the title/note and layman terms
* Ranked by relevance (first is most relevant)
* Still follow all the layman keyword rules (lowercase, no punctuation, ≤2 words)

---

### **3. Output Format**

Return **exactly three lines** (and nothing else).
The output must be valid JSON with the following format:

```
Title: <copy the title exactly as provided>
Enhanced Keywords: <kw1, kw2, kw3, kw4, kw5, kw6, kw7, kw8>
Sponsored Keywords: <kw1, kw2, kw3, kw4>
```

**Do not include:**

* Explanations, reasoning, or scores
* Department or ministry names
* Special symbols, punctuation, or formatting beyond this structure

---

## **Quality Guidelines**

* Focus on **discoverability** by laypeople, not metadata experts
* Keywords should make sense when read aloud (“someone would search this”)
* Avoid redundancy between Enhanced and Sponsored lists
* If `sector_resource` is missing, rely on title, catalog_title, and note
* Sponsored keywords should always sound like **real-world search queries** (e.g., “market prices”, “rainfall data”, “railway schedule”)

---

## **Error Handling**

* If the `title` field is empty, write: `Title: ` (keep it blank after the colon).
* Still generate both **Enhanced Keywords** and **Sponsored Keywords** to the best of your ability.
* Always return **exactly three lines** with no extra text, comments, or formatting.

---

## **Example**

**Input:**

```
title: "Variety-wise Daily Market Prices Data of Commodity"
sector: "Agriculture;Agricultural Marketing"
ministry_department: "Ministry of Agriculture and Farmers Welfare"
frequency: "Daily"
note: "Contains mandi price information for various crops and commodities."
```

**Output (in JSON):**

```
Title: Variety-wise Daily Market Prices Data of Commodity
Enhanced Keywords: mandi, market prices, crop prices, wholesale, daily data, agriculture, mandi rates, price trends, commodity prices
Sponsored Keywords: market prices, mandi prices, crop prices, commodity prices
```

---
# for HVD classification
You will receive an additional field in the input:

* `HVD Flag:` either `0` or `1`.

Interpret it as:

* `0` → the dataset is **not** marked as High Value.
* `1` → the dataset **is** marked as High Value and must be classified into one of the following categories:

1. `geospatial`
2. `earth observation and environment`
3. `meteorological`
4. `statistics`
5. `companies and company ownership`
6. `mobility`

#### HVD Rules

* If `HVD Flag` is `0`:
  * Do **not** classify it into any category.
  * Set `"hvd_category"` to an empty string `""`.

* If `HVD Flag` is `1`:
  * Use the dataset **Title**, **Catalog Title**, and **Note/Description** to decide the **single best-fit** category from the list above.
  * Output the category name exactly as one of:
    * `"geospatial"`, `"earth observation and environment"`, `"meteorological"`, `"statistics"`, `"companies and company ownership"`, `"mobility"`.


'''

In [15]:
def get_keywords(metadata_content):
    response=client.chat.completions.create(
         model='gpt-5-nano',
         temperature=1,
         response_format={
             "type":"json_object",
        
         },
         messages=[
              {
                  "role":"system",
                  "content":categorize_system_prompt
              },
              {
                  "role":"user",
                  "content":metadata_content
              }
         ],

    )
    return json.loads(response.choices[0].message.content)

In [ ]:
def get_enhanced_metadata(metadata_content):
    response = client.chat.completions.create(
        model='gpt-5-nano',
        temperature=1,
        response_format={"type": "json_object"},
        messages=[
            {
                "role": "system",
                "content": categorize_system_prompt
            },
            {
                "role": "user",
                "content": metadata_content
            }
        ],
    )
    return json.loads(response.choices[0].message.content)

In [9]:
df=pd.read_csv("/home/aakash/NIC/cdl-updated/nic-metadata-cleaning/data/ogd_metadata_sample/sample_dataset_nic.csv", encoding="cp1252", )
df.head()

,title,resource_category,description,catalog_title,govt_type,ministry_department,state_department,published_date,changed,created,...,field_high_value_dataset,field_show_export,cdos_state_ministry,is_rated,external_api_reference,note,node_alias,ogdp_download_count,ogdp_view_count,domain
0,Variety-wise Daily Market Prices Data of Commo...,Dataset,The data refers to prices of variety wise agri...,Current daily price of various commodities fro...,Central,Ministry of Agriculture and Farmers Welfare;De...,NaN,02-06-2024,27-06-2025,21-05-2024,...,1,True,Directorate of Marketing and Inspection (DMI),1,6622308.0,NaN,/resource/variety-wise-daily-market-prices-dat...,394032,167942,data.gov.in
1,Kisan Call Centre (KCC) - Transcripts of farme...,Dataset,This dataset comprises transcripts of farmers'...,District wise and month wise queries of farmer...,Central,Ministry of Agriculture and Farmers Welfare;De...,NaN,12-07-2024,27-06-2025,12-07-2024,...,1,True,Department of Agriculture and Farmers Welfare,1,6622307.0,NaN,/resource/kisan-call-centre-kcc-transcripts-fa...,219561,241962,data.gov.in
2,All India Pincode Directory till last month,Dataset,All India Pincode Directory through Webservice...,All India Pincode Directory (Through WebService),Central,Ministry of Communications;Department of Posts,NaN,04-12-2020,27-06-2025,04-12-2020,...,0,True,Department of Posts,1,6818292.0,Data will be updated on monthly basis.,/resource/all-india-pincode-directory-till-las...,105072,177619,data.gov.in
3,Registrars of Companies (RoC)-wise Company Mas...,Dataset,This dataset provides monthly RoC-wise master ...,Company Master Data,Central,Ministry of Corporate Affairs,NaN,24-04-2024,27-06-2025,15-09-2015,...,1,True,Ministry of Corporate Affairs,1,603037492.0,Figures Authorized Capital and Paid up Capital...,/resource/registrars-companies-roc-wise-compan...,39682,9035,data.gov.in
4,Current Daily Price of Various Commodities fro...,Dataset,This dataset records daily wholesale price obs...,Current daily price of various commodities fro...,Central,Ministry of Agriculture and Farmers Welfare;De...,NaN,23-05-2013,27-06-2025,23-05-2013,...,1,True,Directorate of Marketing and Inspection (DMI),1,3670701.0,NaN,/resource/current-daily-price-various-commodit...,37549,59612,data.gov.in

In [10]:
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
import csv
from threading import Lock

In [11]:
def extract_clean_value(value):
    """Clean and extract value from field"""
    if pd.isna(value) or value == 'nan' or value == '':
        return ""
    return str(value).strip()

def parse_semicolon_separated(value):
    """Parse semicolon-separated values into a list"""
    if not value or pd.isna(value):
        return []
    return [v.strip() for v in str(value).split(';') if v.strip()]

In [ ]:
def process_row_generation(row):
    """Process a single row"""
    # Extract all relevant fields from the actual CSV structure
    # Primary fields for enhancement
    title = extract_clean_value(row.get("dcterms:title", ""))
    description = extract_clean_value(row.get("dcterms:description", ""))
    existing_note = extract_clean_value(row.get("dcatin:note", ""))
    existing_alternative = extract_clean_value(row.get("dcterms:alternative", ""))
    existing_abstract = extract_clean_value(row.get("dcterms:abstract", ""))
    
    # Supporting metadata fields
    themes = parse_semicolon_separated(row.get("dcat:theme", ""))
    spatial = extract_clean_value(row.get("dcterms:spatial", ""))  # Removed space
    temporal = extract_clean_value(row.get("dcterms:temporal", ""))
    jurisdiction = extract_clean_value(row.get("dcatin:jurisdictionLevel", ""))
    frequency = extract_clean_value(row.get("dct:accrualPeriodicity", ""))
    temporal_res = extract_clean_value(row.get("dcat:temporalResolution", ""))
    keywords = extract_clean_value(row.get("dcat:keyword", ""))
    publisher = extract_clean_value(row.get("dcterms:publisher", ""))
    creator = extract_clean_value(row.get("dcterms:creator", ""))
    contact_name = extract_clean_value(row.get("vCard:fn", ""))  # Removed spaces
    org_name = extract_clean_value(row.get("vcard:organization-name", ""))  # Removed spaces
    data_type = extract_clean_value(row.get("dcterms:type", ""))
    media_type = extract_clean_value(row.get("dcat:mediaType", ""))
     
    # Build metadata content string for the LLM
    metadata_content = f'''
=== CURRENT METADATA ===
Title: {title}
Description: {description}
Existing Note: {existing_note}
Existing Alternative Title: {existing_alternative}
Existing Abstract: {existing_abstract}

=== CONTEXTUAL INFORMATION ===
Themes: {'; '.join(themes) if themes else 'Not specified'}
Keywords: {keywords if keywords else 'Not specified'}
Publisher: {publisher if publisher else 'Not specified'}
Creator: {creator if creator else 'Not specified'}
Organization: {org_name if org_name else 'Not specified'}
Contact Person: {contact_name if contact_name else 'Not specified'}

=== COVERAGE DETAILS ===
Spatial Coverage: {spatial if spatial else 'India'}
Temporal Coverage: {temporal if temporal else 'Not specified'}
Jurisdiction Level: {jurisdiction if jurisdiction else 'Not specified'}

=== DATA CHARACTERISTICS ===
Update Frequency: {frequency if frequency else 'Not specified'}
Temporal Resolution: {temporal_res if temporal_res else 'Not specified'}
Data Type: {data_type if data_type else 'Dataset'}
Media Type: {media_type if media_type else 'Not specified'}

TASK: Generate enhanced metadata values for all required fields according to the system prompt.
'''
    
    try:
        result = get_enhanced_metadata(metadata_content)
        logging.info(f"Processed: {title[:50]}...")
        
    except Exception as e:
        logging.error(f"LLM failed for '{title}': {e}")
        result = {
            "enhanced_title": title,
            "alternative_title": "",
            "enhanced_description": description,
            "short_description": "",
            "generated_note": "",
            "processing_summary": {
                "title_changes": "",
                "alternative_title_rationale": "",
                "description_changes": "",
                "short_description_rationale": "",
                "note_generation": "",
                "error": str(e)
            },
            "metadata_quality_score": 0.0,
            "quality_score_explanation": f"Processing failed: {str(e)}",
            "source_fields_used": []
        }
    
    return {
        "original_title": str(title),
        "original_description": str(description)[:500],
        "original_note": str(existing_note),
        "original_alternative": str(existing_alternative),
        "original_abstract": str(existing_abstract),
        "enhanced_title": result.get("enhanced_title", title),
        "alternative_title": result.get("alternative_title", ""),
        "enhanced_description": result.get("enhanced_description", description),
        "short_description": result.get("short_description", ""),
        "generated_note": result.get("generated_note", ""),
        "processing_summary": result.get("processing_summary", {}),
        "quality_score": result.get("metadata_quality_score", 0.0),
        "quality_score_explanation": result.get("quality_score_explanation", ""),
        "source_fields_used": result.get("source_fields_used", []),
        "themes": str('; '.join(themes) if themes else ''),
        "publisher": str(publisher),
        "jurisdiction": str(jurisdiction),
        "frequency": str(frequency),
        "llm_response": json.dumps(result)
    }

In [ ]:
# Main execution
input_file = "/home/prajna/civicdatalab/nic-metadata/nic-metadata-cleaning/data/original/metadata_transformation.csv"
output_file = "/home/prajna/civicdatalab/nic-metadata/nic-metadata-cleaning/data/metadata_cleaned_100_alt_title_short_description.csv"
df = pd.read_csv(input_file)
print(f"Loaded {len(df)} rows")
csv_lock = Lock()

fieldnames = [
    # Original fields
    "original_title", 
    "original_description", 
    "original_note",
    "original_alternative", 
    "original_abstract",
    
    # Enhanced fields
    "enhanced_title",
    "alternative_title", 
    "enhanced_description",
    "short_description",
    "generated_note",
    
    # Context fields
    "themes", 
    "keywords", 
    "publisher", 
    "creator", 
    "organization",
    "jurisdiction", 
    "frequency", 
    "spatial", 
    "temporal",
    
    # Processing metadata
    "quality_score",
    "quality_score_explanation",
    "title_changes",
    "alternative_title_rationale",
    "description_changes",
    "short_description_rationale",
    "note_generation",
    "source_fields_used",
    "llm_response"
]

with open(output_file, 'w', newline='', encoding='utf-8') as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()

results_array = []
max_workers = 8
rows_to_process = df.head(105)  # Change to df for all rows

with ThreadPoolExecutor(max_workers=max_workers) as executor:
    future_to_row = {
        executor.submit(process_row_generation, row): idx 
        for idx, row in rows_to_process.iterrows()
    }
    
    for future in as_completed(future_to_row):
        try:
            result_obj = future.result()
            
            # Flatten processing_summary into individual fields
            processing_summary = result_obj.get("processing_summary", {})
            csv_row = {
                # Original fields
                "original_title": result_obj.get("original_title", ""),
                "original_description": result_obj.get("original_description", ""),
                "original_note": result_obj.get("original_note", ""),
                "original_alternative": result_obj.get("original_alternative", ""),
                "original_abstract": result_obj.get("original_abstract", ""),
                
                # Enhanced fields
                "enhanced_title": result_obj.get("enhanced_title", ""),
                "alternative_title": result_obj.get("alternative_title", ""),
                "enhanced_description": result_obj.get("enhanced_description", ""),
                "short_description": result_obj.get("short_description", ""),
                "generated_note": result_obj.get("generated_note", ""),
                
                # Context fields
                "themes": result_obj.get("themes", ""),
                "keywords": result_obj.get("keywords", ""),
                "publisher": result_obj.get("publisher", ""),
                "creator": result_obj.get("creator", ""),
                "organization": result_obj.get("organization", ""),
                "jurisdiction": result_obj.get("jurisdiction", ""),
                "frequency": result_obj.get("frequency", ""),
                "spatial": result_obj.get("spatial", ""),
                "temporal": result_obj.get("temporal", ""),
                
                # Processing metadata
                "quality_score": result_obj.get("quality_score", 0.0),
                "quality_score_explanation": result_obj.get("quality_score_explanation", ""),
                "title_changes": processing_summary.get("title_changes", ""),
                "alternative_title_rationale": processing_summary.get("alternative_title_rationale", ""),
                "description_changes": processing_summary.get("description_changes", ""),
                "short_description_rationale": processing_summary.get("short_description_rationale", ""),
                "note_generation": processing_summary.get("note_generation", ""),
                "source_fields_used": json.dumps(result_obj.get("source_fields_used", [])),
                "llm_response": result_obj.get("llm_response", "")
            }
            
            results_array.append(csv_row)
            
            with csv_lock:
                with open(output_file, 'a', newline='', encoding='utf-8') as f:
                    writer = csv.DictWriter(f, fieldnames=fieldnames)
                    writer.writerow(csv_row)
            
            print(f"✓ {csv_row['original_title'][:60]}...")
            
        except Exception as e:
            logging.error(f"Row failed: {e}")

print(f"\n✓ Complete! Results saved to {output_file}")

Loaded 100 rows

2025-10-29 12:32:07,253 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-29 12:32:07,266 : INFO - Processed: Registrars of Companies (RoC)-wise Company Master ...
2025-10-29 12:32:07,272 : ERROR - Row failed: dict contains fields not in fieldnames: 'enhanced_description', 'generated_note', 'original_note', 'enhanced_title'
2025-10-29 12:32:08,089 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-29 12:32:08,093 : INFO - Processed: Current Daily Price of Various Commodities from Va...
2025-10-29 12:32:08,098 : ERROR - Row failed: dict contains fields not in fieldnames: 'enhanced_description', 'generated_note', 'original_note', 'enhanced_title'
2025-10-29 12:32:08,227 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-29 12:32:08,234 : INFO - Processed: Kisan Call Centre (KCC) - Transcripts of farmers q...
2025-10-29 12:32:08,237 : ERROR - Row failed: dict contains fields not in fieldnames: 'enhanced_description', 'generated_note', 'original_note', 'enhanced_title'
2025-10-29 12:32:09,838 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-29 12:32:09,843 : INFO - Processed: Daily Wholesale Mandi Market Prices of Agricultura...
2025-10-29 12:32:09,846 : ERROR - Row failed: dict contains fields not in fieldnames: 'enhanced_description', 'generated_note', 'original_note', 'enhanced_title'
2025-10-29 12:32:10,582 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-29 12:32:10,593 : INFO - Processed: Real time Air Quality Index from various locations...
2025-10-29 12:32:10,598 : ERROR - Row failed: dict contains fields not in fieldnames: 'enhanced_description', 'generated_note', 'original_note', 'enhanced_title'
2025-10-29 12:32:13,478 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-29 12:32:13,484 : INFO - Processed: Health indicator-wise monthly datasets at sub dist...
2025-10-29 12:32:13,493 : ERROR - Row failed: dict contains fields not in fieldnames: 'enhanced_description', 'generated_note', 'original_note', 'enhanced_title'
2025-10-29 12:32:15,218 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-29 12:32:15,222 : INFO - Processed: List of MSME Registered Units under UDYAM...
2025-10-29 12:32:15,226 : ERROR - Row failed: dict contains fields not in fieldnames: 'enhanced_description', 'generated_note', 'original_note', 'enhanced_title'
2025-10-29 12:32:24,517 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-29 12:32:24,519 : INFO - Processed: All India pincode directory updated till last mont...
2025-10-29 12:32:24,524 : ERROR - Row failed: dict contains fields not in fieldnames: 'enhanced_description', 'generated_note', 'original_note', 'enhanced_title'
2025-10-29 12:32:37,546 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-29 12:32:37,547 : INFO - Processed: Wholesale Price Index (Base Year 2011-12) till las...
2025-10-29 12:32:37,552 : ERROR - Row failed: dict contains fields not in fieldnames: 'enhanced_description', 'generated_note', 'original_note', 'enhanced_title'
2025-10-29 12:32:43,575 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-29 12:32:43,583 : INFO - Processed: All India and State/UT-wise Factsheets of National...
2025-10-29 12:32:43,587 : ERROR - Row failed: dict contains fields not in fieldnames: 'enhanced_description', 'generated_note', 'original_note', 'enhanced_title'
2025-10-29 12:32:44,510 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-29 12:32:44,515 : INFO - Processed: Voice Call Quality Customer Experience till last m...
2025-10-29 12:32:44,519 : ERROR - Row failed: dict contains fields not in fieldnames: 'enhanced_description', 'generated_note', 'original_note', 'enhanced_title'
2025-10-29 12:32:49,008 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-29 12:32:49,019 : INFO - Processed: FDI Equity Inflows from the year 2000 till last qu...
2025-10-29 12:32:49,022 : ERROR - Row failed: dict contains fields not in fieldnames: 'enhanced_description', 'generated_note', 'original_note', 'enhanced_title'
2025-10-29 12:32:56,749 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-29 12:32:56,752 : INFO - Processed: Month-wise All India Crowdsourced Mobile Data Spee...
2025-10-29 12:32:56,757 : ERROR - Row failed: dict contains fields not in fieldnames: 'enhanced_description', 'generated_note', 'original_note', 'enhanced_title'
2025-10-29 12:32:59,097 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-29 12:32:59,099 : INFO - Processed: Sub Divisional Monthly Rainfall from 1901 to 2017...
2025-10-29 12:32:59,103 : ERROR - Row failed: dict contains fields not in fieldnames: 'enhanced_description', 'generated_note', 'original_note', 'enhanced_title'
2025-10-29 12:33:00,435 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-29 12:33:00,439 : INFO - Processed: India Districts Factsheets of National Family Heal...
2025-10-29 12:33:00,445 : ERROR - Row failed: dict contains fields not in fieldnames: 'enhanced_description', 'generated_note', 'original_note', 'enhanced_title'
2025-10-29 12:33:03,855 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-29 12:33:03,860 : INFO - Processed: Daily data of reservoir level of Central Water Com...
2025-10-29 12:33:03,863 : ERROR - Row failed: dict contains fields not in fieldnames: 'enhanced_description', 'generated_note', 'original_note', 'enhanced_title'
2025-10-29 12:33:06,057 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-29 12:33:06,077 : INFO - Processed: Wholesale Price Index (Base Year 2011-12) till las...
2025-10-29 12:33:06,081 : ERROR - Row failed: dict contains fields not in fieldnames: 'enhanced_description', 'generated_note', 'original_note', 'enhanced_title'
2025-10-29 12:33:12,014 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-29 12:33:12,018 : INFO - Processed: Indian Railways Time Table for trains available fo...
2025-10-29 12:33:12,021 : ERROR - Row failed: dict contains fields not in fieldnames: 'enhanced_description', 'generated_note', 'original_note', 'enhanced_title'
2025-10-29 12:33:18,638 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-29 12:33:18,641 : INFO - Processed: Seasonal and Annual Mean Temperature Series for th...
2025-10-29 12:33:18,644 : ERROR - Row failed: dict contains fields not in fieldnames: 'enhanced_description', 'generated_note', 'original_note', 'enhanced_title'
2025-10-29 12:33:20,481 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-29 12:33:20,483 : INFO - Processed: Daily data of Soil Moisture...
2025-10-29 12:33:20,485 : ERROR - Row failed: dict contains fields not in fieldnames: 'enhanced_description', 'generated_note', 'original_note', 'enhanced_title'
2025-10-29 12:33:24,531 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-29 12:33:24,533 : INFO - Processed: Local Government Directory (LGD) - Villages with P...
2025-10-29 12:33:24,538 : ERROR - Row failed: dict contains fields not in fieldnames: 'enhanced_description', 'generated_note', 'original_note', 'enhanced_title'
2025-10-29 12:33:24,650 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-29 12:33:24,654 : INFO - Processed: District-wise, season-wise crop production statist...
2025-10-29 12:33:24,660 : ERROR - Row failed: dict contains fields not in fieldnames: 'enhanced_description', 'generated_note', 'original_note', 'enhanced_title'
2025-10-29 12:33:33,324 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-29 12:33:33,340 : INFO - Processed: Local Government Directory (LGD) - Local Bodies wi...
2025-10-29 12:33:33,343 : ERROR - Row failed: dict contains fields not in fieldnames: 'enhanced_description', 'generated_note', 'original_note', 'enhanced_title'
2025-10-29 12:33:44,114 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-29 12:33:44,116 : INFO - Processed: District Wise Total MSME Registered Enterprises un...
2025-10-29 12:33:44,120 : ERROR - Row failed: dict contains fields not in fieldnames: 'enhanced_description', 'generated_note', 'original_note', 'enhanced_title'
2025-10-29 12:33:48,329 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-29 12:33:48,330 : INFO - Processed: Crime Head-wise Police Disposal of IPC Crime Cases...
2025-10-29 12:33:48,333 : ERROR - Row failed: dict contains fields not in fieldnames: 'enhanced_description', 'generated_note', 'original_note', 'enhanced_title'
2025-10-29 12:33:50,347 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-29 12:33:50,349 : INFO - Processed: Global Youth Tobacco Survey (GYTS-4), India and St...
2025-10-29 12:33:50,352 : ERROR - Row failed: dict contains fields not in fieldnames: 'enhanced_description', 'generated_note', 'original_note', 'enhanced_title'
2025-10-29 12:33:52,254 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-29 12:33:52,258 : INFO - Processed: Rainfall in all India and its departure from norma...
2025-10-29 12:33:52,262 : ERROR - Row failed: dict contains fields not in fieldnames: 'enhanced_description', 'generated_note', 'original_note', 'enhanced_title'
2025-10-29 12:33:56,495 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-29 12:33:56,498 : INFO - Processed: Enrolment by Age and Class (UDISE plus) during 201...
2025-10-29 12:33:56,502 : ERROR - Row failed: dict contains fields not in fieldnames: 'enhanced_description', 'generated_note', 'original_note', 'enhanced_title'
2025-10-29 12:33:58,422 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-29 12:33:58,441 : INFO - Processed: DPIIT-Registered Startups by Sector, State, and Ye...
2025-10-29 12:33:58,447 : ERROR - Row failed: dict contains fields not in fieldnames: 'enhanced_description', 'generated_note', 'original_note', 'enhanced_title'
2025-10-29 12:34:00,884 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-29 12:34:00,890 : INFO - Processed: Shapefile of Rivers...
2025-10-29 12:34:00,895 : ERROR - Row failed: dict contains fields not in fieldnames: 'enhanced_description', 'generated_note', 'original_note', 'enhanced_title'
2025-10-29 12:34:06,683 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-29 12:34:06,687 : INFO - Processed: District wise Services MSME Registered Enterprises...
2025-10-29 12:34:06,693 : ERROR - Row failed: dict contains fields not in fieldnames: 'enhanced_description', 'generated_note', 'original_note', 'enhanced_title'
2025-10-29 12:34:15,275 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-29 12:34:15,286 : INFO - Processed: Seasonal and Annual Min/Max Temp Series - India fr...
2025-10-29 12:34:15,290 : ERROR - Row failed: dict contains fields not in fieldnames: 'enhanced_description', 'generated_note', 'original_note', 'enhanced_title'
2025-10-29 12:34:18,024 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-29 12:34:18,028 : INFO - Processed: Daily data of Evapotranspiration of NRSC...
2025-10-29 12:34:18,032 : ERROR - Row failed: dict contains fields not in fieldnames: 'enhanced_description', 'generated_note', 'original_note', 'enhanced_title'
2025-10-29 12:34:19,364 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-29 12:34:19,373 : INFO - Processed: All India Consumer Price Index (Rural/Urban) upto ...
2025-10-29 12:34:19,377 : ERROR - Row failed: dict contains fields not in fieldnames: 'enhanced_description', 'generated_note', 'original_note', 'enhanced_title'
2025-10-29 12:34:25,094 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-29 12:34:25,106 : INFO - Processed: District wise, Disability wise, Age group wise , G...
2025-10-29 12:34:25,110 : ERROR - Row failed: dict contains fields not in fieldnames: 'enhanced_description', 'generated_note', 'original_note', 'enhanced_title'
2025-10-29 12:34:26,451 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-29 12:34:26,454 : INFO - Processed: All India area weighted monthly, seasonal and annu...
2025-10-29 12:34:26,458 : ERROR - Row failed: dict contains fields not in fieldnames: 'enhanced_description', 'generated_note', 'original_note', 'enhanced_title'
2025-10-29 12:34:29,710 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-29 12:34:29,719 : INFO - Processed: Crime Head-wise Police Disposal of IPC Crime Cases...
2025-10-29 12:34:29,723 : ERROR - Row failed: dict contains fields not in fieldnames: 'enhanced_description', 'generated_note', 'original_note', 'enhanced_title'
2025-10-29 12:34:34,913 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-29 12:34:34,917 : INFO - Processed: Foreign Tourist Arrivals (FTAs), Arrivals of Non-R...
2025-10-29 12:34:34,922 : ERROR - Row failed: dict contains fields not in fieldnames: 'enhanced_description', 'generated_note', 'original_note', 'enhanced_title'
2025-10-29 12:34:48,008 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-29 12:34:48,010 : INFO - Processed: District-wise Demographic Data of Unorganised Work...
2025-10-29 12:34:48,013 : ERROR - Row failed: dict contains fields not in fieldnames: 'enhanced_description', 'generated_note', 'original_note', 'enhanced_title'
2025-10-29 12:34:48,336 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-29 12:34:48,338 : INFO - Processed: Year-wise retail inflation rate based on Consumer ...
2025-10-29 12:34:48,343 : ERROR - Row failed: dict contains fields not in fieldnames: 'enhanced_description', 'generated_note', 'original_note', 'enhanced_title'
2025-10-29 12:34:48,528 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-29 12:34:48,531 : INFO - Processed: Enrolment by Age and Class (UDISE plus) during 201...
2025-10-29 12:34:48,534 : ERROR - Row failed: dict contains fields not in fieldnames: 'enhanced_description', 'generated_note', 'original_note', 'enhanced_title'
2025-10-29 12:34:59,898 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-29 12:34:59,911 : INFO - Processed: Monthly Crude Oil Processed by Refineries...
2025-10-29 12:34:59,913 : ERROR - Row failed: dict contains fields not in fieldnames: 'enhanced_description', 'generated_note', 'original_note', 'enhanced_title'
2025-10-29 12:35:00,814 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-29 12:35:00,828 : INFO - Processed: CBSE Result Statistics Class XII - 2023...
2025-10-29 12:35:00,831 : ERROR - Row failed: dict contains fields not in fieldnames: 'enhanced_description', 'generated_note', 'original_note', 'enhanced_title'
2025-10-29 12:35:05,135 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-29 12:35:05,143 : INFO - Processed: GSVA by Economic Activity at Current Prices for Ta...
2025-10-29 12:35:05,148 : ERROR - Row failed: dict contains fields not in fieldnames: 'enhanced_description', 'generated_note', 'original_note', 'enhanced_title'
2025-10-29 12:35:08,692 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-29 12:35:08,694 : INFO - Processed: Statistics of Road Accidents in India From 2013 to...
2025-10-29 12:35:08,697 : ERROR - Row failed: dict contains fields not in fieldnames: 'enhanced_description', 'generated_note', 'original_note', 'enhanced_title'
2025-10-29 12:35:21,535 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-29 12:35:21,537 : INFO - Processed: Monthly mean maximum & minimum temperature and tot...
2025-10-29 12:35:21,540 : ERROR - Row failed: dict contains fields not in fieldnames: 'enhanced_description', 'generated_note', 'original_note', 'enhanced_title'
2025-10-29 12:35:23,984 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-29 12:35:23,986 : INFO - Processed: District-wise availability of health centres in In...
2025-10-29 12:35:23,990 : ERROR - Row failed: dict contains fields not in fieldnames: 'enhanced_description', 'generated_note', 'original_note', 'enhanced_title'
2025-10-29 12:35:31,150 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-29 12:35:31,151 : INFO - Processed: Monthly Consumption of Petroleum Products...
2025-10-29 12:35:31,155 : ERROR - Row failed: dict contains fields not in fieldnames: 'enhanced_description', 'generated_note', 'original_note', 'enhanced_title'
2025-10-29 12:35:40,591 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-29 12:35:40,596 : INFO - Processed: Area weighted monthly, seasonal and annual rainfal...
2025-10-29 12:35:40,601 : ERROR - Row failed: dict contains fields not in fieldnames: 'enhanced_description', 'generated_note', 'original_note', 'enhanced_title'
2025-10-29 12:35:47,582 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-29 12:35:47,587 : INFO - Processed: District-wise MGNREGA Data at a Glance...
2025-10-29 12:35:47,591 : ERROR - Row failed: dict contains fields not in fieldnames: 'enhanced_description', 'generated_note', 'original_note', 'enhanced_title'
2025-10-29 12:35:48,971 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-29 12:35:48,974 : INFO - Processed: District Wise Total  MSME Registered Manufacturing...
2025-10-29 12:35:48,978 : ERROR - Row failed: dict contains fields not in fieldnames: 'enhanced_description', 'generated_note', 'original_note', 'enhanced_title'
2025-10-29 12:35:49,199 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-29 12:35:49,206 : INFO - Processed: State-wise Population, Decadal Population Growth R...
2025-10-29 12:35:49,209 : ERROR - Row failed: dict contains fields not in fieldnames: 'enhanced_description', 'generated_note', 'original_note', 'enhanced_title'
2025-10-29 12:35:52,768 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-29 12:35:52,778 : INFO - Processed: District Level Manufacturing MSME Registered Enter...
2025-10-29 12:35:52,781 : ERROR - Row failed: dict contains fields not in fieldnames: 'enhanced_description', 'generated_note', 'original_note', 'enhanced_title'
2025-10-29 12:35:57,454 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-10-29 12:35:57,456 : INFO - Processed: Indian Sign Language Dictionary till January 2024...

✓ Complete! Results saved to /home/prajna/civicdatalab/nic-metadata/nic-metadata-cleaning/data/metadata_cleaned_100_alt_title_short_description.csv

In [12]:
import csv
from threading import Lock
from concurrent.futures import ThreadPoolExecutor, as_completed 
def process_row_keyword(row):
    """Process a single row - thread-safe"""
    title = row.get("title", "")
    catalog_title = row.get("catalog_title", "")
    ministry_department = row.get("ministry_department", "")
    sector = row.get("sector", "")
    sector_resource = row.get("sector_resource", "")
    cdos_state_ministry = row.get("cdos_state_ministry", "")
    note = row.get("note", "")
   
    metadata_content = f'''
    Title: {title}
    Catalog Title: {catalog_title}
    Ministry/Department: {ministry_department}
    Sector: {sector}
    Sector Resource: {sector_resource}
    CDOS State Ministry: {cdos_state_ministry}
    Note: {note}
    '''
   
    result = get_keywords(metadata_content) #JSON
    logging.info(f"Result is {result}")
   
    return {
        "title": title,
        "sector": sector,
        "metadata_input": metadata_content,
        "llm_response": json.dumps(result),  # JSON --> JSON String for CSV
        "generated_keywords": result.get("generated_keywords", ""),
        "generated_sponsored_keywords": result.get("generated_sponsored_keywords", ""),
        "generated_theme": result.get("generated_theme", ""),
        "justification": result.get("justification", ""),
        "confidence_score": result.get("confidence_score", 0),
        "metadata_gaps": json.dumps(result.get("metadata_gaps", []))  # List to JSON string
    }

# Setup CSV file
output_file = "results_100.csv"
csv_lock = Lock()  # Thread-safe file writes

# Write header
fieldnames = [
    "title", "sector", "metadata_input", "llm_response",
    "generated_keywords", "generated_sponsored_keywords", "generated_theme",
    "justification", "confidence_score", "metadata_gaps"
]

with open(output_file, 'w', newline='', encoding='utf-8') as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()

# Parallel processing
results_array = []
max_workers = 8

with ThreadPoolExecutor(max_workers=max_workers) as executor:
    future_to_row = {
        executor.submit(process_row_keyword, row): idx 
        for idx, row in df[:102].iterrows()
    }
    
    for future in as_completed(future_to_row):
        try:
            result_obj = future.result()
            results_array.append(result_obj)
            
            # Thread-safe incremental write
            with csv_lock:
                with open(output_file, 'a', newline='', encoding='utf-8') as f:
                    writer = csv.DictWriter(f, fieldnames=fieldnames)
                    writer.writerow(result_obj)
            
            print(f"TITLE: {result_obj['title']}\nSECTOR: {result_obj['sector']}\n\n✓ Written to CSV")
            print("\n----------------------------\n")
            
        except Exception as e:
            logging.error(f"Row processing failed: {e}")

print(f"\n✓ Complete! Results saved to {output_file}")

2026-01-15 10:35:21,721 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:35:21,743 : INFO - Result is {'generated_keywords': 'health data, monthly data, sub district, health indicator, public health, health statistics, district level', 'generated_sponsored_keywords': 'health data, monthly indicator, sub district, health facility, district data', 'generated_theme': 'Health, Family Welfare', 'justification': "Source fields used: title (for temporal and scope clues), sector (Health and Family welfare; Health; Family Welfare), sector_resource (repeated health-related terms to reinforce domain), note (data origin by health facilities across states/UTs), ministry_department (to be ignored for keywording per rules). Extraction/normalization rules applied: parsed semicolon-separated values in sector and sector_resource to assemble domain concepts; avoided acronyms and department names in keywords; ensured 1–2 word layman terms and used singular forms where applicable (e.g., indicator). Temporal aspect inferred from title ('monthly datasets') and reflected in keywords (monthly data; monthly indicator in sponsored keywords). Keywords exclude technical terms and acronyms like HMIS; included India-relevant context such as reference to health facilities and sub-district level scope. Theme mapping used SECTOR_VOCAB_JSON: linked to Health and Family Welfare (Health; Family Welfare) as the subject themes. Sponsored keywords are concise overlaps directly tied to the title/note (e.g., health data, monthly indicator, sub district, health facility, district data). Notes from the dataset (data reported by health facilities across States/UTs) informed the inclusion of 'health facility' in sponsored terms. Ambiguities/assumptions: frequency and granularity fields are not present in the provided data, which constrains time-series/temporal granularity tagging; state_department field is not separately provided beyond the CDOS/state ministry context, so it’s not used as a keyword.", 'confidence_score': 0.85, 'metadata_gaps': 'frequency missing; granularity missing; state_department missing'}

TITLE: Health indicator-wise monthly datasets at sub district level from HMIS
SECTOR: Health and Family welfare;Family Welfare;Health

✓ Written to CSV

----------------------------

2026-01-15 10:35:23,619 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:35:23,622 : INFO - Result is {'generated_keywords': 'air quality, real time, air monitoring, air pollution, environment, location, live data', 'generated_sponsored_keywords': 'real time, air quality, air monitoring, live data', 'generated_theme': 'Industrial Air Pollution, Residential Air Pollution, Vehicular Air Pollution', 'justification': 'Source columns used: title (Real time Air Quality Index from various locations) to identify core concepts; sector and sector_resource (Environment and Forest; Industrial Air Pollution; Residential Air Pollution; Vehicular Air Pollution) to map to SECTOR_VOCAB_JSON sub-sectors; note (mentions real-time live data and potential data quality issues) to capture timeliness and data quality context; ministerial fields were ignored for keywords per guidelines. Extraction rules: split semicolon-separated values in sector/sector_resource to extract individual themes; normalize to lowercase and singular where applicable; avoid department names and acronyms; derive layman terms that describe ambient air quality and real-time monitoring. Keyword selection rationale: include core subjects from title (air quality, real time), include dataset scope (air monitoring, air pollution, environment, location) and include real-time/live aspects from note. Sponsored keywords chosen from strongest overlaps with title/note (real time, air quality, air monitoring, live data). Theme mapping uses SECTOR_VOCAB_JSON: align to Industrial Air Pollution, Residential Air Pollution, and Vehicular Air Pollution, which are explicitly represented in the dataset’s sector terms. Ambiguities/assumptions: dataset covers multiple pollutant sources (industrial, residential, vehicular) which is reflected in multiple themes; no geographic location names are included to avoid location-based terms. Note mentions live data with possible aberrations, which informs the emphasis on real-time monitoring and data quality in justification.', 'confidence_score': 0.9, 'metadata_gaps': ['frequency', 'granularity', 'state_department']}

TITLE: Real time Air Quality Index from various locations
SECTOR: Environment and Forest;Industrial Air Pollution;Residential Air Pollution;Vehicular Air Pollution

✓ Written to CSV

----------------------------

2026-01-15 10:35:25,464 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:35:25,468 : INFO - Result is {'generated_keywords': 'company data, registrar data, company records, master data, rupee capital, paid capital, authorized capital, company details', 'generated_sponsored_keywords': 'registrar data, company data, master data, company records', 'generated_theme': 'Commerce, Companies', 'justification': 'Source extraction: used title and sector fields. Sector was semicolon-separated into two hints: Commerce and Companies, which map to SECTOR_VOCAB_JSON under the Commerce theme and its sub-sector Companies. The note provides capital-related context (capital values in INR), which informed inclusion of capital-related keywords and currency term. Keywords were constrained to 1–2 words, lowercase, singular where possible, and avoided acronyms or department names. From the title “Registrars of Companies (RoC)-wise Company Master Data,” the core subjects identified are company data/master data and registrar/records aspects; thus keywords reflect company data, registrar/records, and capital details. Sponsored keywords are a focused subset aligned with the title/note, prioritizing registrar data, company data, master data, and company records. The theme uses the controlled vocabulary: Commerce as the high-level sector, with Companies as a sub-sector. Excluded terms include ministry names and acronyms (e.g., RoC) per guidelines. Ambiguities: the acronym RoC is avoided in keywords; the phrase “wise” is not represented directly in keywords but implied by sector granularity. Overall, the selections aim for discoverability while staying within policy constraints.', 'confidence_score': 0.9, 'metadata_gaps': ['state_department', 'frequency', 'granularity', 'govt_type']}

TITLE: Registrars of Companies (RoC)-wise Company Master Data
SECTOR: Commerce;Companies

✓ Written to CSV

----------------------------

2026-01-15 10:35:26,847 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:35:26,849 : INFO - Result is {'generated_keywords': 'commodity, price, daily, market, mandi, agriculture, marketing, price data', 'generated_sponsored_keywords': 'market price, mandi, commodity price, daily price, price data', 'generated_theme': 'Agriculture; Agricultural Marketing', 'justification': "Source fields used: title, sector, sector_resource, catalog_title, note. Extraction rules applied: (1) parsed sector into two parts (Agriculture; Agricultural Marketing) and used these as the thematic anchors. (2) derived layman keywords from the title and catalog_title phrases: 'daily', 'market', 'price', 'commodity', and the Indian market term 'mandi' inferred from the catalog title (Current daily price of various commodities from various markets (Mandi)). (3) normalized terms to singular where appropriate (e.g., market, price, commodity) and kept each keyword to 1–2 words. (4) included 'price data' to reflect the data nature and to avoid generic terms. (5) generated sponsored keywords as a subset focused on user search behavior closely tied to the title: market price, mandi, commodity price, daily price, price data. (6) mapped the theme to the SECTOR_VOCAB_JSON: Agriculture with sub-sector Agricultural Marketing, aligning with the dataset’s focus on prices within agricultural markets. (7) note field is missing, which reduces confidence slightly per null-field handling rule, while sector_resource is null but handled by relying on sector and title. (8) avoided department names and acronyms and did not introduce new subjects beyond the provided vocabulary. Ambiguities/assumptions: assumed 'mandi' relevance based on catalog_title reference to markets; treated 'nan' note as null; used the most explicit terms from available fields rather than inferring additional data attributes like frequency beyond the explicit 'Daily'.", 'confidence_score': 0.9, 'metadata_gaps': 'sector_resource; note; frequency; granularity; govt_type'}

TITLE: Variety-wise Daily Market Prices Data of Commodity
SECTOR: Agriculture;Agricultural Marketing

✓ Written to CSV

----------------------------

2026-01-15 10:35:29,389 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:35:29,394 : INFO - Result is {'generated_keywords': 'micro enterprise, small enterprise, medium enterprise, industry data, registered unit, business registration, udyam registration, enterprise data', 'generated_sponsored_keywords': 'udyam registration, registered unit, business registration, micro enterprise', 'generated_theme': 'Industries, Micro, Small Scale, Medium', 'justification': 'Source columns used: title, catalog_title, sector, sector_resource, ministry_department, and note. Extraction rules applied: (1) parse semicolon-separated values in sector to capture individual hints; (2) normalize terms to singular where appropriate (e.g., industry instead of industries) and focus on layman-friendly concepts; (3) derive keywords from core concepts in the title/catalog (MSME, UDYAM, registration) while avoiding department names and acronyms. Rationale for keywords: the dataset lists MSME registered units under UDYAM, with sector indicators showing Industry size classifications (Micro, Small Scale, Medium). Therefore keywords reflect enterprise size (micro/small/medium), the registration process (registration, udyam), and the notion of registered units and industry data. Why certain terms are included/excluded: included terms emphasize the registration and enterprise aspects that users would search for; avoided are internal codes or department acronyms beyond the program name (UDYAM kept as a recognized program term). Ambiguities/assumptions: sector_resource and note fields show as nan, so reliance on sector and title is necessary; this limits contextual nuance and may affect precision of theme mapping. Theme mapping uses SECTOR_VOCAB_JSON: Industries as the broad sector, with Micro, Small Scale, and Medium as sub-sectors to reflect the size classes present in the sector field. If sector_resource or note had meaningful content, they could broaden or shift the theme, but currently they are not informative.', 'confidence_score': 0.8, 'metadata_gaps': 'sector_resource, note, frequency, granularity, state_department'}

TITLE: List of MSME Registered Units under UDYAM
SECTOR: Industries;Medium;Micro;Small Scale

✓ Written to CSV

----------------------------

2026-01-15 10:35:29,629 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:35:29,632 : INFO - Result is {'generated_keywords': 'mandi, commodity price, market price, agricultural marketing, daily price, price information, crop price', 'generated_sponsored_keywords': 'mandi, commodity price, market price, daily price, price information', 'generated_theme': 'Agricultural Marketing, Prices', 'justification': "Source usage:\n- title: used to identify core concepts like daily price, commodities, and mandi markets.\n- sector and sector_resource: extracted semicolon-separated values to align with the Agriculture -> Agricultural Marketing domain; mapped to the SECTOR_VOCAB_JSON sub-sector 'Agricultural Marketing' and the economy sub-theme 'Prices' to reflect price-focused data.\n- note: treated as null (nan), so no additional note-based terms were added.\n- ministry_department: ignored for keyword generation to avoid policy-related terms; used only for contextual understanding.\n\nExtraction and normalization:\n- Parsed semicolon-separated values in sector and sector_resource to derive individual hints: 'Agriculture' and 'Agricultural Marketing'. These map to the SECTOR_VOCAB_JSON theme 'Agricultural Marketing'.\n- Derived layman-friendly terms from the dataset description: mandi, commodity price, market price, daily price, price information, crop price. Terms are kept to 1–2 words, lowercase, singular where applicable, and avoid technical jargon or department names.\n- Excluded department names and acronyms (e.g., MoA, DMI) and avoided pluralization of core terms where unnecessary to meet the singular form preference.\n- Included India-relevant context (mandi) as it directly relates to Indian market terminology.\n\nRationale for term choices:\n- mandi: directly reflects the market type referenced in the title, a culturally relevant Indian term.\n- commodity price / market price / crop price: capture the dataset’s focus on prices across various commodities and markets.\n- daily price / price information: align with the 'Current Daily Price' descriptor and provide a discoverable, general search angle.\n- agricultural marketing: derived from sector, captures the domain context of price information within the agricultural market system.\n- Prices (theme) included to align with the SECTOR_VOCAB_JSON economy sub-theme and to enable cross-dataset discovery on price data.\n\nAmbiguities and assumptions:\n- Note field is null; no note-derived terms were added.\n- Update frequency, granularity, and governance type are not provided; frequency is inferred from the title but no explicit field confirmation is available, so this is treated as metadata-driven inference rather than explicit field data.\n- State-level department and other administrative fields are not used in keyword generation to avoid conflating governance terms with user-facing discovery terms.\n", 'confidence_score': 0.8, 'metadata_gaps': 'frequency, granularity, govt_type, note, state_department'}

TITLE: Current Daily Price of Various Commodities from Various Markets (Mandi)
SECTOR: Agriculture;Agricultural Marketing

✓ Written to CSV

----------------------------

2026-01-15 10:35:33,130 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:35:33,133 : INFO - Result is {'generated_keywords': 'farmer query, agriculture query, call centre, farmer support, transcripts, district data, monthly data, advisory service, crop query', 'generated_sponsored_keywords': 'farmer query, call centre, district query, monthly query, transcripts', 'generated_theme': 'Agriculture', 'justification': "Sources used: title, catalog_title, sector. sector_resource and note are null; state_department is also not provided. Extraction/normalization: derived keywords from title/catalog_title (Kisan Call Centre -> call centre; transcripts of farmers queries & answers -> farmer query; district wise and month wise -> district data and monthly data; singularized 'queries' to 'query'). Terms are kept layman-friendly and India-relevant while avoiding acronyms and department names. Theme mapped to SECTOR_VOCAB_JSON under Agriculture; no specific sub-sector cleanly fits, so only Agriculture is applied. Null note reduces confidence by 0.1; sector_resource being null led to relying on sector/title for keyword derivation. Assumptions: district-wise and monthly aspects are inferred from catalog_title, not explicitly stated elsewhere. Exclusions: no location or department terms are included in keywords.", 'confidence_score': 0.9, 'metadata_gaps': 'sector_resource, note, state_department'}

TITLE: Kisan Call Centre (KCC) - Transcripts of farmers queries & answers
SECTOR: Agriculture

✓ Written to CSV

----------------------------

2026-01-15 10:35:33,713 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:35:33,716 : INFO - Result is {'generated_keywords': 'pincode, directory, postal codes, pin code, address data, postal service, postal directory, india post', 'generated_sponsored_keywords': 'pincode directory, postal codes, monthly update, india post', 'generated_theme': 'Information and Communications, Post', 'justification': 'Source fields used: title, sector, sector_resource, note, and ministry_department. Extraction steps and rules: \n- Parsed sector values: Information and Communications; Post, and sector_resource: Post, to infer themes aligned with the SECTOR_VOCAB_JSON; excluded ministry/department names from keyword generation per guidelines. \n- Title processing: All India Pincode Directory till last month → derived core concepts: pincode, directory. Combined with the catalog concept to form terms like postal codes, pin code, and directory related terms. \n- Note processing: Data will be updated on monthly basis → used to generate a temporal, sponsored term: monthly update. \n- Semantic normalization: converted to lowercase, ensured 1–2 word terms where possible, and avoided technical/internal terms. Duplicates removed. \n- Derived layman keywords reflect domain concepts without department names: pincode, directory, postal codes, pin code, address data, postal service, postal directory, india post. \n- Sponsored keywords chosen from strongest overlaps with title/note: pincode directory (title overlap), postal codes (domain), monthly update (note), india post (domain entity). \n- Theme mapping: mapped to SECTOR_VOCAB_JSON high-level and sub-sector: Information and Communications and its sub-sector Post, forming the theme "Information and Communications, Post". If a broader category was needed, it would be the high-level Information and Communications. \n- Formatting decisions: output follows 2–4 themes cap, kept at two items; keywords kept to 1–2 words each; all in lowercase. \nAssumptions: counted India-related terms via the title (All India) and the note implies monthly updates; avoided using ministry department names as keywords. Ambiguities resolved by prioritizing commonly understood terms for pin code directories and postal data.', 'confidence_score': 0.9, 'metadata_gaps': 'frequency field is not explicitly provided (note mentions monthly updates); granularity and state_department fields were not provided or used; CDOS state ministry present in note but not in a dedicated field; some fields like frequency/granularity could improve temporal tagging if provided'}

TITLE: All India Pincode Directory till last month
SECTOR: Information and Communications;Post

✓ Written to CSV

----------------------------

2026-01-15 10:35:55,914 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:35:55,918 : INFO - Result is {'generated_keywords': 'reservoir level, water level, daily data, water resource data, reservoir data, hydrology data, public data', 'generated_sponsored_keywords': 'reservoir level, daily data, water data, reservoir data, hydrology data', 'generated_theme': 'Surface Water', 'justification': 'Source columns used: title (for extraction of core concepts daily data and reservoir level), sector (Water Resources used to map to the appropriate subject), frequency (conceptual basis for including daily in keywords). Notes on semicolon-separated fields: none present; sector_resource is null, note is null, so extraction relied heavily on title and sector. Extraction/normalization rules applied: keywords are 1–2 words, lowercase, no punctuation, avoid duplicates, prefer singular forms where possible, exclude ministry/department names and acronyms, and parse semicolon-separated values if present (none here). Reasoning for keyword selection: core subjects identified from title—reservoir level and daily data; additional related terms chosen to improve discovery while staying non-technical and user-friendly (water resource data, reservoir data, hydrology data, water level, public data). Temporal indication included via ', " daily data to reflect daily updates. Theme assignment used SECTOR_VOCAB_JSON: sector 'Water Resources' maps to sub-sector 'Surface Water', which best represents reservoir level data linked to surface water resources. Exclusions: avoided department names (e.g., Ministry/Department) and acronyms (e.g., CWC).\nAmbiguities/assumptions: assuming reservoir level data pertains to surface water storage; note and sector_resource fields are missing, so confidence relies on title; frequency not explicitly provided but implied by the word 'Daily' in the title, used to justify including daily in keywords. The dataset lacks granularity and govt_type details, so those fields are not explicitly reflected in the theme beyond the surface water mapping.\nNotes on potential improvements: if frequency/granularity were provided, additional time-related keywords (e.g., daily, time-series) could be added to enhance discovery further, and a second theme could be added if more precise sub-sectors were available in metadata.": '', 'confidence_score': 0.9, 'metadata_gaps': 'sector_resource; note; frequency; granularity; govt_type'}

TITLE: Daily data of reservoir level of Central Water Commission (CWC)
SECTOR: Water Resources

✓ Written to CSV

----------------------------

2026-01-15 10:36:11,593 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:36:11,596 : INFO - Result is {'generated_keywords': 'wholesale price, price index, economy, inflation, monthly, provisional, statistics', 'generated_sponsored_keywords': 'wholesale price, price index, provisional, monthly', 'generated_theme': 'Economy; Prices; Finance', 'justification': 'Source columns used: title (Wholesale Price Index till last month) to identify core topic; sector and sector_resource (Economy; Prices; Finance; Economy) to derive domain terms; note (Data for last two months are provisional) to capture data timeliness and provisional status. Extraction/normalization rules applied: 1) Split semicolon-separated values in sector and sector_resource to obtain distinct domain terms; 2) Normalize terms to layman-friendly, 1–2 word phrases in lowercase; 3) Prefer singular forms (e.g., price not prices) and avoid department names in keywords; 4) Derive time-related and provisional cues from the title and note (e.g., monthly, provisional). Why terms were selected: core subject is price related (Wholesale Price Index) tied to economy and finance sectors; inflation is a natural layman interpretation of price changes; monthly and provisional reflect data cadence and provisional status from the note/title. Why terms were excluded: avoided acronyms, department names, and overly technical terms; avoided duplicating title phrases unless essential. Ambiguities/assumptions: frequency is not explicitly provided; inferred monthly cadence from phrases like “till last month” and note referencing last two months; base year detail not included in layman keywords due to formatting constraints. ', 'confidence_score': 0.8, 'metadata_gaps': 'state_department; frequency; granularity; govt_type'}

TITLE: Wholesale Price Index (Base Year 2011-12) till last month
SECTOR: Economy;Prices;Finance;Economy

✓ Written to CSV

----------------------------

2026-01-15 10:36:12,948 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:36:12,952 : INFO - Result is {'generated_keywords': 'district health, health survey, family health, district data, health indicator, population data, maternal health, child health, district factsheet', 'generated_sponsored_keywords': 'district factsheet, health survey, india health, district data', 'generated_theme': 'Health and Family welfare; Health, Health and Family welfare; Family Welfare', 'justification': "Source fields used: title, sector, sector_resource, note, ministry_department. Processing steps: 1) Split semicolon-separated values in sector and sector_resource to understand domain emphasis; 2) Derive layman keywords from core concepts in the title and note, favoring singular forms and avoiding department names; 3) Map to SECTOR_VOCAB_JSON themes using the top-level 'Health and Family welfare' with sub-sectors 'Health' and 'Family Welfare' to reflect the NFHS district factsheet focus; 4) Generate sponsored keywords from strong overlaps with the title/note (e.g., district factsheet, health survey). Assumptions: the dataset concerns district-level health data from NFHS-5 in India; singularize plural terms where reasonable (e.g., district vs districts); exclude acronyms like NFHS and avoid department names in keywords. Note fields confirm district-level health survey context, supporting health-related keywords. Ambiguities resolved by prioritizing district-level health focus and NFHS-5 district factsheet context. ", 'confidence_score': 0.75, 'metadata_gaps': ['state_department', 'frequency', 'granularity', 'govt_type']}

TITLE: India Districts Factsheets of National Family Health Survey (NFHS) - 5, 2019-2021 (Provisional)
SECTOR: All;Health and Family welfare

✓ Written to CSV

----------------------------

2026-01-15 10:36:14,289 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:36:14,292 : INFO - Result is {'generated_keywords': 'health survey, family health, state wise, india, factsheets, health data, population health', 'generated_sponsored_keywords': 'health survey, state wise, factsheets, family health, india', 'generated_theme': 'Health, Family Welfare', 'justification': "Source columns used: title, sector, sector_resource, note, and catalog_title. The semicolon-separated values in sector and sector_resource were split into individual hints and deduplicated.  Key terms extracted from the title include 'factsheets' and references to a national/India-wide health study, which align with common layman search terms for this dataset. To maintain simplicity and accessibility, terms were limited to 1–2 words and kept in lowercase, avoiding department names and acronyms (e.g., NFHS, IIPS) per guidelines. India-specific context was favored (india) due to the dataset scope ('All India and State/UT-wise'). From the SECTOR_VOCAB_JSON, the relevant high-level themes are Health and Family Welfare, mapped to sub-themes Health and Family Welfare, which are reflected in the generated_theme as Health, Family Welfare. The notes are informational and did not yield additional keywords beyond context; frequency/granularity and govt_type fields are not provided, so themes rely on the sector information. Ambiguities include absence of explicit frequency/granularity data and state department details, which are noted as metadata gaps.", 'confidence_score': 0.9, 'metadata_gaps': 'frequency, granularity, govt_type, state_department'}

TITLE: All India and State/UT-wise Factsheets of National Family Health Survey (NFHS) - 5, 2019-2021
SECTOR: Health and Family welfare;Family Welfare

✓ Written to CSV

----------------------------

2026-01-15 10:36:18,432 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:36:18,435 : INFO - Result is {'generated_keywords': 'foreign investment, fdi inflow, equity inflow, quarterly data, investment inflow, commerce, quarterly update', 'generated_sponsored_keywords': 'fdi inflow, equity inflow, foreign investment, quarterly data, investment data', 'generated_theme': 'Macro Economy, Commerce', 'justification': 'Sources used: title, sector, sector_resource, and note. The semicolon-separated ministry_department entry was split to identify potential context but department names are not used as keywords per guidelines. Extraction rules applied: ', 'confidence_score': 0.8, 'metadata_gaps': 'frequency, granularity, govt_type'}

TITLE: FDI Equity Inflows from the year 2000 till last quarter
SECTOR: Commerce

✓ Written to CSV

----------------------------

2026-01-15 10:36:27,409 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:36:27,411 : INFO - Result is {'generated_keywords': 'voice quality, call quality, customer experience, network performance, last month, service quality, user experience, call experience', 'generated_sponsored_keywords': 'voice quality, call quality, customer experience, last month, call experience', 'generated_theme': 'Information and Communications, Telecom', 'justification': "Source usage: title, sector, and sector_resource were used to identify core topics; note field is null (nan), frequency/granularity not provided, and govt_type not specified. Processing rules applied: semicolon-separated values in sector and sector_resource were expanded and deduplicated; terms were normalized to lowercase and kept singular where possible; ministry/department names and acronyms were excluded from keyword generation. Reasoning for keywords: the title highlights voice/call quality and customer experience in the telecom/information and communications domain, with a time reference ('till last month') that supports temporal context like 'last month'. Chosen layman keywords reflect both the main subject (voice quality, call quality, customer experience) and related aspects (network performance, service quality) without technical jargon. Sponsored keywords are a tight subset of the layman terms most closely aligned with the title/note concepts. Theme mapping uses the SECTOR_VOCAB_JSON entries relevant to the dataset domain: Information and Communications and its sub-sector Telecom. Ambiguities/assumptions: the note is missing, so a minor confidence impact is applied; there is no explicit frequency/granularity in the provided data, and TRAI (state department) is an organizational entity not included in keyword terms per guidelines.", 'confidence_score': 0.8, 'metadata_gaps': 'note field missing (null); frequency not provided; granularity not provided; govt_type not provided; state_department present in input but not used in keywords; sector_resource contained repeated values requiring normalization'}

TITLE: Voice Call Quality Customer Experience till last month
SECTOR: Information and Communications;Telecom

✓ Written to CSV

----------------------------

2026-01-15 10:36:29,208 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:36:29,255 : INFO - Result is {'generated_keywords': 'rainfall, monthly rainfall, historical rainfall, india rainfall, climate data, weather data, precipitation data, time series', 'generated_sponsored_keywords': 'monthly rainfall, rainfall india, historical rainfall, precipitation data', 'generated_theme': 'Earth Sciences, Atmospheric Science', 'justification': 'Source fields used: title (to identify core subject rainfall and monthly scope), catalog_title (Rainfall in India for geographic context), sector and sector_resource (Science and Technology; Atmospheric Science; Earth Sciences to anchor domain), ministry_department (extracting parent ministry but excluding acronyms from keywords), and note (unit context MMS) were considered but not included as keywords. Processing steps: (1) Parsed semicolon-separated values in sector and sector_resource to identify relevant domains (Earth Sciences; Atmospheric Science). (2) Normalized terms to lowercase, removed department acronyms, and avoided administrative terms. (3) Created layman-friendly keywords (1–2 words each) capturing core subject and geographic scope, prioritizing India-relevant terms. (4) Generated sponsored keywords by deriving direct overlaps with the title (monthly rainfall, india rainfall) and aligning with note/context (precipitation data). (5) Generated themes by mapping to SECTOR_VOCAB_JSON items: Earth Sciences and Atmospheric Science under Science and Technology. Exclusions: avoided department names, acronyms (IMD), and technical jargon. Assumptions: dataset covers historical monthly rainfall data for India (1901–2017) implied by title and catalog title; used broad terms like climate data and weather data to aid discoverability while staying within layman language.', 'confidence_score': 0.9, 'metadata_gaps': 'state_department; frequency; granularity; govt_type'}

TITLE: Sub Divisional Monthly Rainfall from 1901 to 2017
SECTOR: Science and Technology;Atmospheric Science;Earth Sciences

✓ Written to CSV

----------------------------

2026-01-15 10:36:29,602 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:36:29,604 : INFO - Result is {'generated_keywords': 'mobile data, data speed, crowdsourced data, download speed, upload speed, telecom data, monthly data, india', 'generated_sponsored_keywords': 'mobile data, data speed, crowdsourced data, monthly data, speed measurement', 'generated_theme': 'Information and Communications; Telecom', 'justification': 'Source fields used: title, sector, sector_resource, and note. Processing steps: parsed semicolon-separated values in sector and sector_resource to identify domain terms; extracted core concepts from the title (crowdsourced mobile data speed measurement) and note context to support keyword decisions; normalized terms to lowercase, singular where applicable, and limited to 1–2 words per keyword. Rules applied: (1) generate 4–10 layman keywords, 1–2 words each, lowercase, no punctuation; (2) avoid department names and acronyms; (3) emphasize India-relevant context when suitable (dataset is All India). Keyword choices reflect the dataset’s core subject: mobile data speeds measured via crowdsourced data across India, with emphasis on speed (download/upload), data nature, and monthly cadence. Sponsored keywords are derived from key overlaps between the title/note and layman terms, focusing on the most direct user search terms. Theme selection used the SECTOR_VOCAB_JSON hierarchy: Information and Communications with sub-sector Telecom, aligning with the dataset’s domain. Assumptions/clarifications: frequency is inferred as monthly from the title (month-wise) rather than provided as a separate field; sector_resource includes repeated Information and Communications; no specialized acronyms were introduced in keywords. Ambiguities/limitations: the note mentions sampling limitations and technical test attributes, which do not directly alter the chosen discovery keywords but could inform future enrichment (e.g., sampling quality, test type).', 'confidence_score': 0.8, 'metadata_gaps': []}

TITLE: Month-wise All India Crowdsourced Mobile Data Speed Measurement
SECTOR: Information and Communications;Telecom

✓ Written to CSV

----------------------------

2026-01-15 10:36:54,300 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:36:54,303 : INFO - Result is {'generated_keywords': 'temperature, seasonal temperature, annual temperature, mean temperature, time series, climate data, india weather, historic temperature, temperature trend, weather series', 'generated_sponsored_keywords': 'seasonal temperature, annual temperature, mean temperature, temperature series, time series', 'generated_theme': 'Earth Sciences, Atmospheric Science', 'justification': "Source columns used: title, sector, sector_resource, note. Extraction/normalization rules: - Parsed semicolon-separated values in sector and sector_resource to identify domain context; sector_resource provided 'Earth Sciences' which reinforces the domain. - Generated layman keywords from the title and inferred concepts (seasonal vs annual, mean temperature, series) to ensure discoverability for non-expert users. - Converted terms to singular where appropriate and kept to 1–2 word phrases; avoided department names in keywords per guidance. - Sponsored keywords derived from strong overlaps between the title (Seasonal and Annual Mean Temperature Series) and layman terms (seasonal temperature, annual temperature, mean temperature, temperature series, time series). - Thematic mapping used SECTOR_VOCAB_JSON: mapped to high-level 'Earth Sciences' and sub-theme 'Atmospheric Science' to reflect meteorological/temperature data. Note field is null ('nan'), so no additional context was added from notes. Ambiguities/assumptions: Assumed nationwide, seasonality, and annual mean temperature series based on catalog title; no explicit geographic scope beyond 'All India' in catalog/title, so geography not expanded into keywords beyond 'india weather' for relevance. The ministry/department field was consulted for domain alignment but not directly used in keywords to avoid administrative bias.", 'confidence_score': 0.8, 'metadata_gaps': ['note field is null (nan)', 'state_department field not provided']}

TITLE: Seasonal and Annual Mean Temperature Series for the period 1901-2021
SECTOR: Science and Technology;Earth Sciences

✓ Written to CSV

----------------------------

2026-01-15 10:36:57,122 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:36:57,123 : INFO - Result is {'generated_keywords': 'wholesale price, price index, financial year, inflation, economy, price trend, market price, macro economy', 'generated_sponsored_keywords': 'wholesale price, price index, financial year, last year', 'generated_theme': 'Prices, Macro Economy', 'justification': 'Source columns used: title (Wholesale Price Index base year and time horizon), sector (Economy; Prices; Finance), sector_resource (null), note (non-informative), state_department (Office of the Economic Adviser). Extraction rules applied: 1) parsed semicolon-separated values in sector to identify core domains (economy, prices, finance) and normalized to lowercase; 2) derived layman keywords from the dataset subject (price related) and the title emphasis on wholesale prices and index; 3) ensured terms are 1–2 words, singular where possible, and avoided department names or acronyms; 4) role of sector_resource being null shifted reliance to sector and title for keyword generation; 5) generated theme keywords by mapping to the provided SECTOR_VOCAB_JSON, selecting sub-sectors under Economy (Prices, Macro Economy). Sponsored keywords chosen as tight overlaps with the title: wholesale price, price index, financial year, last year. Ambiguities/assumptions: note content is non-informative (NA) but kept for completeness; frequency/granularity/govt_type fields are missing and not deduced from available data. Terms like “data” were avoided to prioritize singular forms per guideline.', 'confidence_score': 0.7, 'metadata_gaps': 'sector_resource is null; frequency missing; granularity missing; govt_type missing; state_department present but not mapped to a standard field; note is non-informative (NA)'}

TITLE: Wholesale Price Index (Base Year 2011-12) till last financial year
SECTOR: Economy;Prices;Finance;Economy

✓ Written to CSV

----------------------------

2026-01-15 10:37:00,315 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:37:00,318 : INFO - Result is {'generated_keywords': 'train timetable, railway schedule, train reservation, india railways, timetable information, public transport', 'generated_sponsored_keywords': 'railway timetable, train reservation, train timetable, railway schedule, reservation trains', 'generated_theme': 'Transport, Railways', 'justification': "Source columns used: title, sector, sector_resource, ministry_department. Extraction/normalization: parsed semicolon-separated values in sector and sector_resource to identify domain (transport/railways) and mapped to the corresponding themes from SECTOR_VOCAB_JSON. Keywords were normalized to lowercase and kept to 1–2 words; avoided department names and acronyms. The title strongly indicates railway timetable information and train reservations, guiding both layman keywords (train timetable, reservation) and sponsor terms (railway timetable, train reservation). Since the note is listed as nan (missing), it was treated as a metadata gap affecting completeness; frequency/granularity are not provided, limiting temporal specificity. Assumptions: we treated 'Railways' and 'Transport' as the primary thematic areas and mapped them to the SECTOR_VOCAB_JSON sub-sector path (Transport -> Railways). No new subjects were invented; terms chosen reflect common user search language for railway timetable data in India. Ambiguities/assumptions noted: note missing, which reduces confidence slightly; terminology like 'train timetable' vs 'timetable' can be used interchangeably by users, so both forms are included in keywords to maximize discoverability.", 'confidence_score': 0.9, 'metadata_gaps': 'note missing; frequency missing; granularity missing; state_department field missing (null)'}

TITLE: Indian Railways Time Table for trains available for reservation as on 01.11.2017
SECTOR: Transport;Railways

✓ Written to CSV

----------------------------

2026-01-15 10:37:01,905 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:37:01,907 : INFO - Result is {'generated_keywords': 'soil moisture, daily data, water resources, groundwater, soil data, moisture data', 'generated_sponsored_keywords': 'soil moisture, daily data, water resources, soil data, moisture data', 'generated_theme': 'Water Resources', 'justification': 'Source columns used: title (Daily data of Soil Moisture) and catalog_title (Soil Moisture) establishing the core subject; sector (Water Resources) used to determine the thematic area; sector_resource and note are null, so reliance is on title/catalog; ministry_department provided but not used for keywords per guideline to exclude department names; state_department not provided (null). Rules applied: semicolon-separated values were parsed if present; keywords limited to 1–2 words per term where applicable, in lowercase, no punctuation, and excluding technical terms or department names. Extraction/normalization: from title and catalog_title we identified core concepts “soil moisture” and temporal aspect “daily data,” which informed the key layman terms. Additional supportive terms were added to improve discoverability without introducing jargon: “groundwater,” “soil data,” and “moisture data,” all within 1–2 words where possible. Theme mapping used the SECTOR_VOCAB_JSON; since there is a clear Water Resources domain but no specific sub-sector explicitly matching soil moisture, the top-level “Water Resources” theme was applied. Sponsored keywords are a concise subset reflecting the strongest overlaps with the title (soil moisture, daily data, water resources) plus closely related terms (soil data, moisture data). All terms avoid department names and acronyms, and stay within 1–2 words where feasible. Ambiguities/assumptions: the dataset language implies daily soil moisture data within water resources; no geographic scope or dataset frequency beyond “Daily data” is specified, but the title suggests daily soil moisture data. ', 'confidence_score': 0.8, 'metadata_gaps': 'sector_resource, note, state_department'}

TITLE: Daily data of Soil Moisture
SECTOR: Water Resources

✓ Written to CSV

----------------------------

2026-01-15 10:37:05,265 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:37:05,268 : INFO - Result is {'generated_keywords': 'agriculture, crop, production, district, season, data, statistics, farming, yield', 'generated_sponsored_keywords': 'crop production, district data, season data, crop statistics, production statistics', 'generated_theme': 'Agriculture, Crops', 'justification': 'Source usage: title indicates district-wise and season-wise crop production statistics starting from 1997, while sector lists Agriculture and Agricultural Produces. Semicolon-separated values in sector/sector_resource were split to treat each as separate hints. Rules applied: converted to singular where reasonable (e.g., crop, production, data, statistics, farming, yield); avoided department names and acronyms; kept terms in lowercase; avoided hyphenated forms by using two-word phrases where appropriate. Keyword selection: core subjects derived from the metadata are Agriculture and crop production context; district and season capture geographic and temporal dimensions implied by the title (district-wise, season-wise); data/statistics indicate the dataset nature; farming/yield provide everyday language equivalents for agricultural production. Sponsored keywords were chosen from the strongest overlaps with the title (crop production, district data, season data, crop statistics, production statistics) and kept concise (1–2 words or two-word phrases). Theme mapping: mapped to the controlled vocabulary by selecting the high-level sector Agriculture and its sub-sector Crops, aligning with the dataset focus on crop production statistics. Exclusions: avoided acronyms (DES) and administrative terms; avoided duplicative terms like district once more than needed; no new subjects outside the provided SECTOR_VOCAB_JSON. Noted potential ambiguities: lack of explicit frequency, granularity, and overall metadata gaps (note field missing, frequency/granularity/govt_type not provided), which could affect discovery granularity. Assumptions: the dataset is historical (from 1997) but no explicit temporal metadata beyond the title; treated as historical domain data under Agriculture/Crops.', 'confidence_score': 0.9, 'metadata_gaps': 'note (null in input), frequency (missing), granularity (missing), govt_type (missing), state_department (present as CDOS State Ministry but not a standard field in input)'}

TITLE: District-wise, season-wise crop production statistics from 1997
SECTOR: Agriculture;Agricultural Produces

✓ Written to CSV

----------------------------

2026-01-15 10:37:10,230 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:37:10,233 : INFO - Result is {'generated_keywords': 'village data, pin code, village code, local governance, panchayati raj, monthly update, village directory, administrative dataset', 'generated_sponsored_keywords': 'village data, pin code, village code, local governance, monthly update', 'generated_theme': 'Rural; Panchayati Raj', 'justification': 'Sources and extraction: 1) sector -> Panchayati Raj indicates a rural governance domain; 2) title emphasizes Local Government Directory and villages with pin codes, guiding layman terms like village data, pin code, village code, and village directory; 3) note mentions monthly updates, supporting a monthly update keyword and time-context; 4) sector_resource is null, so reliance on sector and title for keyword/theme decisions; 5) no explicit granularity or frequency fields provided, so frequency inferred from note; 6) avoided department names and acronyms, kept language simple and India-relevant terms; 7) applied rule to keep 1–2 word terms, singular preferred when possible, and avoided jargon.', 'confidence_score': 0.8, 'metadata_gaps': 'sector_resource=null; frequency=null; granularity=null; govt_type=null; state_department=null'}

TITLE: Local Government Directory (LGD) - Villages with PIN Codes
SECTOR: Panchayati Raj

✓ Written to CSV

----------------------------

2026-01-15 10:37:11,464 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:37:11,467 : INFO - Result is {'generated_keywords': 'panchayat, local government, local body, pin code, directory, rural governance, monthly update, local administration', 'generated_sponsored_keywords': 'local government, local body, pin code, panchayat, directory', 'generated_theme': 'Governance and Administration, Local Government', 'justification': "Source columns used: title, sector, note, sector_resource. sector_resource is treated as null. From the title 'Local Government Directory (LGD) - Local Bodies with PIN Codes', I extracted layman terms such as 'local government', 'directory', 'local bodies' (converted to singular 'local body'), and 'pin code'. The sector 'Panchayati Raj' informed inclusion of governance terms related to rural local bodies, yielding 'panchayat'. The note mentions monthly updates, which supports including 'monthly update' as a temporal keyword. All keywords were kept to 1–2 words per rule, in lowercase, and singular forms when possible. Department names and acronyms (e.g., ministry) were avoided per guidelines. For the Theme, I mapped to the controlled vocabulary SECTOR_VOCAB_JSON: the dataset aligns with Governance and Administration and Local Government (sub-sector). No new subjects were invented. Assumptions include treating the LGD as covering rural local bodies (panchayats) given the Panchayati Raj sector, and using the note to infer monthly updates. If sector_resource were populated with more granular terms, additional keywords could be added, but current data supports the above selections.", 'confidence_score': 0.9, 'metadata_gaps': 'sector_resource: null; state_department: missing; frequency: not provided; granularity: not provided; govt_type: not provided'}

TITLE: Local Government Directory (LGD) - Local Bodies with PIN Codes
SECTOR: Panchayati Raj

✓ Written to CSV

----------------------------

2026-01-15 10:37:13,273 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:37:13,277 : INFO - Result is {'generated_keywords': 'youth tobacco, tobacco use, health data, school survey, secondhand smoke, paan masala, electronic cigarettes, india states, public health', 'generated_sponsored_keywords': 'youth tobacco, tobacco survey, india states, secondhand smoke, electronic cigarettes', 'generated_theme': 'Health and Family welfare, Health', 'justification': 'Source columns used: title (Global Youth Tobacco Survey context), sector and sector_resource (Health / Health and Family welfare; Family Welfare) to identify domain, note (tobacco use, secondhand smoke, e-cigarettes, paan masala) for specific topics, and ministry_department (used only for context; not included in keywords). Semicolon-separated values in sector/sector_resource were parsed into individual domain hints and mapped to the SECTOR_VOCAB_JSON where possible. Keywords were normalized to lowercase, limited to 1–2 words, and chosen to reflect core subject (youth tobacco, tobacco use), geographic scope (india states), exposure types (secondhand smoke), and relevant subtopics noted in the text (paan masala, electronic cigarettes). Excluded terms include department names and acronyms; terms like ENDS were paraphrased as electronic cigarettes to maintain plain-language discovery. Theme mapping used Health and Family welfare as the top-level sector with Health as a sub-theme, aligning to the provided SECTOR_VOCAB_JSON. Ambiguities arise from missing fields (e.g., frequency, granularity, govt_type) which were not necessary for keyword/theme derivation but affect metadata completeness.', 'confidence_score': 0.9, 'metadata_gaps': 'frequency, granularity, govt_type, state_department (null); note present; sector_resource present; cds state ministry present'}

TITLE: Global Youth Tobacco Survey (GYTS-4), India and States, 2019
SECTOR: Health;Health and Family welfare

✓ Written to CSV

----------------------------

2026-01-15 10:37:44,616 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:37:44,619 : INFO - Result is {'generated_keywords': 'startup recognition, state startup, industry startup, startup registry, startup list, entrepreneurship data, government recognition', 'generated_sponsored_keywords': 'startup recognition, startup registry, startup list, state startup, industry startup', 'generated_theme': 'Industries, Commerce, Governance and Administration, Economy', 'justification': 'Sources used: title, note, sector, sector_resource, ministry_department. Extraction rules: parse semicolon-separated values where present; ignore ministry/department names per guidelines; prefer singular forms; use lowercase; avoid technical terms. From the title and catalog context, core concepts identified are startups recognized by a government agency; to aid discovery, layman terms include startup recognition, state/industry focus, and listing concepts. Sponsored keywords derive from strong overlaps with the title (recognition, registry/list, state/industry focus). The themes map to SECTOR_VOCAB_JSON: Industries (industry focus), Commerce (business activity), Governance and Administration (government recognition/process), Economy (macro context). Assumptions: sector_resource is null, so reliance on title and note to anchor keywords; department names are not included in keywords. Note mentions DPIIT but acronyms and department names are excluded from keywords. Ambiguities: lack of explicit state or year granularity in the metadata; null values for frequency/granularity and missing govt_type. These reduce precision but do not invalidate the core subject identified from the title and note.', 'confidence_score': 0.8, 'metadata_gaps': 'sector_resource null; state_department null; frequency null; granularity null; govt_type missing'}

TITLE: Industry, State and Year wise Startups Recognized by DPIIT till last week
SECTOR: All

✓ Written to CSV

----------------------------

2026-01-15 10:37:45,696 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:37:45,697 : INFO - Result is {'generated_keywords': 'rainfall, india, monsoon, rainfall data, climate data, rainfall trend', 'generated_sponsored_keywords': 'rainfall india, monsoon rainfall, historical rainfall, rainfall data, climate data', 'generated_theme': 'Science and Technology, Atmospheric Science, Earth Sciences', 'justification': "Source columns used: title, catalog_title, sector, sector_resource, ministry_department. Extraction/normalization: parsed semicolon-separated values in sector and sector_resource to identify domain areas; selected layman-friendly terms (rainfall, india, monsoon, rainfall data, climate data, rainfall trend) that are 1–2 words, lowercase, and non-redundant; avoided department names and acronyms in keywords per guidelines. Theme mapping: aligned with SECTOR_VOCAB_JSON by selecting top-level 'Science and Technology' and its sub-sectors 'Atmospheric Science' and 'Earth Sciences' to reflect the dataset’s meteorological and geoscience focus. Sponsored keywords derived from strongest overlaps between the title/note and layman terms (e.g., rainfall, monsoon, india, historical rainfall) and kept to 1–2 words. Notes: the note indicates rainfall in millimetres, but numeric unit terms are avoided in keywords. Ambiguities/assumptions: frequency, granularity, and govt_type fields are not provided; state_department field present but not used for keyword generation; dataset covers historical rainfall (1901–2019), suggesting a time-series angle though explicit temporal keywords are not required in the keyword set.", 'confidence_score': 0.8, 'metadata_gaps': 'frequency missing; granularity missing; govt_type missing; state_department null'}

TITLE: Rainfall in all India and its departure from normal during Monsoon session (June-Sept) from 1901 to 2019
SECTOR: Science and Technology;Atmospheric Science;Earth Sciences

✓ Written to CSV

----------------------------

2026-01-15 10:37:48,056 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:37:48,059 : INFO - Result is {'generated_keywords': 'crime data, police cases, disposal data, historical, year 2019, crime heads, crime statistics', 'generated_sponsored_keywords': 'crime disposal, police cases, year 2019, crime heads, crime data', 'generated_theme': 'Home Affairs and Enforcement, Police', 'justification': "Sources used: title, sector, sector_resource, and note. Sector was split into two values: 'Home Affairs and Enforcement' and 'Police'; sector_resource provided 'Police' which is a duplicate emphasis but not ignored. Keywords were normalized to lowercase and kept at 1–2 words; acronyms (e.g., IPC) were avoided. From the title, core concepts extracted include crime, disposal, cases, and head-wise framing; year 2019 explicitly stated. To reflect the data note about data gaps and alternative data year, 'historical' and 'year 2019' were included. Sponsored keywords reflect close matches users might search (crime disposal, police cases, year 2019, crime heads, crime data) without department references. Theme mapping uses the SECTOR_VOCAB_JSON: 'Home Affairs and Enforcement' and 'Police' as subject categories. Ambiguity/Nuances: note indicates 2018 data used for 2019 due to missing 2019 data from West Bengal, which affects data completeness and confidence. A metadata gap identified is missing state_department information.", 'confidence_score': 0.8, 'metadata_gaps': 'state_department missing'}

TITLE: Crime Head-wise Police Disposal of IPC Crime Cases (Crime Head-wise) during 2019
SECTOR: Home Affairs and Enforcement;Police

✓ Written to CSV

----------------------------

2026-01-15 10:37:54,471 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:37:54,474 : INFO - Result is {'generated_keywords': 'district data, registration, enterprise, micro, small scale, medium, industry, business count', 'generated_sponsored_keywords': 'district data, registered enterprise, enterprise count, latest date', 'generated_theme': 'Industries, Micro, Small Scale, Medium', 'justification': 'Source columns used: title (District Wise Total MSME Registered Enterprises under UDYAM Registration till last date) for core idea; sector (Industries;Medium;Micro;Small Scale) and sector_resource (repeated Medium;Micro;Small Scale) for domain scope and granularity; ministry_department (Ministry of Micro, Small and Medium Enterprises) as contextual, though not included in keywords; note is treated as missing; state_department/frequency/granularity not provided. Extraction rules: parsed semicolon-separated values in sector and sector_resource to identify core domain terms; normalized to singular where applicable; generated layman keywords are 4–10 terms, in lowercase, 1–2 words each, avoiding acronyms and department names. Selected terms emphasize district level MSME registration and enterprise counts across micro, small scale, and medium sectors (e.g., district data, registration, enterprise, micro, small scale, medium, industry, business count). Sponsored keywords derived from strongest overlaps between title and layman terms: district data, registered enterprise, enterprise count, latest date. Theme mapping uses SECTOR_VOCAB_JSON: Industries as the broad sector, with Micro, Small Scale, and Medium as sub-sectors to reflect the MSME size-based categorization embedded in the metadata. Exclusions: avoided acronyms like MSME/UDYAM, and avoided department/administrative terms in user-facing keywords. Ambiguities/assumptions: Note field is effectively missing (nan), thus confidence is partially reduced; frequency/granularity fields are not provided and not used in keyword/theme generation. If later data populates note or frequency, refinements can be applied.', 'confidence_score': 0.75, 'metadata_gaps': 'note is null; frequency missing; granularity missing; state_department missing (CDOS state context present but not reflected in fields); potential redundancy in sector_resource (duplicated values) not yet normalized'}

TITLE: District Wise Total MSME Registered Enterprises under UDYAM Registration till last date
SECTOR: Industries;Medium;Micro;Small Scale

✓ Written to CSV

----------------------------

2026-01-15 10:37:56,490 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:37:56,493 : INFO - Result is {'generated_keywords': 'temperature record, seasonal temperature, annual temperature, india climate, weather series, minimum temperature, maximum temperature, historical temperature', 'generated_sponsored_keywords': 'minimum temperature, maximum temperature, seasonal temperature, historical temperature, india climate', 'generated_theme': 'Earth Sciences, Atmospheric Science', 'justification': 'Source usage and extraction:\n- title: Seasonal and Annual Min/Max Temp Series - India from 1901 to 2017 was used to identify core subjects such as temperature, seasonal/annual patterns, and historical scope. \n- note: Data values in degree Celsius informed the temperature-centric keywords while avoiding unit-specific terms in the final keywords to maintain general discoverability.\n- sector and sector_resource: Both include Science and Technology, Atmospheric Science, and Earth Sciences, which guided the thematic mapping to the SECTOR_VOCAB_JSON topics Earth Sciences and Atmospheric Science (sub-sectors under Science and Technology).\n- ministry_department: Although multiple departments are listed (Ministry of Earth Sciences; IMD), keywords were crafted to avoid department names per guidelines; instead, domain terms like temperature, climate, and weather were used.\n- extraction and normalization rules applied:\n  - Parsed semicolon-separated values from sector and sector_resource to identify relevant domains (Earth Sciences, Atmospheric Science).\n  - Generated layman keywords (1–2 words per term, lowercase, singular forms where possible) that reflect the dataset’s subject without technical jargon or internal terms.\n  - Ensured no duplicates and avoided plural forms where possible (e.g., data -> temperature record, historical temperature).\n  - Derived sponsored keywords directly mirroring the strongest overlap between the title/note and layman terms, resulting in terms like minimum temperature, maximum temperature, seasonal temperature, historical temperature, india climate.\n  - Generated themes drawn from the controlled vocabulary: Earth Sciences and Atmospheric Science, aligning with the dataset’s temperature/atmospheric focus.\n- term selection rationale:\n  - temperature record and historical temperature capture the long-term temperature series aspect over 1901–2017.\n  - seasonal and annual temperature capture both seasonal and yearly patterns implied by the title.\n  - india climate and weather series reflect the geographic focus and the data’s temporal nature.\n  - minimum temperature and maximum temperature directly map to min/max in the dataset title.\n  - weather series and seasonal/annual temperature provide accessible, non-technical discovery terms.\n- inclusions/exclusions:\n  - Excluded department acronyms and formal titles to avoid non-user-friendly search terms.\n  - Excluded unnecessary qualifiers and kept terms within the 1–2 word limit per keyword.\n- uncertainties/assumptions:\n  - Assumed historical scope is captured by keywords like historical temperature due to data range 1901–2017.\n  - Some fields (frequency, granularity, state_department) are missing; thus, thematic mapping relies primarily on sector/sector_resource/title.\n  - If additional context becomes available (e.g., real-time updates), temporal keywords could be added; current dataset appears historical.\n', 'confidence_score': 0.85, 'metadata_gaps': 'state_department, frequency, granularity, govt_type'}

TITLE: Seasonal and Annual Min/Max Temp Series - India from 1901 to 2017
SECTOR: Science and Technology;Atmospheric Science;Earth Sciences

✓ Written to CSV

----------------------------

2026-01-15 10:38:00,889 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:38:00,934 : INFO - Result is {'generated_keywords': 'school enrolment, age group, class enrolment, primary enrolment, secondary enrolment, student count, school data', 'generated_sponsored_keywords': 'enrolment age, enrolment class, school enrolment, student count', 'generated_theme': 'Education; Elementary, Education; Secondary', 'justification': "Source columns used: title (to identify core topic enrolment by age and class), sector (Education to anchor domain), ministry_department (to infer overarching governance though not used as a keyword), state_department (noted but not used in keywords to avoid administrative terms), note (null, so no additional textual hints). Processing steps: 1) parsed sector into a single domain 'Education'; 2) extracted meaningful, non-technical layman terms from the dataset topic focusing on enrolment, age, and class, while ensuring terms are 1–2 words and in singular where possible; 3) avoided including ministry/department names in keywords per guidelines; 4) generated theme by mapping Education to sub-sectors where applicable; included Elementary and Secondary as these are typical school levels in enrolment data. Excluded terms like 'UDISE plus' and any internal acronyms to maintain discoverability for general users. Sponsored keywords were derived from the strongest overlap between the title and layman terms (enrolment, age, class, school) and kept to 1–2 words. Ambiguities: the dataset has limited textual notes and missing fields in the provided metadata (sector_resource null, note null), so keyword extraction relies heavily on the title and sector. Assumptions: dataset covers primary and secondary school enrolment given the Education sector and typical UDISE contexts; time reference (2012-13) is not added as a keyword to avoid overfitting to a date unless explicitly requested. If frequency/granularity were available, temporal keywords (e.g., historical, yearly) could be added.", 'confidence_score': 0.8, 'metadata_gaps': 'sector_resource null; note null; frequency missing; granularity missing'}

TITLE: Enrolment by Age and Class (UDISE plus) during 2012-13
SECTOR: Education

✓ Written to CSV

----------------------------

2026-01-15 10:38:08,403 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:38:08,405 : INFO - Result is {'generated_keywords': 'river, boundary, water, groundwater, surface water, boundary map, country, river network, map', 'generated_sponsored_keywords': 'river map, river boundary, boundary map, water boundary, river network', 'generated_theme': 'Water Resources, Ground Water, Surface Water', 'justification': "Source usage: title 'Shapefile of Rivers' and catalog_title 'Boundaries of Water Resources Projects' were used to identify core concepts (rivers, boundaries, water). Sector and sector_resource both list 'Ground Water' and 'Surface Water', which guided theme mapping. Extraction/normalization: semicolon-separated values in sector/sector_resource were split into individual domain hints. Layman keywords were generated by converting technical terms to plain language (e.g., 'river', 'boundary', 'water', 'groundwater', 'surface water'). Terms like 'shapefile' were avoided due to being a technical term; instead, more accessible concepts such as 'river', 'boundary', and 'map' (from the note about the zip contents and maps for rivers) were used. Two-word phrases were formed where natural (e.g., 'boundary map', 'river network', 'surface water'). Sponsored keywords were derived from overlaps between the title/note and layman terms (e.g., 'river map', 'river boundary', 'boundary map', 'water boundary', 'river network'). Theme mapping uses the provided SECTOR_VOCAB_JSON: the dataset clearly relates to Water Resources with sub-sectors Ground Water and Surface Water. Ambiguities/assumptions: The dataset mentions country-wide rivers and boundaries of water projects; we assume primary content is river networks and boundaries rather than administrative datasets, so no department names were included in keywords. Null fields handling: frequency/granularity fields are not provided in the input, so they are not reflected in keywords or themes; note presence confirms data context. If more metadata fields were provided (e.g., granularity), temporal keywords could be added.", 'confidence_score': 0.9, 'metadata_gaps': 'frequency: missing; granularity: missing; state_department: effectively present via CDOS State Ministry but field not explicitly populated in standard schema'}

TITLE: Shapefile of Rivers
SECTOR: Ground Water;Surface Water

✓ Written to CSV

----------------------------

2026-01-15 10:38:15,877 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:38:15,883 : INFO - Result is {'generated_keywords': 'micro business, small business, medium business, enterprise data, registered enterprise, district level, registration data, udyam registration', 'generated_sponsored_keywords': 'udyam registration, registered enterprise, district level, enterprise data, registration data', 'generated_theme': 'Industries, Manufacturing, Small Scale', 'justification': 'Source columns used: title, sector, sector_resource, note, and CDOS State Ministry (interpreted as state_department for gap analysis). Extraction/normalization rules: \n- Split semicolon-delimited values in sector and sector_resource into individual tokens and deduplicate (industries, medium, micro, small scale).\n- Prefer singular forms for keywords where applicable (e.g., enterprise instead of enterprises) but allow common two-word phrases that reflect the dataset (e.g., micro business, small business).\n- Exclude department names, acronyms, and overly technical terms; include India-relevant context like udyam where it directly informs the dataset scope.\n- Generate layman keywords that cover both broad and specific aspects (industry type, enterprise scale, and registration context).\n- For sponsored keywords, pick terms most tightly tied to the title/note: udyam registration, registered enterprise, district level, enterprise data, registration data.\n- Theme mapping uses SECTOR_VOCAB_JSON: map to Industries as the broad domain, with Manufacturing and Small Scale as applicable sub-sectors. No new subjects are invented; only existing vocabulary is used.\n\nWhy specific terms were selected:\n- micro business, small business, medium business: reflect the MSME scale categories mentioned in sector values (Micro, Small Scale, Medium).\n- enterprise data and registered enterprise: directly refer to the dataset focus on enterprises and registration status.\n- district level: aligns with district-wise data mentioned in the title.\n- registration data and udyam registration: capture the core process referenced (UDYAM registration for MSMEs).\n\nAmbiguities/assumptions:\n- note field is null (nan); treated as missing, which reduces confidence slightly and is reflected in metadata_gaps and justification. \n- state_department field is not clearly provided as a separate field; the input includes a CDOS State Ministry entry, which is interpreted as a state-context hint rather than a separate state_department value.\n- sector_resource contained repeated values; deduplicated for keyword generation.\n', 'confidence_score': 0.8, 'metadata_gaps': ['note (missing)', 'state_department (not clearly provided)']}

TITLE: District wise Services MSME Registered Enterprises under UDYAM Registration till last date
SECTOR: Industries;Medium;Micro;Small Scale

✓ Written to CSV

----------------------------

2026-01-15 10:38:29,572 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:38:29,574 : INFO - Result is {'generated_keywords': 'disability dataset, district dataset, state dataset, age group, gender, disability type, social development, quarterly', 'generated_sponsored_keywords': 'disability district, district data, age group, gender, disability type', 'generated_theme': 'Social Development; Disabled', 'justification': 'Source columns used: title, sector, sector_resource, note, and minstry/department fields. Extraction/normalization rules applied: (1) parse semicolon-separated values where present (though sector and sector_resource are single-valued here); (2) derive layman terms from the dataset concept by prioritizing core dimensions described in the title and note (disability, district, age group, gender, disability type); (3) ensure keywords are 1–2 words, lowercase, singular where possible, and free of department names or internal acronyms; (4) avoid jargon and technical terms (e.g., api, metadata); (5) include India-relevant contextual cues like district, state, and disability domain; (6) map themes to SECTOR_VOCAB_JSON using the top-level "Social Development" sector and its sub-sector "Disabled". Sponsorship keywords are a subset of the strongest overlaps between the title/note and layman terms. Theme chosen reflects the governance domain (Social Development) and the targeted sub-domain (Disabled). Ambiguities: the dataset mentions quarterly updates and district-wise/disability-wise breakdowns, which informs the keywords but frequency granularity beyond quarterly isn’t embedded in the keywords themselves. The department name was omitted from keywords per policy.', 'confidence_score': 0.85, 'metadata_gaps': ['frequency', 'granularity', 'state_department']}

TITLE: District wise, Disability wise, Age group wise , Gender wise Unique Disability ID (UDID) data as on 11.06.2024
SECTOR: Social Development

✓ Written to CSV

----------------------------

2026-01-15 10:38:32,930 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:38:32,934 : INFO - Result is {'generated_keywords': 'groundwater, evaporation, daily data, water data, water balance', 'generated_sponsored_keywords': 'groundwater data, evaporation, daily data, water data', 'generated_theme': 'Water Resources, Ground Water', 'justification': 'Sources used: title (Daily data of Evapotranspiration; Daily Data), sector (Ground Water). sector_resource and note are null, so no additional hints from them. Extraction and normalization: 1) semicolon-separated fields were split (sector had a single value, Ground Water); converted to a layman-friendly form: groundwater. 2) From the title/catalog title, phrases like daily data and evapotranspiration were interpreted for lay terms: daily data and evaporation. 3) Created keywords in 1–2 words, lowercase, avoiding acronyms and department names. 4) Avoided technical terms (eg, evapotranspiration) in favor of a user-friendly term (evaporation) while preserving dataset intent. 5) Theme mapping: mapped Ground Water under Water Resources in SECTOR_VOCAB_JSON, selecting the top level “Water Resources” and sub-sector “Ground Water” to reflect hierarchical subject classification. 6) Sponsored keywords are a subset of the lay keywords that closely align with the title and likely search queries. Ambiguities/assumptions: NRSC is an acronym in the title; it is not used in keywords per guidance. Note field is missing; sector_resource is null; assumptions about terms like “water balance” are domain-relevant generalizations from evapotranspiration data. If more metadata (notes, exact dataset scope) were available, keyword precision could improve further.', 'confidence_score': 0.9, 'metadata_gaps': 'sector_resource null; note null'}

TITLE: Daily data of Evapotranspiration of NRSC
SECTOR: Ground Water

✓ Written to CSV

----------------------------

2026-01-15 10:38:40,549 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:38:40,551 : INFO - Result is {'generated_keywords': 'consumer price, price index, rural price, urban price, inflation, historical price, monthly price, price trend', 'generated_sponsored_keywords': 'price index, consumer price, rural price, urban price, historical price', 'generated_theme': 'Economy; Prices', 'justification': 'Source columns used: title and sector. sector_resource is null and note is null, so extraction relied primarily on sector and title. Processing steps: 1) parsed sector into top-level categories (Economy, Prices, Finance, Economy, Statistics) to identify appropriate themes using SECTOR_VOCAB_JSON; mapped to the most suitable existing themes (Economy; Prices). 2) generated layman keywords from the dataset core: consumer price index related concepts (CPI is not used as an acronym in keywords; instead plain terms like price and inflation were chosen). 3) created sponsored keywords by selecting the strongest overlaps with the title (price index, consumer price, rural price, urban price, historical price). 4) avoided including ministry/department names or acronyms, and did not introduce new subject terms beyond the provided controlled vocabulary. 5) included India-relevant framing where applicable, while keeping terms simple and non-technical. Ambiguities: the frequency and granularity are not provided, and sector_resource is missing, which reduces some confidence about precise categorization beyond the two-theme mapping. Assumptions: the dataset concerns all-India CPI covering rural and urban components up to May 2023, so keywords focus on CPI/price concepts without location-specific terms beyond the inherent all-India framing. The final theme uses the closest available SECTOR_VOCAB_JSON mapping (Economy; Prices).', 'confidence_score': 0.8, 'metadata_gaps': ['sector_resource', 'note', 'frequency', 'granularity']}

TITLE: All India Consumer Price Index (Rural/Urban) upto May 2023
SECTOR: Economy;Prices;Finance;Economy;Statistics

✓ Written to CSV

----------------------------

2026-01-15 10:38:40,789 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:38:40,791 : INFO - Result is {'generated_keywords': 'rainfall, india rainfall, monthly rainfall, seasonal rainfall, annual rainfall, monsoon rainfall, historical rainfall, climate', 'generated_sponsored_keywords': 'rainfall, india rainfall, monthly rainfall, seasonal rainfall, annual rainfall', 'generated_theme': 'Science and Technology, Atmospheric Science, Earth Sciences', 'justification': 'Source columns used: title, sector, sector_resource, ministry_department, note. Extraction/normalization rules applied: - Parsed semicolon-separated values in sector, sector_resource, and ministry_department to collect domain terms while excluding explicit department names and acronyms. - Derived layman keywords from dataset core topics (rainfall phenomena across India, monthly/seasonal/annual granularity) using singular/neutral forms and avoiding technical jargon. - Ensured keywords are 1–2 words (or two-word terms), in lowercase, with no internal punctuation. - Excluded administrative or organizational terms (e.g., ministry names) and focused on subject nouns like rainfall, month, season, year, climate. - Incorporated India-centric relevance given the dataset scope (All India, Rainfall in India) while avoiding non-inherent terms. From the note, terms such as “monthly rainfall” and “seasonal/annual rainfall” were reinforced as core dataset aspects. Sponsored keywords were derived from strong overlaps between the title/note and layman terms, selecting concise phrases that a user would likely search (e.g., rainfall, india rainfall, monthly rainfall, seasonal rainfall, annual rainfall). Theme mapping used the SECTOR_VOCAB_JSON to select high-level and sub-sectors under Science and Technology (Atmospheric Science, Earth Sciences); these best reflect the data’s domain (meteorological rainfall data, atmospheric/oceanic/climate context) without inventing new subjects. Assumptions: - The dataset concerns India-wide rainfall time series (1901–2015) with monthly, seasonal, and annual granularity; - Both sector and sector_resource align to Science and Technology with Atmospheric Science and Earth Sciences as sub-themes; - Frequency and granularity fields are not provided in the input, so they are not used for keyword generation beyond the explicit monthly/seasonal/annual signals. Ambiguities resolved: kept terms broad enough to cover monthly/seasonal/annual rainfall without overcommitting to specific data formats or real-time vs delayed-mode distinctions beyond what is stated in the note. The final themes reflect the main domains applicable to rainfall data (Science and Technology; Atmospheric Science; Earth Sciences).', 'confidence_score': 0.92, 'metadata_gaps': ['frequency', 'granularity', 'state_department/ CDOS state-level metadata (not fully explicit in input)', 'any missing or ambiguous data quality indicators beyond note']}

TITLE: All India area weighted monthly, seasonal and annual rainfall (in mm) from 1901-2015
SECTOR: Science and Technology;Atmospheric Science;Earth Sciences

✓ Written to CSV

----------------------------

2026-01-15 10:38:50,014 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:38:50,431 : INFO - Result is {'generated_keywords': 'crime, police, case, disposal, india, justice, trend, statistic', 'generated_sponsored_keywords': 'police, crime, disposal, case', 'generated_theme': 'Home Affairs and Enforcement, Police', 'justification': "Source columns used: title (for core subject like crime, police, disposal, cases), sector (Police), sector_resource (Army, treated as less indicative of the main topic), ministry_department (extract parent ministry 'Ministry of Home Affairs' from the list and note NCRB as the data origin), note (indicates data provenance from States/UTs). Extraction/normalization: parsed semicolon-separated values in sector, sector_resource, and ministry_department; generated layman keywords are 1–2 words, lowercase, singular where possible, and avoid department acronyms or internal terms. Keywords from title and note were favored to reflect the dataset’s focus on IPC crime cases handled by police in 2021, hence terms like crime, police, case, disposal; additional general terms like justice, trend, statistic were included to broaden discoverability while staying non-technical. Sponsored keywords derived from strongest overlaps between title/note and layman terms: police, crime, disposal, case. Theme mapping used SECTOR_VOCAB_JSON: prioritized high-level category 'Home Affairs and Enforcement' and its sub-area 'Police' as the most relevant subject for a dataset about police disposal of IPC crime cases. Ambiguities/assumptions: sector_resource contains 'Army' which conflicts with the primary police focus; it is deprioritized for keyword/theme construction. The exact granularity/frequency fields are not provided in the input (null), so temporal specificity is inferred from the title year (2021) but not encoded as a separate keyword. The state-level data note supports using a state-provenance lens in interpretation.", 'confidence_score': 0.75, 'metadata_gaps': 'frequency, granularity, state_department, govt_type'}

TITLE: Crime Head-wise Police Disposal of IPC Crime Cases during 2021
SECTOR: Police

✓ Written to CSV

----------------------------

2026-01-15 10:38:52,609 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:38:52,611 : INFO - Result is {'generated_keywords': 'foreign tourist, international tourist, visitor count, tourist arrival, india tourism, immigration data, travel trend', 'generated_sponsored_keywords': 'foreign tourist, international tourist, tourist arrival, india tourism', 'generated_theme': 'Travel and Tourism, Modes of Travel', 'justification': 'Sources used: title and sector were analyzed to establish the dataset subject (foreign tourist arrivals, NRIs/ITAs) and the broad domain (Travel and Tourism). Since sector_resource is null, reliance on the title helped identify core concepts. The note was consulted to understand data provenance (Bureau of Immigration) and the provisional 2018 remark, which supported including immigration-related context as a keyword. Normalization rules were applied: terms were converted to lowercase, singular forms were preferred where possible (e.g., tourist arrival rather than arrivals), and no department names or acronyms were included in the keywords. Semicolon-separated values were not present in sector_resource, so no extra extraction was needed beyond the title and sector. Keywords chosen reflect both broad and specific aspects (tourism, arrivals, and immigration data) and avoid technical jargon. Sponsored keywords focus on the strongest overlaps with the title, emphasizing core concepts such as foreign/international tourist and tourist arrival, with an emphasis on India imagery in a broad sense. Ambiguities/assumptions: NRIs and ITAs are represented in the title via abbreviations; to maintain clarity, sponsored keywords opted for non-abbreviated equivalents (foreign tourist, international tourist). The dataset lacks explicit granularity (e.g., mode of travel or destinations), so the theme uses high-level Travel and Tourism with a plausible subtheme of Modes of Travel; this aligns with the provided SECTOR_VOCAB_JSON mapping while avoiding over-assertion about unavailable details.', 'confidence_score': 0.9, 'metadata_gaps': 'sector_resource: null; frequency: not provided; granularity: not provided; govt_type: not explicitly stated in the fields provided'}

TITLE: Foreign Tourist Arrivals (FTAs), Arrivals of Non-Resident Indians (NRIs) and International Tourist Arrival (ITAs) from 1981 to 2017
SECTOR: Travel and Tourism

✓ Written to CSV

----------------------------

2026-01-15 10:38:56,102 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:38:56,105 : INFO - Result is {'generated_keywords': 'enrolment, age, class, students, education, schooling, age groups', 'generated_sponsored_keywords': 'enrolment, age, class, students, education', 'generated_theme': 'Education', 'justification': 'Source columns used: title, sector, sector_resource, ministry_department, note. Processing steps: (1) Parsed semicolon-separated values in sector and sector_resource to confirm domain as Education. (2) Extracted core subjects from the title: enrolment, age, class, during 2019-20; (3) Generated layman keywords reflecting enrolment by age and class in education contexts, ensuring terms are 1–2 words, lowercase, singular where possible, and avoid department acronyms. (4) Excluded department names from keywords, per instruction, and avoided technical terms. (5) Created sponsored keywords directly mirroring the main ideas in the title (enrolment, age, class, students, education) to align with user search behavior. (6) Theme mapped to the Education sector as a high-level subject; no more granular sub-sectors were inferred due to lack of explicit grade-level focus in the metadata. Note handling: note is null; this reduces confidence slightly per the null-field handling rule. Abbreviations or internal terms were avoided; India-relevant language included in general domain terms like enrolment and schooling.', 'confidence_score': 0.9, 'metadata_gaps': 'note is null; state_department field is not provided; govt_type field is not provided'}

TITLE: Enrolment by Age and Class (UDISE plus) during 2019-20
SECTOR: Education

✓ Written to CSV

----------------------------

2026-01-15 10:39:02,168 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:39:02,170 : INFO - Result is {'generated_keywords': 'inflation, price index, annual inflation, retail inflation, inflation rate, price trends', 'generated_sponsored_keywords': 'retail inflation, annual inflation, inflation rate, price index', 'generated_theme': 'Economy, Prices', 'justification': 'Sources used: title (Year-wise retail inflation rate based on CPI-C from 2017-18 to 2022-23), note (data in percentage, FY 2022-23 provisional), sector_resource (Finance), sector (All). Extraction rules applied: parsed fields for key domain terms; semicolon-separated fields would be split if present (none here beyond Finance). Normalization: all terms lowercased; terms limited to 1–2 words; preferred singular forms when possible; avoided department names and acronyms (e.g., Rajya Sabha, MOSPI) per guidelines. Keyword selection rationale: the dataset centers on inflation as a retail/consumer price indicator derived from a price index (CPI-C) over 2017-18 to 2022-23; therefore selected layman keywords such as inflation, annual inflation, retail inflation, inflation rate, price index, and price trends accurately reflect the core subject and enable broad search discovery. Sponsored keywords are a subset tightly aligned with the title/note (retail inflation, annual inflation, inflation rate, price index) and omit administrative terms. Theme mapping uses the controlled SECTOR_VOCAB_JSON: Economy with sub-sector Prices, reflecting the economic indicator focus and aligning with government data categorization. Ambiguities/assumptions: the note mentions provisional February 2023 data and the dataset covers multiple fiscal years; the exact frequency/granularity fields are not provided in the input, and state/government-type fields are partially incomplete, which is noted under metadata_gaps. ', 'confidence_score': 0.8, 'metadata_gaps': ['frequency missing', 'granularity missing', 'govt_type missing', 'state_department missing']}

TITLE: Year-wise retail inflation rate based on Consumer Price Index-Combined (CPI-C) from 2017-18 to 2022-23
SECTOR: All

✓ Written to CSV

----------------------------

2026-01-15 10:39:12,429 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:39:12,434 : INFO - Result is {'generated_keywords': 'state economy, tamil nadu, current prices, economic activity, time series, annual data, economic data', 'generated_sponsored_keywords': 'tamil nadu, current prices, economic activity, time series, state economy', 'generated_theme': 'Finance, Economy', 'justification': "Source columns used: title, sector, sector_resource, note. From sector, extracted top-level classifications: Finance, Economy, Statistics. Since the sector_resource field is null, reliance was placed on the sector grouping and the title for subject extraction. The SECTOR_VOCAB_JSON mapping was consulted to select appropriate themes; Finance and Economy were chosen because the dataset concerns Gross State Domestic Product (GSVA) by economic activity at current prices, which aligns with macroeconomic financial/economic domains. The term 'Statistics' from sector was not mapped to a specific subject in the vocabulary, so it was not included as a theme to avoid inventing a non-existent subject. Keywords were generated from the title and note content, ensuring layman-friendly, singular or simple two-word terms. Extracted from the title: Tamil Nadu (location), Current Prices (price basis), Economic Activity (subject), and the time frame implied by the 2011-12 to 2016-17 range, which supports the time series/annual data framing. Additional keywords such as 'state economy' and 'economic data' reflect the broader subject. Frequency and granularity fields were not provided; assumptions about time series/annual nature were inferred from the date range in the title. Acronyms were avoided (gsva, gdp, etc.) in line with the guideline to exclude internal terms. The note indicating units (Rs. in lakh) reinforced the economic data context but was not itself used as a separate keyword to avoid redundancy. Ambiguities include exact frequency and granularity not being stated; the dataset appears central (Ministry of Statistics and Programme Implementation) but explicit govt_type/frequency fields are missing.", 'confidence_score': 0.8, 'metadata_gaps': ['sector_resource', 'frequency', 'granularity', 'state_department', 'govt_type']}

TITLE: GSVA by Economic Activity at Current Prices for Tamil Nadu from 2011-12 to 2016-17 (as on 31.03.2017)
SECTOR: Finance;Economy;Statistics

✓ Written to CSV

----------------------------

2026-01-15 10:39:25,350 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:39:25,353 : INFO - Result is {'generated_keywords': 'crude oil, refinery output, oil processing, monthly data, petroleum, oil industry', 'generated_sponsored_keywords': 'monthly crude, crude oil, refinery output, oil processing, monthly data', 'generated_theme': 'Power and Energy; Non Renewable, Industries; Petroleum and Natural Gas', 'justification': 'Source columns used: title, sector, sector_resource, note, ministry_department. Processing steps: (1) Extracted key subjects from the title: crude oil, refinery, processing, monthly data. (2) Generated layman keywords (1–2 words per item, lowercase, non-technical, singular where possible) from the core subject: crude oil, refinery output, oil processing, monthly data, petroleum, oil industry. (3) Sponsored keywords drawn directly from strong overlaps with the title: monthly crude, crude oil, refinery output, oil processing, aligning with the dataset’s focus. (4) Theme mapping uses SECTOR_VOCAB_JSON: categorized as Power and Energy with sub Non Renewable (reflecting the energy nature) and Industries with sub Petroleum and Natural Gas (reflecting the petroleum refinery context). Note content reinforces provisional data context but not used as keywords. Ambiguities handled: no explicit geographic or unit details; frequency/granularity not provided, so these facets are not encoded in keywords or themes. Assumptions: the core subject is monthly crude oil processed by refineries; terms chosen avoid department names and acronyms, and favor India-relevant domain terms where appropriate (crude oil, refinery, petroleum).', 'confidence_score': 0.7, 'metadata_gaps': 'frequency missing; granularity missing; state_department missing'}

TITLE: Monthly Crude Oil Processed by Refineries
SECTOR: Non Renewable

✓ Written to CSV

----------------------------

2026-01-15 10:39:26,908 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:39:26,911 : INFO - Result is {'generated_keywords': 'unorganised workers, district data, demographic data, labour data, employment data, self declaration, previous day', 'generated_sponsored_keywords': 'unorganised workers, district data, demographic data, self declaration, previous day', 'generated_theme': 'Labor and Employment; Unorganized Sector Workers', 'justification': "Source columns used: title, sector, sector_resource, note. Rules applied: (1) Parsed semicolon-separated fields where present (none in this case beyond the ones provided); (2) Generated layman keywords (1–2 words each, lowercase, no punctuation) reflecting core subject concepts; (3) Derived a sponsored keyword set directly aligned with the title/note; (4) Mapped to SECTOR_VOCAB_JSON for theme: used top-level field 'Labour and Employment' with sub-sector 'Unorganized Sector Workers'. Normalization included using simple, non-technical terms and avoiding department names. Assumptions: district-level focus inferred from title (hence 'district data'); demographic focus inferred from 'Demographic Data'; the note mentions 'self declaration' and 'as on Previous Day', which informed keywords like 'self declaration' and 'previous day'. Exclusions: avoided acronyms and internal terms (eShram, ministry acronyms) and did not create new subject classes beyond the provided SECTOR_VOCAB_JSON mapping. Ambiguities: inconsistent spelling between 'Unorganised' (title) and SECTOR_VOCAB_JSON 'Unorganized Sector Workers' (standardized term). Chose 'Unorganized Sector Workers' in the theme to align with the controlled vocabulary; geographic terms retained only as district data in keywords, not as location-specific fields in themes.", 'confidence_score': 0.8, 'metadata_gaps': ['state_department', 'frequency', 'granularity', 'govt_type']}

TITLE: District-wise Demographic Data of Unorganised Workers registered on eShram as on Previous Day
SECTOR: Unorganized Sector Workers

✓ Written to CSV

----------------------------

2026-01-15 10:39:38,591 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:39:38,599 : INFO - Result is {'generated_keywords': 'rainfall, monsoon, monthly rainfall, seasonal rainfall, annual rainfall, india rainfall, time series, historical rainfall', 'generated_sponsored_keywords': 'rainfall data, historical rainfall, monthly rainfall, india rainfall, seasonal rainfall', 'generated_theme': 'Science and Technology; Atmospheric Science, Science and Technology; Earth Sciences', 'justification': 'Sources used: title, sector, sector_resource, note, and ministry_department. Processing steps: (1) parsed semicolon-separated fields in sector and sector_resource to extract granular subject hints; (2) derived layman-friendly keywords from the dataset subject (rainfall data in india, temporal aspects) ensuring 1–2 words per keyword and lowercase; (3) created sponsored keywords aligned closely with the title and note (emphasizing rainfall data and historical/monthly aspects) while avoiding department names. Theme mapping relied on SECTOR_VOCAB_JSON: the dataset falls under Science and Technology with sub-sectors Atmospheric Science and Earth Sciences, reflecting weather/rainfall measurements and related atmospheric/earth science contexts. Terms were selected to be discoverable by non-experts and to avoid technical jargon. Ambiguities: state_department field availability was unclear (CDOS State Ministry exists in input but state_department field is effectively null), which affects metadata completeness. All terms exclude department acronyms and internal jargon and favor India-relevant terms (rainfall, monsoon, india).', 'confidence_score': 0.85, 'metadata_gaps': "state_department field missing/null; frequency and granularity fields not provided in input; potential ambiguity around mapping from 'CDOS State Ministry' vs 'state_department' field"}

TITLE: Area weighted monthly, seasonal and annual rainfall ( in mm) for 36 meteorological subdivisions from 1901-2015
SECTOR: Science and Technology;Atmospheric Science;Earth Sciences

✓ Written to CSV

----------------------------

2026-01-15 10:39:40,988 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:39:40,990 : INFO - Result is {'generated_keywords': 'result data, class twelve, year 2023, student performance, education data, score data', 'generated_sponsored_keywords': 'class twelve, result data, year 2023, education data', 'generated_theme': 'Secondary', 'justification': "Source columns used: title (to derive core subject terms), sector (to map the domain to Education and determine theme), note (to understand context and abbreviations, though not used as keywords to avoid acronyms). sector_resource was treated as null. Rules applied: - Parsed the title to identify the dataset focus: class XII (Class Twelve) and year 2023, with an emphasis on results/statistics, leading to keywords like 'class twelve', 'result data', 'year 2023'. - Derived layman terms that are 1–2 words, lowercase, non-technical, and avoid department acronyms (e.g., CBSE). - Included generic education data terms (e.g., 'education data') to support discoverability for non-expert users. - For the theme, used SECTOR_VOCAB_JSON to map Education to the high level sub-topic 'Secondary' (since Class XII corresponds to secondary education). - Sponsored keywords were chosen as the strongest overlaps between title/note and lay terms: 'class twelve', 'result data', 'year 2023', 'education data'. Ambiguities/assumptions: The note includes several abbreviations (e.g., JNV, KV, CTSA) which are not used as keywords per guideline; the exact frequency/granularity fields are not provided, so temporal terms beyond the year are not added. ", 'confidence_score': 0.85, 'metadata_gaps': 'sector_resource=null; state_department missing; frequency missing; granularity missing; govt_type missing'}

TITLE: CBSE Result Statistics Class XII - 2023
SECTOR: Education

✓ Written to CSV

----------------------------

2026-01-15 10:39:42,834 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:39:42,844 : INFO - Result is {'generated_keywords': 'climate, temperature, rainfall, cities, monthly, weather, india', 'generated_sponsored_keywords': 'monthly temperature, rainfall, cities, historic climate', 'generated_theme': 'Earth Sciences, Science and Technology', 'justification': "Source fields used: title, sector, sector_resource, ministry_department, and note. Extraction/normalization rules applied: \n- Parsed semicolon-separated fields in sector and sector_resource to identify domain areas (Earth Sciences; Science and Technology).\n- Derived layman keywords from core dataset concepts visible in the title and catalog context: climate, temperature, rainfall, cities, monthly, weather, india. These are kept singular where applicable and limited to 1–2 words per keyword, in lowercase, with no punctuation.\n- Excluded administrative terms and ministry names from the keyword set, per guidelines. Included India-relevant context by adding 'india' where appropriate.\n- Sponsored keywords were drawn from the strongest overlaps between the title/note and layman terms, focusing on the main ideas: monthly temperature, rainfall, cities, historic climate (based on the 1901-2000 data framing in the title).\n- Theme mapping used SECTOR_VOCAB_JSON: mapped to Earth Sciences and Science and Technology as the closest controlled vocabulary representations of the dataset’s subject (climate-related measurements for cities fall under these sectors).\n- Note field appears as missing (nan); treated as null, influencing confidence. Frequency/granularity fields are not provided in the input and were not inferred.\n\nWhy specific terms were selected or excluded:\n- Included terms reflect the dataset’s core elements: climate-related measurements (temperature, rainfall) and the geographic/contextual scope (cities, india).\n- Avoided department names, acronyms, and technical jargon (e.g., api, metadata).\n- Excluded overly generic terms unless they add discovery value; kept terms simple for lay user search.\n- The term historic climate is used in sponsored keywords to reflect the historical data basis (1901-2000) implied by the title.\n\nAmbiguities and assumptions:\n- Note field shows as nan; treated as missing, which reduces confidence modestly.\n- Exact granularity/frequency fields are not present in the input; no temporal modifiers beyond the implied monthly aggregation were added to the keywords or theme except where supported by the title.\n", 'confidence_score': 0.9, 'metadata_gaps': 'note: missing/nan; frequency: missing; granularity: missing; state_department: missing when considering governance fields'}

TITLE: Monthly mean maximum & minimum temperature and total rainfall based upon 1901-2000 data
SECTOR: Science and Technology;Earth Sciences

✓ Written to CSV

----------------------------

2026-01-15 10:39:50,684 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:39:50,688 : INFO - Result is {'generated_keywords': 'road accident, road safety, accident data, traffic trend, state data, road transport, casualty data, india', 'generated_sponsored_keywords': 'road accident, accident data, road transport, traffic data, india', 'generated_theme': 'Transport; Road Transport, Infrastructure; Roads', 'justification': "Source parsing and normalization steps:\n- Extracted semicolon-separated values from sector: got two granular themes 'Transport' and 'Road Transport'. Sector_resource contained repeated pairs but was deduplicated to the same themes, reinforcing relevance to road transport and traffic context.\n- Title analysis used for layman keyword derivation: 'Statistics of Road Accidents in India From 2013 to 2016' directly informs core concepts like road accident, India, and data/statistics orientation. Normalization to singular where appropriate (e.g., 'accident' instead of 'accidents').\n- Generated 4–10 layman keywords (all 1–2 words, lowercase, no punctuation): road accident, road safety, accident data, traffic trend, state data, road transport, casualty data, india. These capture the dataset focus (road accidents in India with state-wise scope) and common discovery terms (data, trends, safety).\n- Generated 3–5 sponsored keywords derived from strong overlaps with the title and note (all 1–2 words): road accident, accident data, road transport, traffic data, india. These emphasize the dataset’s main purpose and likely user search intents without department terms.\n- Theme mapping to SECTOR_VOCAB_JSON: chose 'Transport' as the top-level sector and 'Road Transport' as a sub-sector, with an additional cross-cutting layer 'Infrastructure; Roads' to reflect road infrastructure context evident from the title/state-wise road focus.\n- Exclusions and normalization: avoided ministry names, acronyms, and internal terms. Included India-relevant context ('india') per guidance. Where terms were not clearly present in the vocab, avoided creating new categories and stuck to provided sectors/sub-sectors.\n- Ambiguities addressed: note field is 'NA: Not Available' indicating missing auxiliary information; frequency and granularity fields are not provided in the snippet, which limits temporal tagging and precise data cadence.\n- Data-derived assumptions: the dataset centers on state/UT wise counts of road accidents across 2013–2016, hence keywords like 'state data', 'traffic trend', and 'casualty data' are inferred to enhance discoverability, while staying within one to two words per keyword.", 'confidence_score': 0.8, 'metadata_gaps': ['note', 'frequency', 'granularity', 'state_department']}

TITLE: Statistics of Road Accidents in India From 2013 to 2016
SECTOR: Transport;Road Transport

✓ Written to CSV

----------------------------

2026-01-15 10:39:59,704 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:39:59,706 : INFO - Result is {'generated_keywords': 'health, family welfare, rural health, health centre, district health, health information, historical', 'generated_sponsored_keywords': 'district health, health centre, rural health, health information', 'generated_theme': 'Health, Rural development', 'justification': 'Source columns used: title, sector, sector_resource, note, catalog_title, and state_department. Extraction/normalization steps: \n- Parsed semicolon-separated values in sector and sector_resource to identify core domains (Health and Family welfare; Health). \n- Derived layman terms from the title and note that reflect district-level distribution of health facilities (district health, health centre) and general health context (health information). \n- Ensured keywords are 1–2 words, singular where possible, and in lowercase for the layman keywords; used two-word terms where appropriate (e.g., health centre, rural health, district health). \n- Excluded department names and acronyms; avoided location names unless inherently tied to the dataset; added a temporal cue via historical context. \n- Note content aided no direct new keywords beyond the district/health facility focus; historical aspect added to keywords to reflect 2017 data.\n- Generated themes mapped to SECTOR_VOCAB_JSON: Health (from Health and Family welfare -> Health) and Rural development (from Rural -> Development) to reflect broad policy domains, limited to allowed vocabulary.\n- Sponsored keywords were derived from the strongest overlaps between the title/note and the layman terms, focusing on district health and health centre concepts.\nAmbiguities/assumptions: The note includes district name changes and facility types (PHCs, Sub Centres); these were not translated into keywords to avoid overly specific terms, in line with guidance to avoid excessive localization. There was no explicit frequency field; historical/annual context was inferred from the catalog title and date in the note, so a historical keyword was included among the layman keywords. \nOverall classification aligns with the provided metadata and the SECTOR_VOCAB_JSON, producing discoverable keywords and thematic mappings without inventing new sector terms.', 'confidence_score': 0.9, 'metadata_gaps': 'none'}

TITLE: District-wise availability of health centres in India as on 31st March, 2017
SECTOR: Health and Family welfare;Family Welfare;Health

✓ Written to CSV

----------------------------

2026-01-15 10:40:00,755 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:40:00,757 : INFO - Result is {'generated_keywords': 'petroleum, consumption, monthly, energy, oil, products, demand, provisional', 'generated_sponsored_keywords': 'monthly consumption, petroleum products, energy demand, provisional data', 'generated_theme': 'Power and Energy; Non Renewable', 'justification': 'Source columns used: title (Monthly Consumption of Petroleum Products) for core subject; sector (Power and Energy) to anchor the domain; note content to capture provisional data and data sources (Oil Companies, DGCIS, SEZ data) for contextual hints; sector_resource was null, so relied on sector and title for keywords and theme. Normalization rules applied: keywords kept to 1–2 words, lowercase, singular where applicable, no department names, and avoidance of internal jargon. Extracted from title the core ideas (petroleum products, consumption, monthly) and from note the provisional nature and data sources to justify keywords like provisional data. Sponsored keywords chosen as concise overlaps between title/note and lay terms (monthly consumption, petroleum products, energy demand, provisional data). Theme derived from SECTOR_VOCAB_JSON by mapping the given sector (Power and Energy) to its sub-sector (Non Renewable) to produce the subject theme Power and Energy; Non Renewable. Terms excluded: ministry names, acronyms, and location-based or administrative terms. Ambiguities/assumptions: sector_resource is missing (null), which reduces precision of granularity; assumed India-focused petroleum consumption context from title and note; data sources mentioned in note are not quantified in metadata. ', 'confidence_score': 0.9, 'metadata_gaps': ['sector_resource is null', 'frequency and granularity fields not explicitly provided', 'state_department field mapping is unclear in the provided input (CDOS State Ministry reference present but not mapped to standard field)', 'full data provenance (date range, geographic coverage) not specified']}

TITLE: Monthly Consumption of Petroleum Products
SECTOR: Power and Energy

✓ Written to CSV

----------------------------

2026-01-15 10:40:02,729 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:40:02,732 : INFO - Result is {'generated_keywords': 'district data, manufacturing, enterprise, registration, udyog aadhaar, small scale, micro, medium, last date', 'generated_sponsored_keywords': 'district data, manufacturing, enterprise registration, udyog aadhaar, last date', 'generated_theme': 'Industries; Manufacturing, Industries; Small Scale, Industries; Micro, Industries; Medium', 'justification': "Source columns used: title, sector, sector_resource, catalog_title, note. Extraction rules: split semicolon-separated values in sector/sector_resource into individual hints; prefer singular forms; ignore department acronyms; use India-relevant terms where suitable (udyog aadhaar). From the title and catalog the core subject is district-level data on manufacturing enterprises registered under a MSME-like scheme; thus keywords focus on district data, manufacturing, enterprise registration, and the specific Udyog Aadhaar context. The sector fields map to the SECTOR_VOCAB_JSON category 'Industries' with sub-sectors 'Manufacturing', 'Small Scale', 'Micro', and 'Medium', which aligns with the dataset's focus on MSME manufacturing across scales. The note field contains 'nan', treated as missing; this reduces confidence slightly. Sponsored keywords are a subset of layman keywords that closely reflect the title/note overlap (district data, manufacturing, enterprise registration, udyog aadhaar, last date). Ambiguities include the geographical scope (district level) and the interpretation of 'till last date' without a date reference, which could affect temporal tagging.", 'confidence_score': 0.75, 'metadata_gaps': "note value 'nan' treated as missing; frequency missing; granularity missing; state_department missing"}

TITLE: District Wise Total  MSME Registered Manufacturing Enterprises till last date
SECTOR: Medium;Micro;Small Scale

✓ Written to CSV

----------------------------

2026-01-15 10:40:23,577 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:40:23,578 : INFO - Result is {'generated_keywords': 'district data, rural employment, employment program, rural development, district stats, employment guarantee', 'generated_sponsored_keywords': 'district data, employment guarantee, rural development, district stats', 'generated_theme': 'Rural, Development', 'justification': "Source usage: Title provided 'District-wise MGNREGA Data at a Glance' plus sector 'Development' and sector_resource 'Development' indicate a rural development data focus at district level. Note is 'nan' (missing) and frequency/granularity fields are not provided. Extraction rules applied: (1) parse semicolon separated values (none present here beyond the single 'Development'), (2) generate layman terms from the dataset topic while avoiding department names and acronyms, (3) derive companion keywords from the implied domain (MGNREGA is India's rural employment guarantee scheme) but avoid using the acronym itself in keywords, (4) produce 1–2 word terms in lowercase with no punctuation. Keywords chosen aim to be comprehensible to non-experts and relevant to discovery via generic search. Exclusions: avoided acronyms like MGNREGA, avoided department names, and avoided complex jargon. Theme mapping uses the SECTOR_VOCAB_JSON: map 'Development' within 'Rural' to 'Rural' as the high-level theme and 'Development' as the sub-theme. Ambiguities/assumptions: assumed district-level data implies district-focused insights; did not assume time aspects due to missing frequency/temporal signals. If a more precise sub-theme is needed, the 'Development' tag can be refined with additional metadata.", 'confidence_score': 0.8, 'metadata_gaps': 'note, frequency, granularity'}

TITLE: District-wise MGNREGA Data at a Glance
SECTOR: Development

✓ Written to CSV

----------------------------

2026-01-15 10:40:25,357 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:40:25,360 : INFO - Result is {'generated_keywords': 'population, density, growth, decadal, health, rural, statistics, census, state', 'generated_sponsored_keywords': 'population density, population growth, census data, rural health', 'generated_theme': 'Health and Family welfare; Health, Census and Surveys; Census', 'justification': 'Source columns used: title (to identify core subjects like population, density, decadal growth), sector (Health and Family welfare; Health), sector_resource ( Health and Family welfare; Family Welfare; Health ), note (mentions rural health statistics context). Processing steps: parsed semicolon-separated values in sector and sector_resource to understand domain; extracted layman terms from the title (population, density, decadal growth rate) and note (rural health) to form keywords; normalized to lowercase, ensured singular forms where applicable, avoided department names, acronyms, and location names beyond inherent context. Keywords chosen to reflect core subject (population metrics by state), domain (health/rural health), and data source (census context). Sponsored keywords derived from strongest overlaps between title/note and layman terms, focusing on terms users would likely search (population density, population growth, census data, rural health). Thematic mapping uses SECTOR_VOCAB_JSON: mapped to Health and Family welfare; Health and Census and Surveys; Census, selecting the closest existing top-level and sub-sectors to cover health-domain and census-based population data. Ambiguities/assumptions: dataset covers multiple states (state-wise) and uses decadal census data; to avoid overfitting to a particular state, keywords include generic state-related terms like population and census. Excluded terms: department names, acronyms, and non-essential administrative words. ', 'confidence_score': 0.85, 'metadata_gaps': 'frequency, granularity, state_department, govt_type'}

TITLE: State-wise Population, Decadal Population Growth Rate and Population Density - 2011
SECTOR: Health and Family welfare;Family Welfare;Health

✓ Written to CSV

----------------------------

2026-01-15 10:40:31,861 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:40:31,863 : INFO - Result is {'generated_keywords': 'electricity, drinking water, toilet facility, clean fuel, households, district level, health survey, sanitation', 'generated_sponsored_keywords': 'electricity, drinking water, toilet facility, clean fuel', 'generated_theme': 'Health; Family Welfare', 'justification': 'Source columns used: title, catalog_title, sector, sector_resource, note, ministry_department. Semicolon-separated values in sector/sector_resource were parsed to understand domain framing (Health and Family welfare; Family Welfare; Health) while avoiding direct ministry names in keywords. 1-2 word layman terms were derived from the title indicators of basic household amenities: electricity, drinking water, toilet facility, clean fuel, plus generic contextual terms: households, district level (geographic granularity from catalog_title), health survey, and sanitation. The sponsored keywords pick the strongest, most obvious terms directly tied to the title (electricity, drinking water, toilet facility, clean fuel). Theme mapping uses the controlled vocabulary SECTOR_VOCAB_JSON to assign Health and Family Welfare as the high-level domain, selecting sub-sectors Health and Family Welfare (i.e., Health; Family Welfare). If exact sub-sectors were unavailable, high-level sectors were used, without inventing new terms. Note provided mentions data quality for small counts but does not alter keyword content. No department names or acronyms were included in keywords. Ambiguities considered: topic spans health, sanitation, water, and energy access within a health survey framework; mapping to Health and Family Welfare appropriately covers broad policy/domain context.', 'confidence_score': 0.85, 'metadata_gaps': 'state_department: null; frequency: null; granularity: null; govt_type: null'}

TITLE: Percentage of households having electricity, Improved source of drinking water, Having access to improved toilet facility, Use clean fuel for cooking - DLHS IV
SECTOR: Health and Family welfare;Family Welfare;Health

✓ Written to CSV

----------------------------

2026-01-15 10:40:32,876 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:40:32,878 : INFO - Result is {'generated_keywords': 'sign language, dictionary, india, deaf, disability, accessibility, education', 'generated_sponsored_keywords': 'sign language, dictionary, indian, deaf, disability', 'generated_theme': 'Social Development, Education', 'justification': 'Sources used: title (Indian Sign Language Dictionary till January 2024), sector (Disabled), sector_resource (Disabled), and note (null). Rules applied: 1) Extract individual hints from semicolon-separated fields (here sector/sector_resource each contain a single value: Disabled). 2) Generate layman keywords (1–2 words, lowercase, singular where feasible, no department names). 3) Include India-relevant terms when suitable (india/indian derived from the Indian context in the title). 4) Avoid technical terms and acronyms; focus on broad discoverability (sign language, dictionary, disability, education). 5) Align themes with SECTOR_VOCAB_JSON; map to high-level categories: Social Development (Disabled) and Education, to enable cross-dataset discovery. 6) Sponsored keywords are a tight subset reflecting the strongest overlap with the title/note (sign language, dictionary, indian, deaf, disability). 7) Note field is null, so confidence is reduced slightly and metadata gaps are recorded.\n\nWhy specific terms were selected or excluded:\n- Included: sign language, dictionary – core subject identified from the title. \n- india/indian – reflects the Indian context of the dataset; avoids improper geography terms beyond relevance. \n- deaf, disability – reflect the user base and accessibility focus implied by disability resources. \n- accessibility, education – common related concepts that aid discovery but remain general and non-technical.\n- Excluded: ministry/department names (to avoid internal terms), overly technical terms, and any three-word phrases (keywords limited to 1–2 words).\n\nTheme mapping rationale:\n- Social Development: aligns with the SECTOR_VOCAB_JSON top-level category containing Disabled as a sub-topic under Social Development.\n- Education: relevant due to the dictionary nature of a learning/linguistic resource and potential use in language education contexts.\n\nAmbiguities/assumptions:\n- Note is null; no frequency/granularity/govt_type/state_department data provided. Assumed central governance context but not explicit. \n- The dataset title strongly suggests a dictionary resource for Indian Sign Language; no explicit content details beyond the title, so keywords emphasize the dictionary/Sign Language theme and disability context rather than content specifics of the dataset.', 'confidence_score': 0.9, 'metadata_gaps': 'note; frequency; granularity; govt_type; state_department'}

TITLE: Indian Sign Language Dictionary till January 2024
SECTOR: Disabled

✓ Written to CSV

----------------------------

2026-01-15 10:40:36,382 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:40:36,385 : INFO - Result is {'generated_keywords': 'district rainfall, monthly rainfall, seasonal rainfall, annual rainfall, rainfall data, precipitation', 'generated_sponsored_keywords': 'district rainfall, monthly rainfall, seasonal rainfall, annual rainfall, rainfall data', 'generated_theme': 'Science and Technology, Atmospheric Science', 'justification': "Source fields used: title, sector, sector_resource, ministry_department. Extraction rules: parse semicolon-separated values from sector and sector_resource to capture domain terms; derive layman keywords from the title phrases and common rainfall concepts; convert to singular where possible and ensure 1–2 words per keyword; exclude department names and acronyms; map to SECTOR_VOCAB_JSON for theme using top-level Science and Technology and sub-theme Atmospheric Science. Note was treated as missing; when note is null, applied a deduction of 0.1 to confidence per metadata handling. State department field is not provided (null) and could affect data quality. Some terms from the title are retained to ensure the main ideas (district rainfall and monthly/seasonal/annual rainfall) are discoverable; 'normal' is not included as a keyword to avoid jargon. Country-specific relevance is captured via district rainfall terms, aligning with typical Indian meteorological datasets. No additional time-series tags added since frequency/temporal metadata were not provided; data period in the title (1951-2000) indicates historical data.", 'confidence_score': 0.9, 'metadata_gaps': 'note; state_department'}

TITLE: District Rainfall Normal (in mm) Monthly, Seasonal And Annual : Data Period 1951-2000
SECTOR: Science and Technology;Atmospheric Science

✓ Written to CSV

----------------------------

2026-01-15 10:40:38,258 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:40:38,261 : INFO - Result is {'generated_keywords': 'district manufacturing, registered enterprise, industrial unit, small scale, micro industry, medium industry, district enterprise, manufacturing data', 'generated_sponsored_keywords': 'district manufacturing, registered enterprise, industrial unit, manufacturing enterprise, district enterprise', 'generated_theme': 'Industries, Manufacturing, Micro, Small Scale', 'justification': 'Source columns used: title, sector, sector_resource, note. Extraction and normalization steps: parsed sector values (Industries; Medium; Micro; Small Scale) and sector_resource repeats (Multiple instances of Medium;Micro;Small Scale) to derive domain context; combined with the title emphasis on district level and registration to generate layman keywords. All keywords are 1–2 words, in singular where feasible, and kept in lowercase for discoverability. Excluded terms: ministry/department names and acronyms (e.g., Ministry of Micro, Small and Medium Enterprises; MSME; UDYAM) as per guidance. City/district context (district level) is emphasized to reflect scope. From the note field, nan is treated as missing, so no keyword derived from it. For sponsored keywords, selected terms that closely mirror the title/note and are straightforward searches (district manufacturing, registered enterprise, industrial unit, manufacturing enterprise, district enterprise). Theme mapping uses the SECTOR_VOCAB_JSON: top-level Industries with sub-sectors Manufacturing, Micro, and Small Scale to reflect dataset content. No new subjects were invented; where necessary, high-level sector terms were used. Assumptions: the dataset concerns district-level manufacturing MSMEs with registration status; acronyms like UDYAM/MSME are omitted from keywords per guidance.', 'confidence_score': 0.9, 'metadata_gaps': "note (value is 'nan' implying missing), state_department (null in input), frequency (null), granularity (not provided)"}

TITLE: District Level Manufacturing MSME Registered Enterprises under UDYAM Registration till last date
SECTOR: Industries;Medium;Micro;Small Scale

✓ Written to CSV

----------------------------

2026-01-15 10:40:40,402 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:40:40,405 : INFO - Result is {'generated_keywords': 'air quality, ambient air, daily data, tamil nadu, air pollution, industrial pollution, residential pollution, vehicular pollution', 'generated_sponsored_keywords': 'air quality, ambient air, tamil nadu, daily data, air pollution', 'generated_theme': 'Environment and Forest; Industrial Air Pollution, Environment and Forest; Residential Air Pollution, Environment and Forest; Vehicular Air Pollution', 'justification': 'Sources used: title, sector, sector_resource, catalog_title, and note. Extraction rules: split semicolon separated fields into individual terms; convert to 1–2 word layman terms in lowercase; avoid department names and acronyms; choose terms that reflect everyday concepts and India-relevant context (eg tamil nadu). From the title and catalog_title we identify location (tamil nadu) and temporal scope (daily, historical). Sector fields provide pollution sources (industrial, residential, vehicular) within the environment context, which map to the SECTOR_VOCAB_JSON under Environment and Forest with corresponding sub-sectors. Sponsored keywords are a concise subset of the layman keywords that align closely with the title/note (air quality, ambient air, tamil nadu, daily data, air pollution). Note indicates potential data quality issues due to field instruments, which informs caution but does not change keyword choices.', 'confidence_score': 0.85, 'metadata_gaps': "state_department field null; frequency field not provided; note mentions data quality but no explicit quality flag in metadata; 'CDOS State Ministry' note provided but not mapped to a field"}

TITLE: Location wise daily Ambient Air Quality of Tamil Nadu for the year 2014
SECTOR: Environment and Forest;Industrial Air Pollution;Residential Air Pollution;Vehicular Air Pollution

✓ Written to CSV

----------------------------

2026-01-15 10:40:47,786 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:40:47,788 : INFO - Result is {'generated_keywords': 'poultry farm, poultry bird, district data, livestock census, tamil nadu, agriculture, animal husbandry, census data', 'generated_sponsored_keywords': 'poultry farm, poultry bird, district data, livestock census, tamil nadu', 'generated_theme': 'Agriculture; Animal Husbandry', 'justification': 'Source columns used: title, sector, sector_resource, note, and ministry_department/CDOS state ministry. Processing steps: \n- Parsed semicolon-separated values in sector and sector_resource to understand the domain context (Agriculture; Animal Husbandry) and used these as a basis for subject framing. \n- Extracted core subjects from the title: poultry farms, poultry birds, district wise data, and Tamil Nadu; noted the 18th Livestock census mentioned in the note. \n- Generated layman keywords by mapping dataset core concepts to simple terms, preferring singular forms as much as possible per guidance (e.g., poultry farm, poultry bird). Included location terms (Tamil Nadu) since location is inherent in the title and useful for discovery in Indian contexts. Added general domain terms (agriculture, animal husbandry, census data) to broaden findability while avoiding department names and acronyms. Ensured terms are 1–2 words, lowercase, and non-redundant. \n- Generated sponsored keywords by selecting 3–5 terms with strongest overlap to the title/note: poultry farm, poultry bird, district data, livestock census, tamil nadu. These are concise, directly reflect the main ideas, and avoid internal terms or department names. \n- Generated theme by mapping to the SECTOR_VOCAB_JSON. The dataset clearly falls under Agriculture with a sub-sector of Animal Husbandry, so the theme is represented as "Agriculture; Animal Husbandry". Only one theme is provided since it best represents the dataset domain and aligns with the vocab. \n- No new subjects were invented; if a precise sub-sector had been unavailable, a higher-level sector would have been used. \nAmbiguities/assumptions: The dataset lacks frequency/granularity/government level fields in the provided input; decisions here are based on the available metadata (title, sector, note). The note indicates census data, which supports the inclusion of census-related keywords. If additional context (e.g., update frequency) were provided, keywords could be refined further.', 'confidence_score': 0.8, 'metadata_gaps': ['frequency', 'granularity', 'govt_type', 'state_department']}

TITLE: District wise Number of Poultry Farms and Poultry Birds in Farms, 2007  - Tamil Nadu
SECTOR: Agriculture;Animal Husbandry

✓ Written to CSV

----------------------------

2026-01-15 10:41:00,434 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:41:00,436 : INFO - Result is {'generated_keywords': 'aging, india, health, study, survey, population, elderly, longitudinal', 'generated_sponsored_keywords': 'longitudinal aging, india study, aging survey, health data, population study', 'generated_theme': 'Health and Family welfare; Health', 'justification': 'Sources used: title, sector, sector_resource. Extraction rules: parsed semicolon-separated values in sector (Health and Family welfare; Health) and sector_resource (Health); used the title to anchor the main concept (Longitudinal Ageing Study in India LASI) and derived layman terms reflecting aging, health, population, and survey aspects. Normalization: all terms converted to lowercase, singular where applicable, and limited to 1–2 words per keyword. Words chosen to be India-relevant (india, population) and to reflect the longitudinal health study nature (longitudinal, aging, elderly, survey, study). Sponsored keywords were derived from strong overlaps between the title and layman terms (longitudinal aging from Longitudinal Ageing Study, india study from India context, aging survey, health data, population study). Theme mapping used the SECTOR_VOCAB_JSON: Health and Family welfare → Health as the primary subject; selected a single theme since the dataset centers on health and aging epidemiology. Note: no department/location terms were used in keywords per guidelines. Ambiguities/assumptions: assuming the core subject is health-related aging research in India, despite the note containing state-factsheet details; no explicit frequency/granularity values provided in the metadata, so those aspects are not reflected in keywords/themes.', 'confidence_score': 0.8, 'metadata_gaps': 'frequency missing; granularity missing; state_department field not clearly populated (null); note contains contextual information but not used for keyword derivation'}

TITLE: Longitudinal Ageing Study in India (LASI), Wave  I, 2017-18
SECTOR: Health and Family welfare;Health

✓ Written to CSV

----------------------------

2026-01-15 10:41:03,267 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:41:03,268 : INFO - Result is {'generated_keywords': 'price index, state level, rural price, urban price, consumer price, historical, time series', 'generated_sponsored_keywords': 'price index, rural price, urban price, consumer price, historical index', 'generated_theme': 'Prices, Macro Economy', 'justification': "Source columns used: title (to identify core subject and temporal framing), sector (to derive domain keywords), sector_resource (null), note (null). Rules applied: parsed semicolon-separated sector values to obtain Economy, Prices, Finance, Statistics (deduplicated); extracted core concepts from the title: consumer price index, rural/urban, state level, upto 2021; normalized to layman terms in singular form where possible; created 1–2 word keywords in lowercase with no punctuation. Temporal cue added from the phrase 'upto November 2021' by including historical and time series concepts. Exclusions: department names and acronyms were avoided; no location names beyond inherent 'state level' context. Ambiguities/assumptions: assuming the dataset is historical CPI data at state level with rural/urban breakdown, hence included 'historical' and 'time series' as descriptive facets. The note field is null, so no additional guidance from notes was available.", 'confidence_score': 0.9, 'metadata_gaps': 'sector_resource; note'}

TITLE: State Level Consumer Price Index (Rural/Urban)  upto November 2021
SECTOR: Economy;Prices;Finance;Economy;Statistics

✓ Written to CSV

----------------------------

2026-01-15 10:41:10,147 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:41:10,149 : INFO - Result is {'generated_keywords': 'district score, education data, school performance, state education, performance index, grading index', 'generated_sponsored_keywords': 'district score, education data, school performance, state education, performance index', 'generated_theme': 'Education, Elementary, Secondary', 'justification': "Source columns used: title, sector, sector_resource, note. Extraction/normalization: parsed semicolon-separated values where present (none in this case); treated nan as missing. Keywords chosen to reflect core subject without department names or acronyms; favored simple, layman terms. From title 'State/UT-wise District Score during 2021-22' we derive core concepts: district score and time frame; from sector 'Education' we anchor to the education domain; PGI/content hint in catalog title aligns with school performance metrics, hence terms like 'school performance', 'performance index', and 'grading index'. We avoided 'army' (sector_resource) as it is out of domain for this education dataset. Note is missing ('nan'), so no additional contextual terms could be derived from notes.", 'confidence_score': 0.75, 'metadata_gaps': "note missing; sector_resource value 'Army' appears out of domain for this dataset and may introduce noise"}

TITLE: State/UT-wise District Score during 2021-22
SECTOR: Education

✓ Written to CSV

----------------------------

2026-01-15 10:41:16,662 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:41:16,664 : INFO - Result is {'generated_keywords': 'india temperature, seasonal temperature, annual temperature, temperature series, climate series, historical temperature, weather data, temperature data', 'generated_sponsored_keywords': 'temperature series, india temperature, seasonal temperature, annual temperature', 'generated_theme': 'Science and Technology; Earth Sciences', 'justification': 'Source columns used: title and sector/sector_resource to derive the dataset focus; note is null (nan) indicating missing detail on frequency/granularity, which influenced confidence. Processing steps: parsed semicolon-separated values in sector and sector_resource to confirm domain as Earth Sciences within Science and Technology; extracted core subjects from the title (seasonal, annual, minimum/maximum temperature, temperature series) and catalog title (All India Seasonal and Annual Temperature Series) to form layman keywords. Normalization included converting to lowercase, using 1–2 word terms, and avoiding department names or acronyms (IMD, Ministry names). India relevance was emphasized via terms like india temperature to reflect All India scope. Keywords chosen reflect the core topics (temperature, seasonal/annual series) while ensuring non-technical, discovery-friendly terms. Exclusions: internal terms and acronyms were omitted; geographic scope retained as inherent in the title. Ambiguities/assumptions: exact data frequency and granularity are not provided; assumption is a historical temperature series over a long period, hence inclusion of historical/seasonal/annual terms. If frequency/granularity are provided, temporal keywords (e.g., daily, time series) could be added.', 'confidence_score': 0.7, 'metadata_gaps': ['note', 'frequency', 'granularity', 'state_department']}

TITLE: Seasonal and Annual Minimum / Maximum Temperature series for the period 1901-2021
SECTOR: Science and Technology;Earth Sciences

✓ Written to CSV

----------------------------

2026-01-15 10:41:18,838 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:41:18,840 : INFO - Result is {'generated_keywords': 'motor vehicle, vehicle registration, road transport, transport data, year book, tamil nadu', 'generated_sponsored_keywords': 'motor vehicle, vehicle registration, registration number, road transport, tamil nadu', 'generated_theme': 'Transport; Road Transport', 'justification': "Source columns used: title, note, sector, sector_resource, minist ry_department. Extraction rules: - Split semicolon-separated values in sector and sector_resource to extract individual hints. - Normalize terms to lowercase and prefer singular forms where applicable (e.g., motor vehicle instead of vehicles; registration number rather than numbers). - Avoid department names and acronyms; treat 'Tamil Nadu' as inherent location from the title. - Derive layman keywords from core subject (registrations of motor vehicles) and include India-relevant context (state level data). - Sponsored keywords are tightly tied to the title/note and represent likely search phrases (e.g., motor vehicle, vehicle registration, registration number, road transport, tamil nadu). - Theme mapped to SECTOR_VOCAB_JSON: Transport with sub-sector Road Transport, reflecting the dataset’s focus on road vehicle registrations. Ambiguities/assumptions: frequency, granularity, and govt_type are not provided in the input; assumed annual state-level data from the note and title. Note mentions year book sources, supporting terms like year book and data context. Excluded terms: department names ( Ministry of Road Transport and Highways ) from keyword lists to avoid branding bias; location terms are included only where inherent to dataset context (Tamil Nadu).", 'confidence_score': 0.9, 'metadata_gaps': 'state_department field missing (null); frequency missing; granularity missing; govt_type missing'}

TITLE: Number of Newly Registered Motor Vehicles in 2009-10 and 2010-11 and Number of Registered Motor Vehicles as on 31st March 2010 and as on 31st March 2011 in Tamil Nadu
SECTOR: Transport;Road Transport

✓ Written to CSV

----------------------------

2026-01-15 10:41:19,269 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:41:19,272 : INFO - Result is {'generated_keywords': 'motor vehicle, vehicle registration, india transport, road transport, transport data, vehicle count, time series, historical record', 'generated_sponsored_keywords': 'vehicle registration, motor vehicle, india transport, vehicle count, time series', 'generated_theme': 'Transport; Road Transport', 'justification': 'Source extraction used:\n- sector and sector_resource were parsed as: [Transport, Road Transport] to identify the domain area and its sub-domain.\n- title: "Total Number of Registered Motor Vehicles in India during 1951-2013" provided core concepts: registered motor vehicles in India over a historical period, indicating a time-series count for road transport in India.\n- note: confirms counting nature and time span (1951-2013) without introducing new subject domains; allowed emphasis on temporal data and vehicle/registration notions.\nHow keywords were generated:\n- Enhanced layman keywords (4–10): selected terms express the dataset subject in everyday language while remaining singular where possible and avoiding department names. Terms cover the core subject (motor vehicle, vehicle registration), geographical scope (india), domain (road transport), data characteristics (transport data, vehicle count), and temporal aspect (time series, historical record).\n- Sponsored keywords (3–5): derived from strongest overlaps between the title/note and layman terms, focusing on concise terms users would likely search (vehicle registration, motor vehicle, india transport, vehicle count, time series).\nNormalization and filtering rules applied:\n- All terms are kept lowercase and limited to 1–2 words where possible.\n- Duplicates are avoided; no punctuation beyond spaces.\n- Terms drawn from sector/sector_resource, title, and note; department names and acronyms are excluded.\n- Where plural forms could appear, singular-friendly terms were preferred (e.g., motor vehicle, vehicle registration, vehicle count).\nAmbiguities and assumptions:\n- The dataset spans 1951–2013 and is described as counts; treated as time-series data for temporal relevance (time series keyword).\n- The state/central governance context is present in the metadata but not required in keyword generation; no location-specific or department-specific terms were included in the keywords.\n- If any additional granularity or frequency terms were present, they were not explicit in the provided data; thus, frequency/granularity are left as metadata gaps rather than forced keywords.', 'confidence_score': 0.85, 'metadata_gaps': 'frequency; granularity'}

TITLE: Total Number of Registered Motor Vehicles in India during 1951-2013
SECTOR: Transport;Road Transport

✓ Written to CSV

----------------------------

2026-01-15 10:41:23,438 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:41:23,441 : INFO - Result is {'generated_keywords': 'delhi, motor vehicle, vehicle registration, road transport, registered vehicle, new registration, transport data', 'generated_sponsored_keywords': 'delhi vehicle, vehicle registration, road transport, new registration, registered vehicle', 'generated_theme': 'Transport; Road Transport', 'justification': 'Sources used: title, sector, sector_resource, note. Processing steps: 1) Parsed sector into two terms: Transport and Road Transport. 2) Extracted location and subject hints from the title (delhi, motor vehicle, registration) and normalized to singular forms where appropriate (e.g., vehicle). 3) Generated layman keywords (4–10) with 1–2 words each, all in lowercase, avoiding department names and acronyms, and excluding plural forms where possible. 4) Generated sponsored keywords focused on the strongest overlaps with the title and note: delhi vehicle, vehicle registration, road transport, new registration, registered vehicle. 5) Mapped theme to the controlled vocabulary: Transport; Road Transport, based on SECTOR_VOCAB_JSON. Notes: the dataset concerns counts of motor vehicle registrations in Delhi, hence emphasis on Delhi, vehicle, registration, and road transport terms. Department name was intentionally excluded from keywords.  Ambiguities: none significant; data clearly relates to vehicle registration counts in Delhi for a historical period. ', 'confidence_score': 0.92, 'metadata_gaps': 'frequency, granularity, state_department (null in input), additional standard fields (e.g., place/region field) not provided; note present but no explicit time granularity beyond year range'}

TITLE: Number of Newly Registered Motor Vehicles in 2011-12 and Number of Registered Motor Vehicles as on 31st March, 2012 in Delhi
SECTOR: Transport;Road Transport

✓ Written to CSV

----------------------------

2026-01-15 10:41:46,491 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:41:46,709 : INFO - Result is {'generated_keywords': 'watershed boundary, boundary, groundwater, surface water, watershed, india', 'generated_sponsored_keywords': 'watershed boundary, watershed, boundary, india', 'generated_theme': 'Water Resources; Ground Water, Water Resources; Surface Water', 'justification': 'Source columns used: title (Shape of Watershed Boundaries of India) and sector/sector_resource (Surface Water;Ground Water) indicate hydrological boundaries related to water resources. Note provided (zip of shapefile formats) confirms a geospatial boundary dataset but was not included as a keyword to avoid technical terms. I extracted semicolon-separated values from sector and sector_resource to capture both surface water and groundwater domains; I normalized terms to singular or standard phrases (watershed boundary, boundary, groundwater, surface water). India is included as an inherent geographic context from the title. For keywords, I favored layman, non-technical terms that directly reflect the dataset’s core subject. For sponsored keywords, I selected the strongest overlaps with the title (watershed boundary, watershed, boundary, india). Theme mapping uses the SECTOR_VOCAB_JSON namespace: top-level theme Water Resources with sub-themes Ground Water and Surface Water to reflect resource-level granularity. Ambiguities: the note mentions file formats which are technical; these were not turned into keywords to keep layperson-friendly discovery terms. Assumptions: location (india) is inherent and appropriate for inclusion. ', 'confidence_score': 0.9, 'metadata_gaps': 'frequency, granularity'}

TITLE: Shape of Watershed Boundaries of India
SECTOR: Surface Water;Ground Water

✓ Written to CSV

----------------------------

2026-01-15 10:41:48,648 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:41:48,650 : INFO - Result is {'generated_keywords': 'patent, grant, application, weekly, patent status, intellectual property, industry data', 'generated_sponsored_keywords': 'patent, patent application, weekly patent, patent status', 'generated_theme': 'Industries, Manufacturing', 'justification': "Source fields used: title, sector, sector_resource, ministry_department, note. Parsing rules applied: (1) Extracted individual semicolon-delimited values when present (sector_resource is null here, so none to extract). (2) Derived layman keywords from the title 'Weekly Patent Application Granted' emphasizing core concepts: patent, application, grant/status, and the weekly cadence. Used singular forms where possible (e.g., 'application' rather than 'applications'). Kept keywords lowercase and avoided department acronyms or internal terms. (3) If note is null, applied a small confidence reduction per policy (note treated as missing). (4) Theme mapping used the SECTOR_VOCAB_JSON: sector 'Industries' corresponds to sub-sectors like 'Manufacturing'; chosen 'Manufacturing' as a representative sub-sector under 'Industries' to align with a patent/grant related context. Excluded terms: any department names and non-discoverable jargon. (5) Sponsored keywords derived from strongest overlaps between title and layman terms: patent, patent application, weekly patent, patent status. Ambiguities/assumptions: the dataset lacks explicit frequency granularity beyond 'Weekly' in the title; we assume the dataset tracks weekly patent activities rather than a weekly update dataset. State-level fields are not provided; department names were used only for context and not as keywords.", 'confidence_score': 0.9, 'metadata_gaps': ['sector_resource', 'note', 'state_department', 'frequency', 'granularity', 'govt_type']}

TITLE: Weekly Patent Application Granted
SECTOR: Industries

✓ Written to CSV

----------------------------

2026-01-15 10:41:51,479 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:41:51,481 : INFO - Result is {'generated_keywords': 'cyclone, cyclone history, time series, seasonal data, coastal state, weather history, cyclone count, coastal weather', 'generated_sponsored_keywords': 'cyclone data, cyclone history, coastal states, weather history, cyclone count', 'generated_theme': 'Atmospheric Science, Earth Sciences', 'justification': 'Sources used: title, note, sector, sector_resource. Processing steps: parsed semicolon-separated values in sector and sector_resource to identify core domains (Atmospheric Science and Earth Sciences are explicitly present in sector). The note provides context about regions (coastal states) and historical time span; this informed inclusion of terms like weather history and cyclone history. Constraints applied: keywords are 1–2 words each (where needed combined into two-word phrases), lowercase, non-technical, and avoiding department acronyms. Excluded terms: ministry/department names and internal codes. Reasoning for each keyword: cyclone and cyclone history capture the main subject and its temporal aspect; time series and seasonal data reflect the annual/time-based nature of the dataset; coastal state and coastal weather reflect geographic focus; cyclone count conveys the frequency aspect. Sponsored keywords were drawn from strong overlaps with the title/note (cyclone data, cyclone history, coastal states, weather history, cyclone count). Theme mapping uses SECTOR_VOCAB_JSON: Atmospheric Science and Earth Sciences (sub-sectors under Science and Technology) to provide domain-level classification. Ambiguities/assumptions: frequency and granularity fields are not present in the input; while note mentions years 1891–2017 and annual/seasonal frequency, exact granularity/frequency fields are missing, which is acknowledged in metadata_gaps. Acronyms and department names were deliberately excluded as per guidelines.', 'confidence_score': 0.8, 'metadata_gaps': 'frequency, granularity, govt_type, state_department missing/not provided; sector_resource contains duplicates but was normalized; note provides regional context but no explicit data fields for exact spatial granularity'}

TITLE: Year-wise Annual frequency of cyclones (34 knots or more) and severe cyclones (48 knots or more) crossing different coastal states of India from 1891 to 2017
SECTOR: Science and Technology;Atmospheric Science;Earth Sciences

✓ Written to CSV

----------------------------

2026-01-15 10:41:55,727 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:41:55,730 : INFO - Result is {'generated_keywords': 'temperature data, climate data, time series, historical data, seasonal temperature, monthly temperature, annual temperature, india temperature, weather data, mean temperature', 'generated_sponsored_keywords': 'monthly temperature, seasonal temperature, annual temperature, mean temperature, temperature series', 'generated_theme': 'Science and Technology, Earth Sciences', 'justification': 'Source fields used: title, sector, sector_resource, and note. Extraction/normalization rules applied: (1) semicolon-separated fields were split into individual hints; (2) terms were normalized to lowercase and kept to 1–2 words per keyword; (3) avoided department names/acronyms and non-substantive terms; (4) prioritized India-relevant scope inferred from catalog/title where appropriate. From the title and sector_resource, core concepts identified include temperature, seasonal/mean/monthly/annual aspects, and time series. The following layman keywords were generated to cover both broad and specific facets: temperature data, climate data, time series, historical data, seasonal temperature, monthly temperature, annual temperature, india temperature, weather data, mean temperature. Sponsored keywords were derived from strong overlaps with the title (monthly/seasonal/annual/mean temperature and series): monthly temperature, seasonal temperature, annual temperature, mean temperature, temperature series. For the thematic mapping, the dataset aligns with Science and Technology and more specifically Earth Sciences per SECTOR_VOCAB_JSON (Science and Technology -> Earth Sciences). The note field is marked as nan (missing), so a minor confidence reduction is applied. The geographic scope appears to be All India based on the catalog title, supporting inclusion of india related terms in context. Assumptions include treating the temperature series as long-term climate data for India; acronyms and department names are excluded from keywords; statistics like period (1901-2021) are not used as standalone keywords since they are date ranges rather than discoverable concepts.', 'confidence_score': 0.9, 'metadata_gaps': ['note missing (nan) in the note field']}

TITLE: Monthly, Seasonal and Annual Mean Temperature Series for the period 1901-2021
SECTOR: Science and Technology;Earth Sciences

✓ Written to CSV

----------------------------

2026-01-15 10:42:01,700 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:42:01,702 : INFO - Result is {'generated_keywords': 'chemical imports, major chemicals, product wise, group wise, time series, petrochemicals, imports data, industry data', 'generated_sponsored_keywords': 'imports, major chemicals, product wise, group wise, petrochemicals', 'generated_theme': 'Industries, Chemicals and Petrochemicals', 'justification': "Source columns used: title, sector, sector_resource, note, and ministry_department were considered. Sector contains two parts (Industries;Chemicals and Petrochemicals) which directly map to the SECTOR_VOCAB_JSON as a high level sector (Industries) and its sub-sector (Chemicals and Petrochemicals). The title indicates the dataset is about imports of major chemicals and its product-wise/group-wise breakdown across a date span; note clarifies data provenance (DGCIS) and scope (chemicals monitored by the S&M Division). Processing rules applied: semicolon-separated values were split into individual hints; terms were normalized to lowercase and de-duplicated; preferred singular forms were used where applicable; no acronyms or department names were included in keywords. Suggested layman keywords emphasize the core topics (chemicals, imports, product/group breakdown, industry context) and include a time-series cue (time series) derived from the date range in the title. Sponsored keywords focus on the strongest, most direct overlaps with the title (imports, major chemicals, product wise, group wise, petrochemicals). Theme keywords align with the provided SECTOR_VOCAB_JSON, mapping to the high-level sector and its sub-sector (Industries; Chemicals and Petrochemicals). Ambiguities/assumptions: sector_resource is listed as 'nan' which is treated as missing; frequency and granularity are not provided, so no temporal/real-time indicators are added beyond the implicit time-span in the title. Department names and acronyms were intentionally excluded from the keywords per guidelines.", 'confidence_score': 0.8, 'metadata_gaps': ["sector_resource value is non-informative ('nan')", 'frequency is missing', 'granularity is missing', 'govt_type is missing']}

TITLE: Imports of Major Chemical - Product-wise / Group-wise from 2014-15 to 2021-22
SECTOR: Industries;Chemicals and Petrochemicals

✓ Written to CSV

----------------------------

2026-01-15 10:42:11,637 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:42:11,641 : INFO - Result is {'generated_keywords': 'small business, micro business, medium business, registered unit, maharashtra, manufacturing, small scale', 'generated_sponsored_keywords': 'registered unit, maharashtra, micro enterprise, small enterprise, manufacturing', 'generated_theme': 'Industries, Manufacturing, Small Scale', 'justification': 'Source columns used: title, sector, sector_resource (semicolon-separated values) and note. Extraction/normalization rules applied: 1) Parse sector and sector_resource into individual hints (Medium;Micro;Small Scale → micro business, small business, medium business). 2) Derive layman keywords from the dataset subject without department names; use singular forms where possible (e.g., registered unit instead of registered units). 3) Include geographic context from title (Maharashtra → maharashtra). 4) Include a domain-relevant term to capture MSME orientation (manufacturing, small scale). 5) Exclude acronyms and internal terms; avoid department names. 6) Sponsored keywords derived from strong overlaps between title/note and layman terms, focusing on core concepts: registered unit, maharashtra, micro enterprise, small enterprise, manufacturing. 7) Theme mapping uses SECTOR_VOCAB_JSON: Industries as top level, with sub-sectors Manufacturing and Small Scale to reflect the dataset’s MSME manufacturing context in a Maharashtra state. Ambiguities/assumptions: The note mentions API usage and download parameters but does not alter the subject; assumed the core subject is MSME registered units across micro/small/medium categories in Maharashtra; excluded non-essential terms from keywords.', 'confidence_score': 0.9, 'metadata_gaps': 'state_department: null; frequency: null; granularity: null'}

TITLE: List of MSME Registered Units under Udyog Aadhaar Memorandum - Maharashtra
SECTOR: Medium;Micro;Small Scale

✓ Written to CSV

----------------------------

2026-01-15 10:42:11,928 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:42:11,930 : INFO - Result is {'generated_keywords': 'startup, technology, information, broadcasting, incubation, innovation, ecosystem, entrepreneurship', 'generated_sponsored_keywords': 'startup hub, startup list, technology startup, startup ecosystem', 'generated_theme': 'Information and Technology, Information and Broadcasting', 'justification': 'Sources and extraction process:\n- sector and sector_resource fields were parsed as semicolon-separated values and expanded into individual hints. This yielded domain facets related to information technologies and broadcasting (e.g., Information and Technology; Information and Broadcasting) which guided theme mapping.\n- title and note were consulted to understand the dataset’s core idea (a list of startups via the MeitY Startup Hub) and to derive sponsor terms overlapping with the main concept while avoiding department names. From the title/note, sponsor keywords such as startup hub, startup list, technology startup, and startup ecosystem were selected to closely match user search behavior around the dataset purpose.\n- For layman keywords, 1–2 word terms were drawn from sector hints (Information and Communications, Information and Technology) and related subdomains (broadcasting, incubation, innovation, ecosystem). Singular forms were preferred where possible (e.g., startup, technology, information) to align with the rules. Redundant terms and department names were avoided.\n- Theme mapping was restricted to the supplied SECTOR_VOCAB_JSON. The dataset falls under Information and Communications with sub-sectors Information and Technology and Information and Broadcasting, so themes reflect these two sub-sectors. No new taxonomy was invented; only existing vocab terms were used.\n- Assumptions: the dataset concerns MeitY’s startup ecosystem, focusing on technology startups within the MeitY Startup Hub; deanonymized department names were omitted from keywords per guidance.\n- Ambiguities/choices: Although the dataset mentions MeitY, the rules encourage avoiding department names in keywords; hence sponsor keywords emphasize the startup hub concept rather than the ministry itself. If future metadata adds location or frequency granularity, additional keywords could be added (e.g., time-series terms).\n', 'confidence_score': 0.9, 'metadata_gaps': 'frequency; granularity; state_department'}

TITLE: List of all Startups from Meity Startup Hub
SECTOR: Information and Communications;Information and Technology

✓ Written to CSV

----------------------------

2026-01-15 10:42:18,047 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:42:18,049 : INFO - Result is {'generated_keywords': 'core industries, industry, manufacturing, electricity, renewable energy, base year, financial year, index', 'generated_sponsored_keywords': 'core industries, manufacturing, electricity, base year', 'generated_theme': 'Industries; Manufacturing, Power and Energy', 'justification': 'Source columns used: title (identifies eight core industries and base year), sector (Industries; Manufacturing) and sector_resource (Industries; Manufacturing) to derive layman terms, note (mentions electricity generation from renewable sources) to capture energy-related aspects, and ministry_department/CDOS fields used for context but not as keywords. Extraction/normalization rules applied: semicolon-separated values were split into individual hints; terms were converted to singular where appropriate (industry from industries); all keywords kept lowercase with no punctuation; ensured 1–2 word length per keyword; avoided internal terms and acronyms; included India-relevant context (renewable energy). Rationale for keywords: core industries and industry reflect the central topic; manufacturing aligns with sector_resource; electricity and renewable energy reflect the note about energy data; base year and financial year capture the time dimension emphasized in the title; index is included as it commonly denotes a data series related to core industries. Theme mapping used SECTOR_VOCAB_JSON: mapped to Industries with sub-theme Manufacturing, and Power and Energy for the electricity/renewable aspect. Ambiguities/assumptions: frequency, granularity, and govt_type fields are not provided; state_department is not explicitly given in the input fields (CDOS State Ministry is present but not labeled as state_department), which could affect finer classification. Assumed that base year and financial year refer to time-bundling in the dataset.', 'confidence_score': 0.85, 'metadata_gaps': 'frequency, granularity, govt_type, state_department (null); missing explicit field mappings for someTemporal/Administrative attributes'}

TITLE: Eight Core Industries (Base Year 2011-12) till last financial year
SECTOR: Industries;Manufacturing

✓ Written to CSV

----------------------------

2026-01-15 10:42:39,137 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:42:39,377 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:42:39,379 : INFO - Result is {'generated_keywords': 'maps, satellite imagery, topographic maps, andhra pradesh, panchromatic imagery, bhuvan imagery, geospatial data, web maps', 'generated_sponsored_keywords': 'web maps, topo sheets, andhra pradesh, panchromatic imagery, bhuvan imagery', 'generated_theme': 'Information and Communications, Infrastructure, Governance and Administration, Science and Technology', 'justification': 'Source columns used: title, sector, sector_resource, ministry_department, and notes. Extraction/normalization rules applied: (1) Parse semicolon-separated values in sector and sector_resource; (2) extract key concepts from the title that reflect the dataset purpose (maps, imagery, topo sheets, region) while avoiding department names; (3) generate layman keywords (1–2 words each, lowercase, singular where possible, no punctuation); (4) ensure India-relevant terms when applicable (e.g., state/region terms like andhra pradesh); (5) sponsor keywords derived from strongest overlaps between title/note and layman terms, limited to 3–5 items; (6) map themes to SECTOR_VOCAB_JSON where possible, using 2–4 broad themes. Terms included reflect core subjects: maps and imagery relevant to a geographic region and NSDI context. Excluded items: department names and acronyms; avoided three-word phrases where possible (e.g., survey of india) unless essential. Ambiguities/assumptions: assumed andhra pradesh is an inherent location in the dataset and included as a keyword; treated WMS-related terms as map-focused layman terms while avoiding explicit technical acronyms in the final keywords.', 'confidence_score': 0.8, 'metadata_gaps': 'note field is null; state_department field not provided (null/missing)'}
2026-01-15 10:42:39,450 : INFO - Result is {'generated_keywords': 'elephant, population, wildlife, biodiversity, reserve, trend, time series', 'generated_sponsored_keywords': 'elephant population, population status, elephant reserve, population trend', 'generated_theme': 'Wild life, Bio-diversity', 'justification': 'Source fields used: title (extracts core subject: elephant population; implies a time span 1993–2017), sector (Environment and Forest informs the domain), ministry_department (Ministry of Environment, Forest and Climate Change provides context though not used as a keyword), sector_resource (null), note (null). Normalization rules applied: keywords converted to lowercase; singular preference applied (e.g., elephant, population, trend); semicolon-separated fields would be split if present but sector_resource is null here. Keyword selections: - elephant and population directly reflect the title; - wildlife and biodiversity align with Environment and Forest domain and capture broader context beyond the specific species; - reserve captures the elephant reserve aspect in the title; - trend and time series reflect the temporal nature (1993 to 2017) of the data. Sponsored keywords were chosen as concise overlaps between the title and layman terms: elephant population, population status, elephant reserve, population trend. Theme mapping used SECTOR_VOCAB_JSON: mapped to Wild life and Bio-diversity as high-level subjects within Environment and Forest, appropriate for an elephant population dataset; no sub-sectors beyond what exists in the vocab were forced. Assumptions: dataset pertains to elephants in an Indian environment/forest context given the ministry name; no geographic qualifier is explicit in the metadata. Ambiguities: exact geographic scope and whether data covers multiple reserves within India are not specified in the provided fields.', 'confidence_score': 0.9, 'metadata_gaps': 'sector_resource, note'}

TITLE: Web Map Service from  362 OSM Topo Sheets  of  Survey of India and Panchromatic imagery of Bhuvan  in Andhra Pradesh
SECTOR: All;Agriculture;Water and Sanitation;Information and Communications;Defence;Environment and Forest;Water Resources;Governance and Administration;Infrastructure;Social Development;Transport;Travel and Tourism

✓ Written to CSV

----------------------------

TITLE: Elephant Population from 1993 to 2017
SECTOR: Environment and Forest

✓ Written to CSV

----------------------------

2026-01-15 10:42:40,713 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:42:40,715 : INFO - Result is {'generated_keywords': 'rainfall, daily rainfall, rainfall data, monsoon rainfall, precipitation, water resources, weather data, july rainfall, average rainfall', 'generated_sponsored_keywords': 'july rainfall, rainfall data, grid rainfall, precipitation', 'generated_theme': 'Water Resources', 'justification': ['- Source columns used: title, sector, sector_resource, ministry_department, note. Interpreted frequency and granularity from the title and implied context; inferred governance context from ministry_department.', "- Extraction and normalization rules applied: parsed semicolon-separated values in ministry_department (to identify the central ministry, Ministry of Jal Shakti, as the overarching governance context); treated sector_resource as null (nan) and relied on sector for subject. deduced frequency from the phrase 'Daily Rainfall' in the title, and deduced granularity as 'Gridded' from 'GRID MODEL' in the title. Note provided 'Average rainfall in millimetre (MM)' to inform keyword choices. All keywords kept to 1–2 words per term; composed layman-friendly terms in lowercase; avoided department names in the keyword lists.", "- Why specific terms were selected: core subject is rainfall data for a specific period (July 2023) derived from IMD gridded model. Terms like rainfall, daily rainfall, rainfall data, monsoon rainfall, precipitation, water resources, weather data, july rainfall, and average rainfall capture both the general topic and dataset-specific cues without technical jargon. 'Water resources' is chosen as the primary thematic lane given the sector field. 'July rainfall' and 'daily rainfall' reflect the temporal and frequency aspects implied by the title. 'Monsoon rainfall' aligns with the Indian monsoon context often associated with July rainfall.", '- Why terms were excluded: avoided acronyms (IMD, GRID MODEL) and department names in layman keywords per instructions. Excluded overly technical terms not helpful for a general audience. Avoided duplicating the exact title phrase where possible to enhance discoverability without redundancy.', "- Ambiguities and assumptions: assumed frequency as daily based on the phrase 'Daily Rainfall' in the title; assumed granularity as gridded due to 'GRID MODEL' in the title; state_department field was left null since the primary governance context is central (MoJS) and the dataset does not clearly map to a state-specific department. Note content did not specify an explicit frequency or granularity field, so these were inferred from the title. If actual frequency/granularity differ, keywords may require adjustment."], 'confidence_score': 0.8, 'metadata_gaps': ['sector_resource field is null', 'state_department field is null', 'frequency field not provided (inferred as Daily from title)', 'granularity field not provided (inferred as Gridded from title)']}

TITLE: Daily Rainfall data from India Meteorological Department (IMD GRID MODEL) Agency during July 2023
SECTOR: Water Resources

✓ Written to CSV

----------------------------

2026-01-15 10:42:44,559 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:42:44,561 : INFO - Result is {'generated_keywords': 'pincode boundary, post office, delivery, india, postal mapping, boundary data, geospatial', 'generated_sponsored_keywords': 'pincode boundary, post office, postal mapping, boundary data, geospatial', 'generated_theme': 'Information and Communications; Post', 'justification': 'Sources used: title and catalog_title to identify the dataset focus on indian postal pincodes and boundaries (Delivery Post office Pincode Boundary; All India Pincode Boundary Geo JSON). Since sector_resource is null, and note is null, I relied on the title/catalog context to derive layman keywords and used the high-level sector mapping for theme. Extraction rules: 1) break down key concepts from title (pincode boundary, post office, delivery) into 1–2 word layman terms; 2) include India-relevant elements inferred from All India; 3) form a concise set of 4–10 keywords in lowercase with no punctuation beyond spaces; 4) sponsored keywords are a tight subset reflecting the main idea; 5) map to SECTOR_VOCAB_JSON subject: Information and Communications; Post. Assumptions: dataset concerns geospatial boundaries of pincodes for post offices across India, hence terms like geospatial and boundary data. Exclusions: department name (Department of Posts) is not included in keywords per rules, and avoided overly technical strings like geo json in sponsored terms. Ambiguities: exact data formats beyond GEO JSON are not specified; frequency/granularity not provided.', 'confidence_score': 0.9, 'metadata_gaps': 'sector_resource; note; frequency; granularity; govt_type; state_department'}
2026-01-15 10:42:44,712 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:42:44,714 : INFO - Result is {'generated_keywords': 'rainfall, india rainfall, regional rainfall, subdivision rainfall, rainfall data, historical rainfall, rainfall departure, climate data', 'generated_sponsored_keywords': 'subdivision rainfall, rainfall departure, historical rainfall, rainfall data', 'generated_theme': 'Atmospheric Science, Earth Sciences', 'justification': 'Source columns used: title (Subdivision wise Rainfall and its departure), catalog_title (Rainfall in India) to capture core subject; sector and sector_resource (Science and Technology; Atmospheric Science; Earth Sciences) to determine domain themes; ministry_department (Ministry of Earth Sciences; IMD) for contextual relevance; note (details about measurements in mm) used to understand data context. Extraction and normalization: parsed semicolon-separated values in sector/sector_resource to identify relevant themes; derived layman keywords directly from the title concepts (subdivision rainfall, rainfall departure) and augmented with region-specific and time-context terms from the catalog title (india rainfall) and general dataset framing (rainfall data, historical rainfall, climate data). Sponsored keywords drawn from the strongest overlaps with the title: subdivision rainfall, rainfall departure, historical rainfall, rainfall data. Theme mapping uses the SECTOR_VOCAB_JSON: mapped to Atmospheric Science and Earth Sciences as the most relevant high-level/sub-sectors given the rainfall focus. Ambiguities/assumptions: “departure” refers to departure from historical mean; no explicit frequency/granularity fields are provided (frequency, granularity, govt_type are missing), so temporal aspects are inferred from the title range (1901–2015) rather than explicit metadata. No administrative or location-specific terms were added beyond national scope to avoid over-specifying beyond the dataset’s stated focus.', 'confidence_score': 0.8, 'metadata_gaps': 'frequency, granularity, govt_type, state_department'}

TITLE: Delivery Post office Pincode Boundary
SECTOR: All

✓ Written to CSV

----------------------------

TITLE: Subdivision wise Rainfall and its departure from 1901 to 2015
SECTOR: Science and Technology;Atmospheric Science;Earth Sciences

✓ Written to CSV

----------------------------

2026-01-15 10:42:45,443 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:42:45,444 : INFO - Result is {'generated_keywords': 'inbound tourism, travel, tourism, visitor numbers, foreign arrival, international arrival, indian arrival, india tourism', 'generated_sponsored_keywords': 'inbound tourism, foreign arrival, international arrival, indian arrival, india tourism', 'generated_theme': 'Travel and Tourism', 'justification': 'Source columns used: title, catalog_title, sector, note, ministry_department, state_department. Extraction/normalization: parsed sector value ( Travel and Tourism ) as the thematic anchor and used the catalog title (India Tourism Statistics) to anchor the domain to India; derived layman keywords from the title concepts (inbound tourism, various arrival types) and from sector (travel, tourism). Keywords are kept to 1–2 words each, lowercase, singular when applicable, and avoid acronyms or internal terms. Excluded terms: department names (e.g., Ministry of Tourism) and non-domain jargon. The note indicates immigration data sources, which supports keywords around arrivals. Ambiguities/assumptions: The catalog title strongly suggests India as the geographic context, but the title alone does not explicitly state the country; hence the assumption is that this dataset pertains to India based on catalog_title. No semicolon-separated values were present to split here, so no additional normalization was required. The theme uses the provided SECTOR_VOCAB_JSON to map Travel and Tourism to the appropriate controlled vocabulary category.', 'confidence_score': 0.8, 'metadata_gaps': 'sector_resource, frequency, granularity, govt_type'}

TITLE: Inbound Tourism Foreign Tourist Arrivals, Arrivals of Non-Resident Indians and International Tourist Arrivals 1981-2020
SECTOR: Travel and Tourism

✓ Written to CSV

----------------------------

2026-01-15 10:43:01,982 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:43:01,989 : INFO - Result is {'generated_keywords': 'price index, consumer price, rural urban, state level, monthly index, economic indicator', 'generated_sponsored_keywords': 'price index, consumer price, rural urban, state level, monthly index', 'generated_theme': 'Economy, Prices', 'justification': 'Sources used: title, sector. sector_resource and note are null in the input, so reliance on title/sector is emphasized. Normalization: parsed semicolon-separated sector values (Economy;Prices;Finance;Economy;Statistics) and deduplicated to focus on core subjects; terms are converted to lowercase and kept singular where possible (e.g., price index, monthly index). Extraction/selection rules: (1) derive layman terms that reflect CPI context (price index, consumer price) and the geographic/time framing from the title (state level, rural urban, monthly). (2) avoid department names and internal terms; (3) include India-relevant context where appropriate (state level CPI for rural/urban areas). Sponsorship terms are chosen as the strongest overlaps with the title/note, resulting in: price index, consumer price, rural urban, state level, monthly index. Theme mapping: mapped to SECTOR_VOCAB_JSON using the top-level Economy with sub-sector Prices, yielding the themes Economy; Prices. Ambiguities/assumptions: note and sector_resource are null, which reduces contextual richness; frequency/granularity fields are not provided in the input, so temporal tagging is limited to the implicit monthly aspect in the title. If frequency or granularity were provided, additional time-based keywords could be added.', 'confidence_score': 0.8, 'metadata_gaps': 'sector_resource (null); note (null); frequency (missing); granularity (missing); govt_type (missing)'}

TITLE: State Level Consumer Price Index (Rural/Urban) upto May 2023
SECTOR: Economy;Prices;Finance;Economy;Statistics

✓ Written to CSV

----------------------------

2026-01-15 10:43:03,765 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:43:04,124 : INFO - Result is {'generated_keywords': 'tele law, district court, case registration, legal advice, access justice, judiciary data, legal information, time series', 'generated_sponsored_keywords': 'tele law, case registration, district court, legal advice, access justice', 'generated_theme': 'Judiciary', 'justification': 'Source fields used: title, sector, sector_resource, ministry_department, and note. Extraction steps: 1) Sector parsed to identify the domain (Judiciary) and map to the SECTOR_VOCAB_JSON theme. 2) Title analyzed for core concepts: tele law, district-wise, case registration, and advice enabled data; combined with the note indicating a time frame (FY 2021-22 to 2022-23) to infer a temporal aspect. 3) Semicolon-separated values in ministry_department were parsed to extract the entities (Ministry of Law and Justice; Department of Justice) for context, but these are not used as keywords per guidelines. 4) Normalization: converted terms to lowercase, used singular forms where applicable (e.g., district court instead of district courts), avoided jargon, and ensured each keyword is 1–2 words. 5) Temporal cue added: time series to reflect historical data across fiscal years. 6) Ambiguities handled: the dataset’s focus is district-level judiciary data related to Tele-Law and advice; terms like “district data” were refined to “district court” to better reflect the likely resource focus. 7) Exclusions: department names and acronyms were avoided in keyword generation, in line with the rules. 8) Note and data scope: the note indicates data up to 31 January 2023, which supports a time-series keyword but no explicit frequency was provided. 9) Geography/administrative terms were de-emphasized unless implied by the title (district level implied by “District-wise”). Why specific terms were selected: core ideas from the title/note were translated into layman keywords (tele law, case registration, legal advice) and complemented with broad discovery terms (access justice, judiciary data, legal information) and a time-series indicator to reflect the historical fiscal years referenced. Why certain terms were excluded: acronyms and internal program names (e.g., DISHA) were avoided to keep user-facing discoverability; no department names were included as keywords per rules. Ambiguities/assumptions: It is assumed the dataset relates to district-level Tele-Law case registrations and associated advice within the judiciary, rather than broader department-level activities; if the dataset is more administrative, some keywords may be slightly off but remain within user-friendly discovery terms.', 'confidence_score': 0.8, 'metadata_gaps': 'sector_resource: null; state_department: null; frequency: missing; granularity: missing; govt_type: not provided'}

TITLE: District-wise Tele-Law Case Registration and Advice Enabled Data from FY 2021-22 to 2022-23
SECTOR: Judiciary

✓ Written to CSV

----------------------------

2026-01-15 10:43:18,131 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:43:18,133 : INFO - Result is {'generated_keywords': 'rainfall data, monsoon rainfall, seasonal rainfall, statewise rainfall, rainfall observations, india rainfall, rainfall trends', 'generated_sponsored_keywords': 'state rainfall, monsoon rainfall, rainfall data, rainfall details, monsoon data', 'generated_theme': 'Science and Technology; Earth Sciences, Water Resources', 'justification': 'Source columns and extraction: title clearly indicates state/UT-wise rainfall details observed during the monsoon season for 2020–2022; sector_resource provided as Science and Technology guided theme mapping. Processing steps: 1) derive layman keywords from core subject (rainfall, monsoon, statewise data) while keeping terms simple and plural forms avoided; 2) create sponsored keywords directly reflecting the title emphasis (state rainfall, monsoon rainfall, rainfall data, rainfall details, monsoon data); 3) map themes to the SECTOR_VOCAB_JSON: Science and Technology with Earth Sciences as a sub-sector, and Water Resources as a top-level theme to capture hydrological/weather aspects. Exclusions: avoided department names (Rajya Sabha) and acronyms; avoided location-specific punctuation; used India-relevant terms like rainfall, monsoon. Ambiguities resolved by prioritizing core dataset subject (rainfall observations across states/UTs during monsoon) and aligning with available taxonomy (Earth Sciences under Science and Technology, and Water Resources).', 'confidence_score': 0.85, 'metadata_gaps': ['state_department: null', 'frequency: null', 'granularity: null', 'govt_type: null']}

TITLE: State/UT-wise Details of the Rainfall Observed During the Monsoon Season from 2020 to 2022
SECTOR: All

✓ Written to CSV

----------------------------

2026-01-15 10:43:25,235 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:43:25,238 : INFO - Result is {'generated_keywords': 'youth, hostel, scheme, state, details, youth hostel', 'generated_sponsored_keywords': 'youth hostel, hostel scheme, state details, youth, scheme', 'generated_theme': 'Youth and Sports, Youth Affairs', 'justification': 'Source fields used: title, sector, sector_resource, note. Processing steps: 1) Extracted core subjects from sector values (Youth and Sports) and title context (youth hostels, scheme) and normalized to simple layman terms; 2) Generated 4–10 layman keywords focusing on the dataset subject (youth, hostel, scheme, state, details, youth hostel), keeping terms in singular form where applicable and using lowercase; 3) Created sponsored keywords focused on strong overlaps with the title and note: youth hostel, hostel scheme, state details, youth, scheme; 4) Mapped themes using SECTOR_VOCAB_JSON with the top-level sector Youth and Sports and its sub-sector Youth Affairs to reflect the domain; 5) Excluded ministry/department names and acronyms from keyword generation per guidelines; note value was used as a minor contextual cue but not part of keywords. Assumptions: the dataset concerns state-wise details related to youth hostels under a government scheme, hence emphasis on youth, hostel, state, and scheme terms. Ambiguities handled: no explicit frequency/granularity data; no state_department/government type provided, so themes rely on the available sector, title and notes. ', 'confidence_score': 0.8, 'metadata_gaps': 'frequency, granularity, govt_type, state_department missing; CDOS State Ministry field present but not mapped to a dedicated column; note present and non-null; sector_resource present but identical in this case'}

TITLE: State-wise Details of Youth Hostels - 2023
SECTOR: Youth and Sports

✓ Written to CSV

----------------------------

2026-01-15 10:43:25,563 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:43:25,566 : INFO - Result is {'generated_keywords': 'disability id, disability card, state wise, card data, disability data, parliament data, questions data, social development', 'generated_sponsored_keywords': 'disability card, state wise, unstarred question, parliament data, session 254', 'generated_theme': 'Social Development, Disabled', 'justification': "Sources used: title, sector_resource, note. - Title indicates numbers related to a disability credential (UDID card) generated across states/UTs as of a specific date; interpreted as Unique Disability ID card. - sector_resource contains 'Social Development', which maps to the SECTOR_VOCAB_JSON category 'Social Development' with subtopics including 'Disabled'. Based on this, the theme was assigned as 'Social Development' with the subtopic 'Disabled'. - Note provides context that this data comes from Rajya Sabha session questions; while Rajya Sabha is not used as a keyword, it informed the sponsorship keywords by reflecting data provenance (unstarred question). - Extraction/normalization rules applied: semicolon-separated fields were split (none present here); keywords are kept to 1–2 words, lowercase, non-technical, and non-departmental. From the title and note, terms like disability, card, state wise, and parliament-related data were derived to form layman keywords and sponsor keywords. Assumptions clarified: UDID stands for Unique Disability ID, hence 'disability' related keywords; excluded department names and acronyms per guidance. Ambiguities resolved by choosing widely understood terms (disability card, state wise) and by using the closest subtopic under Social Development (Disabled).", 'confidence_score': 0.9, 'metadata_gaps': 'state_department: null; frequency: null; granularity: null; govt_type: null; sector: All (not granular) '}

TITLE: State/UT-wise Number of UDID Card Generated as on 28.07.2021
SECTOR: All

✓ Written to CSV

----------------------------

2026-01-15 10:43:29,231 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:43:29,234 : INFO - Result is {'generated_keywords': 'economic data, quarterly data, time series, constant prices, economic growth, national accounts, price levels, government data', 'generated_sponsored_keywords': 'quarterly data, constant prices, time series, economic growth, national accounts', 'generated_theme': 'Economy, Macro Economy', 'justification': 'Source columns used: title (to derive time-based and price concepts), sector (Finance;Economy;Statistics) and sector_resource (Macro Economy) to map to the appropriate theme, and note (null in this case). Extraction rules: 1) Split semicolon-separated sector values into individual hints; 2) Generate layman keywords (1–2 words each, lowercase, exclude acronyms and department names); 3) From the title, infer core concepts such as quarterly updates and price basis, then translate into simple terms (e.g., quarterly data, time series, constant prices, economic growth). 4) For sponsored keywords, select the strongest direct overlaps with the title in concise terms (e.g., quarterly data, constant prices, time series, economic growth, national accounts). 5) Theme mapping uses SECTOR_VOCAB_JSON; the resource-level granularity is Macro Economy, which maps under Economy (with sub “Macro Economy”) as Economy, Macro Economy. Exclusions: avoided department acronyms (e.g., MoSPI) and sensitive terms; avoided GDP acronym per guidance. Ambiguities/assumptions: Note field is null (nan), so metadata_gaps highlight that and confidence is adjusted accordingly. The state_department field is null; frequency and granularity are not provided, which limits precise temporal tagging.', 'confidence_score': 0.8, 'metadata_gaps': ['note', 'frequency', 'granularity', 'state_department']}

TITLE: Quarterly Estimates of GDP at Constant (2011-12) Prices from 2011-12 to 2022-23
SECTOR: Finance;Economy;Statistics

✓ Written to CSV

----------------------------

2026-01-15 10:43:33,707 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:43:33,710 : INFO - Result is {'generated_keywords': 'industrial output, monthly index, coal, crude oil, refinery products, cement, steel, fertilizer, electricity, manufacturing', 'generated_sponsored_keywords': 'core industries, monthly data, electricity data, refinery products', 'generated_theme': 'Industries; Manufacturing, Power and Energy, Industries; Petroleum and Natural Gas', 'justification': 'Source columns used: title, sector, sector_resource, note. Processing steps included: (1) parsing semicolon-separated values in sector and sector_resource to capture individual hints (Industries; Manufacturing); (2) extracting core items from the note related to Eight Core Industries (coal, crude oil, refinery products, fertilizers, steel, cement, electricity, inclusion of renewable sources in electricity data); (3) deriving layman keywords that cover both broad and specific aspects while keeping terms simple and singular where applicable; (4) generating sponsored keywords that closely reflect the title/note overlaps (core industries, monthly data, electricity data, refinery products); (5) mapping themes to the SECTOR_VOCAB_JSON taxonomy by selecting relevant high-level sectors and sub-sectors (Industries; Manufacturing; Power and Energy; Industries; Petroleum and Natural Gas). Rules applied include: lowercasing for keyword fields, limiting to 1–2 words per keyword, avoiding department names, and treating semicolon-separated values as separate hints; India-relevant terms were emphasized (e.g., core industries). Assumptions/notes: the dataset concerns Eight Core Industries and their monthly/provisional updates; electricity data now includes renewable sources per the note, which supports the inclusion of electricity-related themes. Themes chosen reflect the documented focus on industrial production and specific core components (oil, gas, energy) without inventing new categories. Exclusions: avoided technical jargon or internal terms and department acronyms; did not force a location-based keyword beyond general industry scope.', 'confidence_score': 0.85, 'metadata_gaps': 'frequency;granularity;govt_type'}

TITLE: Eight Core Industries (Base Year 2011-12) till last month
SECTOR: Industries;Manufacturing

✓ Written to CSV

----------------------------

2026-01-15 10:43:36,558 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:43:36,560 : INFO - Result is {'generated_keywords': 'petroleum, import, export, volume, year, oil, product, data', 'generated_sponsored_keywords': 'petroleum import, petroleum export, petroleum volume, oil trade', 'generated_theme': 'Power and Energy', 'justification': 'Sources used: title (Import & Export of Petroleum Products - Volumes for Year - 2022-23) to identify core subject and time frame; sector (Non Renewable) to establish energy orientation; note to corroborate that the dataset concerns volumes of petroleum product imports and exports; sector_resource treated as null (nan) per the input, so reliance on sector and title was applied. Rules applied: semicolon-separated fields were parsed (none present for sector/sector_resource here); keywords are 1–2 words each, lowercase, singular where possible, no department acronyms, and avoid punctuation. From the title, core concepts extracted include petroleum, import, export, volumes, year; from note emphasis on petroleum products and provisional figures informed the inclusion of terms like petroleum and data, while avoiding heavy technical terms. The keywords are designed to be discoverable by non-experts and India-relevant context (petroleum context). Sponsored keywords were generated as tightly aligned 1–2 word phrases closely reflecting the title/note (petroleum import; petroleum export; petroleum volume; oil trade). Theme chosen: Power and Energy, the top-level sector in the provided controlled vocabulary that best represents a dataset on petroleum product imports/exports; no sub-sector was forced beyond this top-level mapping. Ambiguities/assumptions: sector_resource is effectively missing; time frame is embedded in the title (2022-23) but the keywords avoid hyphenated/year-specific tokens due to formatting constraints; state/government department names are excluded from keywords. If deeper product-level detail is required, more granular keywords from the note (e.g., paraffin wax, MTBE) could be added as variants within the 4–10 keyword limit.', 'confidence_score': 0.8, 'metadata_gaps': ['sector_resource', 'state_department', 'frequency', 'granularity', 'govt_type']}

TITLE: Import & Export of Petroleum Products - Volumes for Year - 2022-23
SECTOR: Non Renewable

✓ Written to CSV

----------------------------

2026-01-15 10:43:51,135 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:43:51,139 : INFO - Result is {'generated_keywords': 'micro unit, small unit, medium unit, registered unit, andhra pradesh, business registry, unit list', 'generated_sponsored_keywords': 'registered unit, udyog aadhaar, andhra pradesh, unit list', 'generated_theme': 'Industries; Medium; Micro; Small Scale', 'justification': 'Source columns used: title (for core subject and state reference) and sector/sector_resource (for enterprise size categories). Parsing rules: semicolon-separated values in sector and sector_resource were split into individual tokens (Medium, Micro, Small Scale) and then mapped to the SECTOR_VOCAB_JSON to form the theme. Since the dataset concerns MSME registered units in Andhra Pradesh, the appropriate high-level theme is Industries with sub-themes reflecting the enterprise sizes present in the metadata (Medium, Micro, Small Scale). Layman keywords were derived from the subject focus (MSME units and registration context) and include simple terms such as micro unit, small unit, registered unit, and Andhra Pradesh. Sponsored keywords are a tighter subset aligned with the title and note (registered unit, Udyog Aadhaar, Andhra Pradesh, unit list). Excluded terms: department names and acronyms (e.g., MSME) were avoided to keep keywords user-friendly. Assumptions: the dataset is about MSME registered units in AP under the Udyog Aadhaar Memorandum scheme; location is treated as inherent and included as a keyword. Note field was not used for keyword generation but confirms data download context; frequency is not provided in metadata and thus not reflected in keywords. Ambiguities: no explicit frequency or granularity is provided, so temporal keywords are not added. If frequency data becomes available, it could be used to add time-based terms.', 'confidence_score': 0.9, 'metadata_gaps': ['frequency (not provided in metadata)', 'state_department (null/not clearly provided in input)']}

TITLE: List of MSME Registered Units under Udyog Aadhaar Memorandum - Andhra Pradesh
SECTOR: Medium;Micro;Small Scale

✓ Written to CSV

----------------------------

2026-01-15 10:43:53,982 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:43:53,984 : INFO - Result is {'generated_keywords': 'crime data, crime rate, state crime, union territory, population, crime report, crime trend', 'generated_sponsored_keywords': 'penal code, crime data, crime rate, population, state data', 'generated_theme': 'Home Affairs and Enforcement, Governance and Administration', 'justification': "Source columns used: title, note, sector, sector_resource, ministry_department, state_department. Extraction rules applied: (1) Parsed semicolon-separated values in sector, sector_resource, and ministry_department to understand domain scope; (2) Derived layman terms from the title which centers on state/UT wise crime counts under the Indian Penal Code, and from the note which mentions crime rate per lakh and population data; (3) Normalized terms to avoid department acronyms and to favor India-relevant, non-technical concepts; (4) Mapped themes to SECTOR_VOCAB_JSON by selecting high-level domains relevant to crime data and administration (Home Affairs and Enforcement and Governance and Administration). Why terms chosen: The core subject is regional crime counts and rates; terms like crime data, crime rate, state crime, union territory, population, crime report, and crime trend closely reflect the dataset’s focus and would aid discovery without requiring specialized knowledge. Why terms excluded: Avoided department names in keywords, avoided heavy jargon, and avoided overly location-specific phrases beyond India context. Ambiguities/assumptions: The sector_resource value 'Army' seems misaligned with a crime statistics resource; treated as contextual metadata rather than a primary keyword. The note mentions comparability issues and Nagaland-specific clarifications, which are acknowledged but not required for the keyword set. Any implied temporal aspect (2020–2022) is captured via keywords like crime trend and crime rate, but explicit frequency granularity is not provided in the metadata. ", 'confidence_score': 0.8, 'metadata_gaps': 'frequency, granularity, govt_type'}

TITLE: State/UT-wise Number of Indian Penal Code (IPC) Crimes from 2020 to 2022
SECTOR: Police

✓ Written to CSV

----------------------------

2026-01-15 10:44:07,436 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:44:07,440 : INFO - Result is {'generated_keywords': 'rainfall, northeast india, monsoon, anomaly, historical rainfall, rainfall departure, time series, earth sciences, climate data', 'generated_sponsored_keywords': 'northeast rainfall, rainfall anomaly, historical rainfall, monsoon departure', 'generated_theme': 'Atmospheric Science, Earth Sciences', 'justification': "Source columns used: title (Rainfall in NE India and its departure from normal for Monsoon session from 1901-2021), sector (Science and Technology; Earth Sciences), sector_resource (Earth Sciences), ministry_department (Ministry of Earth Sciences; India Meteorological Department; IMD Pune). The note field is 'nan' which is treated as missing. Extraction/normalization: semicolon-separated values in sector and sector_resource were split into individual themes. Mapped to the SECTOR_VOCAB_JSON where possible: 'Atmospheric Science' and 'Earth Sciences' are sub-sectors under Science and Technology, aligning with rainfall/monsoon phenomena. Keywords were kept layman-friendly, 1–2 words each, lowercase, and without administrative terms. Time-related concept inferred from the 1901-2021 span; included as 'time series' in keywords. Excluded: ministry names, acronyms (e.g., IMD) and any internal jargon. Ambiguities: note is null, and some fields like frequency/granularity/govt_type are not provided; assumptions were made that this dataset is historical rainfall data related to monsoon in the northeast region. The themes chosen reflect the core subject areas relevant for cross-dataset discovery within the provided taxonomy.", 'confidence_score': 0.9, 'metadata_gaps': ['note', 'state_department', 'frequency', 'granularity', 'govt_type']}

TITLE: Rainfall in NE India and its departure from normal for Monsoon session from 1901-2021
SECTOR: Science and Technology;Earth Sciences

✓ Written to CSV

----------------------------

2026-01-15 10:44:09,192 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:44:09,194 : INFO - Result is {'generated_keywords': 'vehicle registration, motor vehicle, road transport, transport data, vehicle count, annual data', 'generated_sponsored_keywords': 'vehicle registration, motor vehicle, road transport, transport data, vehicle count', 'generated_theme': 'Transport, Road Transport', 'justification': "Source columns used: title, sector, sector_resource, note. The sector field contains semicolon-separated values which were split into: 'Transport' and 'Road Transport'. Keywords were generated as layman-friendly, 1–2 word terms in lowercase without punctuation, representing the dataset's core focus on vehicle registrations and counts within road transport. From the title and note, core concepts include motor vehicles, registrations, and annual data (two years referenced: 2009-10 and 2010-11). Sponsored keywords were selected to closely mirror the strongest overlaps between the title/note and the layman terms, and to avoid department names or locations in line with guidelines. The theme mapping uses the SECTOR_VOCAB_JSON, assigning broad Transport and its sub-sector Road Transport to categorize the dataset for cross-dataset discovery. Assumptions include treating Uttar Pradesh scope as context from the title but avoiding location-specific keywords in sponsored terms. No frequency or granularity details were provided, which limits temporal tagging beyond the note context.", 'confidence_score': 0.8, 'metadata_gaps': 'frequency, granularity, state_department, govt_type'}

TITLE: Number of Newly Registered Motor Vehicles in 2009-10 and 2010-11 and Number of Registered Motor Vehicles as on 31st March 2010 and as on 31st March 2011 in Uttar Pradesh
SECTOR: Transport;Road Transport

✓ Written to CSV

----------------------------

2026-01-15 10:44:11,489 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:44:11,491 : INFO - Result is {'generated_keywords': 'groundwater, water levels, data release, time series, water data, groundwater data', 'generated_sponsored_keywords': 'groundwater levels, bhujal yojana, groundwater data, time series', 'generated_theme': 'Water Resources; Ground Water', 'justification': 'Sources used: title, sector, sector_resource, ministry_department, state_department, note. Rules applied: (1) Keyword extraction prioritized core subject from sector and the title. Extracted concepts include groundwater, ground water levels, data, and the time aspect implied by the date range (2015 to 2022). (2) Kept keywords to 1–2 words, lowercase, no punctuation, and avoided department names. (3) Diverse layman terms were chosen to aid broad discovery, including both general terms (groundwater, water levels, data) and dataset-specific terms (data release, time series). (4) India-relevant terms were emphasized where applicable (groundwater, water data). (5) Sponsored keywords were derived from strongest overlaps with the title and note, resulting in terms that directly reflect the dataset’s purpose (groundwater levels, bhujal yojana, groundwater data, time series). (6) Theme mapping used the provided SECTOR_VOCAB_JSON. The dataset clearly aligns with Water Resources as the high-level sector and Ground Water as the sub-sector. Absent fields (sector_resource, note, frequency, granularity, govt_type) were handled by relying on available fields (title and sector) for keywords and by marking gaps in metadata_gaps. Assumptions: ABHY (Atal Bhujal Yojana) is represented in sponsored keywords as bhujal yojana to reflect the scheme without duplicating department terms.', 'confidence_score': 0.9, 'metadata_gaps': 'sector_resource null; note null; frequency missing; granularity missing; govt_type missing'}

TITLE: Disclosed Ground Water Level Data under Atal Bhujal Yojana from 2015 to 2022
SECTOR: Ground Water

✓ Written to CSV

----------------------------

2026-01-15 10:44:13,931 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:44:13,933 : INFO - Result is {'generated_keywords': 'earthquake, atlas, india, geology, map, fault line, seismic data', 'generated_sponsored_keywords': 'seismic atlas, earthquake data, fault line, geology map', 'generated_theme': 'Earth Sciences, Coastal & Island, Marine Science', 'justification': 'Source columns used: title (Digital Seismotectonic Atlas of India and its Environs) and sector (Governance and Administration; Union/State Government Administration; Mining; Coastal & Island; Earth Sciences; Marine Science; Polar Science; Research & Development) and sector_resource (Earth Sciences). Rules applied:\n- Parsed semicolon-separated values in sector and sector_resource to extract individual hints.\n- Generated layman keywords (1–2 words, singular where possible, lowercase, no internal jargon, no department names) reflecting core subjects: earthquake (from seismotectonic focus), atlas (from title), india (inherent location), geology, map, fault line, seismic data.\n- Excluded administrative terms and department names; included India-relevant terms where suitable (india, atlas, map, earthquakes related concepts).\n- For sponsored keywords, selected overlaps between the title and layman terms: seismic atlas, earthquake data, fault line, geology map.\n- Generated themes mapped to SECTOR_VOCAB_JSON: Earth Sciences, Coastal & Island, Marine Science (primary domain + related sub-sectors) to enable cross-dataset discovery.\n- Note field was treated as missing (nan); this reduces confidence slightly and is noted in metadata_gaps.\n\nWhy these terms were selected or excluded:\n- Included terms that best describe the resource focus on seismotectonics and mapping of India’s geological context.\n- Excluded non-substantive terms and department names (e.g., Geological Survey of India or Ministry names) from keywords.\n- Kept keywords simple and discoverable for the general public and search engines.\n\nAmbiguities/assumptions:\n- Note field appears as nan; treated as missing, which lowers confidence slightly.\n- Sector contains multiple entries; keywords prioritized the most relevant geoscience and mapping concepts.\n- The dataset centers on India, so india is included as an inherent location keyword.\n', 'confidence_score': 0.7, 'metadata_gaps': 'note'}

TITLE: Digital Seismotectonic Atlas of India and its Environs
SECTOR: Governance and Administration;Union/State Government Administration;Union/State Government Administration;Mining;Mining;Coastal & Island;Earth Sciences;Marine Science;Polar Science;Research & Development

✓ Written to CSV

----------------------------

2026-01-15 10:44:23,038 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:44:23,048 : INFO - Result is {'generated_keywords': 'gdp, quarterly gdp, current prices, macro economy, indian economy, economic growth, gdp estimates, time series', 'generated_sponsored_keywords': 'quarterly gdp, gdp estimates, current prices, time series', 'generated_theme': 'Economy; Macro Economy, Finance; Economy', 'justification': 'Source columns used: title, sector, sector_resource, ministry_department (CDOS State Ministry). Note that note, frequency and granularity fields are not provided or are effectively missing. Extraction and normalization steps:\n- Parsed semicolon-separated values from sector (Economy;Macro Economy;Finance;Economy) and sector_resource (Macro Economy) to identify core domains: Economy, Macro Economy, Finance.\n- Generated layman keywords by selecting 1–2 word terms that reflect the dataset’s subject: GDP-related terms (gdp, gdp estimates) and macroeconomic context (macro economy, indian economy, economic growth) plus time-oriented descriptors (quarterly, current prices, time series).\n- Ensured lowercase, limited to 1–2 words per keyword, avoided department names, and avoided internal jargon. Duplicates were removed (e.g., multiple references to economy were consolidated into distinct keywords).\n- Sponsored keywords were derived from strong overlaps with the title (Quarterly Estimates of GDP at Current Prices) and its implications (quarterly, gdp, current prices, time series). Each sponsor term is 1–2 words.\n- Theme generation follows SECTOR_VOCAB_JSON mapping: the dataset clearly aligns with Economy and Finance domains. Using the top-level and sub-sectors, themes selected are: Economy; Macro Economy and Finance; Economy, representing the main policy/domain areas and enabling cross-dataset discovery.\n- Note handling: the note field is shown as nan, indicating missing data; frequency and granularity are not provided. Hence, some metadata gaps exist and are acknowledged in the gaps and justification.\n\nWhy specific terms were selected or excluded:\n- Included gdp and gdp estimates to capture the core subject (GDP estimates).\n- Included quarterly and time series to reflect the frequency and temporal span indicated by the title (quarterly estimates and series from 2011-12 to 2022-23).\n- Included current prices to mirror the phrase in the title and catalog title.\n- Included macro economy and indian economy to reflect the macroeconomic and national context; avoided department names per guidelines.\n- Excluded knee-jerk or overly technical terms not evident in the metadata (e.g., API), and avoided duplicating department names in keywords.\n\nAmbiguities or assumptions:\n- Note field is denoted as nan, treated as missing; thus, no note-derived keywords beyond what is in the title/sector could be confidently added.\n- Frequency and granularity fields are not provided; temporal awareness is inferred from the title (quarterly) but not explicitly encoded elsewhere.\n- The presence of both Economy and Finance in sector suggests a broad financial-economy focus; themes selected reflect this linkage without introducing non-supported subcategories.\n', 'confidence_score': 0.8, 'metadata_gaps': 'note: missing (nan); frequency: missing; granularity: missing; state_department present but not in a dedicated field for processing; no explicit time-period field beyond the title'}

TITLE: Quarterly Estimates of GDP at Current Prices, 2011-12 Series From 2011-12 to 2022-23
SECTOR: Economy;Macro Economy;Finance;Economy

✓ Written to CSV

----------------------------

2026-01-15 10:44:25,529 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:44:25,797 : INFO - Result is {'generated_keywords': 'india geology, earthquake map, geology map, regional geology, crust mapping, mineral resources, geoscience india', 'generated_sponsored_keywords': 'earthquake map, seismic atlas, india atlas, geology map', 'generated_theme': 'Industries, Earth Sciences', 'justification': 'Source columns used: title, sector, sector_resource, note, and ministry_department. Extraction/normalization steps: \n- Parsed sector and sector_resource (Mining;Others) to understand domain context; avoided using department names in keyword generation per guidance. \n- Derived layman-friendly terms from the title and note, prioritizing non-technical, commonly searchable concepts linked to geology and mapping of seismic activity in India. These included broad terms like india geology and geology map, and context-specific terms like earthquake map and crust mapping. \n- Incorporated India-relevant terms (india, geoscience) to improve discoverability for localized searches. \n- Excluded explicit department names (e.g., Geological Survey of India, Ministry of Mines) from layman keywords. \n- Created sponsored keywords directly reflecting the dataset’s main idea (seismic atlas, earthquake map, india atlas, geology map) to capture high-similarity search terms tied to the title/note. \n- Theme mapping: Used SECTOR_VOCAB_JSON to map the resource to high-level categories. Given Mining is present but not a precise sub-sector in the vocab, mapped to Industries; and added Earth Sciences from Science and Technology as a second theme to reflect the geological/seismotectonic nature. \nAssumptions/ambiguities: The title/note strongly indicate seismic/geological mapping of India; there is no exact sub-sector for mining in the provided vocabulary, so Industries is used as the primary theme and Earth Sciences as a supporting theme. The state_department field is missing in the provided data, which limits cross-checking for location-specific governance nuances. \nWhy terms were selected or excluded: Technical terms such as seismotectonics were avoided in layman keywords to improve general searchability. Department names were excluded from keywords but acknowledged in justification. Some potentially relevant terms (e.g., seismology, tectonics) were omitted to maintain accessibility for a general audience. ', 'confidence_score': 0.8, 'metadata_gaps': 'state_department, frequency, granularity, govt_type'}

TITLE: Digital Seismotectonic Atlas of India and its Environs
SECTOR: Mining;Others

✓ Written to CSV

----------------------------

2026-01-15 10:44:29,621 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:44:29,622 : INFO - Result is {'generated_keywords': 'population, density, growth rate, state population, census 2011, rural health, demographics', 'generated_sponsored_keywords': 'population, density, state population, census 2011, growth rate', 'generated_theme': 'Census and Surveys, Health and Family welfare', 'justification': 'Source columns used: title, note, sector, sector_resource, ministry_department. Processing steps: 1) Parsed semicolon-separated values in sector, sector_resource, and ministry_department to identify domain hints. 2) Extracted core topics from the title: population, density, decadal growth, state-wise aspect. 3) Used note content referencing census 2011 to anchor to census-related terms. 4) Formulated layman keywords (1–2 words each, lowercase, singular where possible) and avoided department names. 5) Generated sponsored keywords by selecting the strongest overlaps between title/note and layman terms, ensuring brevity (1–2 words) and relevance. 6) Mapped themes to the controlled vocabulary SECTOR_VOCAB_JSON: Census and Surveys (for population and census context) and Health and Family welfare (for the Rural Health Statistics catalog context). Rules applied: keywords are non-technical, India-relevant where fitting, and exclude acronyms or internal terms. Ambiguities/assumptions: The dataset is titled around population metrics at the state level with a health statistics catalog, so terms like state population and census 2011 were emphasized. Location-specific terms (e.g., particular states) were not forced into keywords to keep them broadly discoverable. The note mentions 2011 census data and state-wise figures; those facts informed the inclusion of census 2011 and state population. ', 'confidence_score': 0.9, 'metadata_gaps': 'frequency; granularity; govt_type; state_department'}

TITLE: State-wise Population, Decadal Population Growth rate and Population Density - 2011
SECTOR: Health and Family welfare;Family Welfare;Health

✓ Written to CSV

----------------------------

2026-01-15 10:44:35,770 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:44:35,774 : INFO - Result is {'generated_keywords': 'groundwater, surface water, water resources, region boundaries, agro climate, country boundaries, region map, water mapping', 'generated_sponsored_keywords': 'agro climate, boundaries, region map, country boundaries', 'generated_theme': 'Water Resources, Ground Water, Surface Water', 'justification': 'Sources used: title (Boundaries of Agro-climatic regions) and note (information about agro-climatic regions across the country) indicate a focus on regional boundaries related to water and agro-ecology. sector and sector_resource provide two concrete hydrology domains: Ground Water and Surface Water, which map to the SECTOR_VOCAB_JSON top-level theme Water Resources and its sub-sectors Ground Water and Surface Water. The note confirms a nationwide scope across agro-climatic regions, supporting terms like agro climate and country boundaries. Extraction/normalization rules applied: \n- Split semicolon-separated values in sector and sector_resource to treat Ground Water and Surface Water as individual hints. \n- Normalize terms to layman form: Ground Water -> groundwater; Surface Water -> surface water. \n- Derive agro climate from the title/note (agro-climatic regions) and include related layman terms such as agro climate. \n- Generate 4–10 layman keywords that are simple, singular where possible, and non-technical; avoid department names or acronyms. \n- Generate 3–5 sponsored keywords directly anchored to the title/note, ensuring they are short, intuitive and don’t include organizational names. \n- Theme mapping uses SECTOR_VOCAB_JSON: primarily Water Resources with sub-sectors Ground Water and Surface Water.\nWhat was excluded: specific file formats mentioned in the note (shp, dbf, etc.), ministry names, and any highly technical terms. Ambiguities/assumptions: the dataset appears to be boundary data for agro-climatic regions across India, so keywords reflect boundaries, mapping, and water domain rather than any temporal data; no frequency/granularity data is provided, so temporal keywords were not added. If future metadata includes frequency or granularity, those could be incorporated.', 'confidence_score': 0.9, 'metadata_gaps': 'frequency, granularity'}

TITLE: Boundaries of Agro-climatic regions
SECTOR: Ground Water;Surface Water

✓ Written to CSV

----------------------------

2026-01-15 10:44:49,621 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:44:49,623 : INFO - Result is {'generated_keywords': 'infant mortality, institutional delivery, underweight children, public health, west bengal, state data, family health, health survey', 'generated_sponsored_keywords': 'infant mortality, institutional delivery, underweight children, west bengal', 'generated_theme': 'Health and Family welfare, Social Development', 'justification': 'Source columns used: title, sector_resource, note. Extraction rules: parsed key topics from the title (infant mortality rate, institutional delivery, under weight/undernutrition of under five), normalized terms to layman-friendly forms (infant mortality, institutional delivery, underweight children). Lowercased all terms, ensured 1–2 word length where possible, and avoided department or administrative terms. The note mentions NFHS-5 data and West Bengal, which informed the inclusion of geographic scope (west bengal) and health-focused context; sector_resource was used to anchor the domain to Social Development. Terms were selected to cover core subjects (infant health, delivery in facilities, child nutrition) and a relevant state reference to aid discovery. Assumptions/notes: not all fields (frequency, granularity, state_department, govt_type) were provided; the keywords favor health-related discovery aligned with the note’s NFHS-5 data reference. Excluded terms: department names and acronyms like Rajya Sabha, NFHS-5, etc., as per guidance.', 'confidence_score': 0.8, 'metadata_gaps': "state_department: null; frequency: null; granularity: null; govt_type: not provided; sector: 'All' indicates broad scope"}

TITLE: State-wise Details of the Infant Mortality Rate, Institutional Delivery and Prevalence of Under Weight Children under five years of Age (in Reply to Unstarred Question on 07 December, 2022)
SECTOR: All

✓ Written to CSV

----------------------------

2026-01-15 10:44:58,294 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:44:58,296 : INFO - Result is {'generated_keywords': 'reservoir, water resource, ground water, surface water, water boundary, boundary, map data, water project', 'generated_sponsored_keywords': 'reservoir, boundary, water resource, map data, water project', 'generated_theme': 'Water Resources, Infrastructure', 'justification': 'Source columns used: title, catalog_title, sector, sector_resource, note (and to a lesser extent ministry_department for context). Extraction rules applied: 1) Split semicolon-separated fields (sector and sector_resource) into individual tokens and normalize to singular, 1–2 word layman terms (e.g., ground water, surface water). 2) Derive core concepts from the title and catalog_title (reservoir, water resources, boundaries) and confirm with the note (mentions reservoirs, entire country, information in multiple formats). 3) Generate 4–10 layman keywords that are simple, non-technical, and India-relevant where applicable; avoid departmental acronyms and keep terms in lowercase. 4) Create sponsored keywords directly reflecting the dataset’s main idea, focusing on terms most likely to be used by users searching for this resource (reservoir, boundary, water resource, map data, water project). 5) Theme mapping uses the controlled vocabulary SECTOR_VOCAB_JSON: primary fit is Water Resources; secondary fit is Infrastructure given the mention of reservoirs/dams and project boundaries. 6) Excluded terms: explicit department names, acronyms, highly technical terms (e.g., shp, zip, geospatial jargon) from keywords. 7) Note content supported relevance (reservoirs across the country; point layer) but avoided adding overly technical keywords like shape file. 8) No duplication across keyword sets.\n\nWhy specific terms were selected or excluded:\n- reservoir: derived from title and note indicating reservoirs; singular form maintained.\n- water resource: broad subject extracted from catalog_title and note context; kept singular form.\n- ground water / surface water: directly taken from Sector and Sector Resource (singular terms kept as 1–2 word keywords).\n- water boundary / boundary: captures the map of limits around water resources projects; kept singular where possible.\n- map data: aligns with the note describing data formats and the implied geospatial map layer; kept non-technical.\n- water project: reflects the overarching purpose (boundaries of water resources projects).\n- boundary: general term to reinforce the concept of delineations present in the data.\n\nAmbiguities and assumptions:\n- Frequency, granularity, and govt_type fields are not provided in the input, which could affect filtering/temporal discovery; these are noted in metadata_gaps.\n- State_department field is not distinctly used in keyword/theme derivation but acknowledged; primary themes rely on water resources domain.\n- The note states the dataset is a point layer; keywords avoid heavy GIS jargon while still implying geospatial data through terms like map data.\n', 'confidence_score': 0.9, 'metadata_gaps': ['frequency', 'granularity', 'govt_type', 'state_department']}

TITLE: Shape file of reservoir
SECTOR: Ground Water;Surface Water

✓ Written to CSV

----------------------------

2026-01-15 10:45:00,919 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-01-15 10:45:00,921 : INFO - Result is {'generated_keywords': 'employment, worker, survey, quarterly, data, sector, india', 'generated_sponsored_keywords': 'worker count, quarterly survey, employment data, sector wise', 'generated_theme': 'Labour and Employment, Employment', 'justification': 'Source columns used: title, sector, sector_resource, note, and ministry_department. The title provides the core topic and time frame (Sector wise ... Fourth Round of Quarterly Employment Survey Jan to March 2022), while the sector field indicates the domain (Employment). sector_resource and note are null, so reliance on sector and title was necessary for keyword generation per the guidelines. Normalization rules applied: convert to lowercase, prefer singular forms (worker instead of workers), avoid punctuation, and avoid internal terms or department acronyms. Semicolon-separated values were not present here, so no splitting was required. Generated layman keywords reflect the dataset’s focus on employment and workers in a straightforward, discoverable way: employment (core subject), worker (singular form), survey (type of data collection), quarterly (frequency indicator inferred from the title), data (data in dataset), sector (sector-wise breakdown), india (country context). Sponsored keywords are derived from strong overlaps between the title/note and layman terms about the dataset’s main idea, yielding: worker count (counts of workers), quarterly survey (type of dataset), employment data (data category), sector wise (phrase from the title). Theme mapping uses the approved SECTOR_VOCAB_JSON: the dataset fits under Labour and Employment, with a sub-topic of Employment, which informs the two-part theme. Some ambiguity remains due to missing note and sector_resource and the absence of explicit frequency/granularity fields in the provided data; assumptions were limited to the interpretation of the title and sector to derive keywords and themes.', 'confidence_score': 0.9, 'metadata_gaps': 'sector_resource, note, frequency, granularity'}

TITLE: Sector wise Estimated Number of Workers under Fourth Round of Quarterly Employment Survey from Jan to March 2022
SECTOR: Employment

✓ Written to CSV

----------------------------


✓ Complete! Results saved to results_100.csv

In [20]:
from concurrent.futures import ThreadPoolExecutor, as_completed
from threading import Lock
import csv, json, logging

def process_row_keyword(row):
    """Process a single row - thread-safe"""
    title = row.get("title", "")
    catalog_title = row.get("catalog_title", "")
    ministry_department = row.get("ministry_department", "")
    sector = row.get("sector", "")
    sector_resource = row.get("sector_resource", "")
    cdos_state_ministry = row.get("cdos_state_ministry", "")
    note = row.get("note", "")

    
    # Fallback to 0 if missing / NaN
    raw_hvd = row.get("field_high_value_dataset", 0)
    try:
        hvd_flag = int(raw_hvd) if raw_hvd == raw_hvd else 0  # handles NaN
    except (ValueError, TypeError):
        hvd_flag = 0

    metadata_content = f"""
Title: {title}
Catalog Title: {catalog_title}
Ministry/Department: {ministry_department}
Sector: {sector}
Sector Resource: {sector_resource}
CDOS State Ministry: {cdos_state_ministry}
Note: {note}
HVD Flag: {hvd_flag}
""".strip()

    # LLM must now return JSON including "hvd_category"
    result = get_keywords(metadata_content)  # expected to return a dict (JSON-like)
    logging.info(f"Result is {result}")

    return {
        "title": title,
        "sector": sector,
        "hvd": hvd_flag,
        "metadata_input": metadata_content,
        "llm_response": json.dumps(result, ensure_ascii=False),
        "generated_keywords": result.get("enhanced_keywords", ""),
        "generated_subject": result.get("generated_subject", ""),
        "generated_theme": result.get("generated_theme", ""),
        "justification": result.get("justification", ""),
        "confidence_score": result.get("confidence_score", 0),
        "metadata_gaps": json.dumps(result.get("metadata_gaps", []), ensure_ascii=False),
        # NEW: HVD classification coming from the LLM
        "hvd_category": result.get("hvd_category", ""),
    }

# CSV setup
output_file = "results_100.csv"
fieldnames = [
    "title",
    "sector",
    "hvd",             
    "metadata_input",
    "llm_response",
    "generated_keywords",
    "generated_subject",
    "generated_theme",
    "justification",
    "confidence_score",
    "metadata_gaps",
    "hvd_category",    
]

csv_lock = Lock()
with open(output_file, "w", newline="", encoding="utf-8") as f:
    csv.DictWriter(f, fieldnames=fieldnames).writeheader()

results_array = []
max_workers = 8

with ThreadPoolExecutor(max_workers=max_workers) as executor:
    future_to_row = {
        executor.submit(process_row_keyword, row): idx
        for idx, row in (df.head(6)).iterrows()
    }
    for future in as_completed(future_to_row):
        try:
            result_obj = future.result()
            results_array.append(result_obj)

            # Thread-safe incremental write
            with csv_lock:
                with open(output_file, "a", newline="", encoding="utf-8") as f:
                    csv.DictWriter(f, fieldnames=fieldnames).writerow(result_obj)

            print(
                f"TITLE: {result_obj['title']}\n"
                f"SECTOR: {result_obj['sector']}\n"
                f"HVD: {result_obj['hvd']}\n"
                f"HVD CATEGORY: {result_obj['hvd_category']}\n\nWritten to CSV"
            )
            print("\n----------------------------\n")

        except Exception as e:
            logging.error(f"Row processing failed: {e}")

print(f"\nComplete Results saved to {output_file}")

2025-11-14 14:35:35,337 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-14 14:35:35,371 : INFO - Result is {'Title': 'All India Pincode Directory till last month'}

TITLE: All India Pincode Directory till last month
SECTOR: Information and Communications;Post
HVD: 0
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-14 14:35:35,727 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-14 14:35:35,732 : INFO - Result is {'Title': 'Current Daily Price of Various Commodities from Various Markets (Mandi)', 'Enhanced Keywords': 'daily price, commodity prices, mandi prices, market prices, agriculture data, price trends, crop prices, wholesale prices', 'Sponsored Keywords': 'mandi data, current prices, market data, price updates'}

TITLE: Current Daily Price of Various Commodities from Various Markets (Mandi)
SECTOR: Agriculture;Agricultural Marketing
HVD: 1
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-14 14:35:45,743 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-14 14:35:45,747 : INFO - Result is {'error': 'I cannot return JSON in this format.'}

TITLE: Variety-wise Daily Market Prices Data of Commodity
SECTOR: Agriculture;Agricultural Marketing
HVD: 1
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-14 14:35:48,602 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-14 14:35:48,606 : INFO - Result is {'Title: Registrars of Companies (RoC)-wise Company Master Data': ''}

TITLE: Registrars of Companies (RoC)-wise Company Master Data
SECTOR: Commerce;Companies
HVD: 1
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-14 14:35:56,314 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-14 14:35:56,320 : INFO - Result is {'Title': 'List of MSME Registered Units under UDYAM', 'Enhanced Keywords': 'registered units, udyam, unit list, business registry, micro units, small units, medium units, enterprise data', 'Sponsored Keywords': 'registered businesses, small business data, micro business units, unit registry, udyam data'}

TITLE: List of MSME Registered Units under UDYAM
SECTOR: Industries;Medium;Micro;Small Scale
HVD: 1
HVD CATEGORY:

Written to CSV

----------------------------

2025-11-14 14:36:19,936 : INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-14 14:36:19,943 : INFO - Result is {'Title': 'Kisan Call Centre (KCC) - Transcripts of farmers queries & answers', 'Enhanced Keywords': 'farmer queries, kisan, district wise, month wise, agriculture data, farmers welfare, local languages, district data, statistics', 'Sponsored Keywords': 'farmers queries, call centre, transcripts, kisan centre'}

TITLE: Kisan Call Centre (KCC) - Transcripts of farmers queries & answers
SECTOR: Agriculture
HVD: 1
HVD CATEGORY:

Written to CSV

----------------------------


Complete Results saved to results_100.csv

In [14]:
result_df=pd.read_csv("/home/aakash/NIC/cdl-updated/nic-metadata-cleaning/notebooks/results_100.csv")
result_df.count(axis=0)

title                 100
sector                100
metadata_input        100
llm_response          100
generated_keywords      0
generated_subject       0
generated_theme         0
justification           0
confidence_score      100
metadata_gaps         100
dtype: int64

In [15]:
results_array

[{'title': 'Current Daily Price of Various Commodities from Various Markets (Mandi)',
  'sector': 'Agriculture;Agricultural Marketing',
  'metadata_input': 'Title: Current Daily Price of Various Commodities from Various Markets (Mandi)\nCatalog Title: Current daily price of various commodities from various markets (Mandi)\nMinistry/Department: Ministry of Agriculture and Farmers Welfare;Department of Agriculture and Farmers Welfare;Directorate of Marketing and Inspection (DMI)\nSector: Agriculture;Agricultural Marketing\nSector Resource: Agriculture;Agricultural Marketing\nCDOS State Ministry: Directorate of Marketing and Inspection (DMI)\nNote: nan',
  'llm_response': '{"Title": "Current Daily Price of Various Commodities from Various Markets (Mandi)"}',
  'generated_keywords': '',
  'generated_subject': '',
  'generated_theme': '',
  'justification': '',
  'confidence_score': 0,
  'metadata_gaps': '[]'},
 {'title': 'Registrars of Companies (RoC)-wise Company Master Data',
  'sector': 'Commerce;Companies',
  'metadata_input': 'Title: Registrars of Companies (RoC)-wise Company Master Data\nCatalog Title: Company Master Data\nMinistry/Department: Ministry of Corporate Affairs\nSector: Commerce;Companies\nSector Resource: Commerce;Companies\nCDOS State Ministry: Ministry of Corporate Affairs\nNote: Figures Authorized Capital and Paid up Capital are in INR; NA: Not Available The data upto 3rd November 2023.',
  'llm_response': '{"error": "Two lines required exactly"}',
  'generated_keywords': '',
  'generated_subject': '',
  'generated_theme': '',
  'justification': '',
  'confidence_score': 0,
  'metadata_gaps': '[]'},
 {'title': 'Variety-wise Daily Market Prices Data of Commodity',
  'sector': 'Agriculture;Agricultural Marketing',
  'metadata_input': 'Title: Variety-wise Daily Market Prices Data of Commodity\nCatalog Title: Current daily price of various commodities from various markets (Mandi)\nMinistry/Department: Ministry of Agriculture and Farmers Welfare;Department of Agriculture and Farmers Welfare;Directorate of Marketing and Inspection (DMI)\nSector: Agriculture;Agricultural Marketing\nSector Resource: nan\nCDOS State Ministry: Directorate of Marketing and Inspection (DMI)\nNote: nan',
  'llm_response': '{"title": "Variety-wise Daily Market Prices Data of Commodity", "enhanced_keywords": ["mandi", "market prices", "daily prices", "commodity prices", "agriculture", "agricultural marketing", "price data", "markets"]}',
  'generated_keywords': '',
  'generated_subject': '',
  'generated_theme': '',
  'justification': '',
  'confidence_score': 0,
  'metadata_gaps': '[]'},
 {'title': 'Real time Air Quality Index from various locations',
  'sector': 'Environment and Forest;Industrial Air Pollution;Residential Air Pollution;Vehicular Air Pollution',
  'metadata_input': 'Title: Real time Air Quality Index from various locations\nCatalog Title: Real time Air Quality Index\nMinistry/Department: Ministry of Environment, Forest and Climate Change;Central Pollution Control Board\nSector: Environment and Forest;Industrial Air Pollution;Residential Air Pollution;Vehicular Air Pollution\nSector Resource: Environment and Forest;Industrial Air Pollution;Residential Air Pollution;Vehicular Air Pollution\nCDOS State Ministry: Central Pollution Control Board\nNote: The real-time data as collected from the field instruments is displayed live without human intervention from CPCB. It is likely that the live data may display some errors or abnormal values. Any abnormal value may be due to any episode or instrumental error at any particular time.',
  'llm_response': '{"Title": "Real time Air Quality Index from various locations", "Enhanced Keywords": "air quality, real time, live data, air pollution, monitoring, multiple sites, india, locations"}',
  'generated_keywords': '',
  'generated_subject': '',
  'generated_theme': '',
  'justification': '',
  'confidence_score': 0,
  'metadata_gaps': '[]'},
 {'title': 'All India Pincode Directory till last month',
  'sector': 'Information and Communications;Post',
  'metadata_input': 'Title: All India Pincode Directory till last month\nCatalog Title: All India Pincode Directory (Through WebService)\nMinistry/Department: Ministry of Communications;Department of Posts\nSector: Information and Communications;Post\nSector Resource: Post\nCDOS State Ministry: Department of Posts\nNote: Data will be updated on monthly basis.',
  'llm_response': '{"title": "All India Pincode Directory till last month", "Enhanced Keywords": "pin code, india, pincode directory, postal code, india post, monthly updates, post office, directory"}',
  'generated_keywords': '',
  'generated_subject': '',
  'generated_theme': '',
  'justification': '',
  'confidence_score': 0,
  'metadata_gaps': '[]'},
 {'title': 'Kisan Call Centre (KCC) - Transcripts of farmers queries & answers',
  'sector': 'Agriculture',
  'metadata_input': 'Title: Kisan Call Centre (KCC) - Transcripts of farmers queries & answers\nCatalog Title: District wise and month wise queries of farmers in Kisan Call Centre (KCC) \nMinistry/Department: Ministry of Agriculture and Farmers Welfare;Department of Agriculture and Farmers Welfare\nSector: Agriculture\nSector Resource: nan\nCDOS State Ministry: Department of Agriculture and Farmers Welfare\nNote: nan',
  'llm_response': '{"Title": "Kisan Call Centre (KCC) - Transcripts of farmers queries & answers", "Enhanced Keywords": "kisan, call centre, transcripts, farmers queries, district wise, month wise, agriculture, monthly data"}',
  'generated_keywords': '',
  'generated_subject': '',
  'generated_theme': '',
  'justification': '',
  'confidence_score': 0,
  'metadata_gaps': '[]'},
 {'title': 'Health indicator-wise monthly datasets at sub district level from HMIS',
  'sector': 'Health and Family welfare;Family Welfare;Health',
  'metadata_input': 'Title: Health indicator-wise monthly datasets at sub district level from HMIS\nCatalog Title: Health indicator-wise monthly datasets at sub district level from HMIS \nMinistry/Department: Ministry of Health and Family Welfare;Department of Health and Family Welfare\nSector: Health and Family welfare;Family Welfare;Health\nSector Resource: Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health;Health and Family welfare;Family Welfare;Health\nCDOS State Ministry: Department of Health and Family Welfare\nNote: NA: Not Available/Not Applicable; The data is as reported by health facilities of respective States/UTs of India.',
  'llm_response': '{"Title": "Health indicator-wise monthly datasets at sub district level from HMIS", "Enhanced Keywords": ["health data", "monthly data", "health indicators", "subdistrict data", "india", "state data", "health facilities", "family welfare"]}',
  'generated_keywords': '',
  'generated_subject': '',
  'generated_theme': '',
  'justification': '',
  'confidence_score': 0,
  'metadata_gaps': '[]'},
 {'title': 'Wholesale Price Index (Base Year 2011-12) till last month',
  'sector': 'Economy;Prices;Finance;Economy',
  'metadata_input': 'Title: Wholesale Price Index (Base Year 2011-12) till last month\nCatalog Title: Wholesale Price Index\nMinistry/Department: Ministry of Commerce and Industry;Department for Promotion of industry and Internal Trade;Office of the Economic Adviser\nSector: Economy;Prices;Finance;Economy\nSector Resource: Economy;Prices;Finance;Economy\nCDOS State Ministry: Office of the Economic Adviser\nNote: Data for last two months are provisional; NA: Not Applicable/Available',
  'llm_response': '{"Title": "Wholesale Price Index (Base Year 2011-12) till last month", "Enhanced Keywords": ["wholesale prices", "price index", "base year", "last month", "monthly data", "economy", "finance", "provisional data"]}',
  'generated_keywords': '',
  'generated_subject': '',
  'generated_theme': '',
  'justification': '',
  'confidence_score': 0,
  'metadata_gaps': '[]'},
 {'title': 'FDI Equity Inflows from the year 2000 till last quarter',
  'sector': 'Commerce',
  'metadata_input': 'Title: FDI Equity Inflows from the year 2000 till last quarter\nCatalog Title: Foreign Direct Investment (FDI) Equity Inflows\nMinistry/Department: Ministry of Commerce and Industry;Department for Promotion of industry and Internal Trade\nSector: Commerce\nSector Resource: Commerce\nCDOS State Ministry: Department for Promotion of industry and Internal Trade\nNote: Data are being updated quarterly basic, it contains data till last quarter of the current year.',
  'llm_response': '{"error": "No"}',
  'generated_keywords': '',
  'generated_subject': '',
  'generated_theme': '',
  'justification': '',
  'confidence_score': 0,
  'metadata_gaps': '[]'},
 {'title': 'Daily data of reservoir level of Central Water Commission (CWC)',
  'sector': 'Water Resources',
  'metadata_input': 'Title: Daily data of reservoir level of Central Water Commission (CWC)\nCatalog Title: Reservoir\nMinistry/Department: Department of Water Resources, River Development & Ganga Rejuvenation;Ministry of Jal Shakti;National Water Informatics Centre\nSector: Water Resources\nSector Resource: nan\nCDOS State Ministry: National Water Informatics Centre\nNote: nan',
  'llm_response': '{"Title": "Daily data of reservoir level of Central Water Commission (CWC)", "Enhanced Keywords": "reservoir levels, daily data, water data, reservoir data, water resources, reservoir monitoring, india, government data"}',
  'generated_keywords': '',
  'generated_subject': '',
  'generated_theme': '',
  'justification': '',
  'confidence_score': 0,
  'metadata_gaps': '[]'},
 {'title': 'India Districts Factsheets of National Family Health Survey (NFHS) - 5, 2019-2021',
  'sector': 'All;Health and Family welfare',
  'metadata_input': 'Title: India Districts Factsheets of National Family Health Survey (NFHS) - 5, 2019-2021\nCatalog Title: National Family Health Survey-5 (NFHS-5) - India Districts Factsheet Data\nMinistry/Department: Ministry of Health and Family Welfare;Department of Health and Family Welfare;International Institute for Population Sciences (IIPS)\nSector: All;Health and Family welfare\nSector Resource: All;Family Welfare\nCDOS State Ministry: International Institute for Population Sciences (IIPS)\nNote: Figures in ( ) are based on 25-49 unweighted cases and * denotes percentage not shown based on fewer than 25 unweighted cases. For more details please, visit to URL \nhttp://rchiips.org/nfhs/districtfactsheet_NFHS-5.shtml',
  'llm_response': '{"Title": "India Districts Factsheets of National Family Health Survey (NFHS) - 5, 2019-2021", "Enhanced Keywords": "district data, health survey, family health, india data, district factsheet, national survey, health indicators, child health"}',
  'generated_keywords': '',
  'generated_subject': '',
  'generated_theme': '',
  'justification': '',
  'confidence_score': 0,
  'metadata_gaps': '[]'},
 {'title': 'Voice Call Quality Customer Experience till last month',
  'sector': 'Information and Communications;Telecom',
  'metadata_input': 'Title: Voice Call Quality Customer Experience till last month\nCatalog Title: Voice Call Quality Customer Experience \nMinistry/Department: Ministry of Communications;Department of Telecommunications (DOT);Telecom Regulatory Authority of India (TRAI)\nSector: Information and Communications;Telecom\nSector Resource: Information and Communications;Telecom;Information and Communications;Telecom;Information and Communications;Telecom;Information and Communications;Telecom;Information and Communications;Telecom;Information and Communications;Telecom;Information and Communications;Telecom;Information and Communications;Telecom\nCDOS State Ministry: Telecom Regulatory Authority of India (TRAI)\nNote: nan',
  'llm_response': '{"Title": "Voice Call Quality Customer Experience till last month"}',
  'generated_keywords': '',
  'generated_subject': '',
  'generated_theme': '',
  'justification': '',
  'confidence_score': 0,
  'metadata_gaps': '[]'},
 {'title': 'Month-wise All India Crowdsourced Mobile Data Speed Measurement',
  'sector': 'Information and Communications;Telecom',
  'metadata_input': 'Title: Month-wise All India Crowdsourced Mobile Data Speed Measurement\nCatalog Title: MySpeed (Crowdsourced Mobile Data Speeds)\nMinistry/Department: Ministry of Communications;Department of Telecommunications (DOT);Telecom Regulatory Authority of India (TRAI)\nSector: Information and Communications;Telecom\nSector Resource: Information and Communications;Telecom;Information and Communications;Telecom;Information and Communications;Telecom;Information and Communications;Telecom;Information and Communications;Telecom;Information and Communications;Telecom;Information and Communications;Telecom;Information and Communications;Telecom\nCDOS State Ministry: Telecom Regulatory Authority of India (TRAI)\nNote: if You are not able to find speeds mentioned for a TSP/ State, this is due to insufficient samples in your selection "na" = "not available" owing to device unable to capture signal level LSA : Licensed_Service_Area, Signal_Strength : signal strength refers to the Transmitter power output as received by a reference antenna, TEST_TYPE : Upload /Download represent whether speed is for Download test or Upload Test, Technology : Network generation technology of wireless technology, TSP: Telecom Service Provider which provide service to users in a specific LSA',
  'llm_response': '{"Title": "Month-wise All India Crowdsourced Mobile Data Speed Measurement", "Enhanced Keywords": ["india", "mobile data", "data speed", "crowdsourced data", "speed test", "telecom", "network speed", "mobile network"]}',
  'generated_keywords': '',
  'generated_subject': '',
  'generated_theme': '',
  'justification': '',
  'confidence_score': 0,
  'metadata_gaps': '[]'},
 {'title': 'All India and State/UT-wise Factsheets of National Family Health Survey (NFHS) - 5, 2019-2021',
  'sector': 'Health and Family welfare;Family Welfare',
  'metadata_input': 'Title: All India and State/UT-wise Factsheets of National Family Health Survey (NFHS) - 5, 2019-2021\nCatalog Title: National Family Health Survey (NFHS) - 5\nMinistry/Department: Ministry of Health and Family Welfare;Department of Health and Family Welfare;International Institute for Population Sciences (IIPS)\nSector: Health and Family welfare;Family Welfare\nSector Resource: Health and Family welfare;Health and Family welfare;Health and Family welfare;Health and Family welfare;Health and Family welfare;Health and Family welfare\nCDOS State Ministry: International Institute for Population Sciences (IIPS)\nNote:  For all indicators except infant and child mortality rates, figures in ( ) are based on 25-49 unweighted cases and  * denotes percentage not shown based on fewer than 25 unweighted cases. \nFor infant and child mortality indicators, figures in ( ) are based on 250-499 unweighted person years of exposure to the risk of death and * denotes figures not given based on fewer than 250 unweighted person years of exposure to the risk of death.\n\nFor more details please, visit  to URL http://rchiips.org/nfhs/NFHS-5_FCTS/COMPENDIUM/NFHS-5%20State%20Factsheet%20Compendium_Phase-I.pdf  and http://rchiips.org/nfhs/NFHS-5_FCTS/Final%20Compendium%20of%20fact%20sheets_India%20and%2014%20States_UTs%20(Phase-II).pdf',
  'llm_response': '{"title": "Title: All India and State/UT-wise Factsheets of National Family Health Survey (NFHS) - 5, 2019-2021", "keywords": ["india health", "family health", "health survey", "child health", "maternal health", "factsheet", "state data", "national data", "health indicators", "population survey"]}',
  'generated_keywords': '',
  'generated_subject': '',
  'generated_theme': '',
  'justification': '',
  'confidence_score': 0,
  'metadata_gaps': '[]'},
 {'title': 'Sub Divisional Monthly Rainfall from 1901 to 2017',
  'sector': 'Science and Technology;Atmospheric Science;Earth Sciences',
  'metadata_input': 'Title: Sub Divisional Monthly Rainfall from 1901 to 2017\nCatalog Title: Rainfall in India\nMinistry/Department: Ministry of Earth Sciences;India Meteorological Department (IMD);India Meteorological Department (IMD), Pune\nSector: Science and Technology;Atmospheric Science;Earth Sciences\nSector Resource: Earth Sciences;Earth Sciences\nCDOS State Ministry: India Meteorological Department (IMD), Pune\nNote: All values are in MMS; NA: Not Available.',
  'llm_response': '{"Title": "Title: Sub Divisional Monthly Rainfall from 1901 to 2017", "Enhanced Keywords": "rainfall, monthly rainfall, subdivisional rainfall, india rainfall, historical rainfall, weather data, climate data, rainfall trends"}',
  'generated_keywords': '',
  'generated_subject': '',
  'generated_theme': '',
  'justification': '',
  'confidence_score': 0,
  'metadata_gaps': '[]'},
 {'title': 'Wholesale Price Index (Base Year 2011-12) till last financial year',
  'sector': 'Economy;Prices;Finance;Economy',
  'metadata_input': 'Title: Wholesale Price Index (Base Year 2011-12) till last financial year\nCatalog Title: Wholesale Price Index\nMinistry/Department: Ministry of Commerce and Industry;Department for Promotion of industry and Internal Trade;Office of the Economic Adviser\nSector: Economy;Prices;Finance;Economy\nSector Resource: nan\nCDOS State Ministry: Office of the Economic Adviser\nNote: NA: Not Applicable/Available',
  'llm_response': '{"title": ""}',
  'generated_keywords': '',
  'generated_subject': '',
  'generated_theme': '',
  'justification': '',
  'confidence_score': 0,
  'metadata_gaps': '[]'},
 {'title': 'Indian Railways Time Table for trains available for reservation as on 01.11.2017',
  'sector': 'Transport;Railways',
  'metadata_input': 'Title: Indian Railways Time Table for trains available for reservation as on 01.11.2017\nCatalog Title: Indian Railways Train Time Table\nMinistry/Department: Ministry of Railways\nSector: Transport;Railways\nSector Resource: Transport;Railways\nCDOS State Ministry: Ministry of Railways\nNote: nan',
  'llm_response': '{"Title: Indian Railways Time Table for trains available for reservation as on 01.11.2017": ""}',
  'generated_keywords': '',
  'generated_subject': '',
  'generated_theme': '',
  'justification': '',
  'confidence_score': 0,
  'metadata_gaps': '[]'},
 {'title': 'Seasonal and Annual Mean Temperature Series for the period 1901-2021',
  'sector': 'Science and Technology;Earth Sciences',

In [19]:
with open('/home/aakash/NIC/cdl-updated/nic-metadata-cleaning/notebooks/metadata_enrichment_result.json') as f:
    json.dump(results_array, f, indent=2, ensure_ascii=False)

print(f"\n Saved {len(results_array)} results to metadata_enrichment_results.json")

UnsupportedOperation: not writable